# aliases.R
# Auto-generated by tools/03_apply_renames.R

#' @export
AB_CIVARTest <- function(...) ab_civar_test(...)

#' @export
ABC_MRCIVARestm <- function(...) abc_mrciva_restm(...)

#' @export
abLRtest2 <- function(...) ab_l_rtest2(...)

#' @export
ABSVAR <- function(...) absvar(...)

#' @export
ACCIRFconfR <- function(...) accir_fconf_r(...)

#' @export
B2CIB <- function(...) b2_cib(...)

#' @export
Bo2Ao <- function(...) bo2_ao(...)

#' @export
BoAo2TBoAo <- function(...) bo_ao2_t_bo_ao(...)

#' @export
BoAoW2G <- function(...) bo_ao_w2_g(...)

#' @export
BoAoWs2Gs <- function(...) bo_ao_ws2_gs(...)

#' @export
CCIVARData <- function(...) ccivar_data(...)

#' @export
CCIVARest <- function(...) cciva_rest(...)

#' @export
CIA2A <- function(...) cia2_a(...)

#' @export
CIB2B <- function(...) cib2_b(...)

#' @export
CIB3B <- function(...) cib3_b(...)

#' @export
CIGVAR_Select <- function(...) cigvar_select_(...)

#' @export
CIGVARData <- function(...) cigvar_data(...)

#' @export
CIGVARest <- function(...) cigvar_estimate(...)

#' @export
CIVARData <- function(...) civar_data(...)

#' @export
CIVARest <- function(...) civar_estimate(...)

#' @export
CIVARTest <- function(...) civar_test(...)

#' @export
CVECM2CVAR <- function(...) cvecm2_cvar(...)

#' @export
Embed <- function(...) embed_ts(...)

#' @export
girf_MRCIGVAR_RM <- function(...) girf_mrcigvar_rm(...)

#' @export
girf_MRCIGVAR_RM_CB <- function(...) girf_mrcigvar_rm_cb(...)

#' @export
girf_MRCIVAR_RM <- function(...) girf_mrcivar_rm(...)

#' @export
girf_MRCIVAR_RM_CB <- function(...) girf_mrcivar_rm_cb(...)

#' @export
girf_MRGVAR_RM <- function(...) girf_mrgvar_rm(...)

#' @export
girf_MRGVAR_RM_CB <- function(...) girf_mrgvar_rm_cb(...)

#' @export
girf_MRVAR_RM <- function(...) girf_mrvar_rm(...)

#' @export
girf_MRVAR_RM_CB <- function(...) girf_mrvar_rm_cb(...)

#' @export
GVAR_Select <- function(...) gvar_select_(...)

#' @export
GVARData <- function(...) gvar_data(...)

#' @export
GVARest <- function(...) gvar_estimate(...)

#' @export
GW2BoAo <- function(...) gw2_bo_ao(...)

#' @export
INVI <- function(...) invi(...)

#' @export
irf_B_sigma <- function(...) irf_from_params(...)

#' @export
irf_CIGVAR_CB <- function(...) irf_cigvar_cb(...)

#' @export
irf_CIVAR_CB <- function(...) irf_civar_cb(...)

#' @export
irf_GloabalResponse_CB <- function(...) irf_gloabal_response_cb(...)

#' @export
IRF_graph <- function(...) plot_irf(...)

#' @export
irf_GVAR <- function(...) irf_gvar(...)

#' @export
irf_GVAR_CB <- function(...) irf_gvar_cb(...)

#' @export
irf_MRCIGVAR <- function(...) irf_mrcigvar(...)

#' @export
irf_MRCIGVAR_CB <- function(...) irf_mrcigvar_cb(...)

#' @export
irf_MRCIVAR_CB <- function(...) irf_mrcivar_cb(...)

#' @export
irf_MRGVAR <- function(...) irf_mrgvar(...)

#' @export
irf_MRGVAR_CB <- function(...) irf_mrgvar_cb(...)

#' @export
irf_MRVAR_CB <- function(...) irf_mrvar_cb(...)

#' @export
irf_MRVAR_NM <- function(...) irf_mrvar_nm(...)

#' @export
irf_MRVAR_NM_CB <- function(...) irf_mrvar_nm_cb(...)

#' @export
irf_VAR_CB <- function(...) irf_var_cb(...)

#' @export
JointX <- function(...) bind_exogenous_by_state(...)

#' @export
MIxCIVARData <- function(...) m_ix_civar_data(...)

#' @export
MRCIGVAR_Select <- function(...) mrcigvar_select_(...)

#' @export
MRCIGVARData <- function(...) mrcigvar_data(...)

#' @export
MRCIGVARDataR <- function(...) mrcigvar_data_r(...)

#' @export
MRCIGVARest <- function(...) mrcigvar_estimate(...)

#' @export
MRCIVAR_Selectm <- function(...) mrcivar_select_m(...)

#' @export
MRCIVARDatam <- function(...) mrcivar_data_m(...)

#' @export
MRCIVARestm1 <- function(...) mrcivar_estimatem1(...)

#' @export
MRCVECMest2 <- function(...) mrcvec_mest2(...)

#' @export
MRCVECMestm <- function(...) mrcvec_mestm(...)

#' @export
MRGVAR_Select <- function(...) mrgvar_select_(...)

#' @export
MRGVARData <- function(...) mrgvar_data(...)

#' @export
MRGVARDataR <- function(...) mrgvar_data_r(...)

#' @export
MRGVARest <- function(...) mrgvar_estimate(...)

#' @export
MRVAR_Select <- function(...) mrvar_select_(...)

#' @export
MRVAR_Select_Summary <- function(...) mrvar_select__summary(...)

#' @export
MRVARData <- function(...) mrvar_data(...)

#' @export
MRVARest <- function(...) mrvar_estimate(...)

#' @export
NoutofT <- function(...) sample_n_out_of_t(...)

#' @export
Redex <- function(...) redex(...)

#' @export
rnormSIGMA <- function(...) rnorm_sigma(...)

#' @export
rnormSIGMA_cond <- function(...) rnorm_sigma_cond(...)

#' @export
Roots2coef <- function(...) roots_to_coef(...)

#' @export
RZSt2VECM <- function(...) rz_st2_vecm(...)

#' @export
ShiftZ2 <- function(...) shift_z2(...)

#' @export
ShiftZ2m <- function(...) shift_z2m(...)

#' @export
SigmaNPD <- function(...) sigma_npd(...)

#' @export
SigmaNPDSelectR <- function(...) sigma_npd_select_r(...)

#' @export
STAT <- function(...) spectral_radius(...)

#' @export
summaryCIVAR <- function(...) summary_civar(...)

#' @export
SW2comb <- function(...) sw2comb(...)

#' @export
Type <- function(...) infer_deterministic_type(...)

#' @export
U1 <- function(...) u1(...)

#' @export
VARB_commtrend <- function(...) varb_commtrend(...)

#' @export
VARBS_commtrend <- function(...) varbs_commtrend(...)

#' @export
VARData <- function(...) var_data(...)

#' @export
VARest <- function(...) var_estimate(...)

#' @export
VECM2VAR <- function(...) vecm2_var(...)

#' @export
VECM2VARm <- function(...) vecm2_va_rm(...)

#' @export
W2Wmat <- function(...) w2_wmat(...)

#' @export
xABF <- function(...) x_abf(...)

