#!/usr/bin/env Rscript

required_packages <- c("knitr")
missing_packages <- required_packages[!vapply(
  required_packages,
  requireNamespace,
  logical(1),
  quietly = TRUE
)]

if (length(missing_packages) > 0) {
  stop(
    "Missing required R packages: ",
    paste(missing_packages, collapse = ", "),
    call. = FALSE
  )
}

pages <- list(
  list(
    source = "README.Rmd",
    target = "docs/index.md",
    exclude = c(
      "Further documentation",
      "Project status",
      "Documentation and development",
      "Issues and feedback"
    )
  ),
  list(
    source = "vignettes/mrcigvar-introduction.Rmd",
    target = "docs/getting-started/overview.md",
    exclude = c(
      "Documentation status",
      "Development notes",
      "Next steps"
    )
  ),
  list(
    source = "vignettes/core-model-workflows.Rmd",
    target = "docs/workflows/core-model-workflows.md",
    exclude = c("Where to go next")
  ),
  list(
    source = "vignettes/mrcigvar-workflow.Rmd",
    target = "docs/workflows/mrcigvar-workflow.md",
    exclude = c("Related vignettes")
  ),
  list(
    source = "vignettes/irf-and-girf.Rmd",
    target = "docs/workflows/irf-and-girf.md",
    exclude = c("Related vignettes")
  ),
  list(
    source = "vignettes/refactor-migration-guide.Rmd",
    target = "docs/reference/migration-guide.md",
    exclude = c("Related vignettes")
  )
)

trim_blank_edges <- function(lines) {
  while (length(lines) > 0 && lines[[1]] == "") {
    lines <- lines[-1]
  }

  while (length(lines) > 0 && lines[[length(lines)]] == "") {
    lines <- lines[-length(lines)]
  }

  lines
}

collapse_blank_runs <- function(lines) {
  out <- character()
  last_blank <- FALSE

  for (line in lines) {
    is_blank <- line == ""
    if (is_blank && last_blank) {
      next
    }
    out <- c(out, line)
    last_blank <- is_blank
  }

  out
}

strip_yaml_front_matter <- function(lines) {
  if (length(lines) < 3 || lines[[1]] != "---") {
    return(lines)
  }

  end_idx <- which(lines[-1] == "---")
  if (length(end_idx) == 0) {
    return(lines)
  }

  lines[-seq_len(end_idx[[1]] + 1)]
}

extract_title <- function(lines) {
  if (length(lines) < 3 || lines[[1]] != "---") {
    return(NULL)
  }

  end_idx <- which(lines[-1] == "---")
  if (length(end_idx) == 0) {
    return(NULL)
  }

  yaml_lines <- lines[2:end_idx[[1]]]
  title_line <- grep("^title\\s*:\\s*", yaml_lines, value = TRUE)

  if (length(title_line) == 0) {
    return(NULL)
  }

  title <- sub("^title\\s*:\\s*", "", title_line[[1]])
  title <- trimws(gsub('^"|"$', "", title))

  if (identical(title, "")) {
    return(NULL)
  }

  title
}

filter_sections <- function(lines, excluded_headings) {
  if (length(excluded_headings) == 0) {
    return(lines)
  }

  out <- character()
  in_fence <- FALSE
  skip_level <- NA_integer_

  for (line in lines) {
    if (grepl("^```", line)) {
      if (is.na(skip_level)) {
        out <- c(out, line)
      }
      in_fence <- !in_fence
      next
    }

    if (!in_fence && grepl("^#{1,6}\\s+", line)) {
      level <- attr(regexpr("^#+", line), "match.length")
      heading <- trimws(sub("^#{1,6}\\s+", "", line))

      if (!is.na(skip_level) && level <= skip_level) {
        skip_level <- NA_integer_
      }

      if (is.na(skip_level) && heading %in% excluded_headings) {
        skip_level <- level
        next
      }
    }

    if (!is.na(skip_level)) {
      next
    }

    out <- c(out, line)
  }

  out
}

render_page <- function(source, target, exclude) {
  source_lines <- readLines(source, warn = FALSE)
  title <- extract_title(source_lines)

  temp_output <- tempfile(fileext = ".md")
  on.exit(unlink(temp_output), add = TRUE)

  knitr::opts_chunk$set(eval = FALSE)
  knitr::knit(
    input = source,
    output = temp_output,
    quiet = TRUE,
    envir = new.env(parent = globalenv())
  )

  lines <- readLines(temp_output, warn = FALSE)
  lines <- strip_yaml_front_matter(lines)
  lines <- lines[lines != "<!-- README.md is generated from README.Rmd. Please edit that file -->"]

  first_heading <- grep("^#{1,6}\\s+", lines, value = TRUE)
  has_title_heading <- length(first_heading) > 0 &&
    trimws(sub("^#{1,6}\\s+", "", first_heading[[1]])) == title

  if (!is.null(title) && !has_title_heading) {
    lines <- c(paste("#", title), "", lines)
  }

  lines <- filter_sections(lines, exclude)
  lines <- trim_blank_edges(lines)
  lines <- collapse_blank_runs(lines)
  lines <- c(
    paste0("<!-- Generated by scripts/render-docs.R from ", source, ". -->"),
    "",
    lines
  )

  dir.create(dirname(target), recursive = TRUE, showWarnings = FALSE)
  writeLines(lines, target, useBytes = TRUE)
  message(sprintf("Rendered %s -> %s", source, target))
}

old_wd <- getwd()
script_arg <- grep("^--file=", commandArgs(trailingOnly = FALSE), value = TRUE)
script_path <- if (length(script_arg) > 0) {
  sub("^--file=", "", script_arg[[1]])
} else {
  "scripts/render-docs.R"
}
repo_root <- normalizePath(file.path(dirname(script_path), ".."), winslash = "/", mustWork = TRUE)
setwd(repo_root)
on.exit(setwd(old_wd), add = TRUE)

for (page in pages) {
  render_page(page$source, page$target, page$exclude)
}
