#!/usr/bin/env Rscript
# tools/02_split_to_modules.R
# Split legacy scripts into module files under R/ using tools/rename_map.csv (module column)

source("tools/helpers.R")

stopifnot(file.exists("tools/rename_map.csv"))
map <- read.csv("tools/rename_map.csv", stringsAsFactors = FALSE)

if (!dir.exists("legacy")) stop("Missing ./legacy (put old scripts there).")
if (!dir.exists("R")) dir.create("R", recursive = TRUE)

targets <- unique(map$module)
for (t in targets) {
  p <- file.path("R", t)
  cat(sprintf("# %s\n# (re)generated by tools/02_split_to_modules.R\n\n", t), file = p)
}

legacy_files <- list.files("legacy", pattern = "\\.[Rr]$", full.names = TRUE)
index <- data.frame(fun = character(), module = character(), source_file = character(), stringsAsFactors = FALSE)

append_block <- function(path, block) {
  cat("\n\n", file = path, append = TRUE)
  cat(block, file = path, append = TRUE)
  cat("\n", file = path, append = TRUE)
}

for (f in legacy_files) {
  txt <- read_text(f)
  blocks <- extract_function_blocks(txt)
  if (length(blocks) == 0) next
  for (b in blocks) {
    m <- map$module[match(b$name, map$old_name)]
    if (is.na(m)) m <- guess_module(b$name)
    out_path <- file.path("R", m)
    append_block(out_path, b$block)
    index[nrow(index)+1,] <- list(fun = b$name, module = m, source_file = basename(f))
  }
}

write.csv(index, "tools/function_index.csv", row.names = FALSE)
cat("Done. Wrote R/ modules and tools/function_index.csv\n")
