#!/usr/bin/env Rscript
# tools/03_apply_renames.R
# Rename functions across R/ using tools/rename_map.csv, and optionally create alias wrappers.

source("tools/helpers.R")

stopifnot(file.exists("tools/rename_map.csv"))
map <- read.csv("tools/rename_map.csv", stringsAsFactors = FALSE)
map <- map[map$old_name != map$new_name, ]

if (!dir.exists("R")) stop("Missing ./R folder (run tools/00_setup.R and tools/02_split_to_modules.R first).")
r_files <- list.files("R", pattern = "\\.R$", full.names = TRUE)

for (f in r_files) {
  ok <- apply_symbol_renames(f, map)
  if (!ok) cat("WARN: could not parse ", f, "\n")
}

# Aliases for backwards compatibility
alias_rows <- map[map$keep_old_alias %in% c(TRUE, "TRUE", "True", 1), ]
if (nrow(alias_rows) > 0) {
  alias_path <- file.path("R", "aliases.R")
  cat("# aliases.R\n# Auto-generated by tools/03_apply_renames.R\n\n", file = alias_path)
  for (i in seq_len(nrow(alias_rows))) {
    old <- alias_rows$old_name[i]
    new <- alias_rows$new_name[i]
    cat(sprintf("#' @export\n%s <- function(...) %s(...)\n\n", old, new), file = alias_path, append = TRUE)
  }
}

cat("Rename complete. Review R/aliases.R and run roxygen2.\n")
