# constraints.R
# (re)generated by tools/02_split_to_modules.R



#'
#' This function estimates constrained VECM using the iteration procedure proposed in Boswijk and Doornik (2003)
#'
#' @param R0    : T x n matrix containing the residuals of the auxiliary regression of dy_t on Z2_t
#' @param R1    : T x n matrix containing the residuals of the auxiliary regression of y_(t-1) on Z2_t
#' @param G     : The restriction matrix on alpha
#' @param H     : The restriction matrix on beta
#' @param h     : The restriction vector on beta ( free-varying parameters of beta )
#' @param alpha : n x crk matrix containing initial values of the adjustment parameters
#' @param beta  : n x crk matrix containing initial values of the cointegration vectors
#' @param Omega : n x n matrix containing initials of the covariance matrix
#' @param Y0    : T x n matrix of dY_t
#' @param Z2    : T x (n(p-1)+#det) matrix containing the lagged stationary regressors of the auxiliary regression
#' @param Z1    : T x n matrix containing the lagged cointegrated VAR process.
#'
#'
#' @section Details:
#' This function runs a likelihood ratio test of linear restrictions on \eqn{\alpha} and \eqn{\beta} in a CIVAR model in the following form:
#'		\deqn{vec(\alpha') = G \psi,  vec(\beta) = H\phi + h}
#'
#' example 1 (restrictions on alpha) test of exogeneity: one weakly exogenous variable
#'     vec(alpha) is n*crk x 1  vector
#'     G          is n*crk x (n-k)*crk matrix  (k is the number of weakly exogenous)
#'     psi        (n-k)*crk x 1 vector
#'     vec(beta)  is n*crk x 1 vector
#'     H          is n*crk x n*crk identity matrix
#'     phi        n*crk x 1 vector
#'     h          n*crk x 1 zero matrix implying ver(beta) = phi.
#'                (H is identity and h is zero vector implies only restrictions on alpha)
#'
#' example 2 (restrictions on beta ) test of PPP
#'     vec(alpha) is n*crk x 1 vector
#'     G          is n*crk x n*crk identity matrix, implying no restriction on alpha
#'     psi        n*crk x 1 vector
#'     vec(beta)  n*crk x 1 vector
#'     H          n*crk x 2 matrix that picks out the elements under restrictions
#'                two columns out of the identity matrix.
#'                ones in a row of H and zero in the corresponding h implies non-restricted beta.
#'     phi        2 x 1  vector
#'     h          n*crk x 1  non zero elements in this vector together with the zero elements in
#'                the corresponding row in H are the normalization conditions.
#'                (H is identity and h is zero vector implies only restrictions on alpha)
#'
#' @return a list containing (VECMRS, beter, alphar, LSKOEFR, LR, and error)
#'
#' @export
#' @keywords internal
#'
ab_civar_test <- function(R0,R1,G,H,h,alpha,beta,Omega,Y0,Z1,Z2) {
  ### this function runs Doornik Boswijk Iteration to estimate restricted alpha and beta
  ### It also estimates the separate MRCIVAR and compare it with the restricted including the model with identical beta.
  ### Add output of of separate Models.
  n   = dim(alpha)[1]
  crk = dim(alpha)[2]
  T1 = nrow(R1)
  S00 <- crossprod(R0)/T1
  S01 <- crossprod(R0, R1)/T1
  S10 <- crossprod(R1, R0)/T1
  S11 <- crossprod(R1)/T1

  alphai = alpha
  betai = beta
  Omegai = Omega
  VS10 = S10
  dim(VS10) <- c(length(S10),1)
  error = 1
  tol   = 0.0000001
  vecpip = solve(S11)%*%S10;dim(vecpip) = c(length(vecpip),1)

  phii = solve(t(H)%*%kronecker(t(alphai)%*%solve(Omegai)%*%alphai,S11)%*%H)%*%
    (t(H)%*%kronecker(t(alphai)%*%solve(Omegai),diag(nrow(beta)))%*%VS10
     - t(H)%*%kronecker(t(alphai)%*%solve(Omegai)%*%alphai,S11)%*%h)

  betai <-H%*%phii+h ; dim(betai) <- c(nrow(beta),crk)

  gammai = solve(t(G)%*%kronecker(solve(Omegai),t(betai)%*%S11%*%betai)%*%G)%*%
    t(G)%*%kronecker(solve(Omegai),t(betai))%*%VS10

  talphai <- G%*%gammai;dim(talphai) <- c(crk,nrow(alpha))
  alphai = t(talphai)

  Omegai = S00 - alphai%*%t(betai)%*%S10-S01%*%betai%*%t(alphai)+alphai%*%t(betai)%*%S11%*%betai%*%t(alphai)


  while  ( error > tol ) {

    phir   = phii
    gammar = gammai
    Omegar = Omegai

    phii = solve(t(H)%*%kronecker(t(alphai)%*%solve(Omegai)%*%alphai,S11)%*%H)%*%
      (t(H)%*%kronecker(t(alphai)%*%solve(Omegai),diag(nrow(beta)))%*%VS10
       - t(H)%*%kronecker(t(alphai)%*%solve(Omegai)%*%alphai,S11)%*%h)

    betai <-H%*%phii+h ; dim(betai) <- c(nrow(beta),crk)

    gammai = solve(t(G)%*%kronecker(solve(Omegai),t(betai)%*%S11%*%betai)%*%G)%*%
      t(G)%*%kronecker(solve(Omegai),t(betai))%*%VS10

    talphai <- G%*%gammai;dim(talphai) <- c(crk,nrow(alpha))

    alphai = t(talphai)

    Omegai = S00 - alphai%*%t(betai)%*%S10-S01%*%betai%*%t(alphai)+alphai%*%t(betai)%*%S11%*%betai%*%t(alphai)
    error = max( abs(log(det(Omegai))-log(det(Omegar))) )

  }
  LR =  T1*(log(det(Omegar))-log(det(Omega)))


  CI = Z1%*%betai

  if ((crk>0)&(length(Z2)>0)) {
    VECMR<-stats::lm(Y0-Z1%*%betai%*%t(alphai)~0+Z2)
    VECMRS <- summary_civar(lm1=VECMR,sname ="Z2")
    LSKOEFR = VECMR$coefficients
  }
  if ((crk>0)&(length(Z2)==0)) {
    VECMR  <- NULL
    LSKOEFR =  NULL
  }
  if ((crk == 0)&(length(Z2)>0)) {
    VECMR <-stats::lm(Y0~0+Z2)
    LSKOEFR = VECMR$coefficients
  }
  if ((crk == 0)&(length(Z2)==0)) {
    VECMR<-NULL
    LSKOEFR<-NULL
  }

  result <- new.env()
  result$VECMR      = VECMR
  result$VECMRS     = VECMRS
  result$betar      = betai
  result$alphar     = alphai
  result$LSKOEFR    = LSKOEFR
  result$LR         = LR
  result$error      = error
  rr<-as.list(result)
  return(rr)
}



#'
#' This function estimates constrained VECM using the iteration procedure proposed in Boswijk and Doornik (2003)
#'
#' @param res an estimated CIVAR object with without restrictions
#' @param H the restriction matrix on beta
#' @param h the restriction vector on beta ( free-varying parameters of beta )
#' @param phi the restriction vector on beta
#' @param G the restriction matrix on alpha
#' @param Dxflag A flag that indicates whether X enters the cointegration space.
#'
#' @section Details:
#' This function runs a likelihood ratio test of linear restrictions on \eqn{\alpha} and \eqn{\beta} in a CIVAR model in the following form:
#'		\deqn{vec(\alpha') = G \psi,  vec(\beta) = H\phi + h}
#'
#' example 1 (restrictions on alpha) test of exogeneity: one weakly exogenous variable
#'     vec(alpha) is n*crk x 1  vector
#'     G          is n*crk x (n-k)*crk matrix  (k is the number of weakly exogenous)
#'     psi        (n-k)*crk x 1 vector
#'     vec(beta)  is n*crk x 1 vector
#'     H          is n*crk x n*crk identity matrix
#'     phi        n*crk x 1 vector
#'     h          n*crk x 1 zero matrix implying ver(beta) = phi.
#'                (H is identity and h is zero vector implies only restrictions on alpha)
#'
#' example 2 (restrictions on beta ) test of PPP
#'     vec(alpha) is n*crk x 1 vector
#'     G          is n*crk x n*crk identity matrix, implying no restriction on alpha
#'     psi        n*crk x 1 vector
#'     vec(beta)  n*crk x 1 vector
#'     H          n*crk x 2 matrix that picks out the elements under restrictions
#'                two columns out of the identity matrix.
#'                ones in a row of H and zero in the corresponding h implies non-restricted beta.
#'     phi        2 x 1  vector
#'     h          n*crk x 1  non zero elements in this vector together with the zero elements in
#'                the corresponding row in H are the normalization conditions.
#'                (H is identity and h is zero vector implies only restrictions on alpha)
#'
#' @return a list containing (VECMRS, beter, alphae, LSKOEFR, LR and error)
#' @examples
#' X = matrix(stats::rnorm(2*207),207,2)
#' colnames(X) = c("ex1","ex2")
#' res_d  = CIVARData(n=6,p=2,T=207,crk=2,type="exog1", X=as.matrix(X))
#' colnames(res_d$Y) =  c("w","p","U_l","r","yn","y")
#' res_e =  CIVARest(res=res_d)
#' res_e$tst$erg
#' res_e$tst$beta
#' res_e$tst$VECMS
#' n = 6;  crk = 2
#' G = diag(n*crk); G0 = G; psi = matrix(1,n*crk,1); psi0=psi;   ### No restrictions on alpha
#' H = diag(n*crk); H2 = H[,-seq(1,n*crk,n)];
#' h2 = matrix(0,n*crk,1);
#' h2[seq(1,n*crk,n),1] = rep(1,crk);
#' phi2 = matrix(1,(n-1)*crk,1)                               ### no restrictions but normalization
#'
#' G0%*%psi0; H2%*%phi2+h2
#'
#' ABtest = CIVARTest(res=res_d,H=H2,h=h2,phi=phi2,G=G0,Dxflag=0)
#' ABtest$betar
#' ABtest$alphar
#' ABtest$VECMR$coefficients
#' ABtest$LR
#' #1-pchisq(ABtest$LR,2)   ### the fourth is the used restrictions
#'
#'
#' res_d  = CIVARData(n=7,p=2,T=207,crk=2,type="const")
#' colnames(res_d$Y) =  c("w","p","U_l","r","yn","y","fsi")
#' res_e =  CIVARest(res=res_d)
#' res_e$tst$erg
#' res_e$tst$beta
#' res_e$tst$VECMS
#'
#' n = 7;  crk = 2
#' G = diag(n*crk); G0 = G; psi = matrix(1,n*crk,1); psi0=psi;   ### No restrictions on alpha
#'
#' H = diag(n*crk); H2 = H[,-c(1,8)]; h2 = matrix(0,n*crk,1);
#' h2[c(1,8),1] = c(1,1);  phi2 = matrix(1,12,1)                 ### normalization
#'
#' G0%*%psi0; H2%*%phi2+h2
#'
#' ABtest = CIVARTest(res=res_d,H=H2,h=h2,phi=phi2,G=G0,Dxflag=1)
#' ABtest$LR
#' ABtest$betar
#' ABtest$alphar
#' #1-pchisq(ABtest$LR,4)
#'
#'
#' @export
civar_test <- function(res=res,H=H,h=h,phi=phi,G=G,Dxflag=0) {
###
### This function runs a likelihood ratio test of linear restrictions on alpha and beta in a CIVAR model
###
###             vec(alpha') = G psi , vec(beta) = H phi + h
###
###        example 1 (restrictions on alpha) test of exogeneity
###                  vec(alpha) is 45 x 1  vector  ( N = 9 crk = 5, defined by the model )
###                  G          is 45 x 40 matrix  ( the first variable is exogeneous, i.e. the 5 adjustment coefficient of the first variable are zero )
###                  psi        40 x 1 vector (free variaring parameters not appearing in the specification but implied by G)
###                  vec(beta)  is 45 x 1 vector   ( N = 0 crk = 5 )
###                  H          is 45 x 45 identity matrix
###                  phi        45 x 1 vector (free variaring parameters not appearing in the specification but implied by h =0
###                  h          45 x 1 zero matrix implying ver(beta) = phi  >> no restrictions on beta.
###                            (H is identity and h is zero vector implies only restrictions on alpha)
###
###        example 2 (restrictions on beta ) test of PPP
###                  vec(alpha) is 40 x 1  vector  ( N = 8 crk = 5 ) conditioal VECM  or VECMX model
###                  G          is 40 x 40 identity matrix, implying there is no restriction on alpha
###                  psi        40 x 1 vector (free variaring parameters not appearing in the specification but implied by the identity matrix G
###                  vec(beta)  is 45 x 1 vector   ( N = 8 crk = 5, defined by the model )
###                  H          is 45 x 2 matrix that picks out the elements under restricitons ( two colunms out of the identity matrix ) a zero row in H and the corresponding h implies zero-restrictions on beta.
###                             ones in a row of H and zero in the corresponding h implies non-restricted beta.
###                  phi        2  x 1  vector (free variaring parameters not appearing in the specification but implied by h =0
###                  h          45 x 1  non zero elements in this vector together with the zero elements in the corresponding row in H are the normalization conditions.
###                             (H is identity and h is zero vector implies only restrictions on alpha)
###
###
###
if (Dxflag==0) {
  res_e = civar_estimate(res=res)
  crk   = res_e$crk
  R0    = res_e$tst$R0
  R1    = res_e$tst$R1
  alpha = t(res_e$tst$estimation$coefficients[1:crk,])
  beta  = res_e$tst$beta
  Omega = res_e$tst$Omega
  Y0 = res_e$tst$Y0
  Z1 = res_e$tst$Z1
  Z2 = res_e$tst$Z2
  test <- ab_civar_test(R0,R1,G,H,h,alpha,beta,Omega,Y0,Z1,Z2)
}   else  {
y = res$Y
if (is.na(res$X)) x = 0 else x = res$X

if (res$type == "const") model = "III"
if (res$type == "none")  model = "I"
bnorm = "1"
type  = "eigen"
p     =  res$p
r     =  res$crk
### N = 7, crk = 5, alphe beta are N  x crk  = 7 x 5   H = 35x35 G 35x35
###  G = diag(35); h = matrix(0,35,1); h[c(1,8,15,22,29)] = c(1,1,1,1,1)  ; H = diag(35); H2 = H[,-c(1,8,15,22,29)]
test<-ab_l_rtest2(y,x,model = model, bnorm = bnorm,type = type,p = p, r=r, q = 0.95, H=H,h=h,G=G)
}
return(test)
}



#'
#' This function runs a test in cointegration space and provides an estimation of restricted alpha and beta.
#'
#' @param y the endogenous variables
#' @param x the exogenous variables
#' @param model Types of the deterministic specification
#' @param bnorm normalization of the cointegration vectors
#' @param type types of returns
#' @param p Lags of the CIVAR model
#' @param r the cointegration rank
#' @param q the significance level
#' @param H restriction matrix of beta
#' @param h restriction vector of beta
#' @param G restriction matrix of alpha
#' @export
#' @keywords internal
#'
ab_l_rtest2 =function (y,x,model = c("I","II","III","IV","V"), bnorm = c("1","2"),type = c("eigen", "trace"),p = 1, r = 2, q = 0.95, H=H,h=h,G=G)   {
###
### This function runs a likelihood ratio test of linear restrictions on alpha and beta in a CIVAR model
###
###		vec(alpha) = G psi , vec(beta) = H phi + h
###
###        example 1 (restrictions on alpha) test of exogeneity
###			   vec(alpha) is 45 x 1  vector  ( N = 9 crk = 5, defined by the model )
###                  G          is 45 x 40 matrix  ( the first variable is exogeneous, i.e. the 5 adjustment coefficient of the first variable are zero )
###		         psi        40 x 1 vector (free variaring parameters not appearing in the specification but implied by G)
###                  vec(beta)  is 45 x 1 vector   ( N = 0 crk = 5 )
###                  H          is 45 x 45 identity matrix
###                  phi        45 x 1 vector (free variaring parameters not appearing in the specification but implied by h =0
###                  h          45 x 1 zero matrix implying ver(beta) = phi  >> no restrictions on beta.
###			   (H is identity and h is zero vector implies only restrictions on alpha)
###
###        example 2 (restrictions on beta ) test of PPP
###  			   vec(alpha) is 40 x 1  vector  ( N = 8 crk = 5 ) conditioal VECM  or VECMX model
###                  G          is 40 x 40 identity matrix, implying there is no restriction on alpha
###		         psi        40 x 1 vector (free variaring parameters not appearing in the specification but implied by the identity matrix G
###                  vec(beta)  is 45 x 1 vector   ( N = 0 crk = 5, defined by the model )
###                  H          is 45 x 2 matrix that picks out the elements under restricitons ( two colunms out of the identity matrix ) a zero row in H and the corresponding h implies zero-restrictions on beta.
###                             ones in a row of H and zero in the corresponding h implies non-restricted beta.
###                  phi        2  x 1  vector (free variaring parameters not appearing in the specification but implied by h =0
###                  h          45 x 1  non zero elements in this vector together with the zero elements in the corresponding row in H are the normalization conditions.
###			   (H is identity and h is zero vector implies only restrictions on alpha)
###
###

    y <- as.matrix(y)
    model <- match.arg(model)
    type <- match.arg(type)
    #ret <- match.arg(ret)
    #ctable <- match.arg(ctable)
    if (q != 0.9 && q != 0.95 && q != 0.99) {
        return("please correct significance level")
    }
    ret = "statistics"

    p <- as.integer(p)
    N1 <- ncol(as.matrix(y))
    #N  <- ncol(as.matrix(y))
    if (N1<r) {
        return("y's dimension must be larger than r")
    }

    if  ( length(x) == 1 ) {  z <- y }
    else {
       z <- cbind(y,x)
    }

    M1 <- ncol(as.matrix(z))
    T <- nrow(as.matrix(z))
    ## Z <- embed(diff(z), p)
    Z <- embed_ts(diff(z), p)
    Y0 <- Z[, c(1:N1)]                # \Delta Y
    #X0 <- Z[,c((N1+1):M1)]           # \Delta X
    Z1 <- z[-T, ][p:(T - 1), ]        #      Z_1
    if ((p==1)&(length(x)==1)) {
       Z2 = NULL
       NOLAG = 1
    }
    else {
       Z2 <- Z[, c((N1+1):(M1*p))]       # \Delta Z_
    }
    T1 <- nrow(as.matrix(Y0))
    #lT = (1:T1)/(1:T1)
    lT = matrix(1,T1,1); colnames(lT) <- "Const"
    #Trend <- matrix((p + 1):TT, (TT - p), 1); colnames(Trend) <- "Trend"
    Trend <- matrix(1:T1, T1, 1); colnames(Trend) <- "Trend"
    if ( model == "I" ) {
    Y0 = Y0
    Z1 = Z1
    Z2 = Z2
    }
    if ( model == "II" ) {
    Y0 = Y0
    Z1 = cbind(lT,Z1)
    Z2 = Z2
    }
    if ( model == "III" ) {
    Y0 = Y0
    Z1 = Z1
    Z2 = cbind(Z2,lT)
    }
    if ( model == "IV" ) {
    Y0 = Y0
    Z1 = cbind(Trend,Z1)
    Z2 = cbind(Z2,lT)
    }
    if ( model == "V" ) {
    Y0 = Y0
    Z1 = cbind(Z1)
    Z2 = cbind(Z2,lT,Trend)
    }

    if (length(Z2)==0) {
        R0 <- Y0
        R1 <- Z1
    }
    else {

        M00 <- crossprod(Y0)/T1
        M11 <- crossprod(Z1)/T1
        M22 <- crossprod(Z2)/T1
        M01 <- crossprod(Y0, Z1)/T1
        M02 <- crossprod(Y0, Z2)/T1
        M10 <- crossprod(Z1, Y0)/T1
        M20 <- crossprod(Z2, Y0)/T1
        M12 <- crossprod(Z1, Z2)/T1
        M21 <- crossprod(Z2, Z1)/T1
        M22inv <- solve(M22)
        R0 <- Y0 - t(M02 %*% M22inv %*% t(Z2))
        R1 <- Z1 - t(M12 %*% M22inv %*% t(Z2))
    }
    S00 <- crossprod(R0)/T1
    S01 <- crossprod(R0, R1)/T1
    S10 <- crossprod(R1, R0)/T1
    S11 <- crossprod(R1)/T1
    Ctemp <- chol(S11, pivot = TRUE)
    pivot <- attr(Ctemp, "pivot")
    oo <- order(pivot)
    C <- t(Ctemp[, oo])
    Cinv <- solve(C)
    S00inv <- solve(S00)
    valeigen <- eigen(Cinv %*% S10 %*% S00inv %*% S01 %*% t(Cinv))

    #valeigen <- eigen(S11inv %*% S10 %*% S00inv %*% S01 )
    lambda <- valeigen$values
    e      <- valeigen$vector

    V <- t(Cinv) %*% e
    Vorg <- V
    V <- sapply(1:M1, function(j) V[, j]/V[1, j])
    W <- S01 %*% V %*% solve(t(V) %*% S11 %*% V)
    PI <- S01 %*% solve(S11)
    DELTA <- S00 - S01 %*% V %*% solve(t(V) %*% S11 %*% V) %*% t(V) %*% S10
    if (length(Z2)==0) {
       GAMMA = NULL
    }
    else {
       GAMMA <- M02 %*% M22inv - PI %*% M12 %*% M22inv
    }
    if (bnorm == "1") {
        beta   <- as.matrix(V[,1:r])
    }
    if (bnorm == "2") {
        beta = as.matrix(V[,1:r]%*%solve(V[1:r,1:r]))
    }

    if ((r>0)&(length(Z2)>0)) {
       CI = Z1%*%beta
       VECM<-stats::lm(Y0~0+CI+Z2)
       if (r==1)  { alpha = as.matrix(VECM$coefficients[1:1,]) }
       if (r > 1) { alpha = t(as.matrix(VECM$coefficients[1:r,])) }
       LSKOEF = stats::lm(Y0-Z1%*%beta%*%t(alpha)~0+Z2)$coefficients

    }
    if ((r>0)&(length(Z2)==0)) {
       CI = Z1%*%beta
       VECM<-stats::lm(Y0~0+CI)
       LSKOEF = NULL
    }
    if ((r == 0)&(length(Z2)>0)) {
       CI = 0
       VECM<-stats::lm(Y0~0+Z2)
       LSKOEF = stats::lm(Y0~0+Z2)$coefficients
    }
    if ((r == 0)&(length(Z2)==0)) {
       CI = 0
       VECM<-NULL
       LSKOEF = NULL
    }
    E = -T1 * log(1 - lambda)
    E = E[1:N1]
    LOGL = -T1/2.0*(log(det(S00))+sum(log((1-lambda)[1:r])))-T1*N1/2.0*log(2*pi)-T1*N1/2.0
    #LOGL = -T1/2.0*(log(det(S00))+sum(log((1-lambda)[1:N1])))-T1*N1/2.0*log(2*pi)-T1*N1/2.0

    Omega = 1.0/(nrow(VECM$residuals))*t(VECM$residuals)%*%VECM$residuals
    # T1*(log(det(Omega))-log(det(S00))-sum(log(1-lambda)[1:r]))   # correct

    ##### Estimation of VECM
    if (r==1)  { alpha = as.matrix(VECM$coefficients[1:1,]) }
    if (r > 1) { alpha = t(as.matrix(VECM$coefficients[1:r,])) }
    resultsvecm <- summary(VECM)

    if (model == "I") {
      Tab <- Tab1
    }
    if (model == "II") {
      Tab <- Tab2
    }
    if (model == "III") {
      Tab <- Tab3
    }
    if (model == "IV") {
      Tab <- Tab4
    }
    if (model == "V") {
      Tab <- Tab5
    }


    b = c(1:12)
    for (i in 1:12)   { b[i] = Tab[2*(i-1)+1,2+M1-N1] }
    a = c(1:12)
    for (i in 1:12)   { a[i] = Tab[2*i,2+M1-N1] }

    if (type == "eigen") {
        critical_vals = b
        M = matrix(0, N1, 1)
        j = 1
        rank = 0
        while (j <= N1 && E[j] > critical_vals[N1 + 1 - j]) {
            M[j, ] = M[j, ] + 1
            j = j + 1
            rank = rank + 1
        }
        if (ret == "test") {
            return(M)
        }
        erge <- cbind(E, critical_vals[N1:1])
        colnames(erge) <- c("teststatistic", "critical_value")

        if ( N1 > 1 ) {
           rownames(erge) <- c("r <= 0 |", paste("r <= ", 1:(N1 - 1),  " |", sep = ""))
        }
        if ( N1 == 1 ) {
           rownames(erge) <- c("r <= 0 |" )
        }

        coint_rank <- paste("Johansen-Test (with maximum-eigenvalue-teststatistic) indicates",
            rank, "cointegrating equation(s) at the", 1 - q,
            "level")
    }
    else {
        type = "trace"
        critical_vals = a
        stat = matrix(0, N1, 1)
        for (i in 1:N1) {
            sum = 0
            for (j in i:N1) {
                sum = sum + E[j]
            }
            stat[i] = sum
        }
        M = matrix(0, N1, 1)
        j = 1
        rank = 0
        while (stat[j] > critical_vals[N1 + 1 - j] && j <= N1) {
            M[j, ] = M[j, ] + 1
            j = j + 1
            rank = rank + 1
        }
        if (ret == "test") {
            return(M)
        }
        ergt <- cbind(stat, critical_vals[N1:1])
        colnames(ergt) <- c("teststatistic", "critical_value")

        if ( N1 > 1 ) {
           rownames(ergt) <- c("r <= 0 |", paste("r <= ", 1:(N1 - 1),  " |", sep = ""))
        }
        if ( N1 == 1 ) {
           rownames(ergt) <- c("r <= 0 |")
        }

        coint_rank <- paste("Johansen-Test (with trace-teststatistic) indicates",
        rank, "cointegrating equation(s) at the", 1 - q, "level")
    }
######### Calculation of restricted MLE for cointegrated system
   alphai = alpha
   betai = beta
   Omegai = Omega
   VS10 = S10
   dim(VS10) <- c(length(S10),1)
   error = 1
   tol   = 0.0001
   vecpip = solve(S11)%*%S10;dim(vecpip) = c(length(vecpip),1)

       phii = solve(t(H)%*%kronecker(t(alphai)%*%solve(Omegai)%*%alphai,S11)%*%H)%*%
          (t(H)%*%kronecker(t(alphai)%*%solve(Omegai),diag(nrow(beta)))%*%VS10
           - t(H)%*%kronecker(t(alphai)%*%solve(Omegai)%*%alphai,S11)%*%h)

       betai <-H%*%phii+h ; dim(betai) <- c(nrow(beta),r)

       gammai = solve(t(G)%*%kronecker(solve(Omegai),t(betai)%*%S11%*%betai)%*%G)%*%
          t(G)%*%kronecker(solve(Omegai),t(betai))%*%VS10

       #phii = solve(t(H)%*%kronecker(t(alphai)%*%solve(Omegai)%*%alphai,S11)%*%H)%*%
       #   t(H)%*%kronecker(t(alphai)%*%solve(Omegai),S11)%*%(vecpip-kronecker(alphai,diag(nrow(beta)))%*%h)

       #betai <-H%*%phii+h ; dim(betai) <- c(nrow(beta),r)

       #gammai = solve(t(G)%*%kronecker(solve(Omegai),t(betai)%*%S11%*%betai)%*%G)%*%
          t(G)%*%kronecker(solve(Omegai),t(betai)%*%S11)%*%vecpip

       talphai <- G%*%gammai;dim(talphai) <- c(r,N1)
       alphai = t(talphai)

       Omegai = S00 - alphai%*%t(betai)%*%S10-S01%*%betai%*%t(alphai)+alphai%*%t(betai)%*%S11%*%betai%*%t(alphai)


   while  ( error > tol ) {

         phir   = phii
         gammar = gammai
         Omegar = Omegai

       phii = solve(t(H)%*%kronecker(t(alphai)%*%solve(Omegai)%*%alphai,S11)%*%H)%*%
          (t(H)%*%kronecker(t(alphai)%*%solve(Omegai),diag(nrow(beta)))%*%VS10
           - t(H)%*%kronecker(t(alphai)%*%solve(Omegai)%*%alphai,S11)%*%h)

       betai <-H%*%phii+h ; dim(betai) <- c(nrow(beta),r)

       gammai = solve(t(G)%*%kronecker(solve(Omegai),t(betai)%*%S11%*%betai)%*%G)%*%
          t(G)%*%kronecker(solve(Omegai),t(betai))%*%VS10

       talphai <- G%*%gammai;dim(talphai) <- c(r,N1)
       alphai = t(talphai)

       Omegai = S00 - alphai%*%t(betai)%*%S10-S01%*%betai%*%t(alphai)+alphai%*%t(betai)%*%S11%*%betai%*%t(alphai)
       error = max( abs(log(det(Omegai))-log(det(Omegar))) )

       #phii = solve(t(H)%*%kronecker(t(alphai)%*%solve(Omegai)%*%alphai,S11)%*%H)%*%
       #   t(H)%*%kronecker(t(alphai)%*%solve(Omegai),S11)%*%(vecpip-kronecker(alphai,diag(nrow(betai)))%*%h)

       #betai <-H%*%phii+h ; dim(betai) <- c(nrow(beta),r)

       #gammai = solve(t(G)%*%kronecker(solve(Omegai),t(betai)%*%S11%*%betai)%*%G)%*%
       #   t(G)%*%kronecker(solve(Omegai),t(betai)%*%S11)%*%vecpip

       #talphai <- G%*%gammai;dim(talphai) <- c(r,N1)
       #alphai = t(talphai)

       #Omegai = S00 - alphai%*%t(betai)%*%S10-S01%*%betai%*%t(alphai)+alphai%*%t(betai)%*%S11%*%betai%*%t(alphai)
       #error = max( abs(log(det(Omegai))-log(det(Omegar))) )

       log(det(Omegai))
   }
   LR = T1*(log(det(Omegar))-log(det(S00))-sum(log(1-lambda)[1:r]))

   #CI = Z1%*%beta
   #stats::lm( Z1%*%t(alphai%*%t(betai))

    if ((r>0)&(length(Z2)>0)) {
       VECMR<-stats::lm(Y0-Z1%*%betai%*%t(alphai)~0+Z2)
       VECMRS <- summary_civar(lm1=VECMR,sname ="Z2")
       LSKOEFR = VECMR$coefficients
    }
    if ((r>0)&(length(Z2)==0)) {
       VECMR  <- NULL
       LSKOEFR =  NULL
    }
    if ((r == 0)&(length(Z2)>0)) {
       VECMR <-stats::lm(Y0~0+Z2)
       LSKOEFR = VECMR$coefficients
    }
    if ((r == 0)&(length(Z2)==0)) {
       VECMR<-NULL
       LSKOEFR<-NULL
    }

        result <- new.env()
        if (type == "trace")  {result$ergt = ergt}
        if (type == "eigen")  {result$erge = erge}
        result$estimation = VECM
  	  result$VECMRS     = VECMRS
        result$lambda     = E
        result$z          = z
        result$Z2         = Z2
        result$beta       = beta
        result$alpha      = alpha
        result$PI         = PI
        result$GAMMA      = GAMMA
        result$model      = model
        result$betar      = betai
        result$alphar     = alphai
        result$LSKOEFR    = LSKOEFR
        result$LSKOEF     = LSKOEF
        result$LR         = LR
        result$error      = error
        rr<-as.list(result)
        return(rr)
}



#'
#' @param R0 I(0) residuals of the auxiliary regression
#' @param R1 I(0) residuals of the auxiliary regression
#' @param Y0 The first difference series of the endogenous I(1) variables
#' @param Z2 The first difference series with lags
#' @param Z1 The level series
#' @param St The regime indicator series
#' @param crk The cointegration rank
#'
#' @return A list containing estimated constrained parameters as initial values for further iterations
#' @export
#' @keywords internal
#'
rz_st2_vecm <- function(R0,R1,Y0,Z2,Z1,St,crk) {
    #This function estimate separate MRCIVAR
    NSt  <- 1-St
    R0_1 <- R0*St
    R1_1 <- R1*St
    Z2_1 <- (Z2*St)[,which(colSums(Z2*St)!=0)]
    Z1_1 <- Z1*St
    Y0_1 <- Y0*St
    M1 <- ncol(as.matrix(Y0))


	 R0_2 <- R0*NSt
	 R1_2 <- R1*NSt
	 Z2_2 <- (Z2*NSt)[,which(colSums(Z2*NSt)!=0)]
	 Z1_2 <- Z1*NSt
    	 Y0_2 <- Y0*NSt


    S00 <- crossprod(R0_1)/sum(St)
    S01 <- crossprod(R0_1, R1_1)/sum(St)
    S10 <- crossprod(R1_1, R0_1)/sum(St)
    S11 <- crossprod(R1_1)/sum(St)

    Ctemp <- chol(S11, pivot = TRUE)
    pivot <- attr(Ctemp, "pivot")
    oo <- order(pivot)
    C <- t(Ctemp[, oo])
    Cinv <- solve(C)
    S00inv <- solve(S00)
    valeigen <- eigen(Cinv %*% S10 %*% S00inv %*% S01 %*% t(Cinv))
    lambda <- valeigen$values
    e <- valeigen$vector
    V <- t(Cinv) %*% e
    Vorg <- V
    V <- sapply(1:M1, function(j) V[, j]/V[1, j])
    W <- S01 %*% V %*% solve(t(V) %*% S11 %*% V)
    PI <- S01 %*% solve(S11)
    DELTA  <- S00 - S01 %*% V %*% solve(t(V) %*% S11 %*% V) %*% t(V) %*% S10
    #GAMMA <- M02 %*% M22inv - PI %*% M12 %*% M22inv
    beta1  <- as.matrix(V[, 1:crk])
    CI_1   <- Z1_1%*%beta1
    VECM_1 <- stats::lm(Y0_1[which(St!=0),]~0+CI_1[which(St!=0),]+Z2_1[which(St!=0),])
    alpha1 = t(VECM_1$coefficients[1:crk,])
    if (dim(alpha1)[1]==1) alpha1 <-t(alpha1)
    Omega1 =  t(VECM_1$residuals)%*%(VECM_1$residuals)/sum(St)

    VECM_1S <- summary_civar(lm1=VECM_1,sname ="Z2_1")


    S00 <- crossprod(R0_2)/sum(NSt)
    S01 <- crossprod(R0_2, R1_2)/sum(NSt)
    S10 <- crossprod(R1_2, R0_2)/sum(NSt)
    S11 <- crossprod(R1_2)/sum(NSt)

    Ctemp <- chol(S11, pivot = TRUE)
    pivot <- attr(Ctemp, "pivot")
    oo <- order(pivot)
    C <- t(Ctemp[, oo])
    Cinv <- solve(C)
    S00inv <- solve(S00)
    valeigen <- eigen(Cinv %*% S10 %*% S00inv %*% S01 %*% t(Cinv))
    lambda <- valeigen$values
    e <- valeigen$vector
    V <- t(Cinv) %*% e
    Vorg <- V
    V <- sapply(1:M1, function(j) V[, j]/V[1, j])
    W <- S01 %*% V %*% solve(t(V) %*% S11 %*% V)
    PI <- S01 %*% solve(S11)
    DELTA <- S00 - S01 %*% V %*% solve(t(V) %*% S11 %*% V) %*% t(V) %*% S10
    #GAMMA <- M02 %*% M22inv - PI %*% M12 %*% M22inv
    beta2 <- as.matrix(V[, 1:crk])
    CI_2 = Z1_2%*%beta2
    VECM_2 <- stats::lm(Y0_2[which(NSt!=0),]~0+CI_2[which(NSt!=0),]+Z2_2[which(NSt!=0),])
    alpha2 = t(VECM_2$coefficients[1:crk,])
    if (dim(alpha2)[1]==1) alpha2 <-t(alpha2)

    Omega2 =  t(VECM_2$residuals)%*%(VECM_2$residuals)/sum(NSt)

    VECM_2S <- summary_civar(lm1=VECM_2,sname ="Z2_2")

    ret = list(beta1,alpha1,VECM_1,VECM_1S,Omega1,beta2,alpha2,VECM_2,VECM_2S,Omega2)
    names(ret) = c("beta1","alpha1","VECM_1","VECM_1S","Omega1","beta2","alpha2","VECM_2","VECM_2S","Omega2")
    return(ret)
}



#'
#' @param x Optimization variables
#' @param beta Cointegration vectors
#' @param alpha Adjustment vectors
#' @param G A matrix specifying restrictions on alpha
#' @param H A matrix specifying restrictions on beta
#' @param phi Freely varying parameters in beta
#' @param psi Freely varying parameters in alpha
#' @param h A vector specifying restrictions in beta
#' @param Z1 I(1) data matrix
#' @param St Regime 1 indicator series
#' @param NSt Regime 2 indicator series
#' @param Y0 I(0) data matrix
#' @param Z2 I(0) data matrix
#'
#' @return Sum of squared residuals
#' @export
#' @keywords internal
f_constrained <- function(x, beta=beta,alpha=alpha,G=G,H=H,phi=phi,psi=psi,h=h, Z1, St, NSt, Y0, Z2) {
  ## this is a help function to incoporate restrictions on beta and regime specific alpha
  ## vec(alpha'_1) = G_1 psi_1,  vec(alpha'_2) = G_2 psi_2   , vec(beta) = H phi + h
  ##
  x1 = x[1:length(phi)]
  x2 = x[(1+length(phi)):(length(phi)+length(psi[[1]]))]
  x3 = x[(1+(length(phi)+length(psi[[1]]))):(length(phi)+length(psi[[1]])+length(psi[[2]]))]

  ### restriction on beta
  phi  = x1
  beta_v = H%*% phi + h
  dim(beta_v) = dim(beta)
  #?dim(x) = dim(beta)

  CI = Z1 %*% beta_v
  ### restrictions on alpha_1,alpha_2
  psi_1 = x2
  psi_2 = x3
  alpha_1 = G[[1]]%*%psi_1
  alpha_2 = G[[2]]%*%psi_2
  dim(alpha_1) = dim(alpha)
  dim(alpha_2) = dim(alpha)
  CI1 = (CI * St)%*%t(alpha_1)
  CI2 = (CI * NSt)%*%t(alpha_2)
  residuals <- stats::lm(Y0-CI1-CI2 ~ 0 + Z2)$residuals
  #SSR = sum(diag(t(residuals) %*% residuals))
  SSR <- det(t(residuals) %*% residuals)
  return(SSR)
}
