# data_input.R
# (re)generated by tools/02_split_to_modules.R



#'
#' This function generates data from a cointegrated global VAR process and returns an CIGVAR(m,n,p) object that is a list containing data and parameters used in the CIGVAR(m,n,p) process.
#'
#' @param m     : number of variables in each country/unit
#' @param n     : number of countries/units
#' @param p     : an (n x 3) matrix, each raw specifies the lag length of the domestic variables, the foreign variables and the number of the exogenous variables.
#' @param T     : number of observations.
#'
#'              (m,n,p,T) are parameters which must be provided.
#' @param W     : an (n x n) weighting matrix. w_ij is the weight of foreign country j in the foreign variables of i-th country diag(W)=0
#' @param r_npo : an (m, p, n) array collecting the roots of the characteristic functions in the lag operator of the country VAR. The number of ones in each ith row of r_npo is the number of unit roots i-th country/unit.
#' @param Ao    : an (m, m, p, n) array collecting the  coefficients of foreign variables.
#' @param Bo    : an (m, m, p, n) array collecting the  coefficients of domestic variables.
#' @param Co    : an (m , k+1, n) array collecting the coefficients of the deterministic components of the n countries.
#' @param Uo    : an (T x mn) matrix of the temporally independent innovation processes
#' @param Sigmao : (mn x mn) matrix of the covariance matrix of the CIGVAR(m,n,p)
#' (W,r_npo,Ao,Bo,Uo,Sigmao) if not provided, they will be generated randomly. The default assumption is one unit root in one country. Hence m-1 cointegration relations in each country.
#'
#' @param type	: deterministic component "const", "none", "exog0", and "exog1" are four options
#' @param X	: a (T x k x n) array of exogenous stationary variables.
#' @param mu    : if type = "const" mu has the same dimension as Co. is an muV is nm vector of the means of the time series in the system
#' @param DFYflag	: DFYflag = 0 implies foreign variables are not in the cointegration space. DFYflag = 1 allows foreign variables enter the cointegration relation.
#' @param crk   : n vector containing the cointegration rank in each country/unit. crk is to specified for estimation of parameters.
#' @param Ncommfakt   : number of common exogenous stochastic factors
#' @param A           : a transformation matrix that adds the common exogenous factors to the system.
#' @param uz          : innovations of the exogenous common factors
#' @return a CIGVAR object containing the generated data, the parameters used and the exogenous variables.
#'
#' @examples
#' n = 5
#' p = (1:15)*0; dim(p) = c(5,3)
#' p[,1] = 3; p[,2]=3;
#' res_d = cigvar_data(m=4,n=5,p=p,T=100,type="const")
#' max(abs(res_d$Y))
#' plot(ts(res_d$Y[,1:10]))
#' res_d$r_npo
#' spectral_radius(res_d$G)
#' res_e = cigvar_estimate(res_d)
#' res_e$Summary
#' spectral_radius(res_d$G)
#' plot(ts(res_d$Y[,1:10]))
#'
#' @export
cigvar_data <- function(m, n, p, T, W = NA, r_npo = NA, Ao = NA, Bo = NA, Co = NA, Uo = NA, Sigmao = NA, type = NA, X = NA, mu = NA, DFYflag = NA,  crk = NA, Ncommfakt=1,A=NA,uz=NA)
{

  if (missing(W)) {
    W = NA
  }
  if (missing(r_npo)) {
    maxPd = max(p[, 1])
    r_npo = c(1:(m * maxPd * n))/c(1:(m * maxPd * n)) * 4
    dim(r_npo) = c(m, maxPd, n)
    r_npo[1, 1, ] = 1
  }

  if (missing(Bo)) {
    Bo = NA
  }
  if (missing(Bo)) {
    Ao = NA
  }
  if (missing(Co)) {
    Co = NA
  }

  if (missing(Uo)) {
    Uo = NA
  }
  if (missing(Sigmao)) {
    Sigmao = NA
  }


  if (missing(type)) {
    type = NA
  }
  if (missing(X)) {
    X = NA
  }

  if (missing(mu)) {
    mu = NA
  }
  if (missing(DFYflag)) {
    DFYflag = 0
  }

  if (missing(crk)) {
    crk = (1:n)/(1:n)
  }
  if (missing(Ncommfakt)) {
    Ncommfakt = 0
  }


  alpha = list()
  beta = list()

  Pmax = max(p[, 1:2])
  P = max(p)
  if (!anyNA(X))
    k = dim(X)[2]
  if (anyNA(Bo)) {
    Bo = (1:(m * m * Pmax * n)) * 0
    dim(Bo) = c(m, m, Pmax, n)
    for (i in 1:n) {
      r_np = c(1:(m * p[i, 1])) * 0
      dim(r_np) = c(m, p[i, 1])
      r_np = r_npo[, 1:p[i, 1], i]
      VARD = var_data(m, p[i, 1], T, r_np = r_np)
      Bo[, , 1:p[i, 1], i] = VARD$B
      alpha[[i]] = b2_cib(VARD$B)[[2]]
      beta[[i]] = b2_cib(VARD$B)[[3]]
    }
  }
  if (anyNA(Sigmao)) {
    Sigmao = matrix(0, m * n, m * n)
    VARD = var_data(m * n, p[1, 1], T)
    Sigmao = VARD$Sigma
  }
  if (anyNA(Uo)) {
    Uo = rnorm_sigma(T, Sigmao)
  }
  if (anyNA(W)) {
    W = matrix(((1:(n * n))/(1:(n * n)) * 1/(n - 1)), n,
               n)
    for (i in 1:n) W[i, i] = 0
  }
  if (anyNA(Ao)) {
    Ao = (1:(m * m * Pmax * n)) * 0
    dim(Ao) = c(m, m, Pmax, n)
    for (i in 1:n) {
      if (p[i, 2] < 2)
        Ao = Ao
      if (p[i, 2] >= 2) {
        VARD = var_data(m, p = (p[i, 2] - 1), T)
        BB = VARD$B/1
        Ao[, , 1, i] = BB[, , 1] + alpha[[i]] %*% t(beta[[i]]) *DFYflag
        Ao[, , p[i, 2], i] = -BB[, , p[i, 2] - 1]
        if ((p[i, 2] - 1) >= 2) {
          for (L in 2:(p[i, 2] - 1)) Ao[, , L, i] = BB[,
                                                       , L] - BB[, , L - 1]
        }
      }
    }
  }
  if (anyNA(type)) {
    type = "none"
  }
  if (type == "none") {
    Co = matrix(0, m, n)
    dim(Co) = c(m, 1, n)
    mu = matrix(0, m, n)
    dim(mu) = c(m, 1, n)
  }
  G = (1:(n * m * n * m * Pmax)) * 0
  dim(G) = c(n * m, n * m, Pmax)
  for (i in 1:n) {
    for (j in 1:n) {
      for (L in 1:Pmax) G[(1 + (i - 1) * m):(i * m), (1 +
                                                        (j - 1) * m):(j * m), L] = Ao[, , L, i] * W[i,
                                                                                                    j]
    }
  }
  for (i in 1:n) {
    for (L in 1:Pmax) G[(1 + (i - 1) * m):(i * m), (1 + (i -
                                                           1) * m):(i * m), L] = Bo[, , L, i]
  }
  Ct = Uo * 0
  if (type == "const") {
    if (anyNA(mu)) {
      mu = matrix(stats::rnorm(n * m), m, n)
      dim(mu) = c(m, 1, n)
    }
    if (anyNA(Co)) {
      Co = mu
      muV = as.vector(mu)
      CoV = muV
      for (L in 1:Pmax) CoV = CoV - G[, , L] %*% muV
      Co = CoV
      dim(Co) = c(m, 1, n)
    }
    else {
      H = diag(n * m)
      for (L in 1:Pmax) H = H - G[, , L]
      CoV = as.vector(Co)
      if (min(abs(eigen(H)$values)) > 0.001) {
        muV = solve(H) %*% CoV
        mu = muV
        dim(mu) = c(m, 1, n)
      }
      else {
        mu = NA
      }
    }
    Ct = matrix(1, T, 1) %*% t(CoV)
  }
  if (type == "exog0") {
    if (anyNA(Co)) {
      Co = matrix(stats::rnorm(m * n * (k + 1)), m * (k +
                                                        1), n)
      dim(Co) = c(m, k + 1, n)
      Co[, 1, ] = (1:m) * 0
      for (i in 1:n) if (p[i, 3] < k)
        Co[, (p[i, 3] + 2):(k + 1), i] = Co[, (p[i, 3] +
                                                 2):(k + 1), i] * 0
    }
    DMCo = dim(Co[, -1, ])
    if (length(DMCo) < 3)
      DMCo = c(dim(Co)[1], 1, dim(Co)[3])
    if (!(DMCo[2] == dim(X)[2]) | !(DMCo[1] == m) | !(DMCo[3] ==
                                                      n)) {
      print("dimension problem")
      return("dimension")
    }
    CoV = matrix(0, dim(X)[2], m * n)
    for (i in 1:dim(X)[2]) CoV[i, ] = as.vector(Co[, 1 +
                                                     i, ])
    Ct = matrix(0, dim(X)[1], m * n)
    for (i in 1:n) Ct[, ((i - 1) * m + 1):((i - 1) * m +
                                             m)] = as.matrix(X[, , i]) %*% CoV[, ((i - 1) * m +
                                                                                    1):((i - 1) * m + m)]
    mu = NA
  }
  else {
    if (type == "exog1") {
      if (anyNA(Co)) {
        Co = matrix(stats::rnorm(m * n * (k + 1)), m *
                      (k + 1), n)
        dim(Co) = c(m, k + 1, n)
        for (i in 1:n) if (p[i, 3] < k)
          Co[, (p[i, 3] + 2):(k + 1), i] = Co[, (p[i,
                                                   3] + 2):(k + 1), i] * 0
      }
      DMCo = dim(Co[, -1, ])
      if (!(DMCo[2] == dim(X)[2]) | !(DMCo[1] == m) | !(DMCo[3] ==
                                                        n)) {
        print("dimension problem")
        return("dimension")
      }
      CoV = matrix(0, dim(X)[2] + 1, m * n)
      for (i in 1:(1 + dim(X)[2])) CoV[i, ] = as.vector(Co[,
                                                           i, ])
      Ct = matrix(0, dim(X)[1], m * n)
      for (i in 1:n) Ct[, ((i - 1) * m + 1):((i - 1) *
                                               m + m)] = cbind(matrix(1, dim(X)[1], 1), X[,
                                                                                          , i]) %*% CoV[, ((i - 1) * m + 1):((i - 1) *
                                                                                                                               m + m)]
      mu = NA
    }
    else {
      X = NA
    }
  }
  Y = Uo + Ct
  for (t in (P + 1):T) {
    for (L in 1:Pmax) Y[t, ] = Y[t, ] + Y[t - L, ] %*% t(G[,
                                                           , L])
  }
  check = max(abs(Y))

  if (Ncommfakt>0) {

    uz = rnorm_sigma(T,diag(Ncommfakt))
    Z = uz
    for (i in 3:T) Z[i,] = Z[i-1,]*1.4-Z[i-2,]*0.4+uz[i,]

    if (anyNA(A)) {
      A = diag(m*n+Ncommfakt)
      #for (i in 1:n) {A[(i-1)*m+Ncommfakt+(m-(Ncommfakt-1)):m ] = diag(Ncommfakt)*50*max(abs(Y[,i*m]))/max(abs(Z))}
      A[(Ncommfakt+1):(Ncommfakt+n*m),1:Ncommfakt]  = 0.3
    }

    YY <- cbind(Z,Y);

    Y = (YY%*%t(A))[,Ncommfakt+(1:(m*n))]
    dim_GC = dim(G); dim_GC[1:2] = dim_GC[1:2]+Ncommfakt
    GC = c(1:prod(dim_GC))*0; dim(GC) = dim_GC
    GC[(Ncommfakt+1):(Ncommfakt+n*m),(Ncommfakt+1):(Ncommfakt+n*m),] = G
    GC[1:Ncommfakt,1:Ncommfakt,1] = 1.4*diag(Ncommfakt); GC[1:Ncommfakt,1:Ncommfakt,2] = -0.4*diag(Ncommfakt)  # assuming unit root common factor(s)
    for (i in 1:Pmax) GC[,,i] = A%*%GC[,,i]%*%solve(A)

    Uo = (cbind(uz,Uo)%*%t(A))[,Ncommfakt+(1:(m*n))]
    Do = (1:(m*n*Pmax*Ncommfakt))*0; dim(Do) = c(m,Ncommfakt,Pmax,n)

  }  else  {
    Z  = NA
    uz = NA
    A  = NA
    GC = NA
    Do = NA
  }

  result = list(Y, X, Uo, G, Sigmao, r_npo, Ao, Bo, Co, W, m, n, p, mu, check, type, crk, Ct,DFYflag,GC,uz,Z,A,Ncommfakt,Do)
  names(result) = c("Y", "X", "Uo", "G", "Sigmao", "r_npo", "Ao", "Bo", "Co", "W", "m", "n", "p", "mu", "check","type", "crk","Ct","DFYflag","GC","uz","Z","A","Ncommfakt","Do")
  return(result)
}



#'
#' This function generates data from a cointegrated vector autoregressive process CIVAR(p) and returns CIVAR(p) object that is a list containing data and parameters used in the CIVAR(p) process.
#'
#' @param n     : number of variables
#' @param p     : lag length
#' @param T     : number of observations
#' @param r_np  : an (n x p) matrix of roots of the characteristic polynomials of n independent AR(p)-processes. An element 1 in a row implies a unit root process. If the matrix is not provided, it will be generated randomly with one unit root in the first row.
#' @param A     : an (n x n) full rank transformation matrix that is used to generate correlated a CIVAR(p) from the n independent AR(p) processes with unit roots.
#' @param B     : an (n,n,p) array containing the coefficients of the CIVAR(p) process. If B is not given, it will be calculated out of r_np and A.
#' @param Co    : an (n,k+1) matrix containing coefficients of deterministic components in a CIVAR(p) process. For type="none" Co = 0*(1:n), for type="const" Co is an n vector, for type="exog0" Co is a (n,k) matrix, and for type="exog1" Co is an (n,1+k) matrix.
#' @param C1    : an (n,1) matrix containing coefficients of the trend component. C1 = 0 if there is no trend in the data.
#' @param U     : residuals, if it is not NA it will be used as input to generate the CIVAR(p)
#' @param Sigma : an n x n covariance matrix of the CIVAR(p)
#' @param type  : types of deterministic components. "none","rconst","const","rtrend", "trend", "exog0" and "exog1" are 7 options
#'                \itemize{
#'                \item{none: }{No deterministic component in VECM (Case I)}
#'                \item{rconst: }{An intercept restricted in the cointegration space (Case II)}
#'                \item{const: }{An unrestricted intercept (Case III)}
#'                \item{rtrend: }{An trend component restricted in the cointegration space and an unrestricted intercept in VECM (Case IV)}
#'                \item{trend: }{An unrestricted trend component and an unretricted intercept in VECM (Case V)}
#'                \item{exog0: }{Model with exogeneous variable and no deterministic components}
#'                \item{exog1: }{Model with exogeneous variable and an unrestricted intercept}
#'                }
#' @param X     : a (T x k) matrix of exogenous variables.
#' @param mu    : an n vector of drifts of the CIVAR(p) process
#' @param Yo    : (p x n) matrix of initial values of the process
#' @param crk   : number of cointegration relations. It equals n-r, where r is the number of unit roots.
#' @return An object of CIVAR(p) containing the generated data, the parameters used and the exogenous variables. res = list(n,p,type,r_np,Phi,A,B,Co,Sigma,Y,X,resid,U,Y1,Yo,check)
#' @examples
#' res_d = civar_data(n=2,p=2,T=100,type="const")
#' res_d = civar_data(n=2,p=2,T=10,Co=c(1:2)*0,type="none")
#' res_d = civar_data(n=2,p=2,T=10,Co=c(1:2)*NA,  type="const")
#'
#' p = 3
#' n = 4
#' r_np = matrix(c(1,2,1.5,1.5,2.5,2.5,2,-1.5,2,-4,1.9,-2.1),4,3)
#'
#' res_d  = civar_data(n=4,p=3,T=200,r_np=r_np,Co=matrix(0,n,1) ,type="none",crk=3)
#' res_e  = civar_estimate(res=res_d)
#' sum(abs(res_e$B-res_d$B))
#' sum(abs(res_e$Co-res_d$Co))
#'
#'
#' res_d  = civar_data(n=4,p=3,T=200)
#' res_e = civar_estimate(res=res_d)
#' sum(abs(res_e$B-res_d$B))
#' sum(abs(res_e$Co-res_d$Co))
#' plot(ts(res_d$Y))
#' @export
civar_data <- function (n, p, T, r_np, A, B, Co, C1,U, Sigma, type, X, mu, Yo, crk)
{
  if (missing(r_np)) {
    r_np = NA
  }
  if (missing(A)) {
    A = NA
  }
  if (missing(B)) {
    B = NA
  }
  if (missing(Co)) {
    Co = NA
  }
  if (missing(C1)) {
    C1 = NA
  }
  if (missing(U)) {
    U = NA
  }
  if (missing(Sigma)) {
    Sigma = NA
  }
  if (missing(type)) {
    type = NA
  }
  if (missing(X)) {
    X = NA
  }
  if (missing(mu)) {
    mu = NA
  }
  if (missing(Yo)) {
    Yo = NA
  }
  if (missing(crk)) {
    crk = NA
  }
  if (anyNA(r_np)) {
    r_np = matrix(0, n, p)
    for (i in 1:n) r_np[i, ] <- 0.51/(stats::runif(p) - 0.5)
    if (anyNA(crk)) {
      r_np[1, 1] = 1
      crk = n - 1
    }
    else {
      for (j in 1:(n - crk)) r_np[j, 1] = 1
    }
  }
  d = dim(r_np)
  if (!(n == d[1] & p == d[2])) {
    print("dimension problem")
    return("dimension")
  }
  Phi = NA
  if (anyNA(Phi)) {
    Phi = matrix(0, n, p)
    for (i in 1:n) Phi[i, ] = roots_to_coef(p, r_np[i, ])
  }
  if (anyNA(A)) {
    A = matrix(stats::runif(n * n), n, n)
    A = A %*% t(A)
    A = eigen(A)[[2]]
  }
  if (anyNA(B)) {
    B = matrix(0, n, n * p)
    dim(B) = c(n, n, p)
    if (n == 1) {
      B = Phi
      dim(B) = c(n, n, p)
    }
    if (n > 1) {
      for (i in 1:p) B[, , i] = A %*% diag(Phi[, i]) %*%
          t(A)
    }
  }
  if (anyNA(Sigma)) {
    Sigmao = matrix(stats::rnorm(n * n), n, n)
    Sigmao = Sigmao %*% t(Sigmao)
    Sigma = A %*% Sigmao %*% t(A)
  }
  else {
    Sigmao = solve(A) %*% Sigma %*% solve(t(A))
  }
  if (anyNA(U)) {
    Uh = rnorm_sigma(T, Sigmao)
    U = Uh %*% t(A)
  }
  else {
    Uh = U %*% solve(t(A))
  }
  if (anyNA(Yo)) {
    Yo = Uh
  }
  else {
    Uh[1:p, ] = Yo
    Yo = Uh
  }
  for (i in 1:n) {
    for (t in (p + 1):T) {
      for (L in 1:p) Yo[t, i] = Yo[t, i] + Yo[t - L, i] *
          Phi[i, L]
    }
  }
  Y1 = Yo %*% t(A)
  Ct = U * 0
  if (anyNA(type)) {
    type = "const"
  }
  #type_soll = infer_deterministic_type(Co, X, type)
  #if (!type_soll == type)
  #  return(list("type mismatch", type_soll, type))
  if (!anyNA(Co) & (!nrow(as.matrix(Co)) == n))
    return("dimension mismatch")

  if ((type == "none") & (anyNA(Co)) & (anyNA(C1))) {
    Co = matrix(0, n, 1)
    C1 = matrix(0, n, 1)
  }
  if ((type == "rtrend") & (anyNA(Co)) & (anyNA(C1))) {
    if (anyNA(mu)) {
      mu = matrix(stats::rnorm(n), n, 1)
    }
    if (anyNA(Co)) {
      Co = mu
      for (L in 1:p) Co = Co - B[, , L] %*% mu
    }
    else {
      H = diag(n)
      for (L in 1:p) H = H - B[, , L]
      if (min(abs(eigen(H)$values)) > 1e-13)
        mu = solve(H) %*% Co
      else mu = NA
    }

    gamma0 <- rep(1,n)
    CIBo <- b2_cib(B)[[1]][,,1]
    C1 <- CIBo%*%gamma0
    Ct <- matrix(c(1:T),T,1)%*%t(C1) + matrix(1, T, 1) %*% t(Co)
  }

  if ((type == "trend") & (anyNA(C1)) & (anyNA(Co))) {
    if (anyNA(Co))  Co = matrix(2, n, 1)
    if (anyNA(C1))  C1 = matrix(1, n, 1)
    CIBo <- b2_cib(B)[[1]][,,1]
    Ct <- matrix(c(1:T),T,1)%*%t(C1) + matrix(1, T, 1) %*% t(Co)
  }
  if (type == "const") {
    if (anyNA(mu)) {
      mu = matrix(stats::rnorm(n), n, 1)
    }
    if (anyNA(Co)) {
      Co = mu
      for (L in 1:p) Co = Co - B[, , L] %*% mu
    }
    else {
      H = diag(n)
      for (L in 1:p) H = H - B[, , L]
      if (min(abs(eigen(H)$values)) > 1e-13)
        mu = solve(H) %*% Co
      else mu = NA
    }
    Ct = matrix(1, T, 1) %*% t(Co)
    C1 = matrix(0,n,1)
  }
  if (type == "rconst") {
    gamma0 = rep(1,n)
    CIBo <- b2_cib(B)[[1]][,,1]
    Co = CIBo%*%gamma0
    C1 = matrix(0,n,1)
    Ct = matrix(1, T, 1) %*% t(Co)
  }


  if (type == "exog0" & anyNA(Co)) {
    k = ncol(as.matrix(X))
    Co = matrix(stats::rnorm(n * (k + 1)), n, k + 1)
    Co[, 1] = 0
  }
  if (type == "exog1" & anyNA(Co)) {
    k = ncol(as.matrix(X))
    Co = matrix(stats::rnorm(n * (k + 1)), n, k + 1)
  }
  if (!anyNA(X)) {
    if (type == "exog0")
      Ct = X %*% t(Co[, -1])
    if (type == "exog1")
      Ct = as.matrix(cbind((1:T)/(1:T), X)) %*% t(Co)
  }
  else {
    X = NA
  }
  if (n > 0) {
    Y = U + Ct
    for (tt in (p + 1):T) {
      for (L in 1:p) Y[tt, ] = Y[tt, ] + Y[tt - L, ] %*%
          t(B[, , L])
    }
  }
  check = max(abs(Y1))
  resid = Uh
  result = list(n, p, type, r_np, Phi, A, B, Co, C1, Sigma, Y,X, resid, U, Y1, Yo, check, crk)
  names(result) = c("n", "p", "type", "r_np", "Phi", "A", "B", "Co","C1", "Sigma","Y", "X", "resid", "U", "Y1","Yo", "check", "crk")
  return(result)
}



#'
#' The function generates data from a conditional cointegrated VAR(p)
#'
#' @param n1 dimension of the conditional cointegrated process
#' @param n2 dimension of the conditioning variables
#' @param crk the cointegration rank
#' @param p lag
#' @param T number of observations
#' @param type types of the deterministic component. "none" and "const" are two options.
#' @param Bc Coefficient matrix of the joint cointegration process
#'
#' @return a CCIVAR object which is a list of (n1,n2,p,type,r_np,By,Bx,Cy,Sigma,Y,X,resid,U,check,crk,Bc,Cc)
#' @export
#'
#' @examples
#'
#' T = 100
#' res_d <- ccivar_data(n1=4,n2=3,crk=3,p=3,T=T,type="const")
#' res_e <- cciva_rest(res=res_d)
#' res_e$Summary
#'
#' @export
ccivar_data <- function(n1,n2,crk,p,T,type,Bc=NA) {
  n = n1+n2
  if (anyNA(Bc)) {
    res_d = civar_data(n=n,p=p,T=T,type=type,crk=crk)
    B     = res_d$B
    BAB = b2_cib(B)
    alpha <- Re(BAB[[2]]); alpha[(n1+1):(n1+n2),]<- 0
    beta  <- Re(BAB[[3]])
    CIB   <- BAB[[1]]
    CIB[,,1] = alpha%*%t(beta)
    Bc = cib3_b(CIB)
  }
  red_d = civar_data(n=n,p=p,T=T,B=Bc,Co = rep(1,n),type=type,crk=crk)
  r_np <- red_d$r_np
  Bd <- red_d$B[1:n1,,]
  By = Bd[,1:n1,]
  Bx = Bd[,(n1+1):(n1+n2),]
  Cy = red_d$Co[1:n1]
  Sigma = red_d$Sigma[1:n1,1:n1]
  Y = red_d$Y[,1:n1]
  X = red_d$Y[,(n1+1):(n1+n2)]
  resid = red_d$resid[,1:n1]
  check = max(abs(red_d$Y))
  U     = red_d$U[,1:n1]
  Bc    <- red_d$B
  Cc    <- red_d$Co
  result <- list(n1,n2,p,type,r_np,By,Bx,Cy,Sigma,Y,X,resid,U,check,crk,Bc,Cc)
  names(result) = c("n1","n2", "p", "type", "r_np", "By", "Bx", "Cy", "Sigma", "Y", "X", "resid","U","check","crk","Bc","Cc")
  return(result)
}



#'
#' This function generates and estimates a mixed VECM with I(0) and I(1) variables
#'
#' @param n	: dimension of the mixed CIVAR
#' @param p	: lag of the mixed CIVAR
#' @param T : number of observations or length of the generated data
#' @param r : number of unit roots in the joint CIVAR
#' @param k  : number of I(0) variables
#' @param type : types of the deterministic components in the conditional CIVAR
#' @param Bo : coefficient matrix of the mixed CIVAR
#' @param Y : data of the mixed CIVAR
#' @param X : data of the exogenous variables
#' @param D : transformation matrix to mix the I(0) and I(1) components
#' @param Go : pre-loaded selection matrix
#' @param B : coefficient matrix of the mixed CIVAR
#' @param Sigma : covariance matrix of the residuals
#'
#' @return  a list contains estimation and test results of the mixed VECM
#' @examples
#'
#' #RR <- m_ix_civar_data(n=9,p=2,T=209,r=5,k=2,type="const",Bo=NA,Y=NA,D=NA)
#' ## DGP of I(1) and I(0) mixed VECM
#' #plot(ts(RR$Y))
#' #
#' #### testing the mixed VECM via testing the restrictions on beta
#' #res_d <- civar_data(n=9,p=2,T=209,type="const",crk=4)
#' #res_e = civar_estimate(res=res_d)
#' #res_e$Summary
#' #n = 9; crk = 4; k = 2; r = 5
#' #CC  <- c(8,9,17,18)
#' #GG  <- c(19:25,28:34)
#' #G = diag(n*crk); psi=matrix(1,n*crk,1)
#' #### this implies there is no restrictions on the adjustment coefficients alpha
#' #H = diag(n*crk);              H2 = H[,-c(seq(1,(n-r-k)*n,n),seq((n-r-k+1)*n,(n-r)*n,n),CC,GG)]
#' #### only normalization
#' #h = matrix(0,n*crk,1);         h[c(seq(1,(n-r-k)*n,n),seq((n-r-k+1)*n,(n-r)*n,n)),1] <- 1
#' #phi = matrix(1,ncol(H2),1)
#' ### check consistency of the restrictions    G%*%psi; H2%*%phi + h
#' #
#' #G%*%psi; H2%*%phi + h
#' #
#' #ABtest = civar_test(res=res_d,H=H2,h=h,phi=phi,G=G,Dxflag=0)
#' #ABtest$betar
#' #ABtest$alphar
#' #ABtest$VECMR$coefficients
#' #ABtest$LR
#' #1-pchisq(ABtest$LR,14)   ### The Ho of last two are I(0) is rejected
#' #
#' #res_d$Y = RR$Y           ### replacing the data of two I(0) variables
#' #ABtest = civar_test(res=res_d,H=H2,h=h,phi=phi,G=G,Dxflag=0)
#' #ABtest$betar
#' #ABtest$alphar
#' #ABtest$VECMR$coefficients
#' #ABtest$LR
#' #1-pchisq(ABtest$LR,14)  ### The Ho of last two are I(0) cannot be rejected
#' #
#' #RR$GABtest$LR           ## RR contains the same LR
#' #
#' #
#' @export
#'
m_ix_civar_data = function(n,p,T,r,k,type,Bo=NA,Y=NA,X=NA,D=NA,Go=NA,B=NA,Sigma = NA) {

  if (anyNA(Bo)) {
    repeat {
      res_d  = var_data(n=n,p=p,T=T,type=type)
      Bo <- res_d$B
      Bo[,1:r,p] = 0
      if (max(Mod(spectral_radius(Bo))) < 0.9) break
    }
  }
  res_d  = var_data(n=n,p=p,T=T,B=Bo,type=type)
  U = res_d$U
  Z = as.matrix(res_d$Y[,1:r]); for (i in 2:T) Z[i,] = Z[i-1,]+Z[i,]
  X <- res_d$Y[,(r+1):n]
  #plot(ts(cbind(Z,X)))

  if (anyNA(D)) {
    D = matrix(stats::rnorm(n*n),n,n)
    #solve(D)
    #D[1:(n-k),(n-k+1):n] <-0
    D[(n-k+1):n,1:(n-k)] <-0
    #D[(n-k+1):n,1:r] <-0
  }
  YS = cbind(Z,X)%*%t(D)
  #plot(ts(YS))
  crk <- n-r
  ########### restricted CIVAR

  B1 <- Bo
  B1[1:r,1:r,1]    =  Bo[1:r,1:r,1]  +  diag(r)
  B1[1:n,1:r,p]    = -Bo[1:n,1:r,p-1]
  if (p>2) for (i in 2:(p-1)) B1[1:n,1:r,i]  = Bo[1:n,1:r,i] - Bo[1:n,1:r,i-1]
  #spectral_radius(B1)

  if (anyNA(B)) {
    B2 <- B1*0
    for (i in 1:p) B2[,,i] <- D%*%B1[,,i]%*%solve(D)
  } else B2 <- B

  #spectral_radius(B2)

  #Co = seq(1,n,1)/seq(1,n,1)
  #U[1:2,] <- 0
  #res_d  = var_data(n=n,p=p,T=T,B=Bo,Co=Co*0,type="const",U=U,Yo=U[1:p,]*0)
  #ZZ <- res_d$Y[,1:r]; Z = ZZ*0; for (i in 3:T) Z[i,] = Z[i-1,]+ZZ[i,];X <- res_d$Y[,(r+1):n]
  #res_dd = var_data(n=n,p=p,T=T,B=B1,Co=Co*0,type="const",U=U,Yo=Yo)
  #res_ddd= var_data(n=n,p=p,T=T,B=B2,Co=Co*0,type="const",U=U%*%t(D),Yo=U[1:p,]*0)
  #Y =  cbind(Z,X)%*%t(D)
  #res_ddd$Y - Y

  ##############
  res_d <- civar_data(n=n,p=p,T=T,B=B2,type=type,crk=crk,Sigma=Sigma)
  #plot(ts(res_d$Y))
  if (!anyNA(Y)) res_d$Y <-Y
  #res_d$Y <- Y
  #plot(ts(res_d$Y))
  res_e = civar_estimate(res=res_d)

  G = diag(n*crk); psi=matrix(1,n*crk,1)          #### this implies there is no restrictions on the adjustment coefficient alpha
  H = diag(n*crk);              H2 = H[,-c(seq(1,(n-r-k)*n,n),seq((n-r-k+1)*n,(n-r)*n,n))]   #### only normalization
  h = matrix(0,n*crk,1);        h[c(seq(1,(n-r-k)*n,n),seq((n-r-k+1)*n,(n-r)*n,n)),1] <- 1 ;
  phi = matrix(1,(n-1)*crk,1)

  ### second set of normalization beta' = (I,beta_2') not done
  G = diag(n*crk); psi=matrix(1,n*crk,1)          #### this implies there is no restrictions on the adjustment coefficient alpha
  H = diag(n*crk);              H2 = H[,-c(seq(1,(n-r-k)*n,n),seq((n-r-k+1)*n,(n-r)*n,n))]   #### only normalization
  h = matrix(0,n*crk,1);        h[c(seq(1,(n-r-k)*n,n),seq((n-r-k+1)*n,(n-r)*n,n)),1] <- 1 ;
  phi = matrix(1,(n-1)*crk,1)

  ### check restrictions: G%*%psi  ; H2%*%phi+h
  ### c(seq(1,(n-r-k)*n,n),seq((n-r-k+1)*n,(n-r)*n,n))

  ABtest = civar_test(res=res_d,H=H2,h=h,phi=phi,G=G,Dxflag=0)


  ABtest$betar
  ABtest$alphar
  ABtest$VECMR$coefficients
  ABtest$LR
  1-stats::pchisq(ABtest$LR,1)   ### the fourth is the used restrictions


  ##################
  CCo = seq(n-k,(n-r-k)*n,n)
  CC  <-CCo+1
  if (k > 1) for (i in 2:k) CC = cbind(CC,CCo+i)
  CC = as.vector(t(CC))
  GGo = 1:(n-k)
  GG <- (n-r-k)*n + GGo
  if (k>1) for (i in 2:k) GG = cbind(GG,GGo+(n-r-k+i-1)*n)
  GG <- as.vector(t(GG))
  GG0 = 1:r
  GG1 <- (n-r-k)*n + GG0
  #GG1 <- c(2,3)
  if (k>1) for (i in 2:k) GG1 = cbind(GG1,GG0+(n-r-k+i-1)*n)
  GG1 <- as.vector(GG1)
  G = diag(n*crk); psi=matrix(1,n*crk,1)          #### this implies there is no restrictions on the adjustment coefficient alpha
  H = diag(n*crk);              H2 = H[,-c(seq(1,(n-r-k)*n,n),seq((n-r-k+1)*n,(n-r)*n,n),GG1)]   #### normalization + I(0) B31=0
  h = matrix(0,n*crk,1);        h[c(seq(1,(n-r-k)*n,n),seq((n-r-k+1)*n,(n-r)*n,n)),1] <- 1 ;
  phi = matrix(1,(n-1)*crk-k*r,1)

  ### check restrictions: G%*%psi  ; H2%*%phi+h
  ### c(seq(1,(n-r-k)*n,n),seq((n-r-k+1)*n,(n-r)*n,n))

  AABtest = civar_test(res=res_d,H=H2,h=h,phi=phi,G=G,Dxflag=0)

  AABtest$betar
  AABtest$alphar
  AABtest$VECMR$coefficients
  AABtest$LR
  1-stats::pchisq(AABtest$LR,k*(n-r))   ### the fourth is the used restrictions
  #plot(ts(res_d$Y))


  #################


  CCo = seq(n-k,(n-r-k)*n,n)
  CC  <-CCo+1
  if (k > 1) for (i in 2:k) CC = cbind(CC,CCo+i)
  CC = as.vector(t(CC))
  GGo = 1:(n-k)
  GG <- (n-r-k)*n + GGo
  if (k>1) for (i in 2:k) GG = cbind(GG,GGo+(n-r-k+i-1)*n)
  GG <- as.vector(t(GG))
  ## GG <- c(14,15,16,17,18)
  G = diag(n*crk); psi=matrix(1,n*crk,1)          #### this implies there is no restrictions on the adjustment coefficient alpha
  H = diag(n*crk);              H2 = H[,-c(seq(1,(n-r-k)*n,n),seq((n-r-k+1)*n,(n-r)*n,n),GG)]   #### normalization + I(0) B31=0,B32=0
  h = matrix(0,n*crk,1);        h[c(seq(1,(n-r-k)*n,n),seq((n-r-k+1)*n,(n-r)*n,n)),1] <- 1 ;
  phi = matrix(1,(n-1)*crk-k*(n-k),1)
  ### H2 = H[,-c(1,3,8,5,6,7)]; h[3]=-1; phi = matrix(1,2,1)
  ### check restrictions: G%*%psi  ; H2%*%phi+h
  ### c(seq(1,(n-r-k)*n,n),seq((n-r-k+1)*n,(n-r)*n,n))

  ABtest = civar_test(res=res_d,H=H2,h=h,phi=phi,G=G,Dxflag=0)

  ABtest$betar
  ABtest$alphar
  ABtest$VECMR$coefficients
  ABtest$LR
  1-stats::pchisq(ABtest$LR,k*r)   ### the fourth is the used restrictions the degree of freedom is n*h-h*h







  #########################

  G = diag(n*crk); psi=matrix(1,n*crk,1)          #### this implies there is no restrictions on the adjustment coefficient alpha
  H = diag(n*crk);              H2 = H[,-c(seq(1,(n-r-k)*n,n),seq((n-r-k+1)*n,(n-r)*n,n),CC,GG)]   #### normalization I(0) B31=0, B32=0, B23=0
  h = matrix(0,n*crk,1);        h[c(seq(1,(n-r-k)*n,n),seq((n-r-k+1)*n,(n-r)*n,n)),1] <- 1 ;
  phi = matrix(1,(n-1)*crk-k*(n-r-k)-k*(n-k),1)

  ### H2 = H[,-c(1,3,4,8,5,6,7)]; h[3]=-1; phi = matrix(1,1,1)

  ### check restrictions: G%*%psi  ; H2%*%phi+h
  ### c(seq(1,(n-r-k)*n,n),seq((n-r-k+1)*n,(n-r)*n,n))
  nG = 0
  if (!anyNA(Go)) { G = Go; nG = dim(Go)[1]-dim(Go)[2] }
  GABtest = civar_test(res=res_d,H=H2,h=h,phi=phi,G=G,Dxflag=0)

  GABtest$betar
  GABtest$alphar
  GABtest$VECMR$coefficients
  GABtest$LR
  1-stats::pchisq(GABtest$LR,k*r+nG)   ### the fourth is the used restrictions
  # collect restricted estimates
  BB3 <- res_d$B*0
  #BB3[,,1] <- GABtest$alphar%*%t(GABtest$betar)
  #AA  <- t(GABtest$LSKOEFR[1:((p-1)*n),])
  #dim(AA) <- c(n,n,(p-1))
  #BB3[,,2:p] <- AA
  #B3 <-cib3_b(BB3)
  #res_e$B <- B3
  #res_e$Sigma <- t(GABtest$VECMR$residuals)%*%GABtest$VECMR$residuals/T
  #for (i in 1:n) {
  #    res_e$tst$VECMS[[i]]$coefficients[(n-r+1):nrow(res_e$tst$VECMS[[i]]$coefficients),] <- GABtest$VECMRS[[i]]$coefficients;
  #    res_e$tst$VECMS[[i]]$coefficients[1:(n-r),1] <- GABtest$alpha[i,];
  #}
  BB3[,,1] <- GABtest$alphar%*%t(GABtest$betar)
  AA  <- t(GABtest$LSKOEFR[1:((p-1)*n),])
  dim(AA) <- c(n,n,(p-1))
  BB3[,,2:p] <- AA
  B3 <-cib3_b(BB3)
  res_e$B <- B3
  ##### transforming back to B

  #####
  res_e$Sigma <- t(GABtest$VECMR$residuals)%*%GABtest$VECMR$residuals/T
  for (i in 1:n) {
    res_e$tst$VECMS[[i]]$coefficients[(n-r+1):nrow(res_e$tst$VECMS[[i]]$coefficients),] <- GABtest$VECMRS[[i]]$coefficients;
    res_e$tst$VECMS[[i]]$coefficients[1:(n-r),1] <- GABtest$alpha[i,];
  }
  RR<-list(D,Bo,res_d$Y,AABtest, ABtest, GABtest,res_e,res_d,1-stats::pchisq(AABtest$LR,1),1-stats::pchisq(ABtest$LR,k*r), 1-stats::pchisq(GABtest$LR,k*r),k)
  names(RR) = c("D","Bo","Y","AABtest", "ABtest", "GABtest","res_e","res_d","p-value_A","p-value_E", "p-value_W","k")
  return(RR)
}

#' Generate GVAR synthetic data
#'
#' Creates a GVAR dataset under the package’s model specification.
#'
#' @examples
#' \dontrun{
#' p = (1:12)*0; dim(p) = c(4,3);p[,1] = 2; p[,2]=1;   p[,3]=1; p[2,2]=2;
#' p    ## country-wise lag specification
#'
#' res_d = gvar_data(m=2,n=4,p=p,T=200,type="exog0",X=X)
#' res_e = gvar_estimate(res = res_d)
#' res_e$Summary
#'
#' IRF_CB = irf_gvar_cb(res_e,nstep=10,comb=NA,irf="gen",runs=200,conf=c(0.05,0.95))
#' dim(IRF_CB)
#' IRF_g = plot_irf(IRF_CB,Names=NA,response=c(1,4),impulse=c(1,2,3,4), ncol=4)
#' }
#'
#' @export
gvar_data <- function (m, n, p, T, W = NA, r_npo = NA, Ao = NA, Bo = NA, Co = NA, Uo = NA, Sigmao = NA, type = NA, X = NA, mu = NA)
{
  if (missing(Bo)) {
    Bo = NA
  }
  if (missing(Sigmao)) {
    Sigmao = NA
  }
  if (missing(Uo)) {
    Uo = NA
  }
  if (missing(W)) {
    W = NA
  }
  if (missing(Ao)) {
    Ao = NA
  }
  if (missing(type)) {
    type = NA
  }
  if (missing(Co)) {
    Co = NA
  }
  if (missing(mu)) {
    mu = NA
  }
  Pmax = max(p[, 1:2])
  P = max(p)
  if (!anyNA(X))
    k = dim(X)[2]
  if (anyNA(Bo)) {
    Bo = (1:(m * m * Pmax * n)) * 0
    dim(Bo) = c(m, m, Pmax, n)
    r_npo = c(1:(m * Pmax * n)) * 0
    dim(r_npo) = c(m, Pmax, n)
    for (i in 1:n) {
      VARD = var_data(m, p[i, 1], T)
      Bo[, , 1:p[i, 1], i] = VARD$B
      r_npo[, 1:p[i, 1], i] = VARD$r_np
    }
  }
  if (anyNA(Sigmao)) {
    Sigmao = matrix(0, m * n, m * n)
    VARD = var_data(m * n, p[1, 1], T)
    Sigmao = VARD$Sigma
  }
  if (anyNA(Uo)) {
    Uo = rnorm_sigma(T, Sigmao)
  }
  if (anyNA(W)) {
    W = matrix(((1:(n * n))/(1:(n * n)) * 1/(n - 1)), n,
               n)
    for (i in 1:n) W[i, i] = 0
  }
  if (anyNA(Ao)) {
    Ao = (1:(m * m * Pmax * n)) * 0
    dim(Ao) = c(m, m, Pmax, n)
    for (i in 1:n) {
      for (L in 1:p[i, 2]) Ao[, , L, i] = matrix((stats::runif(m * m) - 0.5)/10, m, m)
    }
  }
  if (anyNA(type)) {
    type = "none"
  }
  if (type == "none") {
    Co = matrix(0, m, n)
    dim(Co) = c(m, 1, n)
    mu = matrix(0, m, n)
    dim(mu) = c(m, 1, n)
  }
  G = (1:(n * m * n * m * Pmax)) * 0
  dim(G) = c(n * m, n * m, Pmax)
  for (i in 1:n) {
    for (j in 1:n) {
      for (L in 1:Pmax) G[(1 + (i - 1) * m):(i * m), (1 + (j - 1) * m):(j * m), L] = Ao[, , L, i] * W[i,
                                                                                                      j]
    }
  }
  for (i in 1:n) {
    for (L in 1:Pmax) G[(1 + (i - 1) * m):(i * m), (1 + (i - 1) * m):(i * m), L] = Bo[, , L, i]
  }
  Ct = Uo * 0
  if (type == "const") {
    if (anyNA(mu)) {
      mu = matrix(stats::rnorm(n * m), m, n)
      dim(mu) = c(m, 1, n)
    }
    if (anyNA(Co)) {
      Co = mu
      muV = as.vector(mu)
      CoV = muV
      for (L in 1:Pmax) CoV = CoV - G[, , L] %*% muV
    }
    else {
      H = diag(n * m)
      for (L in 1:Pmax) H = H - G[, , L]
      CoV = as.vector(Co)
      muV = solve(H) %*% CoV
      mu = muV
      dim(mu) = c(m, 1, n)
    }
    Ct = matrix(1, T, 1) %*% t(CoV)
  }
  if (type == "exog0") {
    if (anyNA(Co)) {
      Co = matrix(stats::rnorm(m * n * (k + 1)), m * (k +
                                                        1), n)
      dim(Co) = c(m, k + 1, n)
      Co[, 1, ] = (1:m) * 0
      for (i in 1:n) if (p[i, 3] < k)
        Co[, (p[i, 3] + 2):(k + 1), i] = Co[, (p[i, 3] +
                                                 2):(k + 1), i] * 0
    }
    DMCo = dim(Co[, -1, ])
    if (length(DMCo) < 3)
      DMCo = c(dim(Co)[1], 1, dim(Co)[3])
    if (!(DMCo[2] == dim(X)[2]) | !(DMCo[1] == m) | !(DMCo[3] ==
                                                      n)) {
      print("dimension problem")
      return("dimension")
    }
    CoV = matrix(0, dim(X)[2], m * n)
    for (i in 1:dim(X)[2]) CoV[i, ] = as.vector(Co[, 1 +
                                                     i, ])
    Ct = matrix(0, dim(X)[1], m * n)
    for (i in 1:n) Ct[, ((i - 1) * m + 1):((i - 1) * m + m)] = as.matrix(X[, , i]) %*% CoV[, ((i - 1) * m +
                                                                                                1):((i - 1) * m + m)]
    mu = NA
  }
  else {
    if (type == "exog1") {
      if (anyNA(Co)) {
        Co = matrix(stats::rnorm(m * n * (k + 1)), m * (k + 1), n)
        dim(Co) = c(m, k + 1, n)
        for (i in 1:n) if (p[i, 3] < k)
          Co[, (p[i, 3] + 2):(k + 1), i] = Co[, (p[i, 3] + 2):(k + 1), i] * 0
      }
      DMCo = dim(Co[, -1, ])
      CoV = matrix(0, dim(X)[2] + 1, m * n)
      for (i in 1:(1 + dim(X)[2])) CoV[i, ] = as.vector(Co[,
                                                           i, ])
      Ct = matrix(0, dim(X)[1], m * n)
      for (i in 1:n) Ct[, ((i - 1) * m + 1):((i - 1) * m + m)] = cbind(matrix(1, dim(X)[1], 1), X[, , i]) %*% CoV[, ((i - 1) * m + 1):((i - 1) * m + m)]
      mu = NA
    }
    else {
      X = NA
    }
  }
  Y = Uo + Ct
  for (t in (P + 1):T) {
    for (L in 1:Pmax) Y[t, ] = Y[t, ] + Y[t - L, ] %*% t(G[, , L])
  }
  check = max(abs(Y))
  result = list(Y, X, Uo, G, Sigmao, r_npo, Ao, Bo, Co, W,
                m, n, p, mu, check, type)
  names(result) = c("Y", "X", "Uo", "G", "Sigmao", "r_npo", "Ao", "Bo", "Co", "W", "m", "n", "p", "mu", "check", "type")
  return(result)
}



#'
#' This function generates data from an multi-regime cointegrated global VAR process and returns an MRCIGVAR(m,n,p,S) object that is a list containing the data and the parameters used in the MRCIGVAR(m,n,p,S) process.
#'
#' @param m     : number of variables in each country/unit
#' @param n     : number of countries/units
#' @param S     : number of regimes
#' @param p     : an (n, 3, S) array, each raw contains the lag length of the domestic variables, the lag length of the foreign variables, and the number of the exogenous variables of the corresponding country in the respective regimes.
#' @param T     : number of observations.
#' @param W     : an (n x n) weighting matrix. w_ij is the weight of country j in the foreign variables of i-th country diag(W)=0
#' @param SESVI : an n-vector of indices of the switching variables across n countries. E.g. SESVI = seq(1,m*n,m).
#' @param TH    : an (n x S-1) matrix of threshold values
#' @param Go    : an (mn,mn,p,S) array containing coefficients of MRCIGVAR. Go is constructed from Bo, Ao and W.
#' @param Ao    : an (m, m, p, n, S) array containing the coefficients of foreign variables
#' @param Bo    : an (m, m, p, n, S) array containing the coefficients of domestic variables.
#' @param Co    : an (m , k+1, n, S) array containing the coefficients of the deterministic components of the n countries.
#' @param Uo    : a (T, mn, S) array of the temporally independent innovations
#' @param Sigmao : an (mn, mn, S) array of the covariance matrix of MRCIGVAR(m,n,p,S)
#' @param SV    : exogenous switching variables
#' @param type	: types of the deterministic component. "const", "none", "exog0", and "exog1" are 4 options
#' @param X	    : a (T x k x n x S) array of exogenous stationary variables.
#' @param Yo    : initial values
#' @param d     : the time lag between signal and regime-switching
#' @param r     : an n-vector containing the number of unit root process in each country
#' @param r_np  : an (m, Pmax, n, S) array containing the roots of the characteristic polynomials of each country.
#' @param Ncommtrend : number of common stochastic trends in the MRCIGVAR.
#' @param DFYflag : indicator whether the foreign variables enter the cointegration space.
#' @param A       : transformation matrix for common exogenous non-stationary stochastic factors.
#' @param Ncommfakt : number of the common exogenous non-stationary stochastic factors.
#' @param uz      : innovations of the common exogenous non-stationary stochastic factors.
#' @return      an MRGVAR object containing the generated data, the used parameters and the exogenous variables.
#' \itemize{
#'    \item Y     : a (T x mn)  matrix of simulated data
#'    \item X     : a (T x k x n x S) array of exogenous variables
#'    \item Uo    : a (T, mn,S) array of the simulated innovations of the MRGVAR(m,n,p,S)
#'    \item C     : an (nm, (k+1),S) array containing the coefficients of the deterministic components.
#'    \item St    : a (T x n) matrix of the simulated time path of states/regimes
#'    \item check : maximum of the data for checking the stationarity
#' }
#'
#'
#' @examples
#' m = 3
#' n = 5
#'  p = c(2,2,2,2,2,2,2,2,2,2,0,0,0,0,0,2,2,2,2,2,2,2,2,2,2,0,0,0,0,0); dim(p) = c(5,3,2)
#' p = p[1:n,,]; p[,1,] = 3; p[,2,] = 2
#'
#' p[2,2,] = 3
#' TH = c(1:n)*0; dim(TH) = c(1,n)
#' SESVI=rep(1,4,7,10,13)
#' r  = rep(1,n)
#' i = 1
#' S = 2
#'
#' T= 200
#' XX = matrix(rnorm(T*10*2),T*10,2)
#' dim(XX) = c(T,2,5,2)
#' p[,3,]=2
#'
#' res_d <- mrcigvar_data(m=3,n=5,p=p,TH=TH,T=T,S=2, SESVI=c(1,4,7,10,13),type="exog0",r=rep(1,5),
#' DFYflag=0,Ncommfakt=1,X=XX)    ## m: number of variables, n: number of countries
#'
#' max(abs(res_d$Y))
#' plot(ts(res_d$Y[,1:10]))
#' spectral_radius(res_d$Go[,,,2])
#' spectral_radius(res_d$GC[,,,1]);spectral_radius(res_d$GC[,,,2]);
#' spectral_radius(res_d$Go[,,,1])
#' max(abs(res_d$Y))
#'
#' Ao=res_d$Ao;Bo=res_d$Bo;Co=res_d$Co;
#'
#' res_d <- mrcigvar_data(m=3,n=5,p=p,TH=TH,T=T,S=2, SESVI=c(1,4,7,10,13),type="exog0",Ao=Ao,Bo=Bo,
#' Co=Co,r = rep(1,5),DFYflag = 0,Ncommfakt=1,X=XX) ##m:number of variables, n:number of countries
#' res_e  = mrcigvar_estimate(res=res_d)
#'
#'
#' @export
mrcigvar_data <- function(m,n,p,T,S,W=NA,SESVI=NA,TH=NA,Go=NA,Ao=NA,Bo=NA,Sigmao=NA,Uo=NA,SV=NA,type=NA,Co=NA,X=NA,Yo=NA,d=NA,r=NA,r_np=NA,Ncommtrend=NA,DFYflag=0,A=NA,Ncommfakt=1,uz=NA) {
  ### m     : number of variables in a country
  ### n     : number of countries
  ### p     : lag length n x 3 x S array collecting lag length for each country with respect to domestic and foreigen variable for each state. The last column specifies the number of exogenous variabls for each state.
  ### T     : number of observations
  ### S     : number of regimes
  ### SESVI : n vector of indeces of the switching variable in the endogeneous variables Y for the case of self-excited threshhold model.
  ###         (m,n,p,T,S,SESVI) are parameters which must be provided.
  ### TH    : n x S-1  matrix of threshold values of n countries.
  ### Go    : mn x mn x p x S GVAR(m,n,p) coefficients matrix of S different regimes
  ### Sigmao: mn x mn x S array of the covariance matrix of the GVAR(m,n,p) in S different regimes
  ### Uo    : a T x mn x S  array of the temorally independent innovation processes
  ### X       : a T x k x n x S array of exogenous veriables which may be common/different to all countries and different across all states
  ###         (TH,Go,Sigmao,Uo,SV) if not provided, they will be generated randomly.
  ### type  : deterministic component "const" and "none" "exog0" "exog1" are foure options
  ### Co    : if type = "const" mu is an m x n x S array of the intercepts of the time series in the different regimes
  ###
  ###
  ### output:
  ### c("Y","Uo","Go","Sigmao","TH","St","sv","SESVI","check")
  ###
  ### Y     : T x mn data matrix of the simulated data via of the MSGVAR(m,n,p,S)
  ### Uo    : an T x mn x S   array of the temorally independent innovation processes of the MSGVAR(m,n,p,S)
  ### Go    : mn x mn x p x S array collecting the MSGVAR(m,n,p,S) coefficients in S different states
  ### Sigmao: mn x mn x S array collecting the covariance matrices of the simulated MSGVAR(m,n,p,S) in S different states
  ### TH    : S-1 vector of thresholds
  ### St    : simulated time path of states/regimes
  ### SESVI : index if the switching variable
  ### check : maximum of the data to check stationarity
  ###
  ### Remarks: The states of each country at each time step is governed by the switching variables of each country and hence there is a large numbers
  ###          of possible combinations of gegimes.
  ###          The coefficients matrix can be constructed from Go, given a regime combination. The stationarity of the GVAR(m,n,p)
  ###          at each time step is not guaranteed. But this is not relevant. (This is a open question.)
  ###
  ###
  check = c(1:(S + 1)) * 0
  if (missing(TH)) {
    TH = NA
  }
  if (missing(W)) {
    W = NA
  }
  if (missing(SV)) {
    SV = NA
  }
  if (missing(Sigmao)) {
    Sigmao = NA
  }
  if (missing(Uo)) {
    Uo = NA
  }
  if (missing(type)) {
    type = NA
  }
  if (missing(Co)) {
    Co = NA
  }
  if (missing(Go)) {
    Go = NA
  }
  if (missing(Bo)) {
    Bo = NA
  }
  if (missing(Ao)) {
    Ao = NA
  }
  if (missing(X)) {
    X = NA
  }
  if (missing(d)) {
    d = NA
  }
  if (missing(Yo)) {
    Yo = NA
  }
  if (missing(r)) {
    r = NA
  }
  if (missing(r_np)) {
    r_np = NA
  }
  if (missing(Ncommtrend)) {
    Ncommtrend = NA
  }
  if (missing(DFYflag)) {
    DFYflag = 0
  }
  if (missing(Ncommfakt)) {
    Ncommfakt  = 0
  }



  if (anyNA(d)) {
    d = 1
  }
  if (anyNA(r)) {
    r = rep(1, n)
  }
  P = max(p[, 1:2, ], d)
  Pmax = max(p[, 1:2, ])
  if (anyNA(TH)) {
    TH = matrix(stats::runif(S - 1) * n, S - 1, n)
    for (i in 1:n) {
      THh = stats::runif(S - 1) - 0.5
      THh = THh[order(THh)]
      TH[, i] = THh
    }
  }
  if (anyNA(W)) {
    W = matrix(((1:(n * n))/(1:(n * n)) * 1/(n - 1)), n,
               n)
    for (i in 1:n) W[i, i] = 0
  }
  if (anyNA(Sigmao)) {
    Sigmao = (1:(m * n * m * n * S)) * 0
    dim(Sigmao) = c(m * n, m * n, S)
    for (s in 1:S) {
      GVARD = gvar_data(m, n, p[, , s], T)
      Sigmao[, , s] = GVARD$Sigmao
    }
  }
  if (anyNA(r_np)) {
    r_np = (1:(m * Pmax * n * S))/(1:(m * Pmax * n * S)) *
      (3.1 + abs(stats::rnorm(m * Pmax * n * S)))
    dim(r_np) = c(m, Pmax, n, S)
    r_np[1, , , ] = 1
  }
  if (anyNA(Uo)) {
    Uo = (1:(T * n * m * S)) * 0
    dim(Uo) = c(T, m * n, S)
    for (s in 1:S) Uo[, , s] = rnorm_sigma(T, Sigmao[, , s])
  }
  Ct = Uo * 0
  if (anyNA(type)) {
    type = "none"
  }
  if (type == "none") {
    CDC = c(1:(m * n * S)) * 0
    dim(CDC) = c(m, 1, n, S)
    Co = CDC
    GDC = Co
    dim(GDC) = c(n * m, 1, S)
    Ct = Uo * 0
  }
  if (type == "const") {
    CDC = stats::rnorm(m * n * S)
    dim(CDC) = c(m, 1, n, S)
    if (anyNA(Co))
      Co = CDC
    GDC = Co
    dim(GDC) = c(n * m, 1, S)
    CoV = as.vector(Co)
    for (s in 1:S) {
      CoV = as.vector(Co[, , , s])
      for (i in 1:n) Ct[, , s] = matrix(1, T, 1) %*% t(CoV)
    }
  }
  if (type == "exog1") {
    k = dim(X)[2] + 1
    CDC = stats::rnorm(m * k * n * S)
    dim(CDC) = c(m, k, n, S)
    if (anyNA(Co))
      Co = CDC
    GDC = Co
    dim(GDC) = c(n * m, k, S)
    CoV = matrix(0, k, m * n)
    for (s in 1:S) {
      for (i in 1:n) {
        if (p[i, 3, s] < k - 1)
          Co[, (p[i, 3, s] + 1):k, i, s] = 0
        for (j in 1:k) CoV[j, ] = as.vector(Co[, j, ,
                                               s])
        Ct[, , s] = cbind(matrix(1, dim(X)[1], 1), X[,
                                                     , i, s]) %*% CoV
      }
    }
  }
  if (type == "exog0") {
    k = dim(X)[2] + 1
    CDC = stats::rnorm(m * k * n * S)
    dim(CDC) = c(m, k, n, S)
    CDC[, 1, , ] = 0
    if (anyNA(Co))
      Co = CDC
    GDC = Co
    dim(GDC) = c(n * m, k, S)
    CoV = matrix(0, k, m * n)
    for (s in 1:S) {
      for (i in 1:n) {
        if (p[i, 3, s] < k - 1)
          Co[, (p[i, 3, s] + 2):k, i, s] = 0
        for (j in 1:k) CoV[j, ] = as.vector(Co[, j, ,
                                               s])
        Ct[, , s] = cbind(matrix(1, dim(X)[1], 1), X[,
                                                     , i, s]) %*% CoV
      }
    }
  }

  kkk    <- 0
  CIVARB <- NA
  ### Go = NA; Bo = NA; Ao = NA
  if (anyNA(Go) & anyNA(Bo)) {
    repeat {
      CIVARB = (1:(2 * m * 2 * m * Pmax * S * n)) * 0
      dim(CIVARB) = c(2 * m, 2 * m, Pmax, n, S)
      Go = (1:(m * n * m * n * Pmax * S)) * 0
      dim(Go) = c(m * n, m * n, Pmax, S)
      Bo = (1:(m * m * Pmax * n * S)) * 0
      dim(Bo) = c(m, m, Pmax, n, S)
      Bo = varbs_commtrend(m, p, T, r, Ncommtrend, n, S, r_npo = r_np)[[1]]
      Ao = bo2_ao(m, p, T, r, Ncommtrend, n, S, r_npo = r_np,DFYflag=DFYflag)
      BoAo_h = bo_ao2_t_bo_ao(Bo, Ao, W, S)
      Bo = BoAo_h[[1]]
      Ao = BoAo_h[[2]]
      for (i in 1:n) {
        Bi = matrix(stats::rnorm(m * m), m, m)
      }
      for (s in 1:S) Go[, , , s] = bo_ao_w2_g(Bo[, , , , s], Ao[, , , , s], W, m, n, Pmax)

      if (!max(Mod(spectral_radius(Go[,,,1])),Mod(spectral_radius(Go[,,,2])))>1.000000001 ) break
      kkk = k + 1
      if (kkk > 100) break
    }
  }

  if (!anyNA(Go) & anyNA(Bo)) {
    Bo = (1:(m * m * Pmax * n * S)) * 0
    dim(Bo) = c(m, m, Pmax, n, S)
    Ao = Bo * 0
    for (s in 1:S) {
      Bo[, , , , s] = gw2_bo_ao(Go[, , , s], W)$Bo
      Ao[, , , , s] = gw2_bo_ao(Go[, , , s], W)$Ao
    }
  }
  if (anyNA(Go) & !anyNA(Bo)) {
    Go = (1:(m * n * m * n * Pmax * S)) * 0
    dim(Go) = c(m * n, m * n, Pmax, S)
    for (s in 1:S) Go[, , , s] = bo_ao_w2_g(Bo[, , , , s], Ao[, , , , s], W, m, n, Pmax)
  }


  St = matrix(0, T, n)
  Y = Uo[, , 1]
  if (!anyNA(Yo))
    Y[1:P, ] = Yo
  resid = Y * 0
  Yo = Y[1:P, ]
  if (anyNA(SV)) {
    sv = Y[, SESVI] * 0
    SV = NA
  }
  else {
    sv = SV
  }
  ss = matrix(0, n, 1)
  for (tt in (P + 1):T) {
    if (anyNA(SV)) {
      sv[2:T, ] = Y[2:T, SESVI] - Y[1:(T - 1), SESVI]
      SV = NA
    }
    else {
      sv = SV
    }
    svt = sv[tt - d, ]
    Bt = c(1:(m * n * m * n * Pmax)) * 0
    dim(Bt) = c(n * m, n * m, Pmax)
    for (i in 1:n) {
      ss[i] = which.min(abs(TH[, i] - svt[i]))
      if (svt[i] > TH[ss[i], i]) {
        ss[i] = ss[i] + 1
      }
      Bt[(1 + (i - 1) * m):(i * m), , ] = Go[(1 + (i -
                                                     1) * m):(i * m), , , ss[i]]
      Y[tt, (1 + (i - 1) * m):(i * m)] = Uo[tt, (1 + (i -
                                                        1) * m):(i * m), ss[i]] + Ct[tt, (1 + (i - 1) *
                                                                                            m):(i * m), ss[i]]
      resid[tt, (1 + (i - 1) * m):(i * m)] = Uo[tt, (1 +
                                                       (i - 1) * m):(i * m), ss[i]]
    }
    for (L in 1:Pmax) Y[tt, ] = Y[tt, ] + Y[tt - L, ] %*%
      t(Bt[, , L])
    St[tt, ] = ss
  }
  check[S + 1] = max(abs(Y))
  SigmaS = NA

  if (Ncommfakt>0) {

    uz = rnorm_sigma(T,diag(Ncommfakt))
    Z = uz
    for (i in 3:T) Z[i,] = Z[i-1,]*1.4-Z[i-2,]*0.4+uz[i,]

    if (anyNA(A)) {
      A = diag(m*n+Ncommfakt)
      #for (i in 1:n) {A[(i-1)*m+Ncommfakt+(m-(Ncommfakt-1)):m ] = diag(Ncommfakt)*50*max(abs(Y[,i*m]))/max(abs(Z))}
      A[(Ncommfakt+1):(Ncommfakt+n*m),1:Ncommfakt]  = 0.3
    }

    YY <- cbind(Z,Y);

    Y = (YY%*%t(A))[,Ncommfakt+(1:(m*n))]
    dim_GC = dim(Go); dim_GC[1:2] = dim_GC[1:2]+Ncommfakt
    GC = c(1:prod(dim_GC))*0; dim(GC) = dim_GC
    GC[(Ncommfakt+1):(Ncommfakt+n*m),(Ncommfakt+1):(Ncommfakt+n*m),,] = Go
    GC[1:Ncommfakt,1:Ncommfakt,1,] = 1.4*diag(Ncommfakt); GC[1:Ncommfakt,1:Ncommfakt,2,] = -0.4*diag(Ncommfakt)  # assuming unit root common factor(s)
    for (i in 1:Pmax) GC[,,i,1] = A%*%GC[,,i,1]%*%solve(A)
    for (i in 1:Pmax) GC[,,i,2] = A%*%GC[,,i,2]%*%solve(A)
    Uo[,,1] = (cbind(uz,Uo[,,1])%*%t(A))[,Ncommfakt+(1:(m*n))]
    Uo[,,2] = (cbind(uz,Uo[,,2])%*%t(A))[,Ncommfakt+(1:(m*n))]
    Do = (1:(m*n*Pmax*Ncommfakt*2))*0; dim(Do) = c(m,Ncommfakt,Pmax,n,2)

  }  else  {
    Z  = NA
    uz = NA
    A  = NA
    GC = NA
    Do = NA
  }


  result = list(Y, X, Uo, resid, Go, GDC, Co, Sigmao, TH, St,SV, SESVI, Ao, Bo, check, type, m, n, p, S, W, SigmaS, Yo, d, r, CIVARB, kkk,DFYflag,Z,uz,A,GC,Do)
  names(result) = c("Y", "X", "Uo", "resid","Go", "GDC", "Co", "Sigmao","TH", "St", "SV", "SESVI", "Ao","Bo", "check", "type", "m", "n","p", "S", "W", "SigmaS", "Yo",
                    "d", "r", "CIVARB", "kkk","DFYflag","Z","uz","A","GC","Do")
  return(result)
}



#'
#' This function will generate data from a MRCIGVAR object. It will generate enough data for estimation purpose.
#'
#' @param res     : an output of mrcigvar_estimate
#' @return	: an MRCIGVAR object.
#'
#' @export
#' @keywords internal
mrcigvar_data_r <- function(res) {
  ### res_e : an estimated MRGVAR model that is an output of mrcigvar_estimate
  ### T     : number of observations
  ### Remarks: mrcigvar_data_r is used in bootstrapping to generate sufficient observations such that in the regime of rare occurrence also contains
  ###          sufficient observations for estimation purposed
  ###
  ###  MINH:   minimum number of observations of a nation in the rare occurrence regime.

  m = res$m
  n = res$n
  p = res$p
  if (length(p) > 1)
    pp = max(p[, 1:2, ])
  else pp = p
  T = dim(res$Y)[1]
  W = res$W
  S = res$S
  SV = res$SV
  SESVI = res$SESVI
  TH = res$TH
  Ao = res$Ao
  Bo = res$Bo
  Co = res$Co
  Go = res$Go
  Sigmao = res$Sigmao
  type = res$type
  X = res$X
  mu = res$mu
  MINH = T
  repeat {
    Uo_run = array(0, c(T, n * m, S))
    for (s in 1:S) Uo_run[, , s] = rnorm_sigma(T, Matrix::nearPD(Sigmao[,,s])[[1]])       #### zhe ge you wenti
    res_run = mrcigvar_data(m, n, p, T, S, W, SESVI, TH, res$Go, Ao = NA, Bo = NA, Sigmao = NA, Uo = Uo_run, SV, type, Co, X)
    for (i in 1:n) { MINH = min(MINH,sum(diff(res_run$Y)[,SESVI[i]]>TH[1,i]),sum(diff(res_run$Y)[,SESVI[i]]<TH[1,i]))}
    if (MINH > (max(p)*(m*2)+2*m)) break
    else {T=T+T; print(c(MINH,T)); MINH=T}
  }
  return(res_run)
}



#'
#' This function generates data from an multi-regime cointegrated VAR(p) process with identical cointegration relations and different adjustment speeds and returns a MRCIVAR which is a list containing data and parameters used in the multi regime cointegrated VAR(p) process.
#'
#' @param n     : number of variables
#' @param S     : number of regimes
#' @param p     : an (S x 2) matrix. Each row of p contains the lag length for the corresponding regime and the number of exogenous variables for the regime.
#' @param T     : number of observations
#' @param SESVI : index of the switching variable, switching sv_t = Y\[t-1,SESVI\] > Y\[t-2,SESVI\]
#'
#'                (n,S,p,T,SESVI) are parameters that have to be provided.
#' @param TH    : an (S-1) vector of threshold values
#' @param Bo    : an (n,n,p,S) array of the coefficients  of MRVAR(n,p,S). If not given it will be generated.
#' @param Co    : an (n,k+1,S) array of the coefficients of the deterministic components. For type="none" Co = O*(1:n,1:S), for "const" Co is an n-vector for each regime, "exog0" Co is a (n,k+1,S) array with first column of zeros for each regime respectively,for "exog1" Co is an (n,1+k, S) array without zero restrictions.
#' @param Sigmao : an (n,n,S) array containing S covariance matrices of the residuals
#' @param Uo    : residuals, if it is not NA it will be used as input to generate the MRVAR(n,p,S) for each regime.
#' @param SV    : exogenous switching variable
#' @param type  : type of the deterministic components type = ("none","const","exog0","exog1")
#' @param X     : a (T x k x S) matrix of exogenous variables for each state. The second dimension can be filled with zeros to take into account that the the exogenous variables are not identical in each state.
#' @param mu    : an (n x S) matrix of the regime specific mean of the variables
#' @param Yo    : a (p, n, S) array of initial values of the process
#' @param Do    : a (T, n, S) array of extra exogenous components (not used with value zero)
#' @param d     : lag delay of the self-exiting switching
#' @param r     : number of unit roots in the system. (n - r) is then the cointegration rank.
#'
#'               (TH,Bo,Sigmao,Uo,SV) if not provided, they will be generated randomly.
#' @return An MRCIVAR object containing the generated data, the used parameters, and the exogenous variables.
#'
#' @examples
#' Sigma = 1:(4*4*2)
#' dim(Sigma) = c(4,4,2)
#' Sigma[,,1] = diag(4)
#' Sigma[,,2] = diag(4)
#' p=matrix(0,2,2)
#' p[,1] = c(3,3)
#' res_d = mrcivar_data_m(n=4,p=p,T=250,S=2,SESVI=1,TH=0,Sigmao=Sigma,type="const",r=2)
#' colnames(res_d$Y) = c("w","p","I","Q")
#' max(abs(res_d$Y))
#' res_e = mrcivar_estimatem1(res=res_d)
#' res_e$Summary
#'
#' p=matrix(0,2,2)
#' p[,1] = c(3,3)
#' p[,2] = 1
#' T = 200
#' XX = matrix(rnorm(T),T,1)
#' XX = cbind(XX,XX); dim(XX) = c(T,1,2)
#' dim(XX)
#'
#' res_d = mrcivar_data_m(n=4,p=p,T=T,S=2,SESVI=1,TH=0,Sigmao=Sigma,type="exog0",r=1,X=XX)
#' res_e = mrcivar_estimatem1(res=res_d)
#' res_e$Summary
#'
#' res_d = mrcivar_data_m(n=4,p=p,T=T,S=2,SESVI=1,TH=0,Sigmao=Sigma,type="exog1",r=1,X=XX)
#' res_e = mrcivar_estimatem1(res=res_d)
#' res_e$Summary
#'
#' @export
mrcivar_data_m = function(n=2,p=matrix(2,2,2),T=100,S=2,SESVI,TH,Bo,Co,Sigmao,Uo,SV,type,X,mu,Yo,Do,d=1,r=1) {
### T     : number of observations
### n     : number of variables
### p     : lag length, an S x 2 vector of lag length for each state and the number of exogenous variables for each state
### S     : number of states of the underlying Markov Chain
###         (n,p,T,S,SESVI) are parameters which must be provided.
### SESVI : index of the switching variable in the endogenous variables Y for the case of self-excited threshold model.
### TH    : (S-1)-vector of threshold values
### Bo    : n x n x p x S array collecting the coefficients of VAR(p) in S different states
### Sigmao :  n x n x S array of the covariance matrix of the VAR(p) in S different states
### Uo    : an T x n x S  array of the temporally independent innovation processes
### SV    : exogenous switching variable
### d     : lag of the self-exiting
###         (TH,Bo,Sigmao,Uo,SV) if not provided, they will be generated randomly.
###
### output:
### c("Y","Uo","Bo","Sigmao","TH","St","sv","SESVI","r_npo","check")
###
### Y     : the simulated data via of the MRVAR(p)
### Uo    : T x n x S array of the simulated innovations in S different states
### Bo    : n x n x p x S array collecting the VAR(p) coefficients in S different states
### Sigmao : n x n x S array collecting the covariance matrices of the simulated MRVAR(p) in S different states
### TH    : S-1 vector of threshold values
### St    : simulated time path of states
### sv    : the switching variable ( it is SW in the case of exogeneous switching and it is Y[,SESVI] in the case of self-excited threshold model.
### r_npo : n x p matrix collecting the roots of the characteristic functions in L of the n dynamically independent processes.
### check : maximum of the data to check stationarity
###
### Remarks: The VAR(p) process is A transformed from n dynamically independent ar processes, such that the stationary is guaranteed.
###
###
  if (missing(Yo)) {
    Yo = NA
  }
  if (missing(Do)) {
    Do = NA
  }
  if (missing(d)) {
    d = NA
  }
  if (missing(TH)) {
    TH = NA
  }
  if (missing(Bo)) {
    Bo = NA
  }
  if (missing(Sigmao)) {
    Sigmao = NA
  }
  if (missing(Uo)) {
    Uo = NA
  }
  if (missing(type)) {
    type = NA
  }
  if (missing(Co)) {
    Co = NA
  }
  if (missing(mu)) {
    mu = NA
  }
  if (missing(SV)) {
    SV = NA
  }
  if (missing(X)) {
    X = NA
  }
  if (missing(Yo)) {
    Yo = NA
  }
  if (missing(Do)) {
    Do = NA
  }
  check = c(1:(S + 1)) * 0
  if (anyNA(Yo)) {
    Yo = NA
  }
  if (anyNA(Do)) {
    Do = NA
  }
  if (anyNA(d)) {
    d = 1
  }
  P = max(p[, 1], d)
  Pmax = max(p[, 1])
  Pmin = min(p[, 1])
  if (anyNA(TH)) {
    TH = matrix(stats::runif(S - 1), S - 1, 1)
    TH = TH[order(TH)]
  }
  if (anyNA(Bo)) {
    Bo = (1:(n * n * Pmax * S)) * 0
    dim(Bo) = c(n, n, Pmax, S)
    r_npo = t(matrix(rep((2:(n + 1)), Pmax), Pmax, n))
    for (i in 1:r) r_npo[i, 1] = 1
    res_d = var_data(n, Pmax, T = 100, r_np = r_npo)
    B1 = res_d$B
    CIB1 = b2_cib(B1)[[1]]
    repeat {
      res_d2 = var_data(n, Pmin, T = 100)
      B2 = B1 * 0
      B2[, , 1:Pmin] = res_d2$B
      CIB2 = b2_cib(B2)[[1]]
      values = eigen(CIB1[, , 1])$values
      VECTOR = eigen(CIB1[, , 1])$vectors
      if ((n - r) == 1)
        CIB2[, , 1] = VECTOR[, (r + 1):n] %*% as.matrix(-stats::runif(n -
                                                                 r)) %*% solve(VECTOR)[(r + 1):n, ]
      if ((n - r) > 1)
        CIB2[, , 1] = VECTOR[, (r + 1):n] %*% (diag(-stats::runif(n -
                                                             r))) %*% solve(VECTOR)[(r + 1):n, ]
      CBB = cib3_b(CIB2)
      if (max(abs(spectral_radius(CBB))) == 1)
        break
    }
    if (p[1, 1] > p[2, 1]) {
      Bo[, , , 1] = B1
      Bo[, , , 2] = CBB
    }
    else {
      Bo[, , , 1] = CBB
      Bo[, , , 2] = B1
    }
  }
  else {
    r_npo = NA
  }
  if (anyNA(Sigmao)) {
    Sigmao = (1:(n * n * S)) * 0
    dim(Sigmao) = c(n, n, S)
    for (i in 1:S) {
      VARD = var_data(n, Pmax, T)
      Sigmao[, , i] = VARD$Sigma
    }
  }
  if (anyNA(Uo)) {
    Uo = (1:(T * n * S)) * 0
    dim(Uo) = c(T, n, S)
    for (i in 1:S) Uo[, , i] = rnorm_sigma(T, as.matrix(Sigmao[,
                                                              , i]))
  }
  Ct = Uo * 0
  if (anyNA(type) | type == "none") {
    type = "none"
    Co = (1:(S * n)) * 0
    dim(Co) = c(n, 1, S)
  }
  if (type == "exog0") {
    k = dim(X)[2]
    CC = stats::rnorm(n * (1 + k) * S)
    dim(CC) = c(n, k + 1, S)
    CC[, 1, ] = c(1:n) * 0
    if (anyNA(Co))
      Co = CC
    for (s in 1:S) {
      if (p[s, 2] < k)
        Co[, (p[s, 2] + 2):(k + 1), s] = Co[, (p[s, 2] + 2):(k + 1), s] * 0
      Ct[, , s] = X[, , s] %*% t(Co[, -1, s])
    }
  }
  if (type == "exog1") {
    k = dim(X)[2]
    CC = stats::rnorm(n * (1 + k) * S)
    dim(CC) = c(n, k + 1, S)
    if (anyNA(Co))
      Co = CC
    for (s in 1:S) {
      if (p[s, 2] < k)
        Co[, (p[s, 2] + 2):(k + 1), s] = Co[, (p[s, 2] +
                                                 2):(k + 1), s] * 0
      Ct[, , s] = cbind((1:T)/(1:T), X[, , s]) %*% t(Co[,
                                                        , s])
    }
  }
  if (type == "const") {
    if (anyNA(mu)) {
      mu = matrix(stats::rnorm(n * S), n, S)
      dim(mu) = c(n, 1, S)
    }
    if (anyNA(Co)) {
      Co = mu
      for (s in 1:S) {
        for (L in 1:Pmax) Co[, 1, s] = Co[, 1, s] - Bo[,
                                                       , L, s] %*% mu[, 1, s]
        Ct[, , s] = matrix(1, T, 1) %*% t(Co[, 1, s])
      }
    }
    else {
      mu = Co * NA
      for (s in 1:S) {
        H = diag(n)
        for (L in 1:Pmax) H = H - Bo[, , L, s]
        mu = NA
        Ct[, , s] = matrix(1, T, 1) %*% t(Co[, 1, s])
      }

    }
  }
  St = (1:T) * 0
  Y = as.matrix(Uo[, , 1]) * NA
  if (anyNA(Yo)) {
    Y[1:P, ] = Uo[1:P, , 1]
    Yo = Y[1:P, ]
  }
  else {
    Y[1:P, ] = Yo
  }
  if (anyNA(Do)) {
    Do = matrix(0, n, S)
  }
  else {
    Do = Do
  }
  if (anyNA(SV)) {
    sv = Y[, SESVI]
  }
  else sv = SV
  for (tt in (P + 1):T) {
    if (anyNA(SV)) {
      sv = Y[tt - 1, SESVI] > Y[tt - 2, SESVI]
    }
    else {
      sv = SV[tt]
    }
    st = sv
    s = sum(st > TH) + 1
    St[tt] = s
    Y[tt, ] = Uo[tt, , s] + Ct[tt, , s] + Do[, s]
    for (L in 1:Pmax) Y[tt, ] = Y[tt, ] + Y[tt - L, ] %*%
      t(Bo[, , L, s])
  }
  check[S + 1] = max(abs(Y))
  resid = NA
  crk = n - r
  result = list(Y, X, Uo, resid, Bo, Co, Sigmao, TH, St, sv,
                d, SESVI, r_npo, check, n, p, S, type, Yo, r, crk)
  names(result) = c("Y", "X", "Uo", "resid", "Bo", "Co", "Sigmao", "TH", "St", "sv", "d", "SESVI", "r_npo", "check", "n", "p", "S", "type", "Yo", "r", "crk")
  return(result)
}



#'
#' This function generates data from an multi-regime stationary global VAR(p) process and returns an MRGVAR object that is a list containing the generated data and the used parameters.
#'
#' @param m     : number of variables in a country/unit
#' @param n     : number of countries/units
#' @param p     : an (n, 3, S) array, each raw specifies the lag length of the domestic variables, the lag length of the foreign variables and the number of exogenous variables for the respective regime.
#' @param T     : number of observations.
#' @param S     : number of regimes.
#' @param W     : an (n x n) weighting matrix. w_ij is the weight of country j in the foreign variables of i-th country diag(W)=0
#' @param SESVI : an n-vector of indices of the switching variables across n countries. Eg. SESVI = seq(1,m*n,m).
#' @param TH    : an (n, S-1) matrix of threshold values
#' @param Go    : an (mn,mn,p,S) array of the MRGVAR(m,n,p,S) coefficients. G is constructed from Bo, Ao and W.
#' @param Ao    : an (m, m, p, n, S) array collecting coefficients of foreign variables
#' @param Bo    : an (m, m, p, n, S) array collecting coefficients of domestic variables
#' @param Uo    : a (T, mn, S) array of the temporally independent innovation processes
#' @param Sigmao : an (mn, mn, S) array of the covariance matrix of MRGVAR(m,n,p,S)
#' @param SV    : exogenous switching variables
#' @param type	: types of deterministic component "const", "none", "exog0", and  "exog1" are 4 options
#' @param Co    : an (m , k+1, n, S) array collecting the coefficients of the deterministic components of the n countries for every regime.
#' @param X	    : a (T x k x n x S) matrix of exogenous variables.
#' @param Yo    : Initial values
#' @param d     : the time lag between signal and switching
#' @return an MRGVAR object containing the generated data, the used parameters and the exogenous variables.
#' res_d = list(Y,X,Uo,resid,Go,GDC,Co,Sigmao,TH,St,SV,SESVI,Ao,Bo,check,type,m,n,p,S,W,SigmaS,Yo,d)
#' \itemize{
#'    \item Y     : a (T x nm)  matrix of simulated data via of the MRGVAR(m,n,p,S)
#'    \item X     : a (T x k x n x S) matrix of exogenous variables.
#'    \item Uo    : a (T, mn,S) array of the simulated innovations of the MRGVAR(m,n,p,S)
#'    \item C     : an (nm, (k+1),S) array containing the coefficients of the deterministic components.
#'    \item St    : a (T x n) matrix of the simulated time path of states/regimes
#'    \item check : maximum of the data for checking the stationarity
#' }
#'
#' @examples
#' ## case of n = 2, m = 2, S = 2     ## m: number of variables, n: number of countries
#' p = rep(1,12); dim(p) = c(2,3,2)
#' p[1,1,2] = 2; p[2,2,2]=2; p[,3,] = 0
#' TH = c(1:2)*0; dim(TH) = c(1,2)
#' res_d <- mrgvar_data(m=2,n=2,p=p,TH=TH,T=100,S=2,SESVI=c(1,3),type="const")
#' max(res_d$Y)
#' @export

mrgvar_data=function(m,n,p,T,S,W=NA,SESVI=NA,TH=NA,Go=NA,Ao=NA,Bo=NA,Sigmao=NA,Uo=NA,SV=NA,type=NA,Co=NA,X=NA,Yo=NA,d=NA) {
  ### m     : number of variables in a country
  ### n     : number of countries
  ### p     : lag length n x 3 x S array collecting lag length for each country with respect to domestic and foreign variable for each state. The last column specifies the number of exogenous variables for each state.
  ### T     : number of observations
  ### S     : number of regimes
  ### SESVI : n vector of indexes of the switching variable in the endogenous variables Y for the case of self-excited threshold model.
  ###         (m,n,p,T,S,SESVI) are parameters which must be provided.
  ### TH    : n x S-1  matrix of threshold values of n countries.
  ### Go    : mn x mn x p x S GVAR(m,n,p) coefficients matrix of S different regimes
  ### Sigmao: mn x mn x S array of the covariance matrix of the GVAR(m,n,p) in S different regimes
  ### Uo    : a T x mn x S  array of the temporally independent innovation processes
  ### X	    : a T x k x n x S array of exogenous variables which may be common/different to all countries and different across all states
  ###         (TH,Go,Sigmao,Uo,SV) if not provided, they will be generated randomly.
  ### type  : deterministic component "const", "none", "exog0", and "exog1" are foure options
  ### Co    : if type = "const" mu is an m x n x S array of the intercepts of the time series in the different regimes
  ###
  ###
  ### output:
  ### c("Y","Uo","Go","Sigmao","TH","St","sv","SESVI","check")
  ###
  ### Y     : T x mn data matrix of the simulated data via of the MSGVAR(m,n,p,S)
  ### Uo    : an T x mn x S   array of the temporally independent innovation processes of the MSGVAR(m,n,p,S)
  ### Go    : mn x mn x p x S array collecting the MSGVAR(m,n,p,S) coefficients in S different states
  ### Sigmao: mn x mn x S array collecting the covariance matrices of the simulated MSGVAR(m,n,p,S) in S different states
  ### TH    : S-1 vector of thresholds
  ### St    : simulated time path of states/regimes
  ### SESVI : index if the switching variable
  ### check : maximum of the data to check stationarity
  ###
  ### Remarks: The states of each country at each time step is governed by the switching variables of each country and hence there is a large numbers
  ###          of possible combinations of regimes.
  ###          The coefficients matrix can be constructed from Go, given a regime combination. The stationarity of the MRGVAR(m,n,p)
  ###          at each time step is not guaranteed. But this is not relevant. (This is a open question.)

  check = c(1:(S + 1)) * 0
  if (missing(TH)) {
    TH = NA
  }
  if (missing(W)) {
    W = NA
  }
  if (missing(SV)) {
    SV = NA
  }
  if (missing(Sigmao)) {
    Sigmao = NA
  }
  if (missing(Uo)) {
    Uo = NA
  }
  if (missing(type)) {
    type = NA
  }
  if (missing(Co)) {
    Co = NA
  }
  if (missing(Go)) {
    Go = NA
  }
  if (missing(Bo)) {
    Bo = NA
  }
  if (missing(X)) {
    X = NA
  }
  if (missing(SV)) {
    SV = NA
  }
  if (missing(d)) {
    d = NA
  }
  if (missing(Yo)) {
    Yo = NA
  }
  if (anyNA(d)) {
    d = 1
  }
  P = max(p[, 1:2, ], d)
  Pmax = max(p[, 1:2, ])
  if (anyNA(TH)) {
    TH = matrix(stats::runif(S - 1) * n, S - 1, n)
    for (i in 1:n) {
      THh = stats::runif(S - 1) - 0.5
      THh = THh[order(THh)]
      TH[, i] = THh
    }
  }
  if (anyNA(W)) {
    W = matrix(((1:(n * n))/(1:(n * n)) * 1/(n - 1)), n,
               n)
    for (i in 1:n) W[i, i] = 0
  }
  if (anyNA(Sigmao)) {
    Sigmao = (1:(m * n * m * n * S)) * 0
    dim(Sigmao) = c(m * n, m * n, S)
    for (s in 1:S) {
      GVARD = gvar_data(m, n, p[, , s], T, W = W)
      Sigmao[, , s] = GVARD$Sigmao
    }
  }
  if (anyNA(Uo)) {
    Uo = (1:(T * n * m * S)) * 0
    dim(Uo) = c(T, m * n, S)
    for (s in 1:S) Uo[, , s] = rnorm_sigma(T, Sigmao[, , s])
  }
  Ct = Uo * 0
  if (anyNA(type)) {
    type = "none"
  }
  if (type == "none") {
    CDC = c(1:(m * n * S)) * 0
    dim(CDC) = c(m, 1, n, S)
    Co = CDC
    GDC = Co
    dim(GDC) = c(n * m, 1, S)
    Ct = Uo * 0
  }
  if (type == "const") {
    CDC = stats::rnorm(m * n * S)
    dim(CDC) = c(m, 1, n, S)
    if (anyNA(Co))
      Co = CDC
    GDC = Co
    dim(GDC) = c(n * m, 1, S)
    CoV = as.vector(Co)
    for (s in 1:S) {
      CoV = as.vector(Co[, , , s])
      for (i in 1:n) Ct[, , s] = matrix(1, T, 1) %*% t(CoV)
    }
  }
  if (type == "exog1") {
    k = dim(X)[2] + 1
    CDC = stats::rnorm(m * k * n * S)
    dim(CDC) = c(m, k, n, S)
    if (anyNA(Co))
      Co = CDC
    GDC = Co
    dim(GDC) = c(n * m, k, S)
    CoV = matrix(0, k, m * n)
    for (ss in 1:S) {
      CoV = matrix(0, k, m * n)
      for (j in 1:k) CoV[j, ] = as.vector(Co[, j, , ss])
      for (i in 1:n) Ct[, ((i - 1) * m + 1):((i - 1) *
                                               m + m), ss] = cbind(matrix(1, dim(X)[1], 1),
                                                                   as.matrix(X[, , i, ss])) %*% CoV[, ((i - 1) *
                                                                                                         m + 1):((i - 1) * m + m)]
    }
  }
  if (type == "exog0") {
    k = dim(X)[2] + 1
    CDC = stats::rnorm(m * k * n * S)
    dim(CDC) = c(m, k, n, S)
    CDC[, 1, , ] = 0
    if (anyNA(Co))
      Co = CDC
    GDC = Co
    dim(GDC) = c(n * m, k, S)
    CoV = matrix(0, k, m * n)
    for (ss in 1:S) {
      CoV = matrix(0, k, m * n)
      for (j in 1:k) CoV[j, ] = as.vector(Co[, j, , ss])
      for (i in 1:n) Ct[, ((i - 1) * m + 1):((i - 1) *
                                               m + m), ss] = cbind(matrix(1, dim(X)[1], 1),
                                                                   as.matrix(X[, , i, ss])) %*% CoV[, ((i - 1) *
                                                                                                         m + 1):((i - 1) * m + m)]
    }
  }


  kkk = 1
  repeat {
    kkk = kkk + 1
    if (anyNA(Go) & anyNA(Bo)) {
      Go = (1:(m * n * m * n * Pmax * S)) * 0
      dim(Go) = c(m * n, m * n, Pmax, S)
      Bo = (1:(m * m * Pmax * n * S)) * 0
      dim(Bo) = c(m, m, Pmax, n, S)
      Ao = Bo * 0
      for (s in 1:S) {
        GVARD = gvar_data(m, n, p[, , s], T, W = W)
        Go[, , 1:max(p[, 1:2, s]), s] = GVARD$G
        check[s] = max(abs(GVARD$Y))
        Ao[, , 1:max(p[, 1:2, s]), , s] = GVARD$Ao
        Bo[, , 1:max(p[, 1:2, s]), , s] = GVARD$Bo
      }
    }
    if (!anyNA(Go) & anyNA(Bo)) {
      Bo = (1:(m * m * Pmax * n * S)) * 0
      dim(Bo) = c(m, m, Pmax, n, S)
      Ao = Bo * 0
      for (s in 1:S) {
        Bo[, , , , s] = gw2_bo_ao(Go[, , , s], W)$Bo
        Ao[, , , , s] = gw2_bo_ao(Go[, , , s], W)$Ao
      }
    }
    if (anyNA(Go) & !anyNA(Bo)) {
      Go = (1:(m * n * m * n * Pmax * S)) * 0
      dim(Go) = c(m * n, m * n, Pmax, S)
      for (s in 1:S) Go[, , , s] = bo_ao_w2_g(Bo[, , , , s], Ao[,
                                                             , , , s], W, m, n, Pmax)
    }

    if (! max(Mod(spectral_radius(Go[,,,1])),Mod(spectral_radius(Go[,,,2]))) > 1) break
    if ( kkk>100 ) break
  }



  St = matrix(0, T, n)
  Y = Uo[, , 1]
  if (!anyNA(Yo))
    Y[1:P, ] = Yo
  resid = Y * 0
  Yo = Y[1:P, ]
  if (anyNA(SV)) {
    sv = Y[, SESVI]
    SV = NA
  }
  else {
    sv = SV
  }
  ss = matrix(0, n, 1)
  for (tt in (P + 1):T) {
    if (anyNA(SV)) {
      sv = Y[, SESVI]
      SV = NA
    }
    else {
      sv = SV
    }
    svt = sv[tt - d, ]
    Bt = c(1:(m * n * m * n * Pmax)) * 0
    dim(Bt) = c(n * m, n * m, Pmax)
    for (i in 1:n) {
      ss[i] = which.min(abs(TH[, i] - svt[i]))
      if (svt[i] > TH[ss[i], i]) {
        ss[i] = ss[i] + 1
      }
      Bt[(1 + (i - 1) * m):(i * m), , ] = Go[(1 + (i -
                                                     1) * m):(i * m), , , ss[i]]
      Y[tt, (1 + (i - 1) * m):(i * m)] = Uo[tt, (1 + (i -
                                                        1) * m):(i * m), ss[i]] + Ct[tt, (1 + (i - 1) *
                                                                                            m):(i * m), ss[i]]
      resid[tt, (1 + (i - 1) * m):(i * m)] = Uo[tt, (1 +
                                                       (i - 1) * m):(i * m), ss[i]]
    }
    for (L in 1:Pmax) Y[tt, ] = Y[tt, ] + Y[tt - L, ] %*%
      t(Bt[, , L])
    St[tt, ] = ss
  }
  check[S + 1] = max(abs(Y))
  SigmaS = NA
  result = list(Y, X, Uo, resid, Go, GDC, Co, Sigmao, TH, St,
                SV, SESVI, Ao, Bo, check, type, m, n, p, S, W, SigmaS,
                Yo, d, kkk)
  names(result) = c("Y", "X", "Uo", "resid",
                    "Go", "GDC", "Co", "Sigmao",
                    "TH", "St", "SV", "SESVI", "Ao",
                    "Bo", "check", "type", "m", "n",
                    "p", "S", "W", "SigmaS", "Yo",
                    "d","kkk")
  return(result)
}



#'
#' This function will generate data from a MRGVAR object. It will generate enough data for estimation purpose.
#'
#' @param res     : an output of mrgvar_estimate
#' @return an MRGVAR object.
#'
#' @export
#' @keywords internal
mrgvar_data_r=function(res) {
### res_e : an estimated MRGVAR model that is an output of mrgvar_estimate
### T     : number of observations
### Remarks: mrgvar_data_r is used in bootstrapping to generate sufficient observations such that in the regime of rare occurrence also contains
###          sufficient observations for estimation purposed
###
###  MINH:   minimum number of observations of a nation in the rare occurrence regime.

    m = res$m
    n = res$n
    p = res$p
    if (length(p) > 1)
        pp = max(p[, 1:2, ])
    else pp = p
    T = dim(res$Y)[1]
    W = res$W
    S = res$S
    SV = res$SV
    SESVI = res$SESVI
    TH = res$TH
    Ao = res$Ao
    Bo = res$Bo
    Co = res$Co
    Go = res$Go
    type = res$type
    X = res$X
    mu = res$mu
    MINH = T
    repeat {
	 Uo_run = array(0, c(T, n * m, S))
       for (s in 1:S) Uo_run[, , s] = rnorm_sigma(T, res$Sigmao[,,s])       #### zhe ge you wenti
    	 res_run = mrgvar_data(m, n, p, T, S, W, SESVI, TH, res$Go, Ao = NA, Bo = NA, Sigmao = NA, Uo = Uo_run, SV, type, Co, X)
       for (i in 1:n) { MINH = min(MINH,sum(res_run$Y[,SESVI[i]]>TH[1,i]),sum(res_run$Y[,SESVI[i]]<TH[1,i]))}
       if (MINH > (max(p)*(m*2)+2*m)) break
          else {T=T+T; print(c(MINH,T)); MINH=T}
    }
  return(res_run)
}



#'
#' This function generates data from an multi-regime stationary VAR(p) process and returns an MRVAR(n,p,S) object that is a list containing data and the parameters used in the MRVAR(n,p,S) process.
#'
#' @param n     : number of variables
#' @param S     : number of regimes
#' @param p     : an (S x 2) matrix. Each row of p specifies the lag length and the number of exogenous variables for the corresponding regime.
#' @param T     : number of observations
#' @param SESVI : index of the switching variable
#'
#'                (n,S,p,T,SESVI) must be provided.
#' @param TH    : an (S-1)-vector of threshold values
#' @param Bo    : an (n,n,p,S) array of the coefficients of the MRVAR(n,p,S) model. If Bo is not given it will be generated.
#' @param Co    : an (n,k+1,S) array of the coefficients of the deterministic components. For type="none" Co = O*(1:n,1:S), for "const" Co is an (1:n,1:S) array, for "exog0" Co is an (n,k+1,S) array with first column zero for each regime respectively,for "exog1" Co is an (n,1+k, S) array without zero restrictions.
#' @param Sigmao : an (n,n,S)   array containing S covariance matrices of residuals, each for one regime.
#' @param Uo    : residuals, if it is not NA it will be used as input to generate data of the MRVAR(n,p,S) process.
#' @param SV    : exogenous switching variable
#' @param type  : type of the deterministic components type = c("none","const","exog0","exog1")
#' @param X     : a (T x k x S) array of exogenous variables for each state. The second dimension can be filled with zeros to take into account that the the exogenous variables are not identical in each state.
#' @param mu    : an (n x S) matrix of the regime specific means of the variables
#' @param Yo    : a (p, n, S) array of initial values of the process
#' @param Do    : a (T, n, S) array of extra exogenous components (not used with value zero)
#' @param d     : lag delays of the self-exiting switching variable.
#'              (TH,Bo,Co,Sigmao,Uo,SV,type) if not provided, they will be generated randomly.
#' @return an MRVAR(n,p,S) object that is a list containing the generated data, the used parameters and the exogenous variables.
#'
#' @examples
#' p = matrix(c(3,3,0,0),2,2)
#' res_d = mrvar_data(n=2,p=p,T=200,S=2,SESVI=1,type="const")
#' colnames(res_d$Y) = c("Y","P")
#' spectral_radius(res_d$B[,,,1])
#' spectral_radius(res_d$B[,,,2])
#' res_e = mrvar_estimate(res=res_d)
#' res_e$Summary
#' @export
mrvar_data = function(n,p,T,S,SESVI,TH,Bo,Co,Sigmao,Uo,SV,type,X,mu,Yo,Do,d) {
  ### T     : number of observations
  ### n     : number of variables
  ### p     : lag length, an S x 2 vector of lag length for each state and the number of exogenous variables for each state
  ### S     : number of states of the underlying Markov Chain
  ###         (n,p,T,S,SESVI) are parameters which must be provided.
  ### SESVI : index of the switching variable in the endogeneous variables Y for the case of self-excited threshhold model.
  ### TH    : (S-1)-vector of threshold values
  ### Bo    : n x n x p x S array collecting the coefficients of VAR(p) in S different states
  ### Sigmao: n x n x S array of the covariance matrix of the VAR(p) in S different states
  ### Uo    : an T x n x S  array of the temorally independent innovation processes
  ### SV    : exogeneous switching variable
  ### d     : lag of the self-exiting
  ###         (TH,Bo,Sigmao,Uo,SV) if not provided, they will be generated randomly.
  ###
  ### output:
  ### c("Y","Uo","Bo","Sigmao","TH","St","sv","SESVI","r_npo","check")
  ###
  ### Y     : the simulated data via of the MRVAR(p)
  ### Uo    : T x n x S array of the simulated innovations in S different states
  ### Bo    : n x n x p x S array collecting the VAR(p) coefficients in S different states
  ### Sigmao: n x n x S array collecting the covariance matrices of the simulated MRVAR(p) in S different states
  ### TH    : S-1 vector of threshold values
  ### St    : simulated time path of states
  ### sv    : the switching variable ( it is SW in the case of exogeneous switching and it is Y[,SESVI] in the case of self-excited threshold model.
  ### r_npo : n x p matrix collecting the roots of the characteristic functions in L of the n dynamically independent processes.
  ### check : maximum of the data to check stationarity
  ###
  ### Remarks: The VAR(p) process is A transformed from n dynamically independent ar processes, such that the stationary is guaranteed.
  ###
  ###
  if (missing(Yo)) {
    Yo = NA
  }
  if (missing(Do)) {
    Do = NA
  }
  if (missing(d)) {
    d = NA
  }
  if (missing(TH)) {
    TH = NA
  }
  if (missing(Bo)) {
    Bo = NA
  }
  if (missing(Sigmao)) {
    Sigmao = NA
  }
  if (missing(Uo)) {
    Uo = NA
  }
  if (missing(type)) {
    type = NA
  }
  if (missing(Co)) {
    Co = NA
  }
  if (missing(mu)) {
    mu = NA
  }
  if (missing(SV)) {
    SV = NA
  }
  if (missing(X)) {
    X = NA
  }
  if (missing(Yo)) {
    Yo = NA
  }
  if (missing(Do)) {
    Do = NA
  }
  check = c(1:(S + 1)) * 0
  if (anyNA(Yo)) {
    Yo = NA
  }
  if (anyNA(Do)) {
    Do = NA
  }
  if (anyNA(d)) {
    d = 1
  }
  P = max(p[, 1], d)
  Pmax = max(p[, 1])
  if (anyNA(TH)) {
    TH = matrix(stats::runif(S - 1), S - 1, 1)
    TH = TH[order(TH)]
  }




    if (anyNA(Bo)) {
      Bo = (1:(n * n * Pmax * S)) * 0
      dim(Bo) = c(n, n, Pmax, S)
      r_npo = c(1:(n * Pmax * S)) * 0
      dim(r_npo) = c(n, Pmax, S)
      for (i in 1:S) {
        VARD = var_data(n, p[i], T)
        Bo[, , 1:p[i, 1], i] = VARD$B
        r_npo[, 1:p[i, 1], i] = VARD$r_np
        check[i] = max(abs(VARD$Y))
      }
    }
    else {
      r_npo = NA
    }



  if (anyNA(Sigmao)) {
    Sigmao = (1:(n * n * S)) * 0
    dim(Sigmao) = c(n, n, S)
    for (i in 1:S) {
      VARD = var_data(n, Pmax, T)
      Sigmao[, , i] = VARD$Sigma
    }
  }
  if (anyNA(Uo)) {
    Uo = (1:(T * n * S)) * 0
    dim(Uo) = c(T, n, S)
    for (i in 1:S) Uo[, , i] = rnorm_sigma(T, as.matrix(Sigmao[,
                                                              , i]))
  }
  Ct = Uo * 0
  if (anyNA(type)|type=="none") {
    type = "none"
    Co = matrix(0,n,2)
    dim(Co) = c(n,1,2)
  }
  if (type == "exog0") {
    k = dim(X)[2]
    CC = stats::rnorm(n * (1 + k) * S)
    dim(CC) = c(n, k + 1, S)
    CC[, 1, ] = c(1:n) * 0
    if (anyNA(Co))
      Co = CC
    for (s in 1:S) {
      if (p[s, 2] < k)
        Co[, (p[s, 2] + 2):(k + 1), s] = Co[, (p[s, 2] +
                                                 2):(k + 1), s] * 0
      Ct[, , s] = X[, , s] %*% t(Co[, -1, s])
    }
  }
  if (type == "exog1") {
    k = dim(X)[2]
    CC = stats::rnorm(n * (1 + k) * S)
    dim(CC) = c(n, k + 1, S)
    if (anyNA(Co))
      Co = CC
    for (s in 1:S) {
      if (p[s, 2] < k)
        Co[, (p[s, 2] + 2):(k + 1), s] = Co[, (p[s, 2] +
                                                 2):(k + 1), s] * 0
      Ct[, , s] = cbind((1:T)/(1:T), X[, , s]) %*% t(Co[,
                                                        , s])
    }
  }
  if (type == "const") {
    if (anyNA(mu)) {
      mu = matrix(stats::rnorm(n * S), n, S)
      dim(mu) = c(n, 1, S)
    }
    if (anyNA(Co)) {
      Co = mu
      for (s in 1:S) {
        for (L in 1:Pmax) Co[, 1, s] = Co[, 1, s] - Bo[, , L, s] %*% mu[, 1, s]
        Ct[, , s] = matrix(1, T, 1) %*% t(Co[, 1, s])
      }
    }
    else {
      mu = Co * NA
      for (s in 1:S) {
        H = diag(n)
        for (L in 1:Pmax) H = H - Bo[, , L, s]
        mu[, 1, s] = solve(H) %*% Co[, 1, s]
        Ct[, , s] = matrix(1, T, 1) %*% t(Co[, 1, s])
      }
    }
  }
  St = (1:T) * 0
  Y = as.matrix(Uo[, , 1]) * NA
  if (anyNA(Yo)) {
    Y[1:P, ] = Uo[1:P, , 1]
    Yo = Y[1:P, ]
  }
  else {
    Y[1:P, ] = Yo
  }
  if (anyNA(Do)) {
    Do = matrix(0, n, S)
  }
  else {
    Do = Do
  }
  if (anyNA(SV)) {
    sv = Y[, SESVI]
  }
  else sv = SV
  for (tt in (P + 1):T) {
    if (anyNA(SV)) {
      sv = Y[, SESVI]
    }
    else {
      sv = SV
    }
    st = sv[tt - d]
    s = sum(st > TH) + 1
    St[tt] = s
    Y[tt, ] = Uo[tt, , s] + Ct[tt, , s] + Do[, s]
    for (L in 1:Pmax) Y[tt, ] = Y[tt, ] + Y[tt - L, ] %*%
      t(Bo[, , L, s])
  }
  check[S + 1] = max(abs(Y))
  resid = NA
  result = list(Y, X, Uo, resid, Bo, Co, Sigmao, TH, St, sv, d, SESVI, r_npo, check, n, p, S, type, Yo)
  names(result) = c("Y", "X", "Uo", "resid", "Bo", "Co", "Sigmao", "TH", "St","sv", "d", "SESVI", "r_npo","check", "n", "p", "S", "type","Yo")
  return(result)
}



#'
#' This function will generate data from a stationary VAR(p) process and return a list containing data and parameters used in the VAR(p) process.
#'
#' @param n     : number of variables
#' @param p     : lag length
#' @param T     : number of observations
#' @param r_np  : an n x p matrix of roots of the characteristic polynomials of n independent AR(p)-processes. If not provided, it will be generated randomly.
#' @param A     : an n x n full rank matrix of transformation to generate correlated VAR(p) from the n independent AR(p)
#' @param B     : (n,n,p) array of the coefficients of the VAR(p) process. If B is not given, it will be calculated out of r_np and A.
#' @param Co    : (n,k+1) matrix of the coefficients of deterministic components in a VAR(p) process. For type="none" Co = 0*(1:n), for type="const" Co is an n vector, for type="exog0" Co is an (n,k) matrix, and for type="exog1" Co is an (n,1+k) matrix.
#' @param U     : residuals, if it is not NA it will be used as input to generate the VAR(p) process.
#' @param Sigma : an n x n covariance matrix of the VAR(p) residuals.
#' @param type  : types of deterministic components. "none", "const" "exog0" and "exog1" are four options
#' @param X     : a (T x k) matrix of exogenous variables.
#' @param mu    : an n vector of the expected mean of the VAR(p) process
#' @param Yo    : a p x n matrix of initial values of the VAR(p) process
#' @return An object of VAR(p) containing the generated data, the used parameters and the exogenous variables. res = list(n,p,type,r_np,Phi,A,B,Co,Sigma,Y,X,resid,U,Y1,Yo,check)
#' @examples
#' res_d = var_data(n=2,p=2,T=100,type="const")
#' res_d = var_data(n=2,p=2,T=10,Co=c(1:2)*0,type="none")
#' res_d = var_data(n=2,p=2,T=10,Co=c(1:2),  type="const")
#' res_d = var_data(n=3,p=2,T=200,type="exog1",X=matrix(rnorm(400),200,2))
#' res_d = var_data(n=3,p=2,T=200,Co=matrix(c(0,0,0,1,2,3,3,2,1),3,3), type="exog0",
#' X=matrix(rnorm(400),200,2))
#'
#' res_d = var_data(n=2,p=2,T=100,type="const")
#' res_d = var_data(n=3,p=2,T=200,type="exog1",X=matrix(rnorm(400),200,2))
#' @export
var_data = function(n,p,T,r_np,A,B,Co,U,Sigma,type,X,mu,Yo)  {
### T     : number of observations
### n     : number of variables
### p     : lag length
### r_np  : n x p matrix of roots outside unit circle for an n dynamically independent ar-processes (Lag equations).
###         the inverse if the roots will tbe within the unit circle such that the process is stationary.
###         If not provided, it will be generated randomly.
### Sigma : The covariance matrix of the n dynamically independent processes
### A     : an n x n full rank matrix of transformation to generate correlated VAR(p) from the n independent AR(p)
###         (r_np,Sigma,A) if not provided, they will be generated randomly.
### B     : (n,n,p) array of the AR(p) process. If B is not given, it will be calculated out of r_np and A.
### Co    :  (n,k+1) vector of intercept of the VAR(p) process.
###          for "none" Co = O*(1:n), for const Co is a n vector, exog0 Co is a (n,k) matrix for exog1 Co is a (n,1+k) matrix  Depending on type it will be zeros for none,
### type  : deterministic component "none" and "const" "exog0" and "exog1" are four options
### U     : residuals, is not NA will be used to gnerate the data
### X     : (T x k) matrix of exogeneous variables.
### Yo    : (p x n) matrix of initial values of the process
### mu    : n vector of os the expected mean of the VAR(p) process.
### output:
### c("Y","U","Phi","r_np","A","B","Sigma","Y1","check")
###
### Y     : the simulated data via A transformation
### U     : the simulated innovations of VAR(p)
### Phi   : n x p matrix collecting the dynamically independent ar coefficients,
### r_np  : n x p the corresponding roots (in L) of the charachsteristic functions
### A     : the transformation matrix
### B     : the n x n x p arraies of the VAR(p) coefficients
### Sigma : the Covariance matrix of the simulated VAR(p)
### Y1    : the same simulated data calculated via B form
### check : maximum of the data to check stationarity
### type  : can assume "none", "const" "exog0" "exog1"
### X     : exogenous variables
### mu    : mean of the time series
### check : containing stationarity check
### Remarks: the dynamically independent n AR process are stationary. Hence the A transformed VAR(P)
###          is stationary, but the coefficients in B are restricted through the transformation.
###
  if (missing(r_np)) {
      r_np = NA
  }
  if (missing(A)) {
	A = NA
  }
  if (missing(B)) {
	B = NA
  }
  if (missing(Co))   {  Co = NA  }

  if (missing(U))    {  U = NA   }

  if (missing(Sigma)){	Sigma = NA  }
  if (missing(type)) {  type  = NA  }
  if (missing(X))    {   X    = NA  }

  if (missing(mu))   {  mu    = NA  }
  if (missing(Yo))   {  Yo    = NA  }

  if (anyNA(r_np)) {
     r_np = matrix(0,n,p)
     for (i in 1:n)  r_np[i,] <- 0.51/(stats::runif(p)-0.5)  #random number outside unit circle
  }
  d = dim(r_np)
  if (!(n==d[1]&p==d[2])) {print("dimension problem"); return("dimension")}

  Phi = NA
  if (anyNA(Phi))  {
  Phi = matrix(0,n,p)
  for (i in 1:n) Phi[i,] = roots_to_coef(p,r_np[i,])
  }

  if (anyNA(A)) {
  A = matrix(stats::runif(n*n),n,n);
  A = A%*%t(A)
  A = eigen(A)[[2]]
  }

  if (anyNA(B)) {
      B = matrix(0,n,n*p); dim(B) = c(n,n,p)
      if (n==1)  {B = Phi; dim(B) = c(n,n,p) }
      if (n >1)  {
		for (i in 1:p) B[,,i]= A%*%diag(Phi[,i])%*%t(A)
  	}
  }


  if (anyNA(Sigma)) {
  	Sigmao = matrix(stats::rnorm(n*n),n,n);
  	Sigmao = Sigmao%*%t(Sigmao)
	Sigma = A%*%Sigmao%*%t(A)
  }  else {
      Sigmao = solve(A)%*%Sigma%*%solve(t(A))
  }


  if (anyNA(U)) {
  	Uh = rnorm_sigma(T,Sigmao)
  	U = Uh%*%t(A)
     	}  else  {
        Uh =  U %*% solve(t(A))
  }


  if (anyNA(Yo)) {
  	Yo = Uh
      } else {
      Uh[1:p,] = Yo
      Yo       = Uh
  }

  for (i in 1:n)          {
    for ( t in (p+1):T )  {
      for (L in 1:p)    Yo[t,i] = Yo[t,i] + Yo[t-L,i]*Phi[i,L]
    }
  }
  Y1 = Yo%*%t(A)
  Ct = U*0



  if (anyNA(type)) {  type = "const" }

  type_soll = infer_deterministic_type(Co,X,type)
  if (!type_soll==type)  return(list("type mismatch",type_soll,type))

  if (type=="none")   Co = c(1:n)*0
  if (type=="const") {
  	if (anyNA(mu))     {  mu = matrix(stats::rnorm(n),n,1)}
 	if (anyNA(Co)) {
            	Co = mu
            	for (L in 1:p) Co = Co - B[,,L]%*%mu
      	}   else   {

            H = diag(n)
            for (L in 1:p) H = H - B[,,L]
            mu = solve(H)%*%Co
      }
      Ct = matrix(1,T,1)%*%t(Co)
  }

  if (type=="exog0" & anyNA(Co)) { k = ncol(as.matrix(X)); Co = matrix(stats::rnorm(n*(k+1)),n,k+1);Co[,1]=0}
  if (type=="exog1" & anyNA(Co)) { k = ncol(as.matrix(X)); Co = matrix(stats::rnorm(n*(k+1)),n,k+1)}


  if (!anyNA(X)) {
  	if (type=="exog0" )  Ct = X%*%t(Co[,-1])
  	if (type=="exog1" )  Ct = as.matrix(cbind((1:T)/(1:T),X))%*%t(Co)
  }   else   {
      X = NA
  }

  if (n >0)  {
      Y = U + Ct
	for ( tt in (p+1):T ) {
	for (L in 1:p)  Y[tt,] = Y[tt,]+Y[tt-L,]%*%t(B[,,L])
      }
  }
  check = max(abs(Y1))

  #C = (1:n)*0;
  #if (type == "const") {
  #	Y1 = Y1 + as.matrix((1:T)/(1:T))%*%t(mu)
  #    for (L in 1:p) C = C + B[,,L]%*%mu
  #}
  resid = Uh
  ### to unify the name in MODEL
  result = list(n,p,type,r_np,Phi,A,B,Co,Sigma,Y,X,resid,U,Y1,Yo,check)
  names(result)=c("n","p","type","r_np","Phi","A","B","Co","Sigma","Y","X","resid","U","Y1","Yo","check")
  return(result)
}

