# diagnostics.R
# (re)generated by tools/02_split_to_modules.R



#' Compute a near-positive-definite covariance matrix for selected states
#'
#' Builds a residual covariance matrix for the state configuration specified in
#' `StateT` and returns its nearest positive-definite approximation.
#'
#' @param res Estimated GVAR-style model object containing residual arrays and
#'   model dimensions.
#' @param StateT Integer vector giving the selected state for each unit.
#'
#' @return Numeric covariance matrix for the selected state configuration after
#'   applying `Matrix::nearPD()`.
#'
#' @examples
#' \dontrun{
#'   sigma_npd(gvar_model, c(1, 2, 3))
#' }
#'
#' @export
#' @keywords internal
#'
sigma_npd = function(res, StateT) {
      m = res$m
      p = res$p
      if (length(p) > 1) pp = max(p[, 1:2, ]) else pp = p
      n = length(StateT)
      dim(StateT) = c(1, n)
      resid = res$resid[, , 1] * 0
      for (i in 1:n) {
            resid[, (1 + (i - 1) * m):(m * i)] = res$resid[, (1 + (i - 1) * m):(m * i), StateT[i]]
      }

      sigmaT = diag(n * m)
      for (i in 1:n) {
            for (j in 1:n) {
                  NN = sum((abs(resid[, ((i - 1) * m + 1):(i * m)]) > 0) * (abs(resid[, ((j - 1) * m + 1):(j * m)]) > 0)) / m - pp * m
                  if (NN > 5) sigmaT[((i - 1) * m + 1):(i * m), ((j - 1) * m + 1):(j * m)] = t(resid[, ((i - 1) * m + 1):(i * m)]) %*% resid[, ((j - 1) * m + 1):(j * m)] / NN
                  else sigmaT[((i - 1) * m + 1):(i * m), ((j - 1) * m + 1):(j * m)] = t(res$resid[, ((i - 1) * m + 1):(i * m), 1] + res$resid[, ((i - 1) * m + 1):(i * m), 2]) %*% (res$resid[, ((j - 1) * m + 1):(j * m), 1] + res$resid[, ((j - 1) * m + 1):(j * m), 2]) / dim(resid)[1]
            }
      }
      sigmanpd = as.matrix(Matrix::nearPD(sigmaT, conv.tol = 1e-10)[[1]])
      return(sigmanpd)
}
