# estimation.R
# (re)generated by tools/02_split_to_modules.R



#'
#' This function estimates the parameters of a CIGVAR(m,n,p) object based on provided data.
#' It runs a VECM estimation country/unit by country/unit under a given cointegration rank and pieces the results together to obtain a CIGVAR.
#' @param  res  a CIGVAR object of an output of CIGVARData including at least values of m,n,p,type,Y,crk and optionally X.
#' @return a CIGVAR object with estimated parameter values, AIC, BIC and LH
#' @examples
#'
#' n = 5
#' p = (1:15)*0; dim(p) = c(5,3)
#' p[,1] = 3; p[,2]=3;
#' r_npo = (1:(3 * 3 * 5))*0; dim(r_npo) = c(3,3,5)
#' r_npo[,,1] = matrix(c(1,1,3,2,3,3,3,3,3),3,3)
#' r_npo[,,2] = matrix(c(1,2,3,2,3,3,3,3,3),3,3)
#' r_npo[,,3] = matrix(c(1,2,3,2,3,3,3,3,3),3,3)
#' r_npo[,,4] = matrix(c(1,2,3,2,3,3,3,3,3),3,3)
#' r_npo[,,5] = matrix(c(1,2,3,2,3,3,3,3,3),3,3)
#'
#' res_d = CIGVARData(m=3,n=5,p=p,T=500,r_npo=r_npo,type="const",DFYflag=0,Ncommfakt=1)
#' max(res_d$Y)
#' STAT(res_d$G)
#' plot(ts(res_d$Y[,1:10]))
#' res_e = CIGVARest(res_d)
#' res_e$Summary
#' res_e$Summary$CRK_Test
#' ## adjust the model specification according to the cointegration rank test
#' res_d$crk = c(1,2,2,2,2)
#' res_e = CIGVARest(res_d)
#' res_e$Summary
#' ## unit roots in the CIGVAR model
#' STAT(res_e$G)
#' @export
cigvar_estimate <- function (res)  {
  m = res$m
  n = res$n
  p = res$p
  Ncommfakt = res$Ncommfakt
  Z = res$Z
  Y = res$Y; if (max(abs(Y)) > 10000000) return("Check data!!!");
  X = res$X
  W = res$W
  crk = res$crk
  type = res$type
  Bo = res$Bo
  Ao = res$Ao
  Co = res$Co
  Do = res$Do
  r_npo = res$r_npo
  Ncommtrend = res$Ncommtrend
  DFYflag = res$DFYflag
  Pmax = max(p[, 1:2])
  k = max(p[, 3])
  AIC = c(1:n) * 0
  BIC = c(1:n) * 0
  LH = c(1:n) * 0
  resid = Y * 0
  Tresid = resid[, 1:m]
  VECM_domestic  = list()
  VECM_domesticS = list()
  CRKtst = list()
  T = dim(Y)[1]
  FY = Y %*% t(W %x% diag(m))
  Bo = Bo = (1:(m * m * Pmax * n)) * 0
  dim(Bo) = c(m, m, Pmax, n)
  Bo = Bo * 0
  Ao = Bo * 0
  Co = Co * 0
  Do = Do * 0
  if (type == "none")
    C = matrix(0, m * n, 1) * 0
  if (type == "const")
    C = matrix(0, m * n, 1) * 0
  if (type == "exog0")
    C = matrix(0, m * n, dim(X)[2] + 1) * 0
  if (type == "exog1")
    C = matrix(0, m * n, dim(X)[2] + 1) * 0
  for (i in 1:n) {
    y = Y[, ((i - 1) * m + 1):((i - 1) * m + m)]
    x = FY[, ((i - 1) * m + 1):((i - 1) * m + m)]
    ### add colnames
    HilfeYi  = Y[, ((i - 1) * m + 1):((i - 1) * m + m)]
    HilfeFYi = FY[, ((i - 1) * m + 1):((i - 1) * m + m)]
    if (is.null(colnames(HilfeYi))) colnames(HilfeYi)   = paste0(rep("Y",ncol(HilfeYi)),c(1:ncol(HilfeYi)))
    if (is.null(colnames(HilfeFYi))) colnames(HilfeFYi) = paste0(rep("FY",ncol(HilfeYi)),c(1:ncol(HilfeFYi)))
    y = HilfeYi
    x = HilfeFYi

    if (type == "none")
      Model = "I"
    if (type == "const")
      Model = "III"

    if (type == "exog0") {
      Model = "I"
    }
    if (type == "exog1") {
      Model = "III"
    }
    P = matrix(0, 2, 3)
    P[1, 1:2] = p[i, 1:2]
    P[2, 1:2] = p[i, 1:2]

    if (!anyNA(X)) {
      Xi = as.matrix(X[,,i])
      if (is.null(colnames(Xi))) colnames(Xi)   = paste0(rep("exog",ncol(Xi)),c(1:ncol(Xi)))
    }   else  { Xi = NA }

    #tst <- MRCVECMest2(y, x, model = Model, type = "eigen", P = P, crk = crk[i], q = 0.95, Dxflag = 1,X=Xi)
    tst <- mrcvec_mest2(y, x, model = Model, type = "eigen", P = P, crk = crk[i], q = 0.95, Dxflag = DFYflag,X=Xi,CZ=as.matrix(Z))
    #tst <- MRCVECMest2a(y,x, model = Model, type = "eigen",    P = P, crk = crk[i], q = 0.95, Dxflag = DFYflag,X=Xi,CZ=as.matrix(Z))


    #BAC = VECM2VAR(param = tst[[2]][[1]], beta = tst$beta, q = c(crk[i], P[1, 1] - 1, P[1, 2] - 1),kz=0,Dxflag=DFYflag)
    BAC = vecm2_var(param = tst[[2]][[1]], beta = tst$beta, q = c(crk[i], P[1, 1] - 1, P[1, 2] - 1),kz=Ncommfakt,Dxflag=DFYflag)

    Tresid[(T - dim(tst[[2]]$residuals)[1] + 1):T, ] = tst[[2]]$residuals
    Sigma_one = t(Tresid) %*% Tresid/(T - dim(tst[[2]][[1]])[1])
    LH_P = -(T * m/2) * log(2 * pi) - (T * m/2) + (T/2) *
      log(det(solve(Sigma_one)))
    LH_AIC = 2 * (n * (dim(tst[[2]][[1]])[1]) + n * (n +
                                                       1)/2) - 2 * LH_P
    LH_BIC = log(T) * (n * (dim(tst[[2]][[1]])[1]) + n *
                         (n + 1)/2) - 2 * LH_P
    LH_N = 2 * n * (dim(tst[[2]][[1]])[1]) + n * (n + 1)
    AIC[i] = LH_AIC
    BIC[i] = LH_BIC
    LH[i] = LH_P
    VECM_domestic[[i]] = tst[[2]]
    VECM_domesticS[[i]] <- summary_civar(lm1=tst[[2]],sname ="Z2")


    CRKtst[[i]] = tst[[1]]
    Bo[, , 1:p[i, 1], i] = BAC[[1]]
    Ao[, , 1:p[i, 2], i] = BAC[[2]]
    if (!anyNA(Do)) Do[, , 1:p[i, 1], i] = BAC[[4]]
    if (type=="none") Co[,,i] = Co[,,i]
    if (type=="const"|type=="exog1") Co[,,i] = BAC[[3]]
    if (type=="exog0") Co[,-1,i] = BAC[[3]]
    resid[1:nrow(tst[[2]]$residuals), (m * (i - 1) + 1):(i *
                                                           m)] = tst[[2]]$residuals
  }
  Sigmao = t(resid) %*% resid/(T - m * (p[i, 1] + p[i, 2]) -  p[i, 3])

  Sigmao = as.matrix(Matrix::nearPD(Sigmao)[[1]])

  G = bo_ao_w2_g(Bo, Ao, W, m, n, Pmax)
  Gs = diag(n * m)
  for (L in 1:Pmax) {
    Gs = Gs - G[, , L]
  }
  LH_g = -T * m * n/2 * log(2 * pi) - T * m * n/2 + T/2 * log(det(solve(Sigmao)))
  TwoN = 2 * (sum(p[, 1:2]) * m * m + sum(p[, 3]) * m + (type ==
                                                           "const") * n * m)
  AIC_g = TwoN - 2 * LH_g
  BIC_g = log(T) * TwoN/2 - 2 * LH_g
  res$G = G
  res$C = C
  res$Sigmao = Sigmao
  res$r_npo = NA
  res$Ao = Ao
  res$Bo = Bo
  res$Co = Co
  Summary = list(VECM_domesticS,CRKtst,LH,AIC,BIC,LH_g,AIC_g,BIC_g,r_npo,Ncommfakt)
  names(Summary) = c("Estimation_Result","CRK_Test","Country_LH_function_Value","Country_AIC","Country_BIC","LH_g","AIC_g","BIC_g","r_npo","Ncommfakt")
  res$VECM_domestic = VECM_domestic
  res$Summary = Summary
  return(res)
}



#'
#' This function estimates parameters of a specified CIVAR(p) model based on provided data.
#'
#' @param  res  :an object of CIVAR(p) containing the components which are the output of CIVARData including at least: n, p, Y, crk, and optionally X and type.
#' @return res  an object of CIVAR(p) containing estimated parameter values, AIC, BIC, LH and the estimated VECM in regression format.
#' @examples
#' p = 3
#' n = 4
#' r_np = matrix(c(1,2,1.5,1.5,2.5,2.5,2,-1.5,2,-4,1.9,-2.1),4,3)
#'
#' res_d  = CIVARData(n=4,p=3,T=200,r_np=r_np,Co =(1:n)/(1:n)*0,type="none",crk=3)
#' res_e  = CIVARest(res=res_d)
#' res_d  = CIVARData(n=4,p=3,T=200)
#' B = res_d$B
#' plot(ts(res_d$Y))
#' res_d$Co
#' res_d$type
#' res_d$crk
#' res_e = CIVARest(res=res_d)
#'
#'
#'
#' @export
civar_estimate <- function (res)
{
  n = res$n
  p = res$p
  crk = res$crk
  Y = as.matrix(res$Y)
  if (is.null(colnames(Y)))
    colnames(Y) = paste0(rep("Y", ncol(Y)), c(1:ncol(Y)))
  type = res$type
  T = dim(Y)[1]
  X = res$X
  if (!anyNA(X))
    if (is.null(colnames(X)))
      colnames(X) = paste0(rep("exog", ncol(X)),c(1:ncol(X)))
  if (type == "none" | type == "exog0")
    Model = "I"
  if (type == "const" | type == "exog1")
    Model = "III"
  if (type == "rconst")
    Model = "II"
  if (type == "rtrend")
    Model = "IV"
  if (type == "trend")
    Model = "V"
  P = matrix(0, 2, 3)
  P[, 1] = p
  Co = res$Co * 0
  C1 = res$C1 * 0
  tst <- mrcvec_mest2(y = Y, x = 0, model = Model, type = "eigen",P = P, crk = crk, q = 0.95, Dxflag = 0, X = X)
  param = tst[[2]][[1]]
  CIVAREST = vecm2_var(param = param, beta = tst$beta, q = c(crk, p - 1, 0))
  B = vecm2_var(param = param, beta = tst$beta, q = c(crk, p - 1, 0))[[1]]
  C = vecm2_var(param = param, beta = tst$beta, q = c(crk, p - 1, 0))[[3]]
  alpha <- as.matrix(t(param[1:crk, , drop = FALSE]))
  beta <- as.matrix(tst$beta)
  if (type == "rconst")
    Co = alpha %*% t(beta)[, n + 1]
  if (type == "rtrend")
    C1 = alpha %*% t(beta)[, n + 1]
  if (type == "trend") {
    C1 = param[crk + (p - 1) * n + 2, ]
    Co = param[crk + (p - 1) * n + 1, ]
  }
  LREG = tst[[2]]
  sigma = t(LREG$residuals) %*% (LREG$residuals)/(T)
  resid = Y * 0
  resid[(p + 1):T, ] = LREG$residuals
  if (type == "const" | type == "exog1")
    Co = C
  if (type == "exog0") {
    Co[, 2:(1 + dim(CIVAREST[[3]])[2])] = CIVAREST[[3]]
  }
  res$B <- B
  res$Co <- Co
  res$C1 <- C1
  res$Sigma <- sigma
  res$resid <- resid
  LH = -(T * n/2) * log(2 * pi) - (T * n/2) + ((T)/2) * log(det(solve(sigma)))
  AIC = 2 * n * (dim(tst[[2]][[1]])[1]) + n * (n + 1) - 2 *
    LH
  BIC = log(T) * (n * (dim(tst[[2]][[1]])[1]) + n * (n + 1)/2) -
    2 * LH
  LH_N = 2 * n * (dim(tst[[2]][[1]])[1]) + n * (n + 1)
  if (is.null(colnames(Y)))
    colnames(Y) = sprintf("Y%s", 1:n)
  estimation_result = summary_civar(lm1 = LREG, sname = "Z2")
  Summary = list(estimation_result, LH, AIC, BIC, LH_N, tst$erg)
  names(Summary) = c("Estimation_Results", "LH_function_Value",
                     "AIC", "BIC", "LH_N", "Johansen_Test")
  res$tst = tst
  res$Summary = Summary
  return(res)
}



#'
#' This function estimates the unknown parameters of a multi regime conditional VECM based on provided data.
#'
#' @param y	: data matrix of the endogenous variable
#' @param x	: x data matrix of the conditioning variables. If x is missing, it will estimate a unconditional VECM.
#' @param s     : the series of state variable of value (0,1) for the two regime case. Missing s implies single regime VECM.
#' @param model : It assumes one of the values in c("I","II","III","IV","V") corresponding to the five cases in Johansen test.
#' @param type  : c("eigen", "trace") corresponding to the trace test or the max eigenvalue test
#' @param crk   : cointegration rank
#' @param P     : 2 x 2 matrix containing the lag of the cointegrated VAR process. The first row is the lag of the first regime and the number of exogenous variables. If the second row is zero, this is a one regime VECM.
#' @param q     : The significance level
#' @param Dxflag : A flag indicating if the conditioning variables enter the cointegration space
#' @param X     : The conditioning variables
#' @param CZ    : Common factor variables in CIGVAR and MRCIGVAR
#' @return A list containing: the result of the Johansen test, VECM in regression format, lambda, beta, PI, GAMMA, model, P, s.
#'
#' @export
#' @keywords internal
#'
mrcvec_mest2 <- function (y, x, s, model = c("I", "II", "III","IV", "V"), type = c("eigen", "trace"), crk = 2, P = matrix(2, 2, 2), q = 0.95, Dxflag = 0, X = NA,CZ=NA)
{
  y <- as.matrix(y)
  if (q != 0.9 && q != 0.95 && q != 0.99) {
    return("please correct significance level")
  }
  S = 2
  p <- as.integer(max(P))
  pmin <- as.integer(min(P))
  N1 <- ncol(as.matrix(y))
  NN1 <- ncol(as.matrix(x))
  N <- ncol(as.matrix(y))
  n = N
  if (N1 < crk) {
    return("y's dimension must be larger than crk")
  }
  if (missing(s)) {
    s = NA
  }
  if (missing(Dxflag)) {
    Dxflag = 0
  }
  if (!anyNA(s)) {
    St = s[(p + 1):length(s)]
    NSt = 1 - s[(p + 1):length(s)]
  }
  if (!anyNA(CZ)) {
    y = cbind(CZ,y);
    kz = ncol(CZ);
  } else {
    kz = 0
  }
  if (!sum(abs(x)) == 0) {
    z <- cbind(y, x)
    Zy <- embed_ts(diff(y), p, prefix = "d")
    Zx <- embed_ts(diff(x), p, prefix = "d")
    if (P[1, 1] < p) {
      Aa = P[1, 1] * N1 + (1:((p - P[1, 1]) * N1))
      ZyI <- Zy[, -Aa]
    }
    else ZyI = Zy
    if (P[1, 2] < p) {
      Ba = P[1, 2] * NN1 + (1:((p - P[1, 2]) * NN1))
      ZxI = Zx[, -Ba]
    }
    else ZxI = Zx
    if (P[2, 1] < p) {
      Aa = P[2, 1] * N1 + (1:((p - P[2, 1]) * N1))
      ZyII = Zy[, -Aa]
    }
    else ZyII = Zy
    if (P[2, 2] < p) {
      Bb = P[2, 2] * NN1 + (1:((p - P[2, 2]) * NN1))
      ZxII = Zx[, -Bb]
    }
    else ZxII = Zx
    Z = cbind(ZyI, ZxI)
    Z_2 = cbind(ZyII, ZxII)

    #Z2   <-   Z[, -c(1:N1, P[1, 1] * N1 + 1:NN1)]
    #ZS_2 <- Z_2[, -c(1:N1, P[2, 1] * N1 + 1:NN1)]
    Z2 <-      Z[, -c(1:(kz+N1), P[1, 1] * (kz+N1) + 1:NN1)]
    ZS_2 <-  Z_2[, -c(1:(kz+N1), P[2, 1] * (kz+N1) + 1:NN1)]

  }
  else {
    z = y
    Z = embed_ts(diff(y), p, prefix = "d")
    if (p > 1) {
      if (Dxflag == 0) {
        Z2 <- Z[, -c(1:N1)]
        ZS_2 <- Z2
        Z2 <- Z2[, 1:((P[1, 1] - 1) * n)]
        ZS_2 <- ZS_2[, 1:((P[2, 1] - 1) * n)]
      }
      else {
        Z2 <- Z[, -c(1:N1)]
        Zs_2 <- Z2
        Z2 <- Z2[, 1:((P[1, 1] - 1) * n)]
        ZS_2 <- ZS_2[, 1:((P[2, 1] - 1) * n)]
      }
    }
    if (p == 1) {
      Z2 <- Z[, -c(1:N1)]
      ZS_2 <- Z2
    }
  }
  M1 <- ncol(as.matrix(z))
  T <- nrow(as.matrix(z))
  MM1 = ncol(Z)
  Y0 <- Z[, kz+c(1:N1)]
  if (Dxflag==1)   Z1 <- z[-T, ][p:(T - 1), ]
  if (Dxflag==0)   Z1 <- z[-T,1:(kz+N1)][p:(T - 1), ]
  #Z1 <- z[-T, ][p:(T - 1), ]
  M1 <- ncol(as.matrix(Z1))
  if (!anyNA(s))
    Z2 = cbind(St * Z2, NSt * ZS_2)
  T1 <- nrow(as.matrix(Y0))
  TT <- nrow(as.matrix(y))
  lT = matrix(1, T1, 1)
  colnames(lT) <- "Const"
  Trend <- matrix((p + 1):TT, (TT - p), 1)
  colnames(Trend) <- "Trend"
  if (model == "I") {
    Y0 = Y0
    Z1 = Z1
    Z2 = Z2
    if (!anyNA(X) && !anyNA(s))
      Z2 = cbind(Z2, St * X[(nrow(X) - nrow(Z2) + 1):nrow(X),
                            , 1], NSt * X[(nrow(X) - nrow(Z2) + 1):nrow(X),
                                          , 2])
    if (!anyNA(X) && anyNA(s)) {
      Xi = as.matrix(X[(nrow(X) - nrow(Z2) + 1):nrow(X),
      ])
      colnames(Xi) <- colnames(X)
      Z2 = cbind(Z2, Xi)
    }
  }
  if (model == "II") {
    Y0 = Y0
    Z1 = cbind(Z1, lT)
    Z2 = Z2
  }
  if (model == "III") {
    Y0 = Y0
    Z1 = Z1
    if (!anyNA(X) && !anyNA(s))
      Z2 = cbind(Z2, St, St * X[(nrow(X) - nrow(Z2) + 1):nrow(X),
                                , 1], NSt, NSt * X[(nrow(X) - nrow(Z2) + 1):nrow(X),
                                                   , 2])
    if (anyNA(X) && !anyNA(s))
      Z2 = cbind(Z2, St, NSt)
    if (!anyNA(X) && anyNA(s)) {
      Xi = as.matrix(X[(nrow(X) - nrow(Z2) + 1):nrow(X),
      ])
      colnames(Xi) <- colnames(X)
      Z2 = cbind(Z2, lT, Xi)
    }
    if (anyNA(X) && anyNA(s))
      Z2 = cbind(Z2, lT)
  }
  if (model == "IV") {
    Y0 = Y0
    Z1 = cbind(Z1, Trend)
    Z2 = cbind(Z2, lT)
  }
  if (model == "V") {
    Y0 = Y0
    Z1 = cbind(Z1)
    Z2 = cbind(Z2, lT, Trend)
  }
  if (ncol(Z2)>0) {
    Z2 <- shift_z2(Z2,kz,N1,P[1,1]-1)
    M00 <- crossprod(Y0)/T1
    M11 <- crossprod(Z1)/T1
    M22 <- crossprod(Z2)/T1
    M01 <- crossprod(Y0, Z1)/T1
    M02 <- crossprod(Y0, Z2)/T1
    M10 <- crossprod(Z1, Y0)/T1
    M20 <- crossprod(Z2, Y0)/T1
    M12 <- crossprod(Z1, Z2)/T1
    M21 <- crossprod(Z2, Z1)/T1
    M22inv <- solve(M22)
    R0 <- Y0 - t(M02 %*% M22inv %*% t(Z2))
    R1 <- Z1 - t(M12 %*% M22inv %*% t(Z2))
  }
  if (ncol(Z2)==0) {
    R0 = Y0
    R1 = Z1
  }
  S00 <- crossprod(R0)/T1
  S01 <- crossprod(R0, R1)/T1
  S10 <- crossprod(R1, R0)/T1
  S11 <- crossprod(R1)/T1
  Ctemp <- chol(S11, pivot = TRUE)
  pivot <- attr(Ctemp, "pivot")
  oo <- order(pivot)
  C <- t(Ctemp[, oo])
  Cinv <- solve(C)
  S00inv <- solve(S00)
  valeigen <- eigen(Cinv %*% S10 %*% S00inv %*% S01 %*% t(Cinv))
  lambda <- Re(valeigen$values)
  e <- Re(valeigen$vector)
  V <- t(Cinv) %*% e
  Vorg <- V
  V <- sapply(1:M1, function(j) V[, j]/V[1, j])
  PI <- S01 %*% solve(S11)
  if (ncol(Z2)>0)    GAMMA <- M02 %*% M22inv - PI %*% M12 %*% M22inv
  if (ncol(Z2)==0)   GAMMA <- S00 - PI %*% S10

  beta <- (V[, 1:crk])
  if (crk > 0) {
    CI = Z1 %*% beta
    if (ncol(Z2)>0) {
      VECM <- stats::lm(Y0 ~ 0 + CI + Z2)
      VECMS <- summary_civar(lm1 = VECM, sname = "Z2")
    }
    if (ncol(Z2)==0) {
      VECM <- stats::lm(Y0 ~ 0 + CI )
      VECMS <- summary_civar(lm1 = VECM, sname = "")
    }

  }
  if (crk == 0) {
    CI = 0
    if (ncol(Z2)>0) {
      VECM <- stats::lm(Y0 ~ 0 + Z2)
    }
    if (ncol(Z2)==0) {
      VECM <- stats::lm(Y0 ~ 0)
    }
  }
  E = -T1 * log(1 - lambda)
  E = E[1:N]
  resultsvecm <- summary(VECM)
  Omega = t(VECM$residuals) %*% VECM$residuals/nrow(VECM$residuals)
  if (model == "I") {
    Tab <- Tab1
  }
  if (model == "II") {
    Tab <- Tab2
  }
  if (model == "III") {
    Tab <- Tab3
  }
  if (model == "IV") {
    Tab <- Tab4
  }
  if (model == "V") {
    Tab <- Tab5
  }
  b = c(1:12)
  for (i in 1:12) {
    b[i] = Tab[2 * (i - 1) + 1, 2 + M1 - N1]
  }
  a = c(1:12)
  for (i in 1:12) {
    a[i] = Tab[2 * i, 2 + M1 - N1]
  }
  if (type == "eigen") {
    critical_vals = b
    M = matrix(0, N, 1)
    j = 1
    rank = 0
    while (j <= N && E[j] > critical_vals[N + 1 - j]) {
      M[j, ] = M[j, ] + 1
      j = j + 1
      rank = rank + 1
    }
    erg <- cbind(E, critical_vals[N:1])
    colnames(erg) <- c("teststatistic", "critical_value")
    if (N > 1) {
      rownames(erg) <- c("crk <= 0 |", paste("crk <= ",
                                             1:(N - 1), " |", sep = ""))
    }
    if (N == 1) {
      rownames(erg) <- c("crk <= 0 |")
    }
    coint_rank <- paste("Johansen-Test (with maximum-eigenvalue-teststatistic) indicates",
                        rank, "cointegrating equation(s) at the", 1 -
                          q, "level")
    result <- new.env()
    result$erg = erg
    result$estimation = VECM
    result$VECMS = VECMS
    result$lambda = E
    result$z = z
    result$Z2 = Z2
    result$Z1 = Z1
    result$Y0 = Y0
    result$R1 = R1
    result$R0 = R0
    result$Omega = Omega
    result$beta = beta
    result$PI = PI
    result$GAMMA = GAMMA
    result$model = model
    result$P = P
    result$NN1 = NN1
    result$s = s
    rr <- as.list(result)
    return(rr)
  }
  else {
    type = "trace"
    critical_vals = a
    stat = matrix(0, N, 1)
    for (i in 1:N) {
      sum = 0
      for (j in i:N) {
        sum = sum + E[j]
      }
      stat[i] = sum
    }
    M = matrix(0, N, 1)
    j = 1
    rank = 0
    while (stat[j] > critical_vals[N + 1 - j] && j <= N) {
      M[j, ] = M[j, ] + 1
      j = j + 1
      rank = rank + 1
    }
    erg <- cbind(stat, critical_vals[N:1])
    colnames(erg) <- c("teststatistic", "critical_value")
    if (N > 1) {
      rownames(erg) <- c("crk <= 0 |", paste("crk <= ",
                                             1:(N - 1), " |", sep = ""))
    }
    if (N == 1) {
      rownames(erg) <- c("crk <= 0 |")
    }
    coint_rank <- paste("Johansen-Test (with trace-teststatistic) indicates",
                        rank, "cointegrating equation(s) at the", 1 -
                          q, "level")
    result <- new.env()
    result$erg = erg
    result$estimation = VECM
    result$VECMS = VECMS
    result$lambda = E
    result$z = z
    result$Z2 = Z2
    result$Z1 = Z1
    result$Y0 = Y0
    result$R1 = R1
    result$R0 = R0
    result$Omega = Omega
    result$beta = beta
    result$PI = PI
    result$GAMMA = GAMMA
    result$model = model
    result$P = P
    result$NN1 = NN1
    result$s = s
    rr <- as.list(result)
    return(rr)
  }
}



#'
#' This function estimates the unknown parameters of a two regime conditional VECM based on provided data. The cointegrating vectors are identical in the two regimes but the adjustment speeds are different in the two regimes.
#'
#' @param y	: data matrix of the endogenous variables
#' @param x	: data matrix of the conditioning variables. If x is missing, it will estimate an unconditional VECM.
#' @param s     : the series of state variable with values (0,1) for the two regimes. Missing s implies single regime VECM.
#' @param model : It assumes one of the values in c("I","II","III","IV","V") corresponding to the five cases in the Johansen test.
#' @param type  : c("eigen", "trace") corresponding to the trace test or the max eigenvalue test
#' @param crk   : cointegration rank
#' @param P     : a (2 x 2) matrix containing the lag of the cointegrated VAR process. The first row is the lag of the first regime and the number of exogenous variables. If the second row is zero, this is a one regime VECM.
#' @param q     : The significance level used
#' @param Dxflag : a flag indicating if the conditioning variables enter the cointegration space
#' @param X     : the exogenous stationary variables
#' @param CZ    : the exogenous non-stationary common factors
#' @return a list containing: the result of JH test, VECM in regression format, lambda, beta, PI, GAMMA, model, P, s
#' @export
#' @keywords internal
#'
mrcvec_mestm <- function (y, x, s, model = c("I", "II", "III", "IV", "V"), type = c("eigen", "trace"), crk = 2, P = matrix(2, 2, 2), q = 0.95, Dxflag = 0, X = X, CZ=NA)
{
  y <- as.matrix(y)
  if (q != 0.9 && q != 0.95 && q != 0.99) {
    return("please correct significance level")

  }
  S = 2
  p <- as.integer(max(P))
  pmin <- as.integer(min(P))
  N1 <- ncol(as.matrix(y))
  NN1 <- ncol(as.matrix(x))
  N <- ncol(as.matrix(y))
  n = N
  if (N1 < crk) {
    return("y's dimension must be larger than crk")

  }
  if (missing(s)) {
    s = NA
  }
  if (missing(Dxflag)) {
    Dxflag = 0
  }
  if (!anyNA(s)) {
    St = s[(p + 1):length(s)]
    NSt = 1 - s[(p + 1):length(s)]
  }
  if (!anyNA(CZ)) {
    y = cbind(CZ,y);
    kz = ncol(CZ);
  } else {
    kz = 0
  }
  if (!sum(abs(x)) == 0) {
    z <- cbind(y, x)
    Zy <- embed_ts(diff(y), p, prefix = "d")
    Zx <- embed_ts(diff(x), p, prefix = "d")
    if (P[1, 1] < p) {
      Aa = P[1, 1] * N1 + (1:((p - P[1, 1]) * N1))
      Zy1 = Zy[, -Aa]
    }
    else Zy1 = Zy
    if (P[1, 2] < p) {
      Bb = P[1, 2] * NN1 + (1:((p - P[1, 2]) * NN1))
      Zx1 = Zx[, -Bb]
    }
    else Zx1 = Zx
    if (P[2, 1] < p) {
      Aa = P[2, 1] * N1 + (1:((p - P[2, 1]) * N1))
      Zy2 = Zy[, -Aa]
    }
    else Zy2 = Zy
    if (P[2, 2] < p) {
      Bb = P[2, 2] * NN1 + (1:((p - P[2, 2]) * NN1))
      Zx2 = Zx[, -Bb]
    }
    else Zx2 = Zx
    Z = cbind(Zy1, Zx1)
    Z_2 = cbind(Zy2, Zx2)

    Z2 <-     Z[, -c(1:(kz+N1), P[1, 1] * (kz+N1) + 1:NN1)]
    ZS_2 <- Z_2[, -c(1:(kz+N1), P[2, 1] * (kz+N1) + 1:NN1)]


  }
  else {
    z = y
    Z = embed_ts(diff(y), p, prefix = "d")
    if (Dxflag == 0) {
      Z2 <- Z[, -c(1:N1)]
      ZS_2 <- Z2
      Z2 <- Z2[, 1:((P[1, 1] - 1) * n)]
      ZS_2 <- ZS_2[, 1:((P[2, 1] - 1) * n)]
    }
    else {
      Z2 <- Z[, -c(1:N1)]
      Zs_2 <- Z2
      Z2 <- Z2[, 1:((P[1, 1] - 1) * n)]
      ZS_2 <- ZS_2[, 1:((P[2, 1] - 1) * n)]
    }
  }

  T <- nrow(as.matrix(z))
  MM1 = ncol(Z)
  Y0 <- Z[, kz+c(1:N1)]
  if (Dxflag==1)   Z1 <- z[-T, ][p:(T - 1), ]
  if (Dxflag==0)   Z1 <- z[-T,1:(kz+N1)][p:(T - 1), ]
  #Z1 <- z[-T, ][p:(T - 1), ]
  #M1 <- ncol(as.matrix(z))
  M1 <- ncol(as.matrix(Z1))
  if (!anyNA(s))
    Z2 = cbind(St * Z2, NSt * ZS_2)
  T1 <- nrow(as.matrix(Y0))
  lT = (1:T1)/(1:T1)
  Trend <- matrix(1:T1, T1, 1)
  if (model == "I") {
    Y0 = Y0
    Z1 = Z1
    Z2 = Z2
    if (!anyNA(X) & !anyNA(s)) {
      StX  = as.matrix(St * X[(nrow(X) - nrow(Z2) + 1):nrow(X), , 1]); colnames(StX)  = paste0(colnames(X),"1")
      NStX = as.matrix(NSt *X[(nrow(X) - nrow(Z2) + 1):nrow(X), , 2]); colnames(NStX) = paste0(colnames(X),"2")
      Z2 = cbind(Z2,StX,NStX)
      #Z2 = cbind(Z2, St * X[(nrow(X) - nrow(Z2) + 1):nrow(X), , 1], NSt * X[(nrow(X) - nrow(Z2) + 1):nrow(X),, 2])
    }
    if (!anyNA(X) & anyNA(s))
      Z2 = cbind(Z2, X[(nrow(X) - nrow(Z2) + 1):nrow(X),
      ])
  }
  if (model == "II") {
    Y0 = Y0
    Z1 = cbind(T1, Z1)
    Z2 = Z2
  }
  if (model == "III") {
    Y0 = Y0
    Z1 = Z1
    if (!anyNA(s) & !anyNA(X)) {
      StX  = as.matrix(St * X[(nrow(X) - nrow(Z2) + 1):nrow(X), , 1]); colnames(StX)  = paste0(colnames(X),"1")
      NStX = as.matrix(NSt *X[(nrow(X) - nrow(Z2) + 1):nrow(X), , 2]); colnames(NStX) = paste0(colnames(X),"2")


      Z2 = cbind(Z2,St,StX,NSt,NStX)
      #Z2 = cbind(Z2, St, St * X[(nrow(X) - nrow(Z2) + 1):nrow(X), , 1,drop=FALSE], NSt, NSt * X[(nrow(X) - nrow(Z2) + 1):nrow(X), , 2,drop=FALSE])

    }
    if (!anyNA(s) & anyNA(X))
      Z2 = cbind(Z2, St, NSt)
    if (anyNA(s) & !anyNA(X))
      Z2 = cbind(Z2, rep(1, T1), X[(nrow(X) - nrow(Z2) +
                                      1):nrow(X), ])
    if (anyNA(s) & anyNA(X))
      Z2 = cbind(Z2, rep(1, T1))
  }
  if (model == "IV") {
    Y0 = Y0
    Z1 = cbind(Trend, Z1)
    Z2 = cbind(Z2, lT)
  }
  if (model == "V") {
    Y0 = Y0
    Z1 = cbind(Z1)
    Z2 = cbind(Z2, lT, Trend)
  }
  if (ncol(Z2)>0) {
    Z2 <-  shift_z2m(Z2,kz,N1,max(P[,1:2])-1,min(P[,1:2])-1)

    M00 <- crossprod(Y0)/T1
    M11 <- crossprod(Z1)/T1
    M22 <- crossprod(Z2)/T1
    M01 <- crossprod(Y0, Z1)/T1
    M02 <- crossprod(Y0, Z2)/T1
    M10 <- crossprod(Z1, Y0)/T1
    M20 <- crossprod(Z2, Y0)/T1
    M12 <- crossprod(Z1, Z2)/T1
    M21 <- crossprod(Z2, Z1)/T1
    M22inv <- solve(M22)
    R0 <- Y0 - t(M02 %*% M22inv %*% t(Z2))
    R1 <- Z1 - t(M12 %*% M22inv %*% t(Z2))
  }

  if (ncol(Z2) == 0) {
    R0 = Y0
    R1 = Z1
  }

  S00 <- crossprod(R0)/T1
  S01 <- crossprod(R0, R1)/T1
  S10 <- crossprod(R1, R0)/T1
  S11 <- crossprod(R1)/T1
  Ctemp <- chol(S11, pivot = TRUE)
  pivot <- attr(Ctemp, "pivot")
  oo <- order(pivot)
  C <- t(Ctemp[, oo])
  Cinv <- solve(C)
  S00inv <- solve(S00)
  valeigen <- eigen(Cinv %*% S10 %*% S00inv %*% S01 %*% t(Cinv))
  lambda <- Re(valeigen$values)
  e <- Re(valeigen$vector)
  V <- t(Cinv) %*% e
  Vorg <- V
  V <- sapply(1:M1, function(j) V[, j]/V[1, j])
  PI <- S01 %*% solve(S11)
  GAMMA <- M02 %*% M22inv - PI %*% M12 %*% M22inv
  beta <- as.matrix(V[, 1:crk])
  beta0 <- as.matrix(V[, 1:crk])
  if (crk > 0) {
    NLm = stats::nlm(f, as.vector(beta0), beta, Z1, St, NSt, Y0, Z2)
    if ( NLm$code>2 )  betaS <- beta0  else   betaS <- NLm$estimate

    NLmcode = NLm$code
    dim(betaS) = dim(beta)
    for (i in 1:ncol(as.matrix(betaS))) betaS[, i] = betaS[, i]/(betaS[1, i])
    CI = Z1 %*% betaS
    estimation <- stats::lm(Y0 ~ 0 + CI + Z2)
    CI1 = CI * St
    CI2 = CI * NSt
    VECM1 <- stats::lm(Y0 ~ 0 + CI1 + CI2 + Z2)
    VECM1S <- summary_civar(lm1 = VECM1, sname = "Z2")
    alphaS_1 = t(VECM1$coefficients[1:crk, ])
    alphaS_2 = t(VECM1$coefficients[(1 + crk):(2 * crk),])
    if (dim(alphaS_1)[1] == 1)
      alphaS_1 <- t(alphaS_1)
    if (dim(alphaS_2)[1] == 1)
      alphaS_2 <- t(alphaS_2)
  }
  if (crk == 0) {
    CI = 0
    estimation <- stats::lm(Y0 ~ 0 + Z2)
  }
  E = -T1 * log(1 - lambda)
  E = E[1:N]
  resultsvecm <- summary(estimation)
  if (model == "I") {
    Tab <- Tab1
  }
  if (model == "II") {
    Tab <- Tab2
  }
  if (model == "III") {
    Tab <- Tab3
  }
  if (model == "IV") {
    Tab <- Tab4
  }
  if (model == "V") {
    Tab <- Tab5
  }
  b = c(1:12)
  for (i in 1:12) {
    b[i] = Tab[2 * (i - 1) + 1, 2 + M1 - N1]
  }
  a = c(1:12)
  for (i in 1:12) {
    a[i] = Tab[2 * i, 2 + M1 - N1]
  }
  if (type == "eigen") {
    critical_vals = b
    M = matrix(0, N, 1)
    j = 1
    rank = 0
    while (j <= N && E[j] > critical_vals[N + 1 - j]) {
      M[j, ] = M[j, ] + 1
      j = j + 1
      rank = rank + 1
    }
    erg <- cbind(E, critical_vals[N:1])
    colnames(erg) <- c("teststatistic", "critical_value")
    if (N > 1) {
      rownames(erg) <- c("crk <= 0 |", paste("crk <= ",
                                             1:(N - 1), " |", sep = ""))
    }
    if (N == 1) {
      rownames(erg) <- c("crk <= 0 |")
    }
    coint_rank <- paste("Johansen-Test (with maximum-eigenvalue-teststatistic) indicates",
                        rank, "cointegrating equation(s) at the", 1 -
                          q, "level")
    result <- new.env()
    result$erg = erg
    result$estimation = estimation
    result$VECM1 = VECM1
    result$VECM1S = VECM1S
    result$lambda = E
    result$z = z
    result$Z2 = Z2
    result$Z1 = Z1
    result$St = St
    result$NSt = NSt
    result$R0 = R0
    result$R1 = R1
    result$Y0 = Y0
    result$beta = beta
    result$betaS = betaS
    result$alphaS = alphaS = list(alphaS_1, alphaS_2)
    result$NLmcode = NLmcode
    result$PI = PI
    result$GAMMA = GAMMA
    result$model = model
    result$P = P
    result$NN1 = NN1
    result$s = s
    rr <- as.list(result)
    return(rr)
  }
  else {
    type = "trace"
    critical_vals = a
    stat = matrix(0, N, 1)
    for (i in 1:N) {
      sum = 0
      for (j in i:N) {
        sum = sum + E[j]
      }
      stat[i] = sum
    }
    M = matrix(0, N, 1)
    j = 1
    rank = 0
    while (stat[j] > critical_vals[N + 1 - j] && j <= N) {
      M[j, ] = M[j, ] + 1
      j = j + 1
      rank = rank + 1
    }
    erg <- cbind(stat, critical_vals[N:1])
    colnames(erg) <- c("teststatistic", "critical_value")
    if (N > 1) {
      rownames(erg) <- c("crk <= 0 |", paste("crk <= ",
                                             1:(N - 1), " |", sep = ""))
    }
    if (N == 1) {
      rownames(erg) <- c("crk <= 0 |")
    }
    coint_rank <- paste("Johansen-Test (with trace-teststatistic) indicates",
                        rank, "cointegrating equation(s) at the", 1 -
                          q, "level")
    result <- new.env()
    result$erg = erg
    result$estimation = estimation
    result$VECM1 = VECM1
    result$VECM1S = VECM1S
    result$lambda = E
    result$z = z
    result$Z2 = Z2
    result$Z1 = Z1
    result$St = St
    result$NSt = NSt
    result$R0 = R0
    result$R1 = R1
    result$Y0 = Y0
    result$beta = beta
    result$betaS = betaS
    result$alphaS = alphaS = list(alphaS_1, alphaS_2)
    result$NLmcode = NLmcode
    result$PI = PI
    result$GAMMA = GAMMA
    result$model = model
    result$P = P
    result$NN1 = NN1
    result$s = s
    rr <- as.list(result)
    return(rr)
  }
}



#'
#' This function estimates parameters of a specified conditional cointegrated VAR based on provided data.
#'
#' @param res a CCIVAR object that can be an output of CCIVARData containing at least n1,n2, Y, X, and crk.
#'
#' @return a CCIVAR object with estimated parameter values, AIC, BIC, conditional VECM in a regression format.
#'
#' @examples
#' T = 100
#' res_d <- CCIVARData(n1=4,n2=3,crk=3,p=3,T=T,type="const")
#' res_e <- CCIVARest(res=res_d)
#' res_e$Summary
#'
#' @export
cciva_rest <- function (res)
{
  n = res$n1
  p = res$p
  crk = res$crk
  Y = as.matrix(res$Y)
  if (is.null(colnames(Y)))
    colnames(Y) = paste0(rep("Y", ncol(Y)), c(1:ncol(Y)))
  type = res$type
  T = dim(Y)[1]
  X = res$X
  if (is.null(colnames(X)))
    colnames(X) = paste0(rep("X", ncol(X)), c(1:ncol(X)))
  if (!anyNA(X)) if (is.null(colnames(X))) colnames(X) = paste0(rep("exog", ncol(X)), c(1:ncol(X)))
  if (type == "none" | type == "exog0")     Model = "I"
  if (type == "const" | type == "exog1")    Model = "III"
  if (type == "trend")                      Model = "IV"
  P = matrix(0, 2, 3)
  P[, 1] = p
  Co = res$Co * 0
  #      cvecm(y=Y,x=X,model="II",type = "eigen", crk=2, p = 3, q = 0.95)
  tst <- cvecm(y=Y,x=X,model=Model,type = "eigen", crk=crk, p = p, q = 0.95)
  param = tst[[2]][[1]]
  if (type=="trend") beta = tst$beta[-1,] else beta = tst$beta
  CIVAREST = cvecm2_cvar(param = param, beta = beta, p = c(crk,p - 1, p-1),N2 = ncol(X))
  B = CIVAREST[[1]]
  Bx = CIVAREST[[2]]
  C = CIVAREST[[3]]
  alpha <- t(param[1:crk,]); dim(alpha) = c(n,crk)
  #if (type=="trend")   C1 = rowSums(alpha)  else C1 = NA
  if (type=="trend")   C1 = alpha%*%t(as.matrix(tst$beta))[,1]  else C1 = NA
  LREG = tst[[2]]
  sigma = t(LREG$residuals) %*% (LREG$residuals)/(T)
  resid = Y * 0
  resid[(p + 1):T, ] = LREG$residuals
  if (type == "const" | type == "exog1")
    Co = C
  if (type == "exog0") {
    Co[, 2:(1 + dim(CIVAREST[[3]])[2])] = CIVAREST[[3]]
  }
  res$By <- B
  res$Bx <- Bx
  res$Co <- Co
  res$C1 <- C1
  res$Sigma <- sigma
  res$resid <- resid
  LH = -(T * n/2) * log(2 * pi) - (T * n/2) + ((T)/2) * log(det(solve(sigma)))
  AIC = 2 * n * (dim(tst[[2]][[1]])[1]) + n * (n + 1) - 2 *
    LH
  BIC = log(T) * (n * (dim(tst[[2]][[1]])[1]) + n * (n + 1)/2) -
    2 * LH
  LH_N = 2 * n * (dim(tst[[2]][[1]])[1]) + n * (n + 1)
  if (is.null(colnames(Y)))
    colnames(Y) = sprintf("Y%s", 1:n)
  estimation_result = summary_civar(lm1 = LREG, sname = "Z2")
  Summary = list(estimation_result, LH, AIC, BIC, LH_N, tst$erg)
  names(Summary) = c("Estimation_Results", "LH_function_Value","AIC", "BIC", "LH_N", "Johansen_Test")
  res$tst = tst
  res$Summary = Summary
  return(res)
}



#' p = (1:12)*0; dim(p) = c(4,3);p[,1] = 2; p[,2]=1;   p[,3]=1; p[2,2]=2;
#' p
#'
#' res_d = GVARData(m=2,n=4,p=p,T=200,type="exog0",X=X)
#' res_e = GVARest(res = res_d)
#' res_e$Summary
#'
#' IRF_CB = irf_GVAR_CB(res_e,nstep=10,comb=NA,irf="gen",runs=200,conf=c(0.05,0.95))
#' dim(IRF_CB)
#' IRF_g = IRF_graph(IRF_CB,Names=NA,response=c(1,4),impulse=c(1,2,3,4), ncol=4)
#'
#'
#' @export
gvar_estimate <- function (res)  {
  m = res$m
  n = res$n
  p = res$p
  Y = res$Y
  X = res$X
  W = res$W
  type = res$type
  Bo = res$Bo
  Ao = res$Ao

  Co = res$Co
  Pmax = max(p[, 1:2])
  k = max(p[, 3])
  AIC = c(1:n) * 0
  BIC = c(1:n) * 0
  LH = c(1:n) * 0
  resid = Y * 0
  VAR_domestic = list()
  T = dim(Y)[1]
  #if (is.null(colnames(Y))) colnames(Y) = sprintf("Y%s", 1:n)
  FY = Y %*% t(W %x% diag(m));
  #colnames(FY) =  paste("F",colnames(Y),sep="")
  Bo = Bo = (1:(m * m * Pmax * n)) * 0
  dim(Bo) = c(m, m, Pmax, n)
  Ao = Bo * 0
  if (type == "none")
    C = matrix(0, m * n, 1) * 0
  if (type == "const")
    C = matrix(0, m * n, 1) * 0
  if (type == "exog0")
    C = matrix(0, m * n, dim(X)[2] + 1) * 0
  if (type == "exog1")
    C = matrix(0, m * n, dim(X)[2] + 1) * 0
  for (i in 1:n) {
    res_VAR = var_data(n = m, p = p[i, 1], T = T)
    Z = matrix(0, T, p[i, 2] * m)
    HilfeFY = FY[, (m * (i - 1) + 1):(i * m)]
    if (is.null(colnames( HilfeFY)))  colnames(HilfeFY) = sprintf("FY%s", 1:m)
    ##FYp = embed(FY[, (m * (i - 1) + 1):(i * m)], (Pmax + 1))
    FYp = embed_ts(HilfeFY, (Pmax + 1),prefix="")

    Z[(Pmax + 1):T, ] = FYp[, (m + 1):(p[i, 2] * m + m)]
    HilfeZ            = FYp[, (m + 1):(p[i, 2] * m + m)]
    colnames(Z) <- colnames(HilfeZ)

    if (type == "none")
      Z = Z
    if (type == "const")
      Z = Z
    if ((type == "exog0")|(type == "exog1")) {
      Xi <- as.matrix(X[, 1:p[i, 3], i])
      if (is.null(colnames(Xi)))  colnames(Xi) = sprintf("exog%s", 1:ncol(Xi))
      Z = cbind(Z, Xi)
    }
    ki = dim(Z)[2]
    res_VAR$Y = Y[, (m * (i - 1) + 1):(i * m)]
    res_VAR$X = Z
    if ((type == "none") | (type == "exog0")) {
      res_VAR$type = "exog0"
    }
    if ((type == "const") | (type == "exog1")) {
      res_VAR$type = "exog1"
    }
    RR = var_estimate(res_VAR)
    AIC[i] = RR$Summary$AIC
    BIC[i] = RR$Summary$BIC
    LH[i] = RR$Summary$LH
    VAR_domestic[[i]] = RR$varp
    Bo[, , 1:p[i, 1], i] = RR$B
    if (type == "none")
      Ai = RR$Co[, -1]
    if (type == "const")
      Ai = RR$Co[, -1]
    if (type == "exog0")
      Ai = RR$Co[, c(2:(m * p[i, 2] + 1))]
    if (type == "exog1")
      Ai = RR$Co[, c(2:(m * p[i, 2] + 1))]
    dim(Ai) = c(m, m, p[i, 2])
    Ao[, , 1:p[i, 2], i] = Ai
    if (type == "none") {
      C[(m * (i - 1) + 1):(i * m), ] = RR$Co[, 1]
      Co[, , i] = RR$Co[, 1]
    }
    if (type == "const") {
      C[(m * (i - 1) + 1):(i * m), ] = RR$Co[, 1]
      Co[, , i] = RR$Co[, 1]
    }
    if (type == "exog0") {
      C[(m * (i - 1) + 1):(i * m), 1:(1 + p[i, 3])] = RR$Co[,
                                                            c(1, (m * p[i, 2] + 2):(m * p[i, 2] + 1 + p[i,
                                                                                                        3]))]
      Co[, 1:(p[i, 3] + 1), i] = RR$Co[, c(1, (m * p[i,
                                                     2] + 2):(m * p[i, 2] + 1 + p[i, 3]))]
    }
    if (type == "exog1") {
      C[(m * (i - 1) + 1):(i * m), ] = RR$Co[, c(1, (m *
                                                       p[i, 2] + 2):(m * p[i, 2] + 1 + p[i, 3]))]
      Co[, , i] = RR$Co[, c(1, (m * p[i, 2] + 2):(m * p[i,
                                                        2] + 1 + p[i, 3]))]
    }
    resid[, (m * (i - 1) + 1):(i * m)] = RR$resid
  }
  Sigmao = t(resid) %*% resid/(T - m * (p[i, 1] + p[i, 2]) - p[i, 3])
  Sigmao = as.matrix(Matrix::nearPD(Sigmao)[[1]])

  G = bo_ao_w2_g(Bo, Ao, W, m, n, Pmax)
  Gs = diag(n * m)
  for (L in 1:Pmax) {
    Gs = Gs - G[, , L]
  }
  LH_g = -T * m * n/2 * log(2 * pi) - T * m * n/2 + T/2 * log(det(solve(Sigmao)))
  TwoN = sum(AIC) + 2 * sum(LH) - n * m * (m + 1) + (n * m) *
    (n * m + 1)
  AIC_g = TwoN - 2 * LH_g
  BIC_g = log(T) * TwoN/2 - 2 * LH_g
  res$G = G
  res$C = C
  res$Sigmao = Sigmao
  res$r_npo = NA
  res$Ao = Ao
  res$Bo = Bo
  res$Co = Co
  res$mu = solve(Gs) %*% C
  res$VAR_domestic = VAR_domestic
  est_result <- list()
  res$resid = resid
  for (i in 1: n)  est_result[[i]]= summary(VAR_domestic[[i]])
  Summary = list(est_result, LH, AIC, BIC, LH_g, AIC_g, BIC_g)
  names(Summary) = c("Estimation_Result", "Country_LH_function_Value", "Country_AIC", "Country_BIC", "LH_g", "AIC_g", "BIC_g")
  res$Summary = Summary
  return(res)
}



#'
#' This function estimates parameters of a multi regime cointegrated global VAR(p) model. The adjustment speeds to the cointegration relations are assumed to be different in different regimes.
#'
#' @param res   : an MRCIVAR object of the output of MRCIGVARData
#' @return      : an MRCIVAR object with estimated parameters and test statistics.
#' @examples
#' m = 2
#' n = 3
#' p = c(2,2,2,2,2,2,2,2,2,2,0,0,0,0,0,2,2,2,2,2,2,2,2,2,2,0,0,0,0,0); dim(p) = c(5,3,2)
#' p = p[1:n,,]; p[,1,] = 3; p[,2,] = 2
#'
#' TH = c(1:n)*0; dim(TH) = c(1,n)
#' SESVI=rep(1,3,5)
#' r  = rep(1,n)
#'
#' ## case of n = 3, m = 2, S = 2     ## m: number of variables, n: number of countries
#'
#' res_d <- MRCIGVARData(m=2,n=3,p=p,TH=TH,T=300,S=2, SESVI=c(1,3,5),r=rep(1,3),Ncommtrend=1)
#' # Ao
#' max(abs(res_d$Y))
#' plot(ts(res_d$Y))
#' STAT(res_d$Go[,,,2])
#' STAT(res_d$Go[,,,1])
#' max(abs(res_d$Y))
#' res_d$type
#' res_d$W
#' #   Ao =  res_d$Ao;  Bo =  res_d$Bo;  Co =  res_d$Co;
#' #   res_d <- MRCIGVARData(m=2,n=3,p=p,TH=TH,T=300,S=2, SESVI=c(1,3,5),Ao=Ao,Bo=Bo,Co=Co)
#'
#' max(res_d$Y)
#' res_e  = MRCIGVARest(res=res_d)
#' res_e$Summary
#'
#' @export
mrcigvar_estimate <- function(res) {
  ### m     : number of variables in a country
  ### n     : number of countries
  ### p     : lag length n x 3 x S array collecting lag length for each country with respect to domestic and foreign variable for each state. The last column specifies the number of exogenous variables for each state.
  ### T     : number of observations
  ### S     : number of regimes
  ### SESVI : n vector of indeces of the switching variable in the endogeneous variables Y for the case of self-excited threshold model.
  ###         (m,n,p,T,S,SESVI) are parameters which must be provided.
  ### TH    : n x S-1  matrix of threshold values of n countries.
  ### Go    : mn x mn x p x S GVAR(m,n,p) coefficients matrix of S different regimes
  ### Sigmao: mn x mn x S array of the covariance matrix of the GVAR(m,n,p) in S different regimes
  ### Uo    : a T x mn x S  array of the temorally independent innovation processes
  ### X	    : a T x k x n x S array of exogenous veriables which may be common/different to all countries and different across all states
  ###         (TH,Go,Sigmao,Uo,SV) if not provided, they will be generated randomly.
  ### type  : deterministic component "const" and "none" "exog0" "exog1" are foure options
  ### Co    : if type = "const" mu is an m x n x S array of the intercepts of the time series in the different regimes
  ###
  ###
  ### output:
  ### c("Y","Uo","Go","Sigmao","TH","St","sv","SESVI","check")
  ###
  ### Y     : T x mn data matrix of the simulated data via of the MSGVAR(m,n,p,S)
  ### Uo    : an T x mn x S   array of the temorally independent innovation processes of the MSGVAR(m,n,p,S)
  ### Go    : mn x mn x p x S array collecting the MSGVAR(m,n,p,S) coefficients in S different states
  ### Sigmao: mn x mn x S array collecting the covariance matrices of the simulated MSGVAR(m,n,p,S) in S different states
  ### TH    : S-1 vector of thresholds
  ### St    : simulated time path of states/regimes
  ### SESVI : index if the switching variable
  ### check : maximum of the data to check stationarity
  ###
  ### Remarks: The states of each country at each time step is governed by the switching variables of each country and hence there is a large numbers
  ###          of possible combinations of gegimes.
  ###          The coefficients matrix can be constructed from Go, given a regime combination. The stationarity of the GVAR(m,n,p)
  ###          at each time step is not guaranteed. But this is not relevant. (This is a open question.)
  ###
  ###
  m = res$m
  n = res$n
  p = res$p
  Y = as.matrix(res$Y);  if (max(abs(Y)) > 10000000) return("Check data!!!");
  X = res$X
  W = res$W
  type = res$type
  TH = res$TH
  SESVI = res$SESVI
  Go = res$Go
  S = res$S
  Ao = res$Ao
  Bo = res$Bo
  Co = res$Co
  GDC = res$GDC
  Sigmao = res$Sigmao * 0
  d = res$d
  r_npo = res$r_npo
  P = max(p[, 1:2, ], d)
  Pmax = max(p[, 1:2, ])
  St = res$St
  r = res$r
  Uo = res$Uo
  Z = res$Z
  if (is.null(Z)) Z   = NA
  if (!anyNA(Z))  {
    Z = as.matrix(Z)
    kz = ncol(Z)
  } else kz  = 0
  Do = res$Do
  DFYflag = res$DFYflag
  SigmaS = (1:(n * m * S * n * m * S)) * 0
  dim(SigmaS) = c(n * m * S, n * m * S)
  VECM_domestic = list()
  VECM_domesticS = list()
  CRK_tst = list()
  T = nrow(Y)
  check = c(1:(S + 1)) * 0
  LH_P = (1:n) * 0
  LH_AIC = (1:n) * 0
  LH_BIC = (1:n) * 0
  ORLHP = (1:n) * 0
  ORAIC = (1:n) * 0
  ORBIC = (1:n) * 0
  Ct = Uo * 0

  WMATn = W %x% diag(m)
  FY = Y %*% WMATn
  Go = (1:(m * n * m * n * Pmax * S)) * 0
  dim(Go) = c(m * n, m * n, Pmax, S)
  Bo = (1:(m * m * Pmax * n * S)) * 0
  dim(Bo) = c(m, m, Pmax, n, S)
  Ao = Bo * 0
  if (type == "none"|type == "exog0" )
    Model = "I"
  if (type == "const"|type =="exog1" )
    Model = "III"
  for (i in 1:n) {
    pj = t(p[i, , ])
    pjOR = pj * 0
    pjOR[1, 1] = max(pj[, 1])
    pjOR[1, 2] = max(pj[, 2])
    y = Y[, ((i - 1) * m + 1):(i * m)]
    x = FY[, ((i - 1) * m + 1):(i * m)]

    HilfeYi  = Y[, ((i - 1) * m + 1):((i - 1) * m + m)]
    HilfeFYi = FY[, ((i - 1) * m + 1):((i - 1) * m + m)]
    if (is.null(colnames(HilfeYi))) colnames(HilfeYi)   = paste0(rep("Y",ncol(HilfeYi)),c(1:ncol(HilfeYi)))
    if (is.null(colnames(HilfeFYi))) colnames(HilfeFYi) = paste0(rep("FY",ncol(HilfeYi)),c(1:ncol(HilfeFYi)))
    y = HilfeYi
    x = HilfeFYi
    crk = m - r[i]
    Sti = 2 - St[, i]
    Pmaxi = max(p[i, 1, ])
    if (!anyNA(X)) {
      if (is.null(colnames(X))) colnames(X)   = paste0(rep("X",ncol(X)),c(1:ncol(X)))
      ORXi = X[,,i,1]; dim(ORXi) = dim(X)[1:2]
      MRXi = X[,,i,];  #dim(MRXi) = c(dim(X)[1:2],2)
    } else {
      MRXi = NA
      ORXi = NA
    }
    #ORtst <- MRCVECMest2(y, x, model = Model, type = "trace",P = pjOR, crk = crk, q = 0.95, Dxflag = 0,X=ORXi)
    ORtst <- mrcvec_mest2(y,x, model = Model, type = "trace", P = pjOR, crk = crk, q = 0.95, Dxflag = DFYflag, X=ORXi, CZ=as.matrix(Z))
    nrowresidOR = nrow(ORtst[[2]]$residuals)
    UOR = ORtst[[2]]$residuals
    SigmaOR = t(UOR) %*% UOR/(T - P * m + crk - ncol(x) + (Model == "III"))
    ORLHP[i] = -(T * m/2) * log(2 * 3.1415) - (T * m/2) + T/2 * log(det(solve(SigmaOR)))
    ORAIC[i] = 2 * m * (m * pjOR[1, 1] - m + crk + (m + 1)/2) -  2 * ORLHP[i]
    ORBIC[i] = log(T) * m * (m * pjOR[1, 1] - m + crk + (m +  1)/2) - 2 * ORLHP[i]
    #tst <- MRCVECMestm(y, x, s = Sti, model = Model, type = "trace", P = pj, crk = crk, q = 0.95,X=MRXi)
    tst <- mrcvec_mestm(y, x, s = Sti, model = Model, type = "trace", P = pj, crk = crk, q = 0.95,Dxflag = DFYflag, X=MRXi,CZ=as.matrix(Z))
    VECM_domestic[[i]]     = tst$VECM1
    VECM_domesticS[[i]]    = tst$VECM1S
    CRK_tst[[i]] = tst$erg
    nrowresid = nrow(tst$VECM1$residuals)
    Uo[(T - nrowresid + 1):T, ((i - 1) * m + 1):(i * m),
       1] = (2 - St[(T - nrowresid + 1):T, i]) * tst$VECM1$residuals
    Uo[(T - nrowresid + 1):T, ((i - 1) * m + 1):(i * m),
       2] = (St[(T - nrowresid + 1):T, i] - 1) * tst$VECM1$residuals
    sigma1 = t(Uo[(T - nrowresid + 1):T, ((i - 1) * m + 1):(i *
                                                              m), 1]) %*% Uo[(T - nrowresid + 1):T, ((i - 1) *
                                                                                                       m + 1):(i * m), 1]/(sum(2 - St) - (m * sum(p[i, 1:2,
                                                                                                                                                    1]) + m - crk))
    sigma2 = t(Uo[(T - nrowresid + 1):T, ((i - 1) * m + 1):(i *
                                                              m), 2]) %*% Uo[(T - nrowresid + 1):T, ((i - 1) *
                                                                                                       m + 1):(i * m), 2]/(sum(St - 1) - (m * sum(p[i, 1:2,
                                                                                                                                                    2]) + m - crk))
    LH_P[i] = -(T * m/2) * log(2 * 3.1415) - (T * m/2) + (sum(2 -
                                                                St))/2 * log(det(solve(sigma1))) + (sum(St - 1))/2 *
      log(det(solve(sigma2)))
    LH_AIC[i] = 2 * (m * (sum(p[i, 1:2, 1]) - m + crk) +
                       m * (m + 1)/2) + 2 * (m * (sum(p[i, 1:2, 2]) - m +
                                                    crk) + m * (m + 1)/2) - 2 * LH_P[i]
    LH_BIC[i] = log(sum(2 - St)) * (m * (sum(p[i, 1:2, 1]) -
                                           m + crk) + m * (m + 1)/2) + log(sum(St - 1)) * (m * (sum(p[i, 1:2, 2]) - m + crk) + m * (m + 1)/2) - 2 * LH_P[i]


    ConnectPoint = 2*crk+(sum(pj[,1:2])-4)*m
    Diff =  (dim(tst$VECM1[[1]])[1] -  (2*crk+(sum(pj[,1:2])-4)*m))/2

    if ( Diff>0 ) {
      ADD1 = 1:Diff
      ADD2 = Diff + (1:Diff)
      if ((!type=="none")&(kz>0)) {
        CLength = Diff-kz*(pj[1,1]-1)
        ADD1 = c(1:CLength,2*CLength+1:(kz*(pj[1,1]-1)))
        ADD2 = c(CLength+1:CLength,2*CLength+kz*(pj[1,1]-1)+1:(kz*(pj[1,1]-1)))
      }
    }   else {
      ADD1 = NULL
      ADD2 = NULL

    }


    AB1 = vecm2_var(param = tst$VECM1[[1]][c(1:crk,2*crk +(1: (m * (pj[1,1] - 1 + pj[1, 2] - 1))),ConnectPoint+ADD1), ], beta = tst$betaS, q = c(crk,(pj[1, 1] - 1), (pj[1, 2] - 1)),kz=kz,Dxflag=DFYflag)
    AB2 = vecm2_var(param = tst$VECM1[[1]][c(crk+(1:crk), (crk*2 + m * (pj[1, 1] - 1 + pj[1, 2] - 1)) + 1:(m * (pj[2,1] + pj[2, 2] - 2)),ConnectPoint+ADD2), ], beta = tst$betaS, q = c(crk,(pj[2, 1] - 1), (pj[2, 2] - 1)),kz=kz,Dxflag=DFYflag)


    #AB1 = VECM2VAR(param = tst$VECM1[[1]][c(1:crk,2*crk +(1: (m * (pj[1,1] - 1 + pj[1, 2] - 1)))), ], beta = tst$betaS, q = c(crk,(pj[1, 1] - 1), (pj[1, 2] - 1)),Dxflag=DFYflag)
    #AB2 = VECM2VAR(param = tst$VECM1[[1]][c(crk+(1:crk), (crk*2 + m * (pj[1, 1] - 1 + pj[1, 2] - 1)) + 1:(m * (pj[2,1] + pj[2, 2] - 2))), ], beta = tst$betaS, q = c(crk,(pj[2, 1] - 1), (pj[2, 2] - 1)),Dxflag=DFYflag)
    Bo[, , 1:pj[1, 1], i, 1] = AB1[[1]]
    Ao[, , 1:pj[1, 2], i, 1] = AB1[[2]]
    Bo[, , 1:pj[2, 1], i, 2] = AB2[[1]]
    Ao[, , 1:pj[2, 2], i, 2] = AB2[[2]]
    if (!anyNA(Do)) {
      Do[, , 1:pj[1 ,1], i, 1] = AB1[[4]]
      Do[, , 1:pj[1 ,1], i, 2] = AB2[[4]]
    }


    if (type == "const" | type == "exog1") {
      dd = (dim(tst$VECM1[[1]])[1]-(crk*2 + (sum(pj[, -3]) - 4) * m)-2*kz*(pj[1,1]-1))/2
      Co[, , i, 1] = t(tst$VECM1[[1]][crk*2 + (sum(pj[, -3]) - 4) * m + 1:dd, ])
      Co[, , i, 2] = t(tst$VECM1[[1]][crk*2 + (sum(pj[, -3]) - 4) * m + dd +1:dd,])
      Co[, , i, 1] = AB1[[3]]
      Co[, , i, 2] = AB2[[3]]

    }
    if (type == "exog0") {
      dd = (dim(tst$VECM1[[1]])[1]-(crk*2 + (sum(pj[, -3]) - 4) * m)-2*kz*(pj[1,1]-1))/2
      Co[,-1, i, 1] =  t(tst$VECM1[[1]][crk*2 + (sum(pj[, -3]) - 4) * m + 1:dd, ])
      Co[,-1, i, 2] =  t(tst$VECM1[[1]][crk*2 + (sum(pj[, -3]) - 4) * m + 1:dd, ])
      Co[,-1, i, 1] =  AB1[[3]]
      Co[,-1, i, 2] =  AB2[[3]]

    }
  }
  for (s in 1:S) Go[, , , s] = bo_ao_w2_g(Bo[, , , , s], Ao[,
                                                         , , , s], W, m, n, Pmax)
  for (s in 1:S) Sigmao[, , s] = t(Uo[, , s]) %*% Uo[, , s]/sum(St[,
                                                                   i] == s)
  for (s in 1:S) {
    for (i in 1:n) {
      for (j in 1:n) Sigmao[(m * (i - 1) + 1):(i * m),
                            (m * (j - 1) + 1):(j * m), s] = t(Uo[, (m * (i -
                                                                           1) + 1):(i * m), s]) %*% Uo[, (m * (j - 1) +
                                                                                                            1):(j * m), s]/sum((St[, i] == s) * (St[, j] ==
                                                                                                                                                   s))
    }
  }
  for (s in 1:S) {
    for (ss in 1:S) {
      for (i in 1:n) {
        for (j in 1:n) SigmaS[((s - 1) * n * m + (i -
                                                    1) * m + 1):((s - 1) * n * m + i * m), ((ss -
                                                                                               1) * n * m + (j - 1) * m + 1):((ss - 1) * n *
                                                                                                                                m + j * m)] = t(Uo[, (m * (i - 1) + 1):(i *
                                                                                                                                                                          m), s]) %*% Uo[, (m * (j - 1) + 1):(j * m),
                                                                                                                                                                                         ss]/sum((St[, i] == s) * (St[, j] == ss))
      }
    }
  }
  res$Go = Go
  res$Sigmao = Sigmao
  res$Ao = Ao
  res$Bo = Bo
  res$Co = Co
  res$Do = Do
  res$GDC = GDC
  res$SigmaS = SigmaS
  res$resid = Uo
  res$VECM_domestic = VECM_domestic
  ORAIC  = sum(ORAIC)
  ORBIC  = sum(ORBIC)
  ORLHP  = sum(ORLHP)
  LH_BIC = sum(LH_BIC)
  LH_AIC = sum(LH_AIC)
  LH_P   = sum(LH_P)
  Summary = list(VECM_domesticS,CRK_tst,r_npo,ORLHP,ORAIC,ORBIC,LH_P,LH_AIC,LH_BIC)
  names(Summary) = c("Estimation_Result","CRK_Test","r_npo","One_Regeime_LH","One_Regime_AIC","One_Regime_BIC","LH_function_Value","AIC","BIC")
  res$Summary = Summary
  return(res)
}



#'
#'This function executes a Johansen test of cointegration ranks and estimates the parameters of a MRCIVAR(n,p,S) model.
#' @param res an MRCIVAR object of the output of MRCIVARDatam
#'
#' @return an estimated MRCIVAR object containing estimated parameters and test results
#' @export
#'
#' @examples
#' Sigma = 1:(4*4*2)
#' dim(Sigma) = c(4,4,2)
#' Sigma[,,1] = diag(4)
#' Sigma[,,2] = diag(4)
#' p=matrix(0,2,2)
#' p[,1] = c(3,3)
#'
#' res_d = MRCIVARDatam(n=4,p=p,T=250,S=2,SESVI=1,TH=0,Sigmao=Sigma,type="const",r=2)
#' colnames(res_d$Y) = c("w","p","I","Q")
#' max(abs(res_d$Y))
#' res_e = MRCIVARestm1(res=res_d)
#' res_e$Summary
#'
mrcivar_estimatem1 <- function (res)
{
  TH = res$TH
  type = res$type
  p = res$p
  S = res$S
  n = res$n
  Y = res$Y ;  if (max(abs(Y)) > 1000000) return("Check data!!!");
  if (is.null(colnames(Y)))
    colnames(Y) = paste0(rep("Y", ncol(Y)), c(1:ncol(Y)))
  X = res$X
  T = dim(Y)[1]
  SV = res$SV
  sv = res$sv
  d = res$d
  SESVI = res$SESVI
  St = 2 - res$St
  P = max(p[, 1], d)
  Pmax = max(p[, 1])
  Co = res$Co
  r = res$r
  crk = res$crk
  ms = (1:S) * 0
  LH_AIC = 0
  LH_BIC = 0
  LH_P = 0
  LH_N = 0
  b = res$Bo * NA
  cc = res$Co * NA
  sigma = res$Sigmao * NA
  resid = (1:(T * n * S)) * 0
  dim(resid) = c(T, n, S)
  Tresid = resid[, , 1]
  if (type == "none" | type == "exog0")
    Model = "I"
  if (type == "const" | type == "exog1")
    Model = "III"

  if (!anyNA(X)) {
    if (is.null(colnames(X)))
      colnames(X) = paste0(rep("X", ncol(X)), c(1:ncol(X)))
  }


  if (anyNA(X))
    Xi = NA
  else Xi = as.matrix(X[, , 1])

  ORCIVARD = civar_data(n, p = Pmax, T = T, Co = Co[, , 1],
                       type = type, X = Xi)
  ORCIVARD$Y = Y
  ORCIVAR_e = civar_estimate(res = ORCIVARD)
  tst <- mrcvec_mestm(y = Y, x = 0, s = St, model = Model, type = "eigen",
                     P = p, crk = n - r, q = 0.95, X = X)
  Tresid[(T - dim(tst$estimation$residuals)[1] + 1):T, ] = tst$estimation$residuals
  Sigma_one = t(Tresid) %*% Tresid/(T - dim(tst$estimation[[1]])[1])
  resid[, , 1] = Tresid * St
  resid[, , 2] = Tresid * (1 - St)
  sigma[, , 1] = t(resid[, , 1]) %*% resid[, , 1]/(sum(St) -
                                                     1 * (n * (p[2, 1] - 1) + crk))
  sigma[, , 2] = t(resid[, , 2]) %*% resid[, , 2]/(sum(1 -
                                                         St) - 1 * (n * (p[2, 1] - 1) + crk))
  CIVAREST = vecm2_va_rm(param = tst$VECM1[[1]], beta = tst$betaS,
                       p = c(crk, p[1, 1] - 1, p[2, 1] - 1), s = 1)
  Bo = CIVAREST[[1]]
  if (type == "const" | type == "exog1")
    Co = CIVAREST[[3]]
  if (type == "exog0") {
    Co[, 2:(1 + dim(CIVAREST[[3]])[2]), ] = CIVAREST[[3]]
  }
  LH_P = -(T * n/2) * log(2 * pi) - (T * n/2) + (sum(St))/2 *
    log(det(solve(sigma[, , 1]))) + (sum(1 - St))/2 * log(det(solve(sigma[,
                                                                          , 2])))
  LH_P = -(T * n/2) * log(2 * pi) - (T * n/2) + (sum(St))/2 *
    log(det(solve(sigma[, , 1]))) + (sum(1 - St))/2 * log(det(solve(sigma[,
                                                                          , 2])))
  LH_AIC = 2 * (n * (dim(tst$estimation[[1]])[1]) + n * (n +
                                                           1)/2) - 2 * LH_P
  LHH_AIC = 2 * (n * (n * (p[1, 1] - 1 + crk/2) + n * (n +
                                                         1)/2) + n * (n * (p[2, 1] - 1 + crk/2) + n * (n + 1)/2)) -
    2 * LH_P
  LH_BIC = log(T) * (n * (dim(tst$estimation[[1]])[1]) + n *
                       (n + 1)/2) - 2 * LH_P
  LHH_BIC = log(sum(St)) * n * (n * (p[1, 1] - 1 + crk/2) +
                                  n * (n + 1)/2) + log(sum(1 - St)) * n * (n * (p[2, 1] -
                                                                                  1 + crk/2) + n * (n + 1)/2) - 2 * LH_P
  TT = (p[1, 1] - 1) * n + (p[2, 1] - 1) * n + crk - dim(tst$estimation[[1]])[1]
  TTT = dim(tst$estimation[[1]])[1]
  LH_N = 2 * n * (dim(tst$estimation[[1]])[1]) + n * (n + 1)
  LH_TN = log(sum(St)) * n * (n * (p[1, 1] - 1 + crk/2) + n *
                                (n + 1)/2) + log(sum(1 - St)) * n * (n * (p[2, 1] - 1 +
                                                                            crk/2) + n * (n + 1)/2)
  LH_TN1 = log(T) * (n * (dim(tst$estimation[[1]])[1]) + n *
                       (n + 1)/2)
  lm_obj = tst$VECM1
  ORBIC = ORCIVAR_e$Summary$BIC
  ORAIC = ORCIVAR_e$Summary$AIC
  ORLH = ORCIVAR_e$Summary$LH
  ORLHN = ORCIVAR_e$Summary$LH_N
  res$Bo <- Bo
  res$Co <- Co
  res$Sigmao <- sigma
  res$St <- 2 - St
  res$resid <- resid
  est_result = tst$VECM1S
  Summary = list(est_result, tst$erg, LH_AIC, LH_BIC, LH_P,
                 LH_N, LHH_AIC, LHH_BIC, ORBIC, ORAIC, ORLH, ORLHN, LH_TN,
                 LH_TN1, -2 * LH_P)
  names(Summary) = c("Estimation_Result", "CRk_test",
                     "LH_AIC", "LH_BIC", "LH_P", "LH_N",
                     "LHH_AIC", "LHH_BIC", "ORBIC", "ORAIC",
                     "ORLH", "ORLHN", "LH_TN", "LH_TN1",
                     "n2LHP")
  res$Summary = Summary
  res$tst <- tst
  return(res)
}



#'
#' @param res An MRCIVAR object of the output of MRCIGVARDatam
#' @param H A matrix specifying restrictions on beta
#' @param h A vector specifying restrictions on beta
#' @param phi A vector of freely varying parameters in beta
#' @param G A matrix specifying restrictions on alpha
#' @param psi A vector of freely varying parameters in alpha
#'
#' @return A list containing estimated MRVECM under restrictions, restricted parameter, and likelihood test statistic
#' @export
#'
abc_mrciva_restm <- function(res=res,H=H,h=h,phi=phi,G=G,psi=psi) {
  ###
  ### This function runs a likelihood ratio test of linear restrictions on alpha and beta in a CIVAR model
  ###
  ###
  ###        vec(alpha'_1) = G_1[[1]] psi[[1]],  vec(alpha'_2) = G[[2]] psi[[2]]   , vec(beta) = H phi + h
  ###
  ###        example 1 (restrictions on alpha) test of exogeneity
  ###                        vec(alpha) is 45 x 1  vector  ( N = 9 crk = 5, defined by the model )
  ###                  G          is 45 x 40 matrix  ( the first variable is exogeneous, i.e. the 5 adjustment coefficient of the first variable are zero )
  ###                      psi        40 x 1 vector (free variaring parameters not appearing in the specification but implied by G)
  ###                  vec(beta)  is 45 x 1 vector   ( N = 0 crk = 5 )
  ###                  H          is 45 x 45 identity matrix
  ###                  phi        45 x 1 vector (free variaring parameters not appearing in the specification but implied by h =0
  ###                  h          45 x 1 zero matrix implying ver(beta) = phi  >> no restrictions on beta.
  ###                        (H is identity and h is zero vector implies only restrictions on alpha)
  ###
  ###        example 2 (restrictions on beta ) test of PPP
  ###                        vec(alpha) is 40 x 1  vector  ( N = 8 crk = 5 ) conditioal VECM  or VECMX model
  ###                  G          is 40 x 40 identity matrix, implying there is no restriction on alpha
  ###                      psi        40 x 1 vector (free variaring parameters not appearing in the specification but implied by the identity matrix G
  ###                  vec(beta)  is 45 x 1 vector   ( N = 0 crk = 5, defined by the model )
  ###                  H          is 45 x 2 matrix that picks out the elements under restricitons ( two colunms out of the identity matrix ) a zero row in H and the corresponding h implies zero-restrictions on beta.
  ###                             ones in a row of H and zero in the corresponding h implies non-restricted beta.
  ###                  phi        2  x 1  vector (free variaring parameters not appearing in the specification but implied by h =0
  ###                  h          45 x 1  non zero elements in this vector together with the zero elements in the corresponding row in H are the normalization conditions.
  ###                        (H is identity and h is zero vector implies only restrictions on alpha)
  ###
  ###
  ### (y,x,model = c("I","II","III","IV","V"), bnorm = c("1","2"),type = c("eigen", "trace"),p = 1, r = 2, q = 0.95, H=H,h=h,G=G)

  res_e = mrcivar_estimatem1(res=res)
  #### regime-specific constrained  ML
  betaS = res_e$tst$betaS
  alphaS = res_e$tst$alphaS
  BoR    = res$Bo*0
  CoR    = res$Co*0
  type   = res$type


  S = res$S
  n = res$n
  X = res$X
  T = dim(res$Y)[1]


  Z1    = res_e$tst$Z1
  Z2    = res_e$tst$Z2
  St    = res_e$tst$St
  NSt   = res_e$tst$NSt
  Y0    = res_e$tst$Y0
  Sigma = res_e$Sigmao
  R1    = res_e$tst$R1
  R0    = res_e$tst$R0
  code =  res_e$tst$NLmcode
  p    =  res$p
  crk  =  res$crk
  sigmaR = res$Sigmao * NA
  resid = (1:(T * n * S)) * 0
  dim(resid) = c(T, n, S)
  Tresid = resid[, , 1]

  Omega = 1.0/(nrow(res_e$tst$VECM1$residuals))*t(res_e$tst$VECM1$residuals)%*%res_e$tst$VECM1$residuals

  phi_ini  = as.vector(betaS)[(H%*%phi-h)==1]
  psi_ini1 = as.vector(t(alphaS[[1]]))[!G[[1]]%*%psi[[1]]==0]
  psi_ini2 = as.vector(t(alphaS[[2]]))[!G[[2]]%*%psi[[2]]==0]


  #f_constrained(x=c(phi,psi[[1]],psi[[2]]), beta=betaS,alpha=alphaS[[1]],G=G,H=H,phi=phi,psi=psi,h, Z1, St, NSt, Y0, Z2)
  if (crk > 0) {
    x       = c(phi_ini,psi_ini1,psi_ini2)
    XX      = stats::nlm(f_constrained,x, beta=betaS, alpha=alphaS[[1]], G, H, phi, psi,h, Z1, St, NSt, Y0, Z2,iterlim=300)
    xR      = XX$estimate
    #### not converge for bad initial value but converge for good initial value
    phir    = xR[1:length(phi)]
    psi_1r  = xR[(1+length(phi)):(length(phi)+length(psi[[1]]))]
    psi_2r  = xR[(1+(length(phi)+length(psi[[1]]))):(length(phi)+length(psi[[1]])+length(psi[[1]]))]
    betaR   = H%*%phi + h
    alpha_1 = G[[1]]%*%psi[[1]]
    alpha_2 = G[[2]]%*%psi[[2]]

    dim(betaR) = dim(betaS)
    CI = Z1 %*% betaR
    ### restrictions on alpha_1,alpha_2
    dim(alpha_1) = dim(t(alphaS[[1]]))
    alpha_1 = t(alpha_1)
    dim(alpha_2) = dim(t(alphaS[[1]]))
    alpha_2 = t(alpha_2)

    alphaR  = list(alpha_1,alpha_2)
    CI1 = (CI * St) %*%t(alpha_1)
    CI2 = (CI * NSt)%*%t(alpha_2)
    LM  <- stats::lm(Y0-CI1-CI2 ~ 0 + Z2)
    residuals <- LM$residuals
    CI10 = CI * St
    CI20 = CI * NSt
    VECMR <- stats::lm(Y0 ~ 0 + CI10 + CI20 + Z2)
    VECMR$residuals <-  residuals
    #dim(VECMR$coefficients)
    VECMR$coefficients[1:crk,]  = t(alpha_1)
    VECMR$coefficients[(crk+1):(2*crk),] = t(alpha_2)
    VECMR$coefficients[(2*crk+1):nrow(VECMR$coefficients),] = LM$coefficients
    CIVAREST = vecm2_va_rm(param = VECMR$coefficients, beta = betaR, p = c(crk, p[1, 1] - 1, p[2, 1] - 1), s = 1)
    BoR = CIVAREST[[1]]
    if (type == "const" | type == "exog1")
      CoR = CIVAREST[[3]]
    if (type == "exog0") {
      CoR[,2:(1+dim(CIVAREST[[3]])[2]),] = CIVAREST[[3]]
    }

    Tresid[(T - dim(VECMR$residuals)[1] + 1):T, ] = VECMR$residuals
    resid[ (T - dim(VECMR$residuals)[1] + 1):T, , 1] = Tresid[ (T - dim(VECMR$residuals)[1] + 1):T, ] * St
    resid[ (T - dim(VECMR$residuals)[1] + 1):T, , 2] = Tresid[ (T - dim(VECMR$residuals)[1] + 1):T, ] * (1 - St)
    sigmaR[, , 1] = t(resid[, , 1]) %*% resid[, , 1]/(sum(St) - 1 * (n * (p[2, 1] - 1) + crk))
    sigmaR[, , 2] = t(resid[, , 2]) %*% resid[, , 2]/(sum(1 - St) - 1 * (n * (p[2, 1] - 1) + crk))
    LR = sum(St)*log(det(sigmaR[,,1])) + sum(NSt)*log(det(sigmaR[,,2])) - sum(St)*log(det(Sigma[,,1])) -  sum(NSt)*log(det(Sigma[,,2]))
    dgf =  n*crk - crk - length(phi)
    p_value = 1 - stats::pchisq(LR,dgf)
    LH_P = -(T * n/2) * log(2 * pi) - (T * n/2) + (sum(St))/2 * log(det(solve(sigmaR[, , 1]))) + (sum(NSt))/2 * log(det(solve(sigmaR[,, 2])))

  }

  SepIni = rz_st2_vecm(R0,R1,Y0,Z2,Z1,St,crk)

  #tst = AB_MRCIVARTest(R0,R1,G=G,H=H,h=h,alphaR1=alphaS[[1]],alphaR2=alphaS[[2]],betaR=betaS,alpha1=SepIni$alpha1,alpha2=SepIni$alpha2,beta1=SepIni$beta1,beta2=SepIni$beta2,OmegaR=Omega,Omega1=SepIni$Omega1,Omega2=SepIni$Omega2,IC=1,T1=T,St=St,NSt=NSt)
  tst  = NA
  test = list( VECMR,BoR,CoR,sigmaR,betaR,alphaR,LR,p_value, LH_P, XX$code,tst)
  names(test) = c("VECMR","BoR","CoR","sigmaR","betaR","alphaR","LR","p_value","LH_P","code","tst")
  return(test)
}



#'
#' This function estimates the parameters of a specified MRGVAR(m,n,p,S) model based on provided data.
#'
#' @param  res  : an MRGVAR object which is an output of MRGVARData.
#' @return res  : an MRGVAR object with estimated parameters and test statistics.
#' @examples
#'
#' ## case of n = 2, m = 2, S = 2     ## m: number of variables, n: number of countries
#' p = rep(1,12); dim(p) = c(2,3,2)
#' p[1,1,2] = 2; p[2,2,2]=2; p[,3,] = 0
#' TH = c(1:2)*0; dim(TH) = c(1,2)
#' res_d <- MRGVARData(m=2,n=2,p=p,TH=TH,T=100,S=2,SESVI=c(1,3),type="const")
#' max(res_d$Y)
#'
#' ### estimation of the MRGVAR model
#' colnames(res_d$Y) = c("P","Q","Pa","Qa")
#' res_e = MRGVARest(res=res_d)
#' res_e$Summary
#'
#' IRF_CB  = irf_MRGVAR_CB(res=res_e,nstep=10,comb=NA,state=c(1,1),irf="gen1",runs=20,
#' conf=c(0.05,0.95))
#' IRF_g = IRF_graph(IRF_CB[[1]],Names=c("P","Q","Pa","Qa"))    #IRF
#' #IRF_g = IRF_graph(IRF_CB[[2]])   # accumulated IRF
#' @export
mrgvar_estimate <- function (res)
{
  m = res$m
  n = res$n
  p = res$p
  Y = as.matrix(res$Y);  if (max(abs(Y)) > 1000000) return("Check data!!!");
  X = res$X
  W = res$W
  type = res$type
  TH = res$TH
  SESVI = res$SESVI
  Go = res$Go
  S = res$S
  Ao = res$Ao
  Bo = res$Bo
  Co = res$Co
  GDC = res$GDC
  Sigmao = res$Sigmao * 0
  d = res$d
  r_npo = res$r_npo
  P = max(p, d)
  Pmax = max(p[, 1:2, ])
  SigmaS = (1:(n * m * S * n * m * S)) * 0
  dim(SigmaS) = c(n * m * S, n * m * S)
  VAR_domestic = list()
  SESVIi = SESVI/SESVI + SESVI[1] - 1
  kmax = max(p[, 3, ])
  T = dim(Y)[1]
  FY = Y %*% t(W %x% diag(m))
  resid = (1:(T * m * n * S)) * 0
  dim(resid) = c(T, m, n, S)
  if (type == "none" | type == "const")
    k = 1
  if (type == "exog0" | type == "exog1")
    k = dim(X)[2] + 1
  CC = c(1:(m * (Pmax * m + k) * S)) * 0
  dim(CC) = c(m, m * Pmax + k, S)
  EMCVG = c(1:n) * 0
  for (i in 1:n) {
    Pi = max(p[i, 1:2, ])
    CCi = c(1:(m * (Pi * m + k) * S)) * 0
    dim(CCi) = c(m, m * Pi + k, S)
    Z = matrix(0, T, Pi * m)
    HilfeFYp = FY[, (m * (i - 1) + 1):(i * m)]
    if (is.null(colnames( HilfeFYp)))  colnames(HilfeFYp) = sprintf("FY%s", 1:m)
    ## FYp = embed(FY[, (m * (i - 1) + 1):(i * m)], (Pi + 1))
    FYp = embed_ts(HilfeFYp, (Pi + 1),prefix="")
    Z[(Pi + 1):T, ] = FYp[, (m + 1):(Pi * m + m)]
    HilfeZ          = FYp[, (m + 1):(Pi * m + m)]
    colnames_Zi     <- colnames(HilfeZ)            # for none and const


    kz = dim(Z)[2]
    if (type == "none") {
      Z = rep(Z, S)
      dim(Z) = c(T, kz, S)
      ZZ = array(0, c(T, kz, S))
      for (s in 1:S) ZZ[, 1:kz, s] = Z[, , s]
    }
    if (type == "const") {
      Z = rep(Z, S)
      dim(Z) = c(T, kz, S)
      ZZ = array(0, c(T, kz, S))
      for (s in 1:S) ZZ[, 1:kz, s] = Z[, , s]
    }
    if (type == "exog0") {
      Z = rep(Z, S)
      dim(Z) = c(T, kz, S)
      ZZ = array(0, c(T, kz + kmax, S))
      for (s in 1:S) ZZ[, 1:(kz + p[i, 3, s]), s] = cbind(Z[, , s], X[, 1:p[i, 3, s], i, s])
      colnames_Zi =  c(colnames_Zi, colnames(X)[1:p[i, 3,s]] )
    }
    if (type == "exog1") {
      Z = rep(Z, S)
      dim(Z) = c(T, kz, S)
      ZZ = array(0, c(T, kz + kmax, S))
      for (s in 1:S) ZZ[, 1:(kz + p[i, 3, s]), s] = cbind(Z[, , s], X[, 1:p[i, 3, s], i, s])

      colnames_Zi =  c(colnames_Zi, colnames(X)[1:p[i, 3,s]] )
    }
    if (type == "none" | type == "exog0")
      type_holder = "exog0"
    if (type == "const" | type == "exog1")
      type_holder = "exog1"
    XX = (1:(T * dim(ZZ)[2] * S)) * 0
    dim(XX) = c(T, dim(ZZ)[2], S)
    if (!anyNA(X))
      for (s in 1:S) XX[, 1:(m * p[i, 2, s] + p[i, 3, s]), s] = ZZ[, c(1:(m * p[i, 2, s]), (m * Pi + 1):(m * Pi + p[i, 3, s])), s]
    if (anyNA(X))
      for (s in 1:S) XX[, 1:(m * p[i, 2, s]), s] = ZZ[, c(1:(m * p[i, 2, s])), s]
    colnames(XX) = colnames_Zi
    pp = t(p[i, , ])
    pp[, 2] = pp[, 2] * m
    ppp = pp[, 1:2]
    ppp[, 2] = pp[, 2] + pp[, 3]
    res_MRVAR = mrvar_data(n = m, p = ppp, T = T, S = S, Co = NA, SESVI = SESVIi[i], type = type_holder, X = XX)
    res_MRVAR$Y = Y[, (m * (i - 1) + 1):(i * m)]
    #res_MRVAR$X = XX
    res_MRVAR$SV = res_MRVAR$Y[, SESVIi[i]]
    res_MRVAR$TH = TH[, i]

    RR = mrvar_estimate(res = res_MRVAR)
    VAR_domestic[[i]] = RR
    for (s in 1:S) {
      Bo[, , 1:p[i, 1, s], i, s] = RR$Bo[, , 1:p[i, 1, s], s]
      Ai = RR$Co[, 2:(m * p[i, 2, s] + 1), s]
      dim(Ai) = c(m, m, p[i, 2, s])
      Ao[, , 1:p[i, 2, s], i, s] = Ai
      if (type == "none")
        Co[, , i, s] = RR$Co[, 1, s]
      if (type == "const")
        Co[, , i, s] = RR$Co[, 1, s]
      if (type == "exog1")
        Co[, 1:(1 + p[i, 3, s]), i, s] = RR$Co[, c(1, (m * p[i, 2, s] + 2):(m * p[i, 2, s] + p[i, 3, s] + 1)), s]
      if (type == "exog0")
        Co[, 1:(1 + p[i, 3, s]), i, s] = RR$Co[, c(1, (m * p[i, 2, s] + 2):(m * p[i, 2, s] + p[i, 3, s] + 1)), s]
    }
    Sigmao[(m * (i - 1) + 1):(i * m), (m * (i - 1) + 1):(i * m), ] = RR$Sigmao
    resid[, , i, ] = RR$resid
    GDC = Co
    dim(GDC) = c(m * n, k, S)
  }
  for (s in 1:S) {
    for (i in 1:n) {
      for (j in 1:n) Sigmao[(m * (i - 1) + 1):(i * m),
                            (m * (j - 1) + 1):(j * m), s] = t(resid[, , i,
                                                                    s]) %*% (resid[, , j, s])/(dim(Z)[1] - dim(Z)[2])
    }
  }
  for (s in 1:S) {
    for (ss in 1:S) {
      for (i in 1:n) {
        for (j in 1:n) SigmaS[((s - 1) * n * m + (i - 1) * m + 1):((s - 1) * n * m + i * m), ((ss - 1) * n * m + (j - 1) * m + 1):((ss - 1) * n * m + j * m)] = t(resid[, , i, s]) %*% (resid[, , j, ss])/sum((!resid[, 1, i, s] == 0) * (!resid[, 1, j, ss] == 0))
      }
    }
  }
  for (s in 1:S) {
    BBo = Bo[, , , , s]
    AAo = Ao[, , , , s]
    dim(BBo) = c(m, m, Pmax, n)
    dim(AAo) = c(m, m, Pmax, n)
    Go[, , , s] = bo_ao_w2_g(BBo, AAo, W, m, n, Pmax)
  }
  dim(resid) = c(T, m * n, S)
  res$Go = Go
  res$Sigmao = Sigmao
  res$Ao = Ao
  res$Bo = Bo
  res$Co = Co
  res$GDC = GDC
  res$SigmaS = SigmaS
  res$resid = resid
  res$VAR_domestic = VAR_domestic
  est_result = list()
  for (i in 1:n) {
    for (s in 1:S) {
      est_result[[(i-1)*S+s]] =summary(VAR_domestic[[i]]$vars_obj[[s]])
    }
  }
  Summary = list(est_result,CC,r_npo)
  names(Summary) = c("Estimation_Result","C","r_npo")
  res$Summary = Summary
  return(res)
}



#'
#' This function estimates the parameters of a specified MRVAR(n,p,S) based on provided data.
#'
#' @param  res  :an object of MRVAR that is an output of MRVARData including at least: n, S, p, type, Y, SESVI, TH, d, and optionally X.
#' @return an MRVAR object that is a list containing estimated parameters and some test statistics.
#'
#' @examples
#' p = matrix(c(3,3,0,0),2,2)
#' res_d = MRVARData(n=2,p=p,T=200,S=2,SESVI=1,type="const")
#' colnames(res_d$Y) = c("Y","P")
#' STAT(res_d$B[,,,1])
#' STAT(res_d$B[,,,2])
#' res_e = MRVARest(res=res_d)
#' res_e$Summary
#'
#' @export
mrvar_estimate <- function (res)
{
  TH = res$TH
  type = res$type
  p = res$p
  S = res$S
  n = res$n
  Y = res$Y;  if (max(abs(Y)) > 1000000) return("Check data!!!");
  X = res$X
  T = dim(Y)[1]
  SV = res$SV
  sv = res$sv
  d = res$d
  SESVI = res$SESVI
  P = max(p[, 1], d)
  Pmax = max(p[, 1])
  ms = (1:S) * 0
  LH_AIC = 0
  LH_BIC = 0
  LLH_AIC = 0
  LLH_BIC = 0
  LH_P = 0
  LH_N = 0
  LH_NN = 0
  b = res$Bo * 0
  cc = res$Co * 0
  sigma = res$Sigmao * 0
  resid = (1:(T * n * S)) * 0
  dim(resid) = c(T, n, S)
  Z = stats::embed(Y, Pmax + 1)
  if (!anyNA(X)) {
    XX = bind_exogenous_by_state(X)
    if (type == "none") {
      ZO = stats::embed(Y, Pmax + 1)
      cc = matrix(0, n, S)
      dim(cc) = c(n, 1, S)
    }
    if (type == "const")
      ZO = cbind(Z, (1:(T - Pmax))/(1:(T - Pmax)))
    if (type == "exog0")
      ZO = cbind(Z, XX[(Pmax + 1):T, ])
    if (type == "exog1")
      ZO = cbind(Z, ((Pmax + 1):T)/((Pmax + 1):T), XX[(Pmax +
                                                         1):T, ])
    mso = dim(ZO)[2]
    LREGOR = stats::lm(ZO[, 1:n] ~ 0 + ZO[, (n + 1):mso])
  }
  if (!anyNA(X)) {
    XX = bind_exogenous_by_state(X)
    Co = matrix(1, n, dim(XX)[2] + 1)
    if (type == "exog0")
      Co[, 1] = 0
    VARDataHelp = var_data(n = n, p = Pmax, T = T, type = type,
                          Co = Co, X = XX)
  }
  else {
    if (type == "none")
      Co = matrix(0, n, 1)
    if (type == "const")
      Co = matrix(1, n, 1)
    VARDataHelp = var_data(n = n, p = Pmax, T = T, type = type,
                          Co = Co)
  }
  VARDataHelp$Y = res$Y
  ORBIC = var_estimate(res = VARDataHelp)$Summary$BIC
  ORAIC = var_estimate(VARDataHelp)$Summary$AIC
  m <- ncol(Z)
  mm = c(1:S) * 0
  vars_obj = list()
  St = (1:T) * 0
  if (is.null(SV)) {
    sv = Y[, SESVI]
  }
  else sv = SV
  for (tt in (P + 1):T) {
    svt = sv[tt - d]
    s = which.min(abs(TH - svt))
    if (svt > TH[s]) {
      s = s + 1
    }
    else {
      s = s
    }
    St[tt] = s
  }
  select = matrix(0, T - P, S)
  select2 = select
  for (s in 1:S) {
    select[, s] = (1:(T - P)) * (St[(P + 1):T] == s)
    select2[, s] = ((P + 1):T) * (St[(P + 1):T] == s)
    Z = stats::embed(Y, P + 1)[, 1:((p[s, 1] + 1) * n)]
    if (type == "none") {
      Z = Z
      cc = matrix(0, n, S)
      dim(cc) = c(n, 1, S)
    }
    if (type == "const")
      Z = cbind(Z, (1:(T - P))/(1:(T - P)))
    if (type == "exog0")
      Z = cbind(Z, X[(P + 1):T, 1:p[s, 2], s])
    if (type == "exog1")
      Z = cbind(Z, ((P + 1):T)/((P + 1):T), X[(P + 1):T,
                                              1:p[s, 2], s])
    ms[s] = dim(Z)[2]
    if ((dim(as.matrix(Z[select[, s], 1:n]))[1] - dim(as.matrix(Z[select[, s], (n + 1):ms[s]]))[2] - n > 0)) {
      LREG = stats::lm(Z[select[, s], 1:n] ~ 0 + Z[select[, s], (n + 1):ms[s]])
      bs = as.matrix(LREG$coefficients)[1:(n * p[s, 1]), ]
      if (type == "none")
        cs = as.matrix(LREG$coefficients)[1, ] * 0
      if (type == "const")
        cs = as.matrix(LREG$coefficients)[ms[s] - n,]
      if (type == "exog0")
        cs = as.matrix(LREG$coefficients)[(n * p[s,1] + 1):(ms[s] - n), ]
      if (type == "exog1")
        cs = as.matrix(LREG$coefficients)[(n * p[s,1] + 1):(ms[s] - n), ]
      sigmas = t(LREG$residuals) %*% (LREG$residuals)/(dim(as.matrix(Z[select[,s], 1:n]))[1] - dim(as.matrix(Z[select[, s],(n + 1):ms[s]]))[2])
      bs = t(bs)
      dim(bs) = c(n, n, p[s, 1])
      b[, , 1:p[s, 1], s] = bs
      if (type == "none")
        cc[, 1, s] = (1:n) * 0
      if (type == "const")
        cc[, 1, s] = cs
      if (type == "exog0") {
        cc[, c(2:(1 + p[s, 2])), s] = t(cs)
        cc[, 1, s] = (1:n) * 0
      }
      if (type == "exog1")
        cc[, c(1:(1 + p[s, 2])), s] = t(cs)
      sigma[, , s] = sigmas
      resid[select2[, s], , s] = LREG$residuals
    }  else return("check data for regime")

    if (!is.na(log(det(as.matrix(sigma[, , s])))))
      LH_AIC = LH_AIC + 2 * n * (dim(Z[, (n + 1):ms[s]])[2] +
                                   (n + 1)/2) + dim(as.matrix(Z[select[, s], 1:n]))[1] *
      log(det(as.matrix(sigma[, , s]))) + dim(as.matrix(Z[select[,
                                                                 s], 1:n]))[1] * n * (1 + log(2 * pi))
    if (!is.na(log(det(as.matrix(sigma[, , s])))))
      LH_BIC = LH_BIC + log(dim(as.matrix(Z[select[, s],
                                            1:n]))[1]) * n * (dim(Z[, (n + 1):ms[s]])[2] +
                                                                (n + 1)/2) + dim(as.matrix(Z[select[, s], 1:n]))[1] *
      log(det(as.matrix(sigma[, , s]))) + dim(as.matrix(Z[select[,
                                                                 s], 1:n]))[1] * n * (1 + log(2 * pi))
    if (!is.na(log(det(as.matrix(sigma[, , s])))))
      LH_P = LH_P + dim(as.matrix(Z[select[, s], 1:n]))[1] *
      log(det(as.matrix(sigma[, , s]))) + dim(as.matrix(Z[select[,
                                                                 s], 1:n]))[1] * n * (1 + log(2 * pi))
    if (!is.na(log(det(as.matrix(sigma[, , s])))))
      LH_N = LH_N + 2 * n * (dim(Z[, (n + 1):ms[s]])[2] +
                               (n + 1)/2)
    if (!is.na(log(det(as.matrix(sigma[, , s])))))
      LH_NN = LH_NN + log(dim(as.matrix(Z[select[, s],
                                          1:n]))[1]) * (n * (dim(Z[, (n + 1):ms[s]])[2] +
                                                               (n + 1)/2))
    if (!is.na(log(det(as.matrix(sigma[, , s])))))
      LLH_AIC = LH_P + LH_N
    if (!is.na(log(det(as.matrix(sigma[, , s])))))
      LLH_BIC = LH_P + LH_NN
    Ys = as.matrix(Z[select[, s], 1:n])
    Zs = as.matrix(Z[select[, s], (n + 1):ms[s]])
    YY = Y[1:(nrow(as.matrix(Z[select[, s], 1:n])) + p[s,1]), ]
    if ((res$type == "exog0") | (res$type == "exog1")) {
      XX = X[1:(nrow(Z[select[, s], 1:n]) + p[s, 1]), 1:p[s,2], s]
      if (length(colnames(XX))==0) colnames(XX) = paste("XX",1:ncol(XX),sep="")
    }
    if (n > 1) {
      if (length(colnames(YY))==0) colnames(YY) = paste("YY",1:ncol(YY),sep="")
      if (res$type == "none")    var_yy = vars::VAR(y = YY, p = p[s, 1], type = "none")
      if (res$type == "const")   var_yy = vars::VAR(y = YY, p = p[s, 1], type = "const")
      if (res$type == "exog0")   var_yy = vars::VAR(y = YY, p = p[s, 1], type = "none",  exogen = XX)
      if (res$type == "exog1")   var_yy = vars::VAR(y = YY, p = p[s, 1], type = "const", exogen = XX)

      for (i in 1:n) {
        Names_of_coefficits = names(var_yy$varresult[[i]]$coefficients)
        LREG = stats::lm(Ys[, i] ~ 0 + Zs)
        var_yy$varresult[[i]] <- LREG
        names(var_yy$varresult[[i]]$coefficients) <- Names_of_coefficits
      }
      var_yy$datamat[, ] <- Z[select[, s], ]
      if (p[s, 1] > 1) {
        var_yy$y[, ] <- t(cbind(t(Ys[1:p[s, 1], ]), t(Ys)))
      }
      else {
        var_yy$y[, ] <- t(cbind(as.matrix(Ys[1:p[s, 1], ]), t(Ys)))
      }
    }
    else {
      var_yy = stats::lm(Ys ~ 0 + Zs)
    }
    vars_obj[[s]] = var_yy
  }
  res$Bo <- b
  res$Co <- cc
  res$Sigmao <- sigma
  res$St <- St
  res$resid <- resid

  MRVAR_result = list()
  for (i in 1:S) {
    MRVAR_result[[i]] = summary(vars_obj[[i]])
  }

  Summary = list(MRVAR_result, LH_AIC, LH_BIC, LH_P, LH_N, LH_NN, LLH_AIC, LLH_BIC, ORBIC, ORAIC)
  names(Summary) = c("Estimation_Result", "LH_AIC", "LH_BIC", "LH_P", "LH_N", "LH_NN", "LLH_AIC", "LLH_BIC", "ORBIC", "ORAIC")
  res$Summary = Summary
  res$vars_obj= vars_obj
  return(res)
}



#'
#' This function estimates parameters of a specified VAR(p) model based on provided data.
#'
#' @param  res  :a VAR(p) object which is an output of VARData including at least: n, p, type, Y and optionally X and type.
#' @return res  :a VAR(p) containing estimated parameter values, AIC, BIC and LH.
#' @examples
#' res_d = VARData(n=2,p=2,T=100,type="const")
#' res_e = VARest(res=res_d);
#' IRF_CB = irf_VAR_CB(res=res_e,nstep=20, comb=NA, irf = "gen1", runs = 100, conf = c(0.05, 0.95))
#' IRF_list <-IRF_graph(IRF_CB)
#' res_e$Summary
#'
#' @export
var_estimate <- function (res)
{     ### add summary
  n = res$n
  p = res$p
  Y = as.matrix(res$Y)
  X = as.matrix(res$X)
  sigma = res$Sigma
  type = res$type
  T = dim(Y)[1]
  Co = res$Co*0
  Z = stats::embed(Y, p + 1)
  if (type == "none")
    Z = Z
  if (type == "const")
    Z = cbind(Z, matrix(1, T - p, 1))
  if (type == "exog0")
    Z = cbind(Z, X[(p + 1):T, ])
  if (type == "exog1")
    Z = cbind(cbind(Z, matrix(1, T - p, 1)), X[(p + 1):T,
                                               ])
  m = dim(Z)[2]
  LREG = stats::lm(Z[, 1:n] ~ 0 + Z[, (n + 1):m])
  bs = as.matrix(LREG$coefficients)[1:(n * p), ]

  if (type == "const") {
    cs = as.matrix(LREG$coefficients)[m - n, ]
    dim(cs) = c(n, 1)
  }
  if (type == "none") {
    cs = as.matrix(LREG$coefficients)[1, ] * 0
    dim(cs) = c(n, 1)
  }
  if (type == "exog1")
    cs = t(as.matrix(LREG$coefficients)[(n * p + 1):(m -
                                                       n), ])
  if (type == "exog0") {
    if (ncol(X) > 1)
      cs = cbind(matrix(0, n, 1), t(as.matrix(LREG$coefficients)[(n *
                                                                    p + 1):(m - n), ]))
    if (ncol(X) == 1)
      cs = cbind(matrix(0, n, 1), as.matrix(LREG$coefficients)[(n *
                                                                  p + 1):(m - n), ])
  }
  sigma[,] = t(LREG$residuals) %*% (LREG$residuals)/(dim(Z)[1] -
                                                       dim(Z)[2])
  resid = Y * 0
  resid[(p + 1):T, ] = LREG$residuals
  bs = t(bs)
  dim(bs) = c(n, n, p)
  B = bs
  attr(cs,"dimnames") <- NULL
  if (type == "exog0")
    Co = (cs)
  if (type == "exog1")
    Co = (cs)
  if (type == "const")
    Co = (cs)
  if (type == "none")
    Co   = (cs)
  res$B <- B
  res$Co <- Co
  res$Sigma <- sigma
  res$resid <- resid
  LH = -(T * n/2) * log(2 * pi) - (T * n/2) + (T/2) * log(det(solve(sigma)))
  AIC = 2 * n * (m - n) + n * (n + 1) - 2 * LH
  BIC = log(T) * (n * (m - n) + n * (n + 1)/2) - 2 * LH
  if (is.null(colnames(Y)))
    colnames(Y) = sprintf("Y%s", 1:n)
  if (is.null(colnames(X)))
    colnames(X) = sprintf("X%s", 1:ncol(X))
  if (n > 1) {
    if (res$type == "none")
      varp = vars::VAR(y = Y, p = p, type = "none")
    if (res$type == "const")
      varp = vars::VAR(y = Y, p = p, type = "const")
    if (res$type == "exog0")
      varp = vars::VAR(y = Y, p = p, type = "none",
                       exogen = X)
    if (res$type == "exog1")
      varp = vars::VAR(y = Y, p = p, type = "const",
                       exogen = X)
  }
  else {
    varp = LREG
  }
  estimation_result = summary(varp)
  Summary = list(estimation_result,LH,AIC,BIC)
  names(Summary) = c("Estimation_Result","LH_function_value","AIC","BIC")
  res$Summary <- Summary
  res$varp    <- varp

  return(res)
}
