# model_selection.R
# (re)generated by tools/02_split_to_modules.R



#'
#' This function calculates AIC and BIC criteria for a range of lag specifications of the domestic and foreign variables up to the maximum given in L_V.
#'
#' @param  res  : an object generated from CIGVARest.
#' @param  L_V  : a 2 components vector containing the maxima of the domestic lag and the foreign lag, respectively.
#' @return a matrix with different lag specifications and the corresponding information criteria.
#' @examples
#'
#'
#' n = 5
#' p = (1:15)*0; dim(p) = c(5,3)
#' p[,1] = 3; p[,2]=3;
#' p[2,1] = 2;  p[3,1] = 2
#' res_d = cigvar_data(m=2,n=5,p=p,T=5000,type="const",DFYflag=0)
#' res_d$r_npo
#' res_d$check
#'
#' plot(ts(res_d$Y[1:100,1:10]))
#'
#' res_e = cigvar_estimate(res_d)
#' res_e$Summary
#' res_e$crk = c(1,1,1,1,1)
#' L_V = c(4,4)
#' CIGVARSelecte = cigvar_select_(res=res_e,L_V=c(4,4))
#' CIGVARSelecte[which.min(CIGVARSelecte[,17]),]
#' CIGVARSelecte[which.min(CIGVARSelecte[,19]),]
#'
#' @export
cigvar_select_ = function(res,L_V=L_V)  {
Criteria = matrix(0,n*(L_V[1]-1)*(L_V[2]-1),4+n*3)
idx = 0
res_dd   = res
idx = 0
n   = res$n
for (I in 1:n )           {
for (l_d in 2: L_V[1] )   {
for (l_f in 2: L_V[2] )   {

      idx = idx + 1
      res_dd$p[I,1] = l_d
      res_dd$p[I,2] = l_f


    	res_s = cigvar_estimate(res_dd)
      Criteria[idx,] = c(as.vector(res_dd$p),res_s$Summary$AIC_g,res_s$Summary$BIC_g,sum(res_s$Summary$AIC),sum(res_s$Summary$BIC))
      #colnames(Criteria) = c("l_d","l_f","AIC_g","BIC_g","AIC","BIC")
    }
 }
}
return(Criteria)
}



#' @examples
#'
#' n = 4
#' p = (1:12)*0; dim(p) = c(4,3);p[,1] = 2; p[,2]=1; p[2:3,2] = 2
#' res_d = gvar_data(m=2,n=4,p=p,T=4000,type="const")
#'
#'
#' I = 3
#' L_V = c(4,4)
#' res_d$p
#' GVARSelect = gvar_select_(res=res_d,L_V=c(4,4),I=2)
#' GVARSelect[which.min(GVARSelect[,3]),]
#' GVARSelect[which.min(GVARSelect[,4]),]
#'
#' @export
gvar_select_ = function(res=res,L_V=L_V,I=I)  {
m = res$m
n = res$n
Y = as.matrix(res$Y)
T = dim(Y)[1]
type = res$type
XXX  = res$X

Wmat = res$W
Wnmat = kronecker(Wmat,diag(m))
FYI   = Y%*%Wnmat[,((I-1)*m+1):(I*m)]
Yi = as.matrix(Y[,((I-1)*m+1):(I*m)])
Criteria = matrix(0,L_V[1]*L_V[2],4)
idx = 0

for (l_d in 1: L_V[1] )   {
   for (l_f in 1:L_V[2] ) {
      idx = idx + 1
	X = stats::embed(FYI,l_f+1)[,-(1:m)]
	XX = matrix(0,T,dim(X)[2])
	XX[(l_f+1):T,] = X
      if (type=="none")  { type_holder = "exog0"; Co = (1:(m*(1+l_f*m))); dim(Co) = c(m,l_f*m+1); Co[,1]=0}
      if (type=="const") { type_holder = "exog1"; Co = (1:(m*(1+l_f*m))); dim(Co) = c(m,l_f*m+1); Co[,1]=1}


	if (l_d>=l_f) {
            if (type=="exog0") { type_holder = type; XX = cbind(XX,XXX[,,I]); Co = matrix(1,m,1+dim(XX)[2]); Co[,1]=0}
	      if (type=="exog1") { type_holder = type; XX = cbind(XX,XXX[,,I]); Co = matrix(1,m,1+dim(XX)[2]); Co[,1]=1}
		res_dd = var_data(n=m,p=l_d,T=T,Co=Co,type=type_holder,X=as.matrix(XX))
		res_dd$Y = Yi
	}   else  {
            XX = XX[(l_f-l_d+1):T,];
	   	if (type=="exog0") { type_holder = type; XX = cbind(XX,XXX[(l_f-l_d+1):T,,I]);Co = matrix(1,m,1+dim(XX)[2]); Co[,1]=0 }
	   	if (type=="exog1") { type_holder = type; XX = cbind(XX,XXX[(l_f-l_d+1):T,,I]);Co = matrix(1,m,1+dim(XX)[2]); Co[,1]=1 }
		res_dd = var_data(n=m,p=l_d,T=(T-(l_f-l_d)),Co=Co,type=type_holder,X=XX)
		res_dd$Y = Yi[(l_f-l_d+1):T,]
	}
	res_e = var_estimate(res=res_dd)
	Criteria[idx,] = c (l_d,l_f,res_e$Summary$AIC,res_e$Summary$BIC)
    }
}
colnames(Criteria) = c("Domestic Lags","Foreign Lags","AIC","BIC")
return(Criteria)
}



#'
#' @param  res  : an MRCIGVAR object generated from mrcigvar_data or estimated from MRCIGVARest.
#' @param  L_V  : a 2 components vector containing the maxima of the domestic lag length and the foreign lag length respectively.
#' @param  TH_V  : a vector containing possible threshold values .
#' @return a matrix with different lag specifications,  threshold values and the corresponding information criteria.
#' @examples
#'
#' m = 2                  ## m: number of variables, n: number of countries
#' n = 4
#' p = c(2,2,2,2,2,2,2,2,2,2,0,0,0,0,0,2,2,2,2,2,2,2,2,2,2,0,0,0,0,0); dim(p) = c(5,3,2)
#' p = p[1:4,,]; p[,1:2,2] = 3
#'
#' TH = c(1:4)*0; dim(TH) = c(1,4)
#'
#' res_d <- mrcigvar_data(m=2,n=4,p=p,TH=TH,T=400,S=2, SESVI=c(1,3,5,7),r=rep(1,4))
#'
#' res_em = mrcigvar_estimate(res=res_d)
#'
#' L_v = c(3,3)
#' TH_v = c(0,0.1)
#' res_d$p
#'
#' MRCIGVARSelect = mrcigvar_select_(res=res_d,L_V=L_v,TH_V=TH_v)
#' dim(MRCIGVARSelect)
#' MRCIGVARSelect[which.min(MRCIGVARSelect[,28]),]
#'
#' @export
mrcigvar_select_ = function(res,L_V=L_V,TH_V=TH_V)  {
  Criteria = matrix(0,n*(L_V[1]-1)*(L_V[2]-1)*2*length(TH_V),length(as.vector(res$p))+6)
  idx = 0
  res_dd   = res
  idx = 0
  n   = res$n

  for (i in 1:n )           	{
    for (l_d in 2: L_V[1] )   	{
      for (l_f in 2: L_V[2] )   	{
        for (s  in 1:2       )    	{
          for (l_th in 1: length(TH_V) ){
            idx = idx + 1
            res_dd$p[i,1,s] = l_d
            res_dd$p[i,2,s] = l_f
            res_dd$TH       = TH_V[l_th]

            res_s = mrcigvar_estimate(res_dd)
            Criteria[idx,] = c(c(as.vector(res_dd$p),TH_V[l_th],s),res_s$Summary$AIC,res_s$Summary$BIC,res_s$Summary$One_Regime_AIC,res_s$Summary$One_Regime_BIC)
            #colnames(Criteria) = c("l_d","l_f","AIC","BIC","ORAIC","ORBIC")
          }
        }
      }
    }
  }
  return(Criteria)
}



#' @examples
#'
#' Sigma = 1:(4*4*2)
#' dim(Sigma) = c(4,4,2)
#' Sigma[,,1] = diag(4)
#' Sigma[,,2] = diag(4)
#' p=matrix(0,2,2)
#' p[,1] = c(3,2)
#'
#' res_d = mrcivar_data_m(n=4,p=p,T=2610,S=2,SESVI=1,TH=0,Sigmao=Sigma,type="const",r=1)
#' res_e = mrcivar_estimatem1(res=res_d)
#'
#' TH_v = c(0,0.1)
#' L_v = c(6,6)
#'
#' Selm = mrcivar_select_m(res=res_e,L_V=L_v,TH_V=TH_v)
#' mrvar_select__summary(Selm)
#'
#' @export
mrcivar_select_m <- function(res=res,L_V=L_V,TH_V=TH_V) {
  res_dd = res
  p      = res_dd$p
  n      = res_dd$n
  T      = dim(res_dd$Y)[1]
  SESVI  = res_dd$SESVI
  type   = res_dd$type
  TH     = res_dd$TH
  X      = res_dd$X
  p[,1]  = max(L_V)
  S      = res_dd$S
  r      = res_dd$r
  #res_dd = MRCIVARData(n=n,p=p,T=T,S=S,SESVI=SESVI,TH=TH,Sigmao=NA,type=type,r=r)

  Criteria = matrix(0,(L_V[1]-1)*(L_V[2]-1)*length(TH_V),9)
  idx = 0

  for (l_d in 2: L_V[1] )             {
    for (l_f in 2:L_V[2] )           {
      for (l_th in 1:length(TH_V))  {
        idx = idx + 1
        res_dd$p[1,1] = l_d
        res_dd$p[2,1] = l_f
        res_dd$TH     = TH_V[l_th]

        #res_dd = mrcivar_data_m(n=n,p=p,T=T,S=S,SESVI=SESVI,TH=TH,Sigmao=NA,type=type,r=r)
        #res_dd$Y= res$Y

        # for MRCIVARestm
        res_s         = mrcivar_estimatem1(res=res_dd)
        Criteria[idx,] = c (l_d,l_f,TH_V[l_th],res_s$Summary$LH_AIC,res_s$Summary$LH_BIC,res_s$Summary$LHH_AIC,res_s$Summary$LHH_BIC,res_s$Summary$ORAIC,res_s$Summary$ORBIC)
        colnames(Criteria) = c("Lag_regime1","Lag_regime2" ,"threshold","AIC","BIC","LHH_AIC","LHH_BIC","ORAIC","ORBIC")
        # for MECIVARest
        #res_s         = MRCIVARest(res=res_dd)
        #Criteria[idx,] = c (l_d,l_f,TH_V[l_th],res_s$LH_AIC,res_s$LH_BIC,res_s$LH_P,res_s$LH_N,res_s$ORAIC,res_s$ORBIC)
        #colnames(Criteria) = c("Lag_regime1","Lag_regime2" ,"threshold","AIC","BIC","LH_P","LH_N","ORAIC","ORBIC")
      }
    }
  }
  return(Criteria)
}



#' p[,2,] = 1; p[1,1,1] = 1; p[3,1,1] = 1; p[2,1,2] = 1
#'
#' TH = c(1:5)*0; dim(TH) = c(1,5)
#' res_d <- mrgvar_data(m=3,n=5,p=p,TH =TH,T=400,S=2,SESVI=((1:5)*3-2))
#' max(abs(res_d$Y))		# to make sure it is not explosive
#' colnames(res_d$Y) = c("Y11","Y21","Y31","Y12","Y22","Y32","Y13","Y23","Y33","Y14",
#' "Y24","Y34","Y15","Y25","Y35")
#' res_e = mrgvar_estimate(res=res_d)
#'
#' ### four numbers for the maxima lag length in country I:
#' ### regime 1: domestic foreign regime 2: domestic and foreign
#' L_v  = c(3,3,3,3)
#' ### a vector containing possible threshold values
#' TH_v = c(-0.1, -0.05, 0,0.05, 0.1  )
#' CC = mrgvar_select_(res=res_d,I=1,L_V=L_v,TH_V=TH_v)
#'  CCC = CC[[1]]
#'
#' CCC[which.min(CCC[,9]),]
#' CCC[which.min(CCC[,18]),]
#'
#' CC = mrgvar_select_(res=res_d,I=2,L_V=L_v,TH_V=TH_v)
#' CCC = CC[[1]]
#'
#' CCC[which.min(CCC[,9]),]
#' CCC[which.min(CCC[,18]),]
#'
#' @export
#'
mrgvar_select_ <- function(res,I,L_V,TH_V) {
  ##    res   object of mrgvar_data
  ##    I     index of the equation under investigation, I =1 we investigate the first equation, I = 10 we investigate the 10th equation.
  ##    L_V   maximum of the lags of regimes (4 4 4 4) Regime 1 domestic lags 4   foreign lags 4   regime 2 lags 4  4
  ##    TH_V  vector of threshold values that will be estimated for each chosen lag combinations
  m= res$m
  n= res$n
  p= res$p
  Y= as.matrix(res$Y)
  X     = res$X
  W = res$W
  type  = res$type
  TH    = res$TH
  SESVI = res$SESVI
  Go= res$Go
  S     = res$S
  Ao= res$Ao
  Bo    = res$Bo
  Co    = res$Co
  GDC   = res$GDC
  Sigmao= res$Sigmao*0
  d     = res$d
  P     = max(p,d)
  Pmax  = max(p[,1:2,])
  SigmaS = (1:(n*m*S*n*m*S))*0
  dim(SigmaS) = c(n*m*S,n*m*S)
  VAR_domestic = list()

  foreignLagSame = 1


  k1 = p[I,3,1]
  k2 = p[I,3,2]
  kmax  = max(p[,3,])

  T= dim(Y)[1]
  FY= Y%*%t(W%x%diag(m))
  resid = (1:(T*m*n*S))*0; dim(resid) = c(T,m,n,S)
  ##PS  = (1:(T*n*S))*0;   dim(PS)    = c(T,n,S)
  ###   CC is the single country coefficients of determinsitic components i.e. the foreign variables and the deterministic variables
  ###   It is m x (m*p+k+1) where m*p is the number of foreign variables and k is the number of deterministic variables. with zeros for "none"

  P     = max(L_V,d)
  P_candidate = array(0,c(L_V[1],L_V[2],L_V[3],L_V[4]))
  Criteria   = matrix(0,prod(L_V),4+length(TH_V))
  Criteria_b = matrix(0,prod(L_V),4+length(TH_V))
  Criteria_c = matrix(0,prod(L_V),4+length(TH_V))
  Criteria_d = matrix(0,prod(L_V),4+length(TH_V))

  if (type=="none" |type=="const")  k = 1;
  if (type=="exog0"|type=="exog1")  k = dim(X)[2]+1;
  CC  =  c(1:(m*(Pmax*m+k)*S))*0
  dim(CC) = c(m,m*Pmax+k,S)

  #res_MSVAR = MSVARData(n=m,p=p,T=T,S=S,Co=CC,TM=TM,type="exog",X=Z)
  #res_MSVAR = MSVARData(n=m,p=p,T=T,S=S)

  EMCVG       = c(1:n)*0

  Pppp = matrix(0,3,2)

  for (h in 1:length(TH_V)) {
    idx = 0
    for (l_1 in 1:L_V[1])             {
      for (l_2 in 1:L_V[2])       {
        for (l_3 in 1:L_V[3])  {
          for (l_4 in 1:L_V[4]){
            if ( foreignLagSame == 1) l_4=l_2
            Pppp[,1] = c(l_1,l_2,k1);
            Pppp[,2] = c(l_3,l_4,k2);

            idx = idx+1;
            for (i in I:I) {
              p[i,,]      = Pppp
              Pi          = max(p[i,1:2,])
              CCi  = c(1:(m*(Pi*m+k)*S))*0
              dim(CCi) = c(m,m*Pi+k,S)
              Z         = matrix(0,T,Pi*m)
              FYp    = stats::embed(FY[,(m*(i-1)+1):(i*m)],(Pi+1))
              Z[(Pi+1):T,]= FYp[,(m+1):(Pi*m+m)]
              kz          = dim(Z)[2]
              if (type=="none")   {Z = rep(Z,S); dim(Z) = c(T,kz,S); ZZ = array(0,c(T,kz,S)); for (s in 1:S) ZZ[,1:kz,s]=Z[,,s]}
              if (type=="const")  {Z = rep(Z,S); dim(Z) = c(T,kz,S); ZZ = array(0,c(T,kz,S)); for (s in 1:S) ZZ[,1:kz,s]=Z[,,s]}
              if (type=="exog0")  {Z = rep(Z,S); dim(Z) = c(T,kz,S); ZZ = array(0,c(T,kz+kmax,S)); for (s in 1:S) ZZ[,1:(kz+p[i,3,s]),s] = cbind(Z[,,s],X[,1:p[i,3,s],i,s])}
              if (type=="exog1")  {Z = rep(Z,S); dim(Z) = c(T,kz,S); ZZ = array(0,c(T,kz+kmax,S)); for (s in 1:S) ZZ[,1:(kz+p[i,3,s]),s] = cbind(Z[,,s],X[,1:p[i,3,s],i,s])}
              if (type=="none"|type=="exog0")  type_holder = "exog0"
              if (type=="const"|type=="exog1") type_holder = "exog1"
              XX = (1:(T*dim(ZZ)[2]*S))*0; dim(XX) = c(T,dim(ZZ)[2],S)
              if (!anyNA(X)) for (s in 1:S) XX[,1:(m*p[i,2,s]+p[i,3,s]),s] = ZZ[,c(1:(m*p[i,2,s]),(m*Pi+1):(m*Pi+p[i,3,s])),s]
              if (anyNA(X))  for (s in 1:S) XX[,1:(m*p[i,2,s]),s] = ZZ[,c(1:(m*p[i,2,s])),s]

              ### put data into a mrvar_data object in order to replace the data and order parameters
              pp = t(p[i,,]); pp[,2] = pp[,2]*m; ppp = pp[,1:2]; ppp[,2] = pp[,2]+pp[,3]
              if (SESVI[i]/m > SESVI[i]%/%m)   SESVIi = SESVI[i]- (SESVI[i]%/%m)*m  else SESVIi = m

              if (max(ppp[,1])>=max(ppp[,2])%/%m) {
                res_MRVAR =  mrvar_data(n=m,p=ppp,T=T,S=S,Co=NA,SESVI=SESVIi,type=type_holder,X=XX)
                res_MRVAR$Y       =  Y[,(m*(i-1)+1):(i*m)]
                res_MRVAR$X       =  XX
                res_MRVAR$SV      =  res_MRVAR$Y[,SESVIi]
                res_MRVAR$TH      =  TH_V[h]

              }  else  {

                startT = max(ppp[,2])%/%m - max(ppp[,1])+1
                res_MRVAR =  mrvar_data(n=m,p=ppp,T=(T-startT+1),S=S,Co=NA,SESVI=SESVIi,type=type_holder,X=XX[startT:T,,])
                res_MRVAR$Y       =  Y[startT:T,(m*(i-1)+1):(i*m)]
                res_MRVAR$X       =  XX[startT:T,,]
                res_MRVAR$SV      =  res_MRVAR$Y[,SESVIi]
                res_MRVAR$TH      =  TH_V[h]
              }
              RR=  mrvar_estimate(res=res_MRVAR)
              if (length(RR)>1) {
                Criteria[idx,c(c(1:4),4+h)]     = c(l_1,l_2,l_3,l_4,RR$Summary$LH_AIC)
                Criteria_b[idx,c(c(1:4),4+h)]   = c(l_1,l_2,l_3,l_4,RR$Summary$LH_BIC)
                Criteria_c[idx,c(c(1:4),4+h)]   = c(l_1,l_2,l_3,l_4,RR$Summary$LH_P)
                Criteria_d[idx,c(c(1:4),4+h)]   = c(l_1,l_2,l_3,l_4,RR$Summary$LH_N)
              }


              Criterion = cbind(Criteria,Criteria_b,Criteria_c,Criteria_d)

            }
          }
        }
      }
    }
  }
  return(list(Criterion,RR))
}



#'
#' @param res An estimated GVAR object
#' @param StateT A vector of selected regimes of each country
#'
#' @return A positive definite covariance matrix of the selected states each country
#' @export
#' @keywords internal
#'
sigma_npd_select_r = function(res,StateT) {
      n = length(StateT);
      dim(StateT) = c(1,n);
      Ranking = 1:n;
      SigmaS = res$SigmaS
      N = dim(SigmaS)[1]/(2*n)
      sigmaT = diag(n*N)
        for (i in 1:n)        {
        for (j in 1:n)  {
            sigmaT[((i-1)*N+1):(i*N),((j-1)*N+1):(j*N)] = SigmaS[((StateT[1,i]-1)*n*N+(i-1)*N+1):((StateT[1,i]-1)*n*N+i*N),((StateT[1,j]-1)*n*N+(j-1)*N+1):((StateT[1,j]-1)*n*N+j*N)]
      }
      }
      #if (anyNA(sigmaT)) { sigmanpd = SigmaRKSelect(Model,StateT,Ranking)[[1]] }
      #else {
      #    sigmanpd = as.matrix(Matrix::nearPD(sigmaT,conv.tol = 1e-10)[[1]])
      #}
      sigmanpd = as.matrix(Matrix::nearPD(sigmaT,conv.tol = 1e-10)[[1]])
      return(sigmanpd)
}



#'
#' @param  res  : an MRVAR object generated from mrvar_data or estimated from MRVARest.
#' @param  L_V  : a 2 components vector containing the maxima lags in the two regimes, respectively.
#' @param  TH_V  : a vector containing the possible threshold values over which the model selection criteria values will be calculated.
#' @return a matrix with different lag specifications and threshold values as well as the corresponding information criterion values.
#' @examples
#'
#' res_d = mrvar_data(n=4,p=matrix(c(2,1,2,2,0,0,0,0),4,2),T=800,S=2,SESVI=1)
#' max(res_d$Y)
#' colnames(res_d$Y) = c("P","Y","R","U")
#' res_e = mrvar_estimate(res=res_d)
#' TH_v = c(0,0.0)
#' L_v = c(5,5)
#' Sel = mrvar_select_(res=res_e,L_V=L_v,TH_V=TH_v)
#' mrvar_select__summary(Sel)
#' @export
mrvar_select_ <- function (res, L_V = L_V, TH_V = TH_V)
{
  res_dd = res
  p = res_dd$p
  n = res_dd$n
  T = dim(res_dd$Y)[1]
  SESVI = res_dd$SESVI
  type = res_dd$type
  X = res_dd$X
  p[, 1] = max(L_V)
  S = res_dd$S
  res_dd = mrvar_data(n = n, p = p, T = T, S = S, SESVI = SESVI,
                     type = type, X = X)
  res_dd$Y = res$Y
  Criteria = matrix(0, L_V[1] * L_V[2] * length(TH_V), 13)
  idx = 0
  for (l_d in 1:L_V[1]) {
    for (l_f in 1:L_V[2]) {
      for (l_th in 1:length(TH_V)) {
        idx = idx + 1
        res_dd$p[1, 1] = l_d
        res_dd$p[2, 1] = l_f
        res_dd$TH = TH_V[l_th]
        res_ss = mrvar_estimate(res_dd)
        TT = res_ss$Summary$LH_N + res_ss$Summary$LH_P
        Criteria[idx, ] = c(l_d, l_f, TH_V[l_th], res_ss$Summary$LH_AIC,
                            res_ss$Summary$LH_BIC, res_ss$Summary$LH_P, res_ss$Summary$LH_N, res_ss$Summary$LH_NN,
                            res_ss$Summary$ORAIC, res_ss$Summary$ORBIC, TT, res_ss$Summary$LLH_AIC,
                            res_ss$Summary$LLH_BIC)
        colnames(Criteria) = c("Lag_regime1", "Lag_regime2",
                               "threshold", "AIC", "BIC",
                               "LH_P", "LH_N", "LH_NN",
                               "ORAIC", "ORBIC", "TT", "LLH_AIC",
                               "LLH_BIC")
      }
    }
  }
  return(Criteria)
}



#'
#' @param Sel An output of mrvar_select_
#'
#' @return The optimal model according to BIC or AIC
#' @export
#'
mrvar_select__summary = function(Sel) {
  result = list()
  result[[1]] = Sel[which.min(Sel[,5]),c(1,2,3,5)]
  result[[2]] = Sel[which.min(Sel[,4]),c(1,2,3,4)]
  return(result)
}
