# utils.R
# (re)generated by tools/split_functions.R



#' Common trends for CIGVAR models
#'
#' This function creates independent common stochastic trends and idiosyncratic trends.
#'
#' @param m number of variables
#' @param p lags
#' @param T number of observations
#' @param r_npo roots of the characteristic polynomial
#' @param Ncommtrend number of common trends
#' @param n number of countries
#'
#' @return A list containing the parameter matrix of the domestic variables, the cointegration vectors and the adjustment vectors
#' @export
#' @keywords internal
#'
VARB_commtrend <- function (m, p, T, r_npo, Ncommtrend, n)
{
  alpha = list()
  beta = list()
  if (missing(Ncommtrend)) {
    Ncommtrend = NA
  }
  if (Ncommtrend==0) Ncommtrend <- NA
  Pmax = max(p[, 1:2])
  Pmin = min(p[, 1:2][p[, 1:2] > 0])
  Bo = (1:(m * m * Pmax * n)) * 0
  dim(Bo) = c(m, m, Pmax, n)
  if (anyNA(Ncommtrend)) {
    for (i in 1:n) {
      r_np = c(1:(m * p[i, 1])) * 0
      dim(r_np) = c(m, p[i, 1])
      r_np = r_npo[, 1:p[i, 1], i]
      VARD = VARData(m, p[i, 1], T, r_np = r_np)
      Bo[, , 1:p[i, 1], i] = VARD$B
      alpha[[i]] = B2CIB(VARD$B)[[2]]
      beta[[i]] = B2CIB(VARD$B)[[3]]
    }
  }
  if (!anyNA(Ncommtrend)) {
    B = matrix(stats::rnorm(m * m), m, m)
    Nnocommtrend = m - Ncommtrend
    B[(Nnocommtrend + 1):m, ] = 0
    B = B + diag(m)
    r_np = c(1:(Ncommtrend * Pmin))/c(1:(Ncommtrend * Pmin)) *
      1.5
    dim(r_np) = c(Ncommtrend, Pmin)
    r_np[1:Ncommtrend, 1] = 1
    VAR_IONE = VARData(n = Ncommtrend, p = Pmin, T = 100,
                       r_np = r_np)
    for (i in 1:n) {
      B = matrix(stats::rnorm(m * m), m, m)
      B[(Nnocommtrend + 1):m, ] = 0
      B = B + diag(m)
      Nnocommtrend = m - Ncommtrend
      r_np = c(1:(Nnocommtrend * p[i, 1])) * 0
      dim(r_np) = c(Nnocommtrend, p[i, 1])
      r_np <- r_npo[(Ncommtrend + 1):m, 1:p[i, 1], i]
      dim(r_np) = c(Nnocommtrend, p[i, 1])
      VAR_IZero = VARData(Nnocommtrend, p[i, 1], T = 100,
                          r_np = r_np)
      for (j in 1:p[i, 1]) {
        Dblock = matrix(0, m, m)
        Dblock[1:Nnocommtrend, 1:Nnocommtrend] = VAR_IZero$B[,
                                                             , j]
        if (dim(VAR_IONE$B)[3] >= j)
          Dblock[(Nnocommtrend + 1):m, (Nnocommtrend +
                                          1):m] = VAR_IONE$B[, , j]
        Bo[, , j, i] = B %*% Dblock %*% solve(B)
      }
      alpha[[i]] = B2CIB(Bo[, , 1:p[i, 1], i])[[2]]
      beta[[i]] = B2CIB(Bo[, , 1:p[i, 1], i])[[3]]
    }
  }
  return(list(Bo, alpha, beta))
}


#' Estimation of a multi regime conditional vector error correction process.
#'
#' This function estimates the unknown parameters of a multi regime conditional VECM based on provided data.
#'
#' @param y	: data matrix of the endogenous variable
#' @param x	: x data matrix of the conditioning variables. If x is missing, it will estimate a unconditional VECM.
#' @param s     : the series of state variable of value (0,1) for the two regime case. Missing s implies single regime VECM.
#' @param model : It assumes one of the values in c("I","II","III","IV","V") corresponding to the five cases in Johansen test.
#' @param type  : c("eigen", "trace") corresponding to the trace test or the max eigenvalue test
#' @param crk   : cointegration rank
#' @param P     : 2 x 2 matrix containing the lag of the cointegrated VAR process. The first row is the lag of the first regime and the number of exogenous variables. If the second row is zero, this is a one regime VECM.
#' @param q     : The significance level
#' @param Dxflag : A flag indicating if the conditioning variables enter the cointegration space
#' @param X     : The conditioning variables
#' @param CZ    : Common factor variables in CIGVAR and MRCIGVAR
#' @return A list containing: the result of the Johansen test, VECM in regression format, lambda, beta, PI, GAMMA, model, P, s.
#'
#' @export
#' @keywords internal
#'
MRCVECMest2 <- function (y, x, s, model = c("I", "II", "III","IV", "V"), type = c("eigen", "trace"), crk = 2, P = matrix(2, 2, 2), q = 0.95, Dxflag = 0, X = NA,CZ=NA)
{
  y <- as.matrix(y)
  if (q != 0.9 && q != 0.95 && q != 0.99) {
    return("please correct significance level")
  }
  S = 2
  p <- as.integer(max(P))
  pmin <- as.integer(min(P))
  N1 <- ncol(as.matrix(y))
  NN1 <- ncol(as.matrix(x))
  N <- ncol(as.matrix(y))
  n = N
  if (N1 < crk) {
    return("y's dimension must be larger than crk")
  }
  if (missing(s)) {
    s = NA
  }
  if (missing(Dxflag)) {
    Dxflag = 0
  }
  if (!anyNA(s)) {
    St = s[(p + 1):length(s)]
    NSt = 1 - s[(p + 1):length(s)]
  }
  if (!anyNA(CZ)) {
    y = cbind(CZ,y);
    kz = ncol(CZ);
  } else {
    kz = 0
  }
  if (!sum(abs(x)) == 0) {
    z <- cbind(y, x)
    Zy <- Embed(diff(y), p, prefix = "d")
    Zx <- Embed(diff(x), p, prefix = "d")
    if (P[1, 1] < p) {
      Aa = P[1, 1] * N1 + (1:((p - P[1, 1]) * N1))
      ZyI <- Zy[, -Aa]
    }
    else ZyI = Zy
    if (P[1, 2] < p) {
      Ba = P[1, 2] * NN1 + (1:((p - P[1, 2]) * NN1))
      ZxI = Zx[, -Ba]
    }
    else ZxI = Zx
    if (P[2, 1] < p) {
      Aa = P[2, 1] * N1 + (1:((p - P[2, 1]) * N1))
      ZyII = Zy[, -Aa]
    }
    else ZyII = Zy
    if (P[2, 2] < p) {
      Bb = P[2, 2] * NN1 + (1:((p - P[2, 2]) * NN1))
      ZxII = Zx[, -Bb]
    }
    else ZxII = Zx
    Z = cbind(ZyI, ZxI)
    Z_2 = cbind(ZyII, ZxII)

    #Z2   <-   Z[, -c(1:N1, P[1, 1] * N1 + 1:NN1)]
    #ZS_2 <- Z_2[, -c(1:N1, P[2, 1] * N1 + 1:NN1)]
    Z2 <-      Z[, -c(1:(kz+N1), P[1, 1] * (kz+N1) + 1:NN1)]
    ZS_2 <-  Z_2[, -c(1:(kz+N1), P[2, 1] * (kz+N1) + 1:NN1)]

  }
  else {
    z = y
    Z = Embed(diff(y), p, prefix = "d")
    if (p > 1) {
      if (Dxflag == 0) {
        Z2 <- Z[, -c(1:N1)]
        ZS_2 <- Z2
        Z2 <- Z2[, 1:((P[1, 1] - 1) * n)]
        ZS_2 <- ZS_2[, 1:((P[2, 1] - 1) * n)]
      }
      else {
        Z2 <- Z[, -c(1:N1)]
        Zs_2 <- Z2
        Z2 <- Z2[, 1:((P[1, 1] - 1) * n)]
        ZS_2 <- ZS_2[, 1:((P[2, 1] - 1) * n)]
      }
    }
    if (p == 1) {
      Z2 <- Z[, -c(1:N1)]
      ZS_2 <- Z2
    }
  }
  M1 <- ncol(as.matrix(z))
  T <- nrow(as.matrix(z))
  MM1 = ncol(Z)
  Y0 <- Z[, kz+c(1:N1)]
  if (Dxflag==1)   Z1 <- z[-T, ][p:(T - 1), ]
  if (Dxflag==0)   Z1 <- z[-T,1:(kz+N1)][p:(T - 1), ]
  #Z1 <- z[-T, ][p:(T - 1), ]
  M1 <- ncol(as.matrix(Z1))
  if (!anyNA(s))
    Z2 = cbind(St * Z2, NSt * ZS_2)
  T1 <- nrow(as.matrix(Y0))
  TT <- nrow(as.matrix(y))
  lT = matrix(1, T1, 1)
  colnames(lT) <- "Const"
  Trend <- matrix((p + 1):TT, (TT - p), 1)
  colnames(Trend) <- "Trend"
  if (model == "I") {
    Y0 = Y0
    Z1 = Z1
    Z2 = Z2
    if (!anyNA(X) && !anyNA(s))
      Z2 = cbind(Z2, St * X[(nrow(X) - nrow(Z2) + 1):nrow(X),
                            , 1], NSt * X[(nrow(X) - nrow(Z2) + 1):nrow(X),
                                          , 2])
    if (!anyNA(X) && anyNA(s)) {
      Xi = as.matrix(X[(nrow(X) - nrow(Z2) + 1):nrow(X),
      ])
      colnames(Xi) <- colnames(X)
      Z2 = cbind(Z2, Xi)
    }
  }
  if (model == "II") {
    Y0 = Y0
    Z1 = cbind(Z1, lT)
    Z2 = Z2
  }
  if (model == "III") {
    Y0 = Y0
    Z1 = Z1
    if (!anyNA(X) && !anyNA(s))
      Z2 = cbind(Z2, St, St * X[(nrow(X) - nrow(Z2) + 1):nrow(X),
                                , 1], NSt, NSt * X[(nrow(X) - nrow(Z2) + 1):nrow(X),
                                                   , 2])
    if (anyNA(X) && !anyNA(s))
      Z2 = cbind(Z2, St, NSt)
    if (!anyNA(X) && anyNA(s)) {
      Xi = as.matrix(X[(nrow(X) - nrow(Z2) + 1):nrow(X),
      ])
      colnames(Xi) <- colnames(X)
      Z2 = cbind(Z2, lT, Xi)
    }
    if (anyNA(X) && anyNA(s))
      Z2 = cbind(Z2, lT)
  }
  if (model == "IV") {
    Y0 = Y0
    Z1 = cbind(Z1, Trend)
    Z2 = cbind(Z2, lT)
  }
  if (model == "V") {
    Y0 = Y0
    Z1 = cbind(Z1)
    Z2 = cbind(Z2, lT, Trend)
  }
  if (ncol(Z2)>0) {
    Z2 <- ShiftZ2(Z2,kz,N1,P[1,1]-1)
    M00 <- crossprod(Y0)/T1
    M11 <- crossprod(Z1)/T1
    M22 <- crossprod(Z2)/T1
    M01 <- crossprod(Y0, Z1)/T1
    M02 <- crossprod(Y0, Z2)/T1
    M10 <- crossprod(Z1, Y0)/T1
    M20 <- crossprod(Z2, Y0)/T1
    M12 <- crossprod(Z1, Z2)/T1
    M21 <- crossprod(Z2, Z1)/T1
    M22inv <- solve(M22)
    R0 <- Y0 - t(M02 %*% M22inv %*% t(Z2))
    R1 <- Z1 - t(M12 %*% M22inv %*% t(Z2))
  }
  if (ncol(Z2)==0) {
    R0 = Y0
    R1 = Z1
  }
  S00 <- crossprod(R0)/T1
  S01 <- crossprod(R0, R1)/T1
  S10 <- crossprod(R1, R0)/T1
  S11 <- crossprod(R1)/T1
  Ctemp <- chol(S11, pivot = TRUE)
  pivot <- attr(Ctemp, "pivot")
  oo <- order(pivot)
  C <- t(Ctemp[, oo])
  Cinv <- solve(C)
  S00inv <- solve(S00)
  valeigen <- eigen(Cinv %*% S10 %*% S00inv %*% S01 %*% t(Cinv))
  lambda <- Re(valeigen$values)
  e <- Re(valeigen$vector)
  V <- t(Cinv) %*% e
  Vorg <- V
  V <- sapply(1:M1, function(j) V[, j]/V[1, j])
  PI <- S01 %*% solve(S11)
  if (ncol(Z2)>0)    GAMMA <- M02 %*% M22inv - PI %*% M12 %*% M22inv
  if (ncol(Z2)==0)   GAMMA <- S00 - PI %*% S10

  beta <- (V[, 1:crk])
  if (crk > 0) {
    CI = Z1 %*% beta
    if (ncol(Z2)>0) {
      VECM <- stats::lm(Y0 ~ 0 + CI + Z2)
      VECMS <- summaryCIVAR(lm1 = VECM, sname = "Z2")
    }
    if (ncol(Z2)==0) {
      VECM <- stats::lm(Y0 ~ 0 + CI )
      VECMS <- summaryCIVAR(lm1 = VECM, sname = "")
    }

  }
  if (crk == 0) {
    CI = 0
    if (ncol(Z2)>0) {
      VECM <- stats::lm(Y0 ~ 0 + Z2)
    }
    if (ncol(Z2)==0) {
      VECM <- stats::lm(Y0 ~ 0)
    }
  }
  E = -T1 * log(1 - lambda)
  E = E[1:N]
  resultsvecm <- summary(VECM)
  Omega = t(VECM$residuals) %*% VECM$residuals/nrow(VECM$residuals)
  if (model == "I") {
    Tab <- Tab1
  }
  if (model == "II") {
    Tab <- Tab2
  }
  if (model == "III") {
    Tab <- Tab3
  }
  if (model == "IV") {
    Tab <- Tab4
  }
  if (model == "V") {
    Tab <- Tab5
  }
  b = c(1:12)
  for (i in 1:12) {
    b[i] = Tab[2 * (i - 1) + 1, 2 + M1 - N1]
  }
  a = c(1:12)
  for (i in 1:12) {
    a[i] = Tab[2 * i, 2 + M1 - N1]
  }
  if (type == "eigen") {
    critical_vals = b
    M = matrix(0, N, 1)
    j = 1
    rank = 0
    while (j <= N && E[j] > critical_vals[N + 1 - j]) {
      M[j, ] = M[j, ] + 1
      j = j + 1
      rank = rank + 1
    }
    erg <- cbind(E, critical_vals[N:1])
    colnames(erg) <- c("teststatistic", "critical_value")
    if (N > 1) {
      rownames(erg) <- c("crk <= 0 |", paste("crk <= ",
                                             1:(N - 1), " |", sep = ""))
    }
    if (N == 1) {
      rownames(erg) <- c("crk <= 0 |")
    }
    coint_rank <- paste("Johansen-Test (with maximum-eigenvalue-teststatistic) indicates",
                        rank, "cointegrating equation(s) at the", 1 -
                          q, "level")
    result <- new.env()
    result$erg = erg
    result$estimation = VECM
    result$VECMS = VECMS
    result$lambda = E
    result$z = z
    result$Z2 = Z2
    result$Z1 = Z1
    result$Y0 = Y0
    result$R1 = R1
    result$R0 = R0
    result$Omega = Omega
    result$beta = beta
    result$PI = PI
    result$GAMMA = GAMMA
    result$model = model
    result$P = P
    result$NN1 = NN1
    result$s = s
    rr <- as.list(result)
    return(rr)
  }
  else {
    type = "trace"
    critical_vals = a
    stat = matrix(0, N, 1)
    for (i in 1:N) {
      sum = 0
      for (j in i:N) {
        sum = sum + E[j]
      }
      stat[i] = sum
    }
    M = matrix(0, N, 1)
    j = 1
    rank = 0
    while (stat[j] > critical_vals[N + 1 - j] && j <= N) {
      M[j, ] = M[j, ] + 1
      j = j + 1
      rank = rank + 1
    }
    erg <- cbind(stat, critical_vals[N:1])
    colnames(erg) <- c("teststatistic", "critical_value")
    if (N > 1) {
      rownames(erg) <- c("crk <= 0 |", paste("crk <= ",
                                             1:(N - 1), " |", sep = ""))
    }
    if (N == 1) {
      rownames(erg) <- c("crk <= 0 |")
    }
    coint_rank <- paste("Johansen-Test (with trace-teststatistic) indicates",
                        rank, "cointegrating equation(s) at the", 1 -
                          q, "level")
    result <- new.env()
    result$erg = erg
    result$estimation = VECM
    result$VECMS = VECMS
    result$lambda = E
    result$z = z
    result$Z2 = Z2
    result$Z1 = Z1
    result$Y0 = Y0
    result$R1 = R1
    result$R0 = R0
    result$Omega = Omega
    result$beta = beta
    result$PI = PI
    result$GAMMA = GAMMA
    result$model = model
    result$P = P
    result$NN1 = NN1
    result$s = s
    rr <- as.list(result)
    return(rr)
  }
}


#' Estimation of a two regime conditional vector error correction model.
#'
#' This function estimates the unknown parameters of a two regime conditional VECM based on provided data. The cointegrating vectors are identical in the two regimes but the adjustment speeds are different in the two regimes.
#'
#' @param y	: data matrix of the endogenous variables
#' @param x	: data matrix of the conditioning variables. If x is missing, it will estimate an unconditional VECM.
#' @param s     : the series of state variable with values (0,1) for the two regimes. Missing s implies single regime VECM.
#' @param model : It assumes one of the values in c("I","II","III","IV","V") corresponding to the five cases in the Johansen test.
#' @param type  : c("eigen", "trace") corresponding to the trace test or the max eigenvalue test
#' @param crk   : cointegration rank
#' @param P     : a (2 x 2) matrix containing the lag of the cointegrated VAR process. The first row is the lag of the first regime and the number of exogenous variables. If the second row is zero, this is a one regime VECM.
#' @param q     : The significance level used
#' @param Dxflag : a flag indicating if the conditioning variables enter the cointegration space
#' @param X     : the exogenous stationary variables
#' @param CZ    : the exogenous non-stationary common factors
#' @return a list containing: the result of JH test, VECM in regression format, lambda, beta, PI, GAMMA, model, P, s
#' @export
#' @keywords internal
#'
MRCVECMestm <- function (y, x, s, model = c("I", "II", "III", "IV", "V"), type = c("eigen", "trace"), crk = 2, P = matrix(2, 2, 2), q = 0.95, Dxflag = 0, X = X, CZ=NA)
{
  y <- as.matrix(y)
  if (q != 0.9 && q != 0.95 && q != 0.99) {
    return("please correct significance level")

  }
  S = 2
  p <- as.integer(max(P))
  pmin <- as.integer(min(P))
  N1 <- ncol(as.matrix(y))
  NN1 <- ncol(as.matrix(x))
  N <- ncol(as.matrix(y))
  n = N
  if (N1 < crk) {
    return("y's dimension must be larger than crk")

  }
  if (missing(s)) {
    s = NA
  }
  if (missing(Dxflag)) {
    Dxflag = 0
  }
  if (!anyNA(s)) {
    St = s[(p + 1):length(s)]
    NSt = 1 - s[(p + 1):length(s)]
  }
  if (!anyNA(CZ)) {
    y = cbind(CZ,y);
    kz = ncol(CZ);
  } else {
    kz = 0
  }
  if (!sum(abs(x)) == 0) {
    z <- cbind(y, x)
    Zy <- Embed(diff(y), p, prefix = "d")
    Zx <- Embed(diff(x), p, prefix = "d")
    if (P[1, 1] < p) {
      Aa = P[1, 1] * N1 + (1:((p - P[1, 1]) * N1))
      Zy1 = Zy[, -Aa]
    }
    else Zy1 = Zy
    if (P[1, 2] < p) {
      Bb = P[1, 2] * NN1 + (1:((p - P[1, 2]) * NN1))
      Zx1 = Zx[, -Bb]
    }
    else Zx1 = Zx
    if (P[2, 1] < p) {
      Aa = P[2, 1] * N1 + (1:((p - P[2, 1]) * N1))
      Zy2 = Zy[, -Aa]
    }
    else Zy2 = Zy
    if (P[2, 2] < p) {
      Bb = P[2, 2] * NN1 + (1:((p - P[2, 2]) * NN1))
      Zx2 = Zx[, -Bb]
    }
    else Zx2 = Zx
    Z = cbind(Zy1, Zx1)
    Z_2 = cbind(Zy2, Zx2)

    Z2 <-     Z[, -c(1:(kz+N1), P[1, 1] * (kz+N1) + 1:NN1)]
    ZS_2 <- Z_2[, -c(1:(kz+N1), P[2, 1] * (kz+N1) + 1:NN1)]


  }
  else {
    z = y
    Z = Embed(diff(y), p, prefix = "d")
    if (Dxflag == 0) {
      Z2 <- Z[, -c(1:N1)]
      ZS_2 <- Z2
      Z2 <- Z2[, 1:((P[1, 1] - 1) * n)]
      ZS_2 <- ZS_2[, 1:((P[2, 1] - 1) * n)]
    }
    else {
      Z2 <- Z[, -c(1:N1)]
      Zs_2 <- Z2
      Z2 <- Z2[, 1:((P[1, 1] - 1) * n)]
      ZS_2 <- ZS_2[, 1:((P[2, 1] - 1) * n)]
    }
  }

  T <- nrow(as.matrix(z))
  MM1 = ncol(Z)
  Y0 <- Z[, kz+c(1:N1)]
  if (Dxflag==1)   Z1 <- z[-T, ][p:(T - 1), ]
  if (Dxflag==0)   Z1 <- z[-T,1:(kz+N1)][p:(T - 1), ]
  #Z1 <- z[-T, ][p:(T - 1), ]
  #M1 <- ncol(as.matrix(z))
  M1 <- ncol(as.matrix(Z1))
  if (!anyNA(s))
    Z2 = cbind(St * Z2, NSt * ZS_2)
  T1 <- nrow(as.matrix(Y0))
  lT = (1:T1)/(1:T1)
  Trend <- matrix(1:T1, T1, 1)
  if (model == "I") {
    Y0 = Y0
    Z1 = Z1
    Z2 = Z2
    if (!anyNA(X) & !anyNA(s)) {
      StX  = as.matrix(St * X[(nrow(X) - nrow(Z2) + 1):nrow(X), , 1]); colnames(StX)  = paste0(colnames(X),"1")
      NStX = as.matrix(NSt *X[(nrow(X) - nrow(Z2) + 1):nrow(X), , 2]); colnames(NStX) = paste0(colnames(X),"2")
      Z2 = cbind(Z2,StX,NStX)
      #Z2 = cbind(Z2, St * X[(nrow(X) - nrow(Z2) + 1):nrow(X), , 1], NSt * X[(nrow(X) - nrow(Z2) + 1):nrow(X),, 2])
    }
    if (!anyNA(X) & anyNA(s))
      Z2 = cbind(Z2, X[(nrow(X) - nrow(Z2) + 1):nrow(X),
      ])
  }
  if (model == "II") {
    Y0 = Y0
    Z1 = cbind(T1, Z1)
    Z2 = Z2
  }
  if (model == "III") {
    Y0 = Y0
    Z1 = Z1
    if (!anyNA(s) & !anyNA(X)) {
      StX  = as.matrix(St * X[(nrow(X) - nrow(Z2) + 1):nrow(X), , 1]); colnames(StX)  = paste0(colnames(X),"1")
      NStX = as.matrix(NSt *X[(nrow(X) - nrow(Z2) + 1):nrow(X), , 2]); colnames(NStX) = paste0(colnames(X),"2")


      Z2 = cbind(Z2,St,StX,NSt,NStX)
      #Z2 = cbind(Z2, St, St * X[(nrow(X) - nrow(Z2) + 1):nrow(X), , 1,drop=FALSE], NSt, NSt * X[(nrow(X) - nrow(Z2) + 1):nrow(X), , 2,drop=FALSE])

    }
    if (!anyNA(s) & anyNA(X))
      Z2 = cbind(Z2, St, NSt)
    if (anyNA(s) & !anyNA(X))
      Z2 = cbind(Z2, rep(1, T1), X[(nrow(X) - nrow(Z2) +
                                      1):nrow(X), ])
    if (anyNA(s) & anyNA(X))
      Z2 = cbind(Z2, rep(1, T1))
  }
  if (model == "IV") {
    Y0 = Y0
    Z1 = cbind(Trend, Z1)
    Z2 = cbind(Z2, lT)
  }
  if (model == "V") {
    Y0 = Y0
    Z1 = cbind(Z1)
    Z2 = cbind(Z2, lT, Trend)
  }
  if (ncol(Z2)>0) {
    Z2 <-  ShiftZ2m(Z2,kz,N1,max(P[,1:2])-1,min(P[,1:2])-1)

    M00 <- crossprod(Y0)/T1
    M11 <- crossprod(Z1)/T1
    M22 <- crossprod(Z2)/T1
    M01 <- crossprod(Y0, Z1)/T1
    M02 <- crossprod(Y0, Z2)/T1
    M10 <- crossprod(Z1, Y0)/T1
    M20 <- crossprod(Z2, Y0)/T1
    M12 <- crossprod(Z1, Z2)/T1
    M21 <- crossprod(Z2, Z1)/T1
    M22inv <- solve(M22)
    R0 <- Y0 - t(M02 %*% M22inv %*% t(Z2))
    R1 <- Z1 - t(M12 %*% M22inv %*% t(Z2))
  }

  if (ncol(Z2) == 0) {
    R0 = Y0
    R1 = Z1
  }

  S00 <- crossprod(R0)/T1
  S01 <- crossprod(R0, R1)/T1
  S10 <- crossprod(R1, R0)/T1
  S11 <- crossprod(R1)/T1
  Ctemp <- chol(S11, pivot = TRUE)
  pivot <- attr(Ctemp, "pivot")
  oo <- order(pivot)
  C <- t(Ctemp[, oo])
  Cinv <- solve(C)
  S00inv <- solve(S00)
  valeigen <- eigen(Cinv %*% S10 %*% S00inv %*% S01 %*% t(Cinv))
  lambda <- Re(valeigen$values)
  e <- Re(valeigen$vector)
  V <- t(Cinv) %*% e
  Vorg <- V
  V <- sapply(1:M1, function(j) V[, j]/V[1, j])
  PI <- S01 %*% solve(S11)
  GAMMA <- M02 %*% M22inv - PI %*% M12 %*% M22inv
  beta <- as.matrix(V[, 1:crk])
  beta0 <- as.matrix(V[, 1:crk])
  if (crk > 0) {
    NLm = stats::nlm(f, as.vector(beta0), beta, Z1, St, NSt, Y0, Z2)
    if ( NLm$code>2 )  betaS <- beta0  else   betaS <- NLm$estimate

    NLmcode = NLm$code
    dim(betaS) = dim(beta)
    for (i in 1:ncol(as.matrix(betaS))) betaS[, i] = betaS[, i]/(betaS[1, i])
    CI = Z1 %*% betaS
    estimation <- stats::lm(Y0 ~ 0 + CI + Z2)
    CI1 = CI * St
    CI2 = CI * NSt
    VECM1 <- stats::lm(Y0 ~ 0 + CI1 + CI2 + Z2)
    VECM1S <- summaryCIVAR(lm1 = VECM1, sname = "Z2")
    alphaS_1 = t(VECM1$coefficients[1:crk, ])
    alphaS_2 = t(VECM1$coefficients[(1 + crk):(2 * crk),])
    if (dim(alphaS_1)[1] == 1)
      alphaS_1 <- t(alphaS_1)
    if (dim(alphaS_2)[1] == 1)
      alphaS_2 <- t(alphaS_2)
  }
  if (crk == 0) {
    CI = 0
    estimation <- stats::lm(Y0 ~ 0 + Z2)
  }
  E = -T1 * log(1 - lambda)
  E = E[1:N]
  resultsvecm <- summary(estimation)
  if (model == "I") {
    Tab <- Tab1
  }
  if (model == "II") {
    Tab <- Tab2
  }
  if (model == "III") {
    Tab <- Tab3
  }
  if (model == "IV") {
    Tab <- Tab4
  }
  if (model == "V") {
    Tab <- Tab5
  }
  b = c(1:12)
  for (i in 1:12) {
    b[i] = Tab[2 * (i - 1) + 1, 2 + M1 - N1]
  }
  a = c(1:12)
  for (i in 1:12) {
    a[i] = Tab[2 * i, 2 + M1 - N1]
  }
  if (type == "eigen") {
    critical_vals = b
    M = matrix(0, N, 1)
    j = 1
    rank = 0
    while (j <= N && E[j] > critical_vals[N + 1 - j]) {
      M[j, ] = M[j, ] + 1
      j = j + 1
      rank = rank + 1
    }
    erg <- cbind(E, critical_vals[N:1])
    colnames(erg) <- c("teststatistic", "critical_value")
    if (N > 1) {
      rownames(erg) <- c("crk <= 0 |", paste("crk <= ",
                                             1:(N - 1), " |", sep = ""))
    }
    if (N == 1) {
      rownames(erg) <- c("crk <= 0 |")
    }
    coint_rank <- paste("Johansen-Test (with maximum-eigenvalue-teststatistic) indicates",
                        rank, "cointegrating equation(s) at the", 1 -
                          q, "level")
    result <- new.env()
    result$erg = erg
    result$estimation = estimation
    result$VECM1 = VECM1
    result$VECM1S = VECM1S
    result$lambda = E
    result$z = z
    result$Z2 = Z2
    result$Z1 = Z1
    result$St = St
    result$NSt = NSt
    result$R0 = R0
    result$R1 = R1
    result$Y0 = Y0
    result$beta = beta
    result$betaS = betaS
    result$alphaS = alphaS = list(alphaS_1, alphaS_2)
    result$NLmcode = NLmcode
    result$PI = PI
    result$GAMMA = GAMMA
    result$model = model
    result$P = P
    result$NN1 = NN1
    result$s = s
    rr <- as.list(result)
    return(rr)
  }
  else {
    type = "trace"
    critical_vals = a
    stat = matrix(0, N, 1)
    for (i in 1:N) {
      sum = 0
      for (j in i:N) {
        sum = sum + E[j]
      }
      stat[i] = sum
    }
    M = matrix(0, N, 1)
    j = 1
    rank = 0
    while (stat[j] > critical_vals[N + 1 - j] && j <= N) {
      M[j, ] = M[j, ] + 1
      j = j + 1
      rank = rank + 1
    }
    erg <- cbind(stat, critical_vals[N:1])
    colnames(erg) <- c("teststatistic", "critical_value")
    if (N > 1) {
      rownames(erg) <- c("crk <= 0 |", paste("crk <= ",
                                             1:(N - 1), " |", sep = ""))
    }
    if (N == 1) {
      rownames(erg) <- c("crk <= 0 |")
    }
    coint_rank <- paste("Johansen-Test (with trace-teststatistic) indicates",
                        rank, "cointegrating equation(s) at the", 1 -
                          q, "level")
    result <- new.env()
    result$erg = erg
    result$estimation = estimation
    result$VECM1 = VECM1
    result$VECM1S = VECM1S
    result$lambda = E
    result$z = z
    result$Z2 = Z2
    result$Z1 = Z1
    result$St = St
    result$NSt = NSt
    result$R0 = R0
    result$R1 = R1
    result$Y0 = Y0
    result$beta = beta
    result$betaS = betaS
    result$alphaS = alphaS = list(alphaS_1, alphaS_2)
    result$NLmcode = NLmcode
    result$PI = PI
    result$GAMMA = GAMMA
    result$model = model
    result$P = P
    result$NN1 = NN1
    result$s = s
    rr <- as.list(result)
    return(rr)
  }
}


#' @param lm1 The coefficient matrix of the output of lm
#' @param sname The elements in column names to be replaced
#' @export
#' @keywords internal
#'
summaryCIVAR <- function(lm1=lm1,sname ="Z2\\[,4:9\\]") {
  #### this function replace the Matrix name and leave the colnames in the output
  summ =summary(lm1)
  n = length(summ)
  if (n>1) {
    for (i in 1:n) {
      LL <- dimnames(summ[[i]]$coefficients)[[1]]
      dimnames(summ[[i]]$coefficients)[[1]] <- sub(sname, "", LL)
    }
  }  else {
    LL <- dimnames(summ$coefficients)[[1]]
    dimnames(summ$coefficients)[[1]] <- sub(sname, "", LL)

  }
  return(summ)
}


#' Transformation of the estimated parameters of a VECM into the parameters of the corresponging VAR
#'
#' @param param The parameter of an estimated VECM
#' @param beta The cointegration vectors
#' @param q A vector specifying different type of VECMs
#' @param s The indicator of multi regime VECMs
#' @param kz The number of exogenous common factors
#' @param Dxflag Indicator whether the foreign variables enter the cointegration space
#'
#' @return A list of (A, B, C) with B the auto regression parameter matrix, C the parameter of the deterministic components, and A the parameter matrix of foreign variables for CIGVAR.
#' @export
#' @keywords internal
#'
#'
VECM2VAR <- function(param, beta, q = c(1, 2, 2, 2, 2),s=NA,kz=0,Dxflag=0)
{
  m = dim(param)[2]
  VECB = t(param)
  if (missing(s))  s = NA
  if (anyNA(s)) {
    if (!q[3] == 0) {   # for GVAR with foreign variables
      B = (1:(m * m * (q[2] + 1))) * 0
      dim(B) = c(m, m, (q[2] + 1))
      A = (1:(m * m * (q[3] + 1))) * 0
      D = NA
      dim(A) = c(m, m, (q[3] + 1))
      AB = VECB[, 1:q[1]] %*% t(beta)
      B[, , 1] = AB[, kz+(1:m)]
      if (Dxflag == 1 ) A[, , 1] = AB[,kz+(m + 1):(2 * m)]
      if (Dxflag == 0 ) A[, , 1] = A[, , 1]*0
      for (i in 2:(q[2] + 1)) B[, , i] = VECB[, q[1] + ((i - 2) * m + 1):((i - 2) * m + m)]
      for (i in 2:(q[3] + 1)) A[, , i] = VECB[, (q[1] + q[2] * m) + ((i - 2) * m + 1):((i - 2) * m + m)]

      B = CIB3B(B)
      A = CIA2A(A)
      if ( kz > 0 ) {
        D = (1:(m*kz*(q[2]+1)))*0; dim(D) =c(m,kz,q[2]+1)
        D[,,1] = AB[,1:kz]
        for (i in 2:(q[2] + 1)) D[, , i] = VECB[, dim(VECB)[2]-q[2]*kz + (((i - 2) * kz + 1):((i - 2) * kz + kz))]
        D = CIA2A(D)
      }
    }
    else {
      B = (1:(m * m * (q[2] + 1))) * 0
      dim(B) = c(m, m, (q[2] + 1))
      AB = VECB[, 1:q[1]] %*% t(beta)
      B[, , 1] = AB[, 1:m]
      if (q[2] > 0) {
        for (i in 2:(q[2] + 1)) B[, , i] = VECB[, q[1] +
                                                  ((i - 2) * m + 1):((i - 2) * m + m)]
        B <- CIB3B(CIB = B)
      }
      if (q[2] == 0) {
        B[, , 1] = B[, , 1] + diag(m)
      }
      A = NA
    }
    if (dim(param)[1] > q[1] + (q[2] + q[3]) * m + q[2]*kz) {
      C = as.matrix(t(param)[, (q[1] + (q[2] + q[3]) * m + 1):(dim(param)[1]-q[2]*kz) ])
    }
    else C = NA
  }
  else {
    if (length(q) == 5) {
      P = max(q[-1])
      B = (1:(m * m * (P + 1) * 2)) * 0
      dim(B) = c(m, m, (P + 1), 2)
      A = B
      AB = VECB[, 1:q[1]] %*% t(beta)
      B[, , 1, 1] = AB[, 1:m]
      A[, , 1, 1] = AB[, (m + 1):(2 * m)]
      B[, , 1, 2] = AB[, 1:m]
      A[, , 1, 2] = AB[, (m + 1):(2 * m)]
      for (i in 2:(q[2] + 1)) B[, , i, 1] = VECB[, q[1] +
                                                   ((i - 2) * m + 1):((i - 2) * m + m)]
      for (i in 2:(q[3] + 1)) A[, , i, 1] = VECB[, (q[1] +
                                                      q[2] * m) + ((i - 2) * m + 1):((i - 2) * m +
                                                                                       m)]
      for (i in 2:(q[4] + 1)) B[, , i, 2] = VECB[, (q[1] +
                                                      (q[2] + q[3]) * m) + ((i - 2) * m + 1):((i -
                                                                                                 2) * m + m)]
      for (i in 2:(q[5] + 1)) A[, , i, 2] = VECB[, (q[1] +
                                                      (q[2] + q[3] + q[4]) * m) + ((i - 2) * m + 1):((i -
                                                                                                        2) * m + m)]
      B[, , 1:(q[2] + 1), 1] = CIB3B(B[, , 1:(q[2] + 1),
                                       1])
      B[, , 1:(q[4] + 1), 2] = CIB3B(B[, , 1:(q[4] + 1),
                                       2])
      A[, , 1:(q[3] + 1), 1] = CIA2A(A[, , 1:(q[3] + 1),
                                       1])
      A[, , 1:(q[5] + 1), 2] = CIA2A(A[, , 1:(q[5] + 1),
                                       2])
      if (dim(param)[1] > q[1] + (sum(q[-1])) * m) {
        C = (1:(m * 2)) * 0
        dim(C) = c(m, 1, 2)
        C[, 1, 1] = as.matrix(t(param)[, q[1] + sum(q[-1]) *
                                         m + 1])
        C[, 1, 2] = as.matrix(t(param)[, q[1] + sum(q[-1]) *
                                         m + 2])
      }
      else {
        C = NA
      }
    }
    if (length(q) == 3) {
      P = max(q[-1])
      B = (1:(m * m * (P + 1) * 2)) * 0
      dim(B) = c(m, m, (P + 1), 2)
      AB = VECB[, 1:q[1]] %*% t(beta)
      B[, , 1, 1] = AB[, 1:m]
      B[, , 1, 2] = AB[, 1:m]
      for (i in 2:(q[2] + 1)) B[, , i, 1] = VECB[, q[1] +
                                                   ((i - 2) * m + 1):((i - 2) * m + m)]
      for (i in 2:(q[3] + 1)) B[, , i, 2] = VECB[, (q[1] +
                                                      q[2] * m) + ((i - 2) * m + 1):((i - 2) * m +
                                                                                       m)]
      B[, , 1:(q[2] + 1), 1] = CIB3B(B[, , 1:(q[2] + 1),
                                       1])
      B[, , 1:(q[3] + 1), 2] = CIB3B(B[, , 1:(q[3] + 1),
                                       2])
      A = NA
      if (dim(param)[1] > q[1] + (sum(q[-1])) * m) {
        C = (1:(m * 2)) * 0
        dim(C) = c(m, 1, 2)
        C[, 1, 1] = as.matrix(t(param)[, q[1] + sum(q[-1]) *
                                         m + 1])
        C[, 1, 2] = as.matrix(t(param)[, q[1] + sum(q[-1]) *
                                         m + 2])
      }
      else {
        C = NA
      }
    }
  }
  return(list(B, A, C, D))
}


#' Transformation of the coefficient matrix of a CIGVAR to the coefficient matrix of the corresponding VECM.
#'
#' @param  B  an (m,m,L) array containing the coefficients of the level VAR.
#' @return A list containing three components.
#' \itemize{
#'    \item CIB        : the coefficients matrix of the error correction form
#'    \item alpha	     : the adjustment coefficients
#'    \item beta       : the cointegration vectors
#'    \item sm         : the discrepancy between the selected alpha beta and CIB.
#' }
#' @export
#' @keywords internal
#'
B2CIB <- function (B)
{
  CIB = B * 0
  L = dim(B)[3]
  n = dim(B)[1]
  for (i in L:1) for (j in L:i) CIB[, , i] = CIB[, , i] - B[, , j]
  CIB[, , 1] = -diag(n) - CIB[, , 1]
  P = eigen(CIB[, , 1])$vectors
  lambda = eigen(CIB[, , 1])$values
  P=P[,sort(Mod(lambda),decreasing = FALSE,index.return=TRUE)$ix]
  lambda <- lambda[sort(Mod(lambda),decreasing = FALSE,index.return=TRUE)$ix]

  k = 0
  for (i in 1:(n - 1)) {
    sm = sum(abs(CIB[, , 1] - P[, i:n] %*% diag(lambda[i:n]) %*% solve(P)[i:n, ]))
    if (sm < 1e-06)
      k = i
  }
  sm = sum(abs(CIB[, , 1] - as.matrix(P[, n:n]) %*% lambda[n:n] %*% t(as.matrix(solve(P)[n:n, ]))))
  if (sm < 1e-06)
    k = n
  if (k < n) {
    alpha = P[, k:n] %*% diag(lambda[k:n])
    beta = t(solve(P)[k:n, ])
    sm = sum(abs(CIB[, , 1] - alpha %*% t(beta)))
  }
  if (k == n) {
    alpha = as.matrix(P[, n:n] * lambda[n:n])
    beta = as.matrix(solve(P)[n:n, ])
    sm = sum(abs(CIB[, , 1] - alpha %*% t(beta)))
  }
  return(list(CIB, alpha, beta, sm))
}


#' Transformation of the estimated parameters of a conditional VECM into the parameters of the corresponding conditional VAR
#'
#' @param param estimated parameters of a conditional VECM
#' @param beta the estimated cointegration vecters
#' @param p a vector specifying different types of conditional VECM
#' @param s indicator variable of different regimes
#' @param N2 dimension of the conditioning variables
#'
#' @return A list of (A, B, C) with B the conditional VAR parameter matrix, C the parameter of the deterministic components, and A the parameter matrix of foreign variables for CIGVAR.
#' @export
#'
CVECM2CVAR <- function (param, beta, p = c(1, 2, 2, 2, 2), s = NA, N2)
{
  m = dim(param)[2]
  VECB = t(param)
  if (anyNA(s)) {                                #### one regime
    if (!p[3] == 0) {
      B = (1:(m * m * (p[2] + 1))) * 0
      dim(B) = c(m, m, (p[2] + 1))
      A = (1:(m * N2 * (p[3] + 1))) * 0
      dim(A) = c(m, N2, (p[3] + 1))
      AB = VECB[, 1:p[1]] %*% t(beta)
      B[, , 1] = AB[, 1:m]
      A[, , 1] = AB[, (m + 1):(m+N2)]
      for (i in 2:(p[2] + 1)) B[, , i] = VECB[, p[1] +  ((i - 2) * m + 1):((i - 2) * m + m)]
      for (i in 2:(p[3] + 1)) A[, , i] = VECB[, (p[1] +  p[2] * m) + ((i - 2) * N2 + 1):((i - 2) * N2 + N2)]
      B <- CIB3B(B)
      A <- CIA2A(A)
    }
    else {
      B = (1:(m * m * (p[2] + 1))) * 0
      dim(B) = c(m, m, (p[2] + 1))
      AB = VECB[, 1:p[1]] %*% t(beta)
      B[, , 1] = AB[, 1:m]
      if (p[2] > 0)
        for (i in 2:(p[2] + 1)) B[, , i] = VECB[, p[1] +
                                                  ((i - 2) * m + 1):((i - 2) * m + m)]
      B <- CIB3B(CIB = B)
      A = NA
    }
    if (dim(param)[1] > p[1] + (p[2]*m + p[3]*N2) ) {
      C = as.matrix(t(param)[, (p[1] + (p[2]*m + p[3]*N2) + 1):dim(param)[1]])
    }      else C = NA
  }
  else {                                #### MRCIGVAR (crk, lag_domestic_1,lag_foreign_1,lag_domestic_2,lag_foreign_2)
    if (length(p) == 5) {
      P = max(p[-1])
      B = (1:(m * m * (P + 1) * 2)) * 0
      dim(B) = c(m, m, (P + 1), 2)
      A = B
      AB = VECB[, 1:p[1]] %*% t(beta)
      B[, , 1, 1] = AB[, 1:m]
      A[, , 1, 1] = AB[, (m + 1):(2 * m)]
      B[, , 1, 2] = AB[, 1:m]
      A[, , 1, 2] = AB[, (m + 1):(2 * m)]
      for (i in 2:(p[2] + 1)) B[, , i, 1] = VECB[, p[1] +
                                                   ((i - 2) * m + 1):((i - 2) * m + m)]
      for (i in 2:(p[3] + 1)) A[, , i, 1] = VECB[, (p[1] +
                                                      p[2] * m) + ((i - 2) * m + 1):((i - 2) * m +
                                                                                       m)]
      for (i in 2:(p[4] + 1)) B[, , i, 2] = VECB[, (p[1] +
                                                      (p[2] + p[3]) * m) + ((i - 2) * m + 1):((i -
                                                                                                 2) * m + m)]
      for (i in 2:(p[5] + 1)) A[, , i, 2] = VECB[, (p[1] +
                                                      (p[2] + p[3] + p[4]) * m) + ((i - 2) * m + 1):((i -
                                                                                                        2) * m + m)]
      B[, , 1:(p[2] + 1), 1] = CIB3B(B[, , 1:(p[2] + 1),
                                       1])
      B[, , 1:(p[4] + 1), 2] = CIB3B(B[, , 1:(p[4] + 1),
                                       2])
      A[, , 1:(p[3] + 1), 1] = CIA2A(A[, , 1:(p[3] + 1),
                                       1])
      A[, , 1:(p[5] + 1), 2] = CIA2A(A[, , 1:(p[5] + 1),
                                       2])
      if (dim(param)[1] > p[1] + (sum(p[-1])) * m) {
        C = (1:(m * 2)) * 0
        dim(C) = c(m, 1, 2)
        C[, 1, 1] = as.matrix(t(param)[, p[1] + sum(p[-1]) *
                                         m + 1])
        C[, 1, 2] = as.matrix(t(param)[, p[1] + sum(p[-1]) *
                                         m + 2])
      }
      else {
        C = NA
      }
    }
    if (length(p) == 3) {                       ### MRCIVAR  crk, lag of regime 1,  lag of regime two
      P = max(p[-1])
      B = (1:(m * m * (P + 1) * 2)) * 0
      dim(B) = c(m, m, (P + 1), 2)
      AB = VECB[, 1:p[1]] %*% t(beta)
      B[, , 1, 1] = AB[, 1:m]
      B[, , 1, 2] = AB[, 1:m]
      for (i in 2:(p[2] + 1)) B[, , i, 1] = VECB[, p[1] +
                                                   ((i - 2) * m + 1):((i - 2) * m + m)]
      for (i in 2:(p[3] + 1)) B[, , i, 2] = VECB[, (p[1] +
                                                      p[2] * m) + ((i - 2) * m + 1):((i - 2) * m +
                                                                                       m)]
      B[, , 1:(p[2] + 1), 1] = CIB3B(B[, , 1:(p[2] + 1),
                                       1])
      B[, , 1:(p[3] + 1), 2] = CIB3B(B[, , 1:(p[3] + 1),
                                       2])
      A = NA
      if (dim(param)[1] > p[1] + (sum(p[-1])) * m) {
        C = (1:(m * 2)) * 0
        dim(C) = c(m, 1, 2)
        C[, 1, 1] = as.matrix(t(param)[, p[1] + sum(p[-1]) *
                                         m + 1])
        C[, 1, 2] = as.matrix(t(param)[, p[1] + sum(p[-1]) *
                                         m + 2])
      }
      else {
        C = NA
      }
    }
  }
  return(list(B, A, C))
}


#' Estimation of a conditional vector error correction process.
#'
#' This function estimates the unknown parameters of a multi regime conditional VECM based on provided data.
#'
#'
#' @param y data matrix of the endogenous variables
#' @param x data matrix of the exogenous variables
#' @param model type of the specification of the deterministic components. "none" and "const" are two options.
#' @param type =c("eigen", "trace")
#' @param crk cointegration rank
#' @param p lag length in level
#' @param q significance level
#'
#' @return a list of estimated parameters and test statistics
#' @export
#' @keywords internal
#'
cvecm <- function (y,x,model = c("I","II","III","IV","V"),type = c("eigen", "trace"), crk=2, p = 1, q = 0.95)
{
  y <- as.matrix(y)
  if (q != 0.9 && q != 0.95 && q != 0.99) {
    return("please correct significance level")
  }

  p <- as.integer(p)
  N1 <- ncol(as.matrix(y))
  N  <- ncol(as.matrix(y))
  if (N1<crk) {
    return("y's dimension must be larger than crk")
  }

  if  ( length(x) == 1 ) {  z <- y }
  else {
    z <- cbind(y,x)
  }

  M1 <- ncol(as.matrix(z))
  T <- nrow(as.matrix(z))
  #Z <- embed(diff(z), p)
  Z <- Embed(diff(z), p)

  Y0 <- Z[, c(1:N1)]                # \Delta Y
  #X0 <- Z[,c((N1+1):M1)]           # \Delta X
  Z1 <- z[-T, ][p:(T - 1), ]        #      Z_1
  if ((p==1)&(length(x)==1)) {
    Z2 = NULL
    NOLAG = 1
  }
  else {
    Z2 <- Z[, c((M1+1):(M1*p))]               # \Delta Z_
    Z2 <- Z2[, Redex(N1=N1,N2=ncol(x),p)]       # \Delta Z_
  }
  T1 <- nrow(as.matrix(Y0))
  #lT = (1:T1)/(1:T1)
  #Trend <- matrix(1:T1, T1, 1)
  lT = matrix(1,T1,1); colnames(lT) <- "Const"
  Trend <- matrix(1, T1, 1); colnames(Trend) <- "Trend"

  if ( model == "I" ) {
    Y0 = Y0
    Z1 = Z1
    Z2 = Z2
  }
  if ( model == "II" ) {
    Y0 = Y0
    Z1 = cbind(lT,Z1)
    Z2 = Z2
  }
  if ( model == "III" ) {
    Y0 = Y0
    Z1 = Z1
    Z2 = cbind(Z2,lT)
  }
  if ( model == "IV" ) {
    Y0 = Y0
    Z1 = cbind(Trend,Z1)
    Z2 = cbind(Z2,lT)
  }
  if ( model == "V" ) {
    Y0 = Y0
    Z1 = cbind(Z1)
    Z2 = cbind(Z2,lT,Trend)
  }

  if (length(Z2)==0) {
    R0 <- Y0
    R1 <- Z1
  }
  else {

    M00 <- crossprod(Y0)/T1
    M11 <- crossprod(Z1)/T1
    M22 <- crossprod(Z2)/T1
    M01 <- crossprod(Y0, Z1)/T1
    M02 <- crossprod(Y0, Z2)/T1
    M10 <- crossprod(Z1, Y0)/T1
    M20 <- crossprod(Z2, Y0)/T1
    M12 <- crossprod(Z1, Z2)/T1
    M21 <- crossprod(Z2, Z1)/T1
    M22inv <- solve(M22)
    R0 <- Y0 - t(M02 %*% M22inv %*% t(Z2))
    R1 <- Z1 - t(M12 %*% M22inv %*% t(Z2))
  }
  S00 <- crossprod(R0)/T1
  S01 <- crossprod(R0, R1)/T1
  S10 <- crossprod(R1, R0)/T1
  S11 <- crossprod(R1)/T1
  Ctemp <- chol(S11, pivot = TRUE)
  pivot <- attr(Ctemp, "pivot")
  oo <- order(pivot)
  C <- t(Ctemp[, oo])
  Cinv <- solve(C)
  S00inv <- solve(S00)
  valeigen <- eigen(Cinv %*% S10 %*% S00inv %*% S01 %*% t(Cinv))

  #valeigen <- eigen(S11inv %*% S10 %*% S00inv %*% S01 )
  lambda <- Re(valeigen$values)
  e      <- Re(valeigen$vector)

  V <- t(Cinv) %*% e
  Vorg <- V
  V <- sapply(1:M1, function(j) V[, j]/V[1, j])
  #W <- S01 %*% V %*% solve(t(V) %*% S11 %*% V)
  PI <- S01 %*% solve(S11)
  #DELTA <- S00 - S01 %*% V %*% solve(t(V) %*% S11 %*% V) %*% t(V) %*% S10
  if (length(Z2)==0) {
    GAMMA = NULL
  }
  else {
    GAMMA <- M02 %*% M22inv - PI %*% M12 %*% M22inv
  }
  beta   <- V[,1:crk]

  if ((crk>0)&(length(Z2)>0)) {
    CI = Z1%*%beta
    VECM<-stats::lm(Y0~0+CI+Z2)
  }
  if ((crk>0)&(length(Z2)==0)) {
    CI = Z1%*%beta
    VECM<-stats::lm(Y0~0+CI)
  }
  if ((crk == 0)&(length(Z2)>0)) {
    CI = 0
    VECM<-stats::lm(Y0~0+Z2)
  }
  if ((crk == 0)&(length(Z2)==0)) {
    CI = 0
    VECM<-NULL
  }
  E = -T1 * log(1 - lambda)
  E = E[1:N]
  ##### Estimation of VECM

  resultsvecm <- summary(VECM)

  if (model == "I")   {    Tab <- Tab1  }
  if (model == "II")  {    Tab <- Tab2  }
  if (model == "III") {    Tab <- Tab3  }
  if (model == "IV")  {    Tab <- Tab4  }
  if (model == "V")   {    Tab <- Tab5  }


  b = c(1:12)
  for (i in 1:12)   { b[i] = Tab[2*(i-1)+1,2+M1-N1] }
  a = c(1:12)
  for (i in 1:12)   { a[i] = Tab[2*i,2+M1-N1] }

  if (type == "eigen") {
    critical_vals = b
    M = matrix(0, N, 1)
    j = 1
    rank = 0
    while (j <= N && E[j] > critical_vals[N + 1 - j]) {
      M[j, ] = M[j, ] + 1
      j = j + 1
      rank = rank + 1
    }
    erg <- cbind(E, critical_vals[N:1])
    colnames(erg) <- c("teststatistic", "critical_value")

    if ( N > 1 ) {
      rownames(erg) <- c("crk <= 0 |", paste("crk <= ", 1:(N - 1),  " |", sep = ""))
    }
    if ( N == 1 ) {
      rownames(erg) <- c("crk <= 0 |" )
    }

    coint_rank <- paste("Johansen-Test (with maximum-eigenvalue-teststatistic) indicates",
                        rank, "cointegrating equation(s) at the", 1 - q,
                        "level")
    #print(coint_rank)
    result <- new.env()
    result$erg = erg
    result$estimation = VECM
    result$lambda     = E
    result$z          = z
    result$Z2         = Z2
    result$beta       = beta
    result$PI         = PI
    result$GAMMA      = GAMMA
    result$model      = model
    rr<-as.list(result)
    return(rr)
  }
  else {
    type = "trace"
    critical_vals = a
    stat = matrix(0, N, 1)
    for (i in 1:N) {
      sum = 0
      for (j in i:N) {
        sum = sum + E[j]
      }
      stat[i] = sum
    }
    M = matrix(0, N, 1)
    j = 1
    rank = 0
    while (stat[j] > critical_vals[N + 1 - j] && j <= N) {
      M[j, ] = M[j, ] + 1
      j = j + 1
      rank = rank + 1
    }
    erg <- cbind(stat, critical_vals[N:1])
    colnames(erg) <- c("teststatistic", "critical_value")

    if ( N > 1 ) {
      rownames(erg) <- c("crk <= 0 |", paste("crk <= ", 1:(N - 1),  " |", sep = ""))
    }
    if ( N == 1 ) {
      rownames(erg) <- c("crk <= 0 |")
    }

    coint_rank <- paste("Johansen-Test (with trace-teststatistic) indicates",
                        rank, "cointegrating equation(s) at the", 1 - q,
                        "level")
    #print(coint_rank)
    result <- new.env()
    result$erg = erg
    result$estimation = VECM
    result$lambda     = E
    result$z          = z
    result$Z2         = Z2
    result$beta       = beta
    result$PI         = PI
    result$GAMMA      = GAMMA
    result$model      = model
    rr<-as.list(result)
    return(rr)
  }
}


#' This function solves AB_SVAR from the reduced form and return the A, B matrices and the sum of squared errors
#'
#'
#' @param x 	  : difference between the reduced form and the AB form
#' @param A0	  : A matrix in an AB_SVAR model
#' @param B0    : B matrix in an AB_SVAR model
#' @param Sigma : Covariance matrix of the reduced form
#'
#' @return  difference
#' @export
#' @keywords internal
#'
xABF <-  function(x,A0,B0,Sigma) {
  ### this function solves A and B from the reduced form Sigma for a AB-SVAR
  n = dim(A0)[1]
  if (sum((A0==0)|(A0==1))+sum((B0==0)|(B0==1))!= 2*n*n-n*(n+1)/2) return("not exactly identified")
  if (length(x)!=n*(n+1)/2)  return("dimension of x is incorrect")
  A = A0
  B = B0
  VA = as.vector(A)
  VB = as.vector(B)

  VA[!((VA==0)|(VA==1))] = x[1:length(VA[!((VA==0)|(VA==1))])]

  VB[!((VB==0)|(VB==1))] = x[(length(VA[!((VA==0)|(VA==1))])+1):(length(VA[!((VA==0)|(VA==1))])+length(VB[!((VB==0)|(VB==1))]))]

  A = matrix(VA,n,n)
  B = matrix(VB,n,n)
  return(sum((A%*%Sigma%*%t(A)-B%*%t(B))^2))
}


#' Transformation from Bo with common trends to Ao
#'
#' This function calculates Ao coefficients from Bo with common trends.
#'
#' @param m Number of variables
#' @param p Lags
#' @param T Number of observations
#' @param r Number of stochastic trends
#' @param Ncommtrend Number of the common trends
#' @param n Number of countries
#' @param S Number of regimes
#' @param r_npo The matrix containing the roots of the characteristic polynomial
#' @param DFYflag switching indicator whether the foreign variables enter the cointegration space
#'
#' @return Parameter matrix of the foreign variables in the country equation of the GVAR model
#' @export
#' @keywords internal
#'
Bo2Ao <- function(m,p,T,r, Ncommtrend,n,S,r_npo,DFYflag=NA) {
  if ( anyNA(DFYflag) ) DFYflag = 0
  Boab  = VARBS_commtrend(m,p,T,r,Ncommtrend,n,S,r_npo)
  Pmax = max(p[,1:2,])
  beta  = Boab[[3]]
  alpha = Boab[[2]]
  Ao = (1:(m * m * Pmax * n * S)) * 0
  dim(Ao) = c(m, m, Pmax, n, S)
  for (i in 1:n) {
    for (s in 1:S) {
      if (p[i,2,s] < 2) Ao = Ao
      if (p[i,2,s] >= 2) {
        VARD = VARData(m, p=(p[i, 2,s]-1),T)
        BB = VARD$B
        Ao[,,1,i,s] = BB[,,1]+alpha[[i]][[s]]%*%t(beta[[i]][[s]])*DFYflag
        Ao[,,p[i,2,s],i,s] = -BB[,,p[i,2,s]-1]
        if ((p[i, 2,s]-1)>=2) { for (L in 2:(p[i, 2,s]-1)) Ao[, ,L, i,s] = BB[,,L]-BB[,,L-1]}
      }
    }
  }

  return(Ao)
}


#' Estimation of MRCIVAR models
#'
#'This function executes a Johansen test of cointegration ranks and estimates the parameters of a MRCIVAR(n,p,S) model.
#' @param res an MRCIVAR object of the output of MRCIVARDatam
#'
#' @return an estimated MRCIVAR object containing estimated parameters and test results
#' @export
#'
#' @examples
#' Sigma = 1:(4*4*2)
#' dim(Sigma) = c(4,4,2)
#' Sigma[,,1] = diag(4)
#' Sigma[,,2] = diag(4)
#' p=matrix(0,2,2)
#' p[,1] = c(3,3)
#'
#' res_d = MRCIVARDatam(n=4,p=p,T=250,S=2,SESVI=1,TH=0,Sigmao=Sigma,type="const",r=2)
#' colnames(res_d$Y) = c("w","p","I","Q")
#' max(abs(res_d$Y))
#' res_e = MRCIVARestm1(res=res_d)
#' res_e$Summary
#'
MRCIVARestm1 <- function (res)
{
  TH = res$TH
  type = res$type
  p = res$p
  S = res$S
  n = res$n
  Y = res$Y ;  if (max(abs(Y)) > 1000000) return("Check data!!!");
  if (is.null(colnames(Y)))
    colnames(Y) = paste0(rep("Y", ncol(Y)), c(1:ncol(Y)))
  X = res$X
  T = dim(Y)[1]
  SV = res$SV
  sv = res$sv
  d = res$d
  SESVI = res$SESVI
  St = 2 - res$St
  P = max(p[, 1], d)
  Pmax = max(p[, 1])
  Co = res$Co
  r = res$r
  crk = res$crk
  ms = (1:S) * 0
  LH_AIC = 0
  LH_BIC = 0
  LH_P = 0
  LH_N = 0
  b = res$Bo * NA
  cc = res$Co * NA
  sigma = res$Sigmao * NA
  resid = (1:(T * n * S)) * 0
  dim(resid) = c(T, n, S)
  Tresid = resid[, , 1]
  if (type == "none" | type == "exog0")
    Model = "I"
  if (type == "const" | type == "exog1")
    Model = "III"

  if (!anyNA(X)) {
    if (is.null(colnames(X)))
      colnames(X) = paste0(rep("X", ncol(X)), c(1:ncol(X)))
  }


  if (anyNA(X))
    Xi = NA
  else Xi = as.matrix(X[, , 1])

  ORCIVARD = CIVARData(n, p = Pmax, T = T, Co = Co[, , 1],
                       type = type, X = Xi)
  ORCIVARD$Y = Y
  ORCIVAR_e = CIVARest(res = ORCIVARD)
  tst <- MRCVECMestm(y = Y, x = 0, s = St, model = Model, type = "eigen",
                     P = p, crk = n - r, q = 0.95, X = X)
  Tresid[(T - dim(tst$estimation$residuals)[1] + 1):T, ] = tst$estimation$residuals
  Sigma_one = t(Tresid) %*% Tresid/(T - dim(tst$estimation[[1]])[1])
  resid[, , 1] = Tresid * St
  resid[, , 2] = Tresid * (1 - St)
  sigma[, , 1] = t(resid[, , 1]) %*% resid[, , 1]/(sum(St) -
                                                     1 * (n * (p[2, 1] - 1) + crk))
  sigma[, , 2] = t(resid[, , 2]) %*% resid[, , 2]/(sum(1 -
                                                         St) - 1 * (n * (p[2, 1] - 1) + crk))
  CIVAREST = VECM2VARm(param = tst$VECM1[[1]], beta = tst$betaS,
                       p = c(crk, p[1, 1] - 1, p[2, 1] - 1), s = 1)
  Bo = CIVAREST[[1]]
  if (type == "const" | type == "exog1")
    Co = CIVAREST[[3]]
  if (type == "exog0") {
    Co[, 2:(1 + dim(CIVAREST[[3]])[2]), ] = CIVAREST[[3]]
  }
  LH_P = -(T * n/2) * log(2 * pi) - (T * n/2) + (sum(St))/2 *
    log(det(solve(sigma[, , 1]))) + (sum(1 - St))/2 * log(det(solve(sigma[,
                                                                          , 2])))
  LH_P = -(T * n/2) * log(2 * pi) - (T * n/2) + (sum(St))/2 *
    log(det(solve(sigma[, , 1]))) + (sum(1 - St))/2 * log(det(solve(sigma[,
                                                                          , 2])))
  LH_AIC = 2 * (n * (dim(tst$estimation[[1]])[1]) + n * (n +
                                                           1)/2) - 2 * LH_P
  LHH_AIC = 2 * (n * (n * (p[1, 1] - 1 + crk/2) + n * (n +
                                                         1)/2) + n * (n * (p[2, 1] - 1 + crk/2) + n * (n + 1)/2)) -
    2 * LH_P
  LH_BIC = log(T) * (n * (dim(tst$estimation[[1]])[1]) + n *
                       (n + 1)/2) - 2 * LH_P
  LHH_BIC = log(sum(St)) * n * (n * (p[1, 1] - 1 + crk/2) +
                                  n * (n + 1)/2) + log(sum(1 - St)) * n * (n * (p[2, 1] -
                                                                                  1 + crk/2) + n * (n + 1)/2) - 2 * LH_P
  TT = (p[1, 1] - 1) * n + (p[2, 1] - 1) * n + crk - dim(tst$estimation[[1]])[1]
  TTT = dim(tst$estimation[[1]])[1]
  LH_N = 2 * n * (dim(tst$estimation[[1]])[1]) + n * (n + 1)
  LH_TN = log(sum(St)) * n * (n * (p[1, 1] - 1 + crk/2) + n *
                                (n + 1)/2) + log(sum(1 - St)) * n * (n * (p[2, 1] - 1 +
                                                                            crk/2) + n * (n + 1)/2)
  LH_TN1 = log(T) * (n * (dim(tst$estimation[[1]])[1]) + n *
                       (n + 1)/2)
  lm_obj = tst$VECM1
  ORBIC = ORCIVAR_e$Summary$BIC
  ORAIC = ORCIVAR_e$Summary$AIC
  ORLH = ORCIVAR_e$Summary$LH
  ORLHN = ORCIVAR_e$Summary$LH_N
  res$Bo <- Bo
  res$Co <- Co
  res$Sigmao <- sigma
  res$St <- 2 - St
  res$resid <- resid
  est_result = tst$VECM1S
  Summary = list(est_result, tst$erg, LH_AIC, LH_BIC, LH_P,
                 LH_N, LHH_AIC, LHH_BIC, ORBIC, ORAIC, ORLH, ORLHN, LH_TN,
                 LH_TN1, -2 * LH_P)
  names(Summary) = c("Estimation_Result", "CRk_test",
                     "LH_AIC", "LH_BIC", "LH_P", "LH_N",
                     "LHH_AIC", "LHH_BIC", "ORBIC", "ORAIC",
                     "ORLH", "ORLHN", "LH_TN", "LH_TN1",
                     "n2LHP")
  res$Summary = Summary
  res$tst <- tst
  return(res)
}


#' Test of restrictions in the cointegration space of a MRCIVAR model
#'
#' @param res An MRCIVAR object of the output of MRCIGVARDatam
#' @param H A matrix specifying restrictions on beta
#' @param h A vector specifying restrictions on beta
#' @param phi A vector of freely varying parameters in beta
#' @param G A matrix specifying restrictions on alpha
#' @param psi A vector of freely varying parameters in alpha
#'
#' @return A list containing estimated MRVECM under restrictions, restricted parameter, and likelihood test statistic
#' @export
#'
ABC_MRCIVARestm <- function(res=res,H=H,h=h,phi=phi,G=G,psi=psi) {
  ###
  ### This function runs a likelihood ratio test of linear restrictions on alpha and beta in a CIVAR model
  ###
  ###
  ###        vec(alpha'_1) = G_1[[1]] psi[[1]],  vec(alpha'_2) = G[[2]] psi[[2]]   , vec(beta) = H phi + h
  ###
  ###        example 1 (restrictions on alpha) test of exogeneity
  ###                        vec(alpha) is 45 x 1  vector  ( N = 9 crk = 5, defined by the model )
  ###                  G          is 45 x 40 matrix  ( the first variable is exogeneous, i.e. the 5 adjustment coefficient of the first variable are zero )
  ###                      psi        40 x 1 vector (free variaring parameters not appearing in the specification but implied by G)
  ###                  vec(beta)  is 45 x 1 vector   ( N = 0 crk = 5 )
  ###                  H          is 45 x 45 identity matrix
  ###                  phi        45 x 1 vector (free variaring parameters not appearing in the specification but implied by h =0
  ###                  h          45 x 1 zero matrix implying ver(beta) = phi  >> no restrictions on beta.
  ###                        (H is identity and h is zero vector implies only restrictions on alpha)
  ###
  ###        example 2 (restrictions on beta ) test of PPP
  ###                        vec(alpha) is 40 x 1  vector  ( N = 8 crk = 5 ) conditioal VECM  or VECMX model
  ###                  G          is 40 x 40 identity matrix, implying there is no restriction on alpha
  ###                      psi        40 x 1 vector (free variaring parameters not appearing in the specification but implied by the identity matrix G
  ###                  vec(beta)  is 45 x 1 vector   ( N = 0 crk = 5, defined by the model )
  ###                  H          is 45 x 2 matrix that picks out the elements under restricitons ( two colunms out of the identity matrix ) a zero row in H and the corresponding h implies zero-restrictions on beta.
  ###                             ones in a row of H and zero in the corresponding h implies non-restricted beta.
  ###                  phi        2  x 1  vector (free variaring parameters not appearing in the specification but implied by h =0
  ###                  h          45 x 1  non zero elements in this vector together with the zero elements in the corresponding row in H are the normalization conditions.
  ###                        (H is identity and h is zero vector implies only restrictions on alpha)
  ###
  ###
  ### (y,x,model = c("I","II","III","IV","V"), bnorm = c("1","2"),type = c("eigen", "trace"),p = 1, r = 2, q = 0.95, H=H,h=h,G=G)

  res_e = MRCIVARestm1(res=res)
  #### regime-specific constrained  ML
  betaS = res_e$tst$betaS
  alphaS = res_e$tst$alphaS
  BoR    = res$Bo*0
  CoR    = res$Co*0
  type   = res$type


  S = res$S
  n = res$n
  X = res$X
  T = dim(res$Y)[1]


  Z1    = res_e$tst$Z1
  Z2    = res_e$tst$Z2
  St    = res_e$tst$St
  NSt   = res_e$tst$NSt
  Y0    = res_e$tst$Y0
  Sigma = res_e$Sigmao
  R1    = res_e$tst$R1
  R0    = res_e$tst$R0
  code =  res_e$tst$NLmcode
  p    =  res$p
  crk  =  res$crk
  sigmaR = res$Sigmao * NA
  resid = (1:(T * n * S)) * 0
  dim(resid) = c(T, n, S)
  Tresid = resid[, , 1]

  Omega = 1.0/(nrow(res_e$tst$VECM1$residuals))*t(res_e$tst$VECM1$residuals)%*%res_e$tst$VECM1$residuals

  phi_ini  = as.vector(betaS)[(H%*%phi-h)==1]
  psi_ini1 = as.vector(t(alphaS[[1]]))[!G[[1]]%*%psi[[1]]==0]
  psi_ini2 = as.vector(t(alphaS[[2]]))[!G[[2]]%*%psi[[2]]==0]


  #f_constrained(x=c(phi,psi[[1]],psi[[2]]), beta=betaS,alpha=alphaS[[1]],G=G,H=H,phi=phi,psi=psi,h, Z1, St, NSt, Y0, Z2)
  if (crk > 0) {
    x       = c(phi_ini,psi_ini1,psi_ini2)
    XX      = stats::nlm(f_constrained,x, beta=betaS, alpha=alphaS[[1]], G, H, phi, psi,h, Z1, St, NSt, Y0, Z2,iterlim=300)
    xR      = XX$estimate
    #### not converge for bad initial value but converge for good initial value
    phir    = xR[1:length(phi)]
    psi_1r  = xR[(1+length(phi)):(length(phi)+length(psi[[1]]))]
    psi_2r  = xR[(1+(length(phi)+length(psi[[1]]))):(length(phi)+length(psi[[1]])+length(psi[[1]]))]
    betaR   = H%*%phi + h
    alpha_1 = G[[1]]%*%psi[[1]]
    alpha_2 = G[[2]]%*%psi[[2]]

    dim(betaR) = dim(betaS)
    CI = Z1 %*% betaR
    ### restrictions on alpha_1,alpha_2
    dim(alpha_1) = dim(t(alphaS[[1]]))
    alpha_1 = t(alpha_1)
    dim(alpha_2) = dim(t(alphaS[[1]]))
    alpha_2 = t(alpha_2)

    alphaR  = list(alpha_1,alpha_2)
    CI1 = (CI * St) %*%t(alpha_1)
    CI2 = (CI * NSt)%*%t(alpha_2)
    LM  <- stats::lm(Y0-CI1-CI2 ~ 0 + Z2)
    residuals <- LM$residuals
    CI10 = CI * St
    CI20 = CI * NSt
    VECMR <- stats::lm(Y0 ~ 0 + CI10 + CI20 + Z2)
    VECMR$residuals <-  residuals
    #dim(VECMR$coefficients)
    VECMR$coefficients[1:crk,]  = t(alpha_1)
    VECMR$coefficients[(crk+1):(2*crk),] = t(alpha_2)
    VECMR$coefficients[(2*crk+1):nrow(VECMR$coefficients),] = LM$coefficients
    CIVAREST = VECM2VARm(param = VECMR$coefficients, beta = betaR, p = c(crk, p[1, 1] - 1, p[2, 1] - 1), s = 1)
    BoR = CIVAREST[[1]]
    if (type == "const" | type == "exog1")
      CoR = CIVAREST[[3]]
    if (type == "exog0") {
      CoR[,2:(1+dim(CIVAREST[[3]])[2]),] = CIVAREST[[3]]
    }

    Tresid[(T - dim(VECMR$residuals)[1] + 1):T, ] = VECMR$residuals
    resid[ (T - dim(VECMR$residuals)[1] + 1):T, , 1] = Tresid[ (T - dim(VECMR$residuals)[1] + 1):T, ] * St
    resid[ (T - dim(VECMR$residuals)[1] + 1):T, , 2] = Tresid[ (T - dim(VECMR$residuals)[1] + 1):T, ] * (1 - St)
    sigmaR[, , 1] = t(resid[, , 1]) %*% resid[, , 1]/(sum(St) - 1 * (n * (p[2, 1] - 1) + crk))
    sigmaR[, , 2] = t(resid[, , 2]) %*% resid[, , 2]/(sum(1 - St) - 1 * (n * (p[2, 1] - 1) + crk))
    LR = sum(St)*log(det(sigmaR[,,1])) + sum(NSt)*log(det(sigmaR[,,2])) - sum(St)*log(det(Sigma[,,1])) -  sum(NSt)*log(det(Sigma[,,2]))
    dgf =  n*crk - crk - length(phi)
    p_value = 1 - stats::pchisq(LR,dgf)
    LH_P = -(T * n/2) * log(2 * pi) - (T * n/2) + (sum(St))/2 * log(det(solve(sigmaR[, , 1]))) + (sum(NSt))/2 * log(det(solve(sigmaR[,, 2])))

  }

  SepIni = RZSt2VECM(R0,R1,Y0,Z2,Z1,St,crk)

  #tst = AB_MRCIVARTest(R0,R1,G=G,H=H,h=h,alphaR1=alphaS[[1]],alphaR2=alphaS[[2]],betaR=betaS,alpha1=SepIni$alpha1,alpha2=SepIni$alpha2,beta1=SepIni$beta1,beta2=SepIni$beta2,OmegaR=Omega,Omega1=SepIni$Omega1,Omega2=SepIni$Omega2,IC=1,T1=T,St=St,NSt=NSt)
  tst  = NA
  test = list( VECMR,BoR,CoR,sigmaR,betaR,alphaR,LR,p_value, LH_P, XX$code,tst)
  names(test) = c("VECMR","BoR","CoR","sigmaR","betaR","alphaR","LR","p_value","LH_P","code","tst")
  return(test)
}


#' Split a string
#'
#' @param x A character vector with one element.
#' @param split What to split on.
#'
#' @return A character vector.
#' @export
#'
#' @examples
#' x <- "alfa,bravo,charlie,delta"
#' strsplit1(x, split = ",")
strsplit1 <- function(x, split) {
  strsplit(x, split = split)[[1]]
}


#' Check the consistency between type, Co, and EXOG
#'
#' This function will output type according to specification of Co and EXOG and type.
#' @param Co The coefficients of the deterministic components
#' @param EXOG The exogenous variables
#' @param type The type of the deterministic specification for comparison
#'
#' @return type
#' @export
#'
#' @examples
#' Type(Co=matrix(c(0,0,1,1),2,2),EXOG= c(1:10),type="exog0")
#' Type(Co=matrix(c(1,1,1,1),2,2),EXOG= c(1:10),type="exog1")
#' Type(Co=matrix(c(1,1,1,1,0,0),2,3),EXOG= c(1:10),type=NA)
#' Type(Co=c(1,1),EXOG= NA,type=NA)
#' Type(Co=c(0,0),EXOG= NA,type=NA)
#' VARData(n=2,p=2,T=100,Co=matrix(c(2,2,1,1),2,2),type="exog0",X=c(1:100))
#' VARData(n=2,p=2,T=100,Co=matrix(c(1,1,1,1),2,2),type="exog1",X=c(1:100))
Type <- function (Co, EXOG, type)
{
  if (anyNA(Co) & anyNA(EXOG) & anyNA(type))
    type = "const"
  if (anyNA(Co) & !anyNA(EXOG) & anyNA(type))
    type = "exog1"
  if (anyNA(Co) & !anyNA(EXOG) & !anyNA(type))
    type = type
  if (!anyNA(Co) & anyNA(EXOG)) {
    if (sum(Co == 0) == length(Co))
      type = "none"
    else type = "const"
  }
  if (!anyNA(Co) & !anyNA(EXOG)) {
    if (ncol(as.matrix(Co)) == ncol(as.matrix(EXOG)) + 1) {
      if (sum(as.matrix(Co)[, 1] == 0) == length(as.matrix(Co)[, 1]))
        type = "exog0"
      else type = "exog1"
    }
    else type = " Co column<> EXOG column "
  }
  return(type)
}


#' Embedding a time series
#'
#' Embeds the time series y into a low-dimensional Euclidean space with column names.
#'
#' @param y The time series to be embedded
#' @param p Number of lags for embedding
#' @param prefix Prefix of the column names
#'
#' @return A matrix containing the embedded time series y.
#' @export
#' @keywords internal
Embed <- function(y=tseries::ts(c(1:20)),p=3,prefix="") {
  YY = stats::embed(y,p)
  if (!is.null(colnames(y))) {
    strc = colnames(y)
    strc = paste(prefix,strc,sep="")
    str0 = strc
    if (p > 1) {
      for (i in 1:(p-1)) {
        stri <- paste(str0, ".", sep="")
        stri <- paste(stri,as.character(i),sep="")
        strc <- cbind(strc,stri)
      }
    }
    colnames(YY) <- as.vector(strc)
  }
  return(YY)
}


#' An auxiliary function for nonlinear estimation of the cointegration vectors
#'
#' @param x A vector containing the parameters in the cointegration vectors.
#' @param beta The initial value of the cointegration vectors
#' @param Z1 The lagged I(1) series of the model
#' @param St The indicator series of regime 1
#' @param NSt The indicator series of regime 2
#' @param Y0 The first difference series
#' @param Z2 The lagged difference series
#'
#' @export
#' @keywords internal
f <- function(x,beta,Z1,St,NSt,Y0,Z2) {
  dim(x) = dim(beta)
  CI = Z1%*%x
  CI1 = CI*St
  CI2 = CI*NSt
  residuals <-stats::lm(Y0~0+CI1+CI2+Z2)$residuals
  SSR = sum(diag(t(residuals)%*%residuals))
  return(SSR)
}


#' Shift of Z2 regressors
#'
#' This function generates impulse response functions of an estimated CIGVAR(m,n,p) with confidence bands.
#'
#' @param  Z2 : Regressor's matrix to be shifted
#' @param  kz : number of common exogenous factors
#' @param  n1 : number of domestic variables
#' @param  p  : the lag length of domestic variables in Z2 which is also the lag length of exogenous common factors
#' @return a shifted Z2 if there are exogenous common factors. It returns Z2 without shift if there are no common factors.
#'
#' @export
#'
#' @keywords internal
ShiftZ2 <- function(Z2,kz,n1,p) {
  # kz : number of Commfakts
  # Z2 : Regressiors on the auxiliery regression
  # n1 : number of domestic variables in a country
  # p  : lag length of domestic regressors. It is the same as the lag length of common factors (p[1,1]-1)
  if ((kz>0)&(p>0)) {
    cc = (1:(kz*p))*0
    for (j in 1:p) {
      for (i in 1:kz) {
        cc[(j-1)*kz+i] = (j-1)*(n1+kz)+i
      }
    }
    Z2 = cbind(Z2[,-cc],Z2[,cc])
  }
  return(Z2)
}


#' Shift of Z2 regressors
#'
#' This function generates impulse response functions of an estimated CIGVAR(m,n,p) with confidence bands.
#'
#' @param  Z2 : Regressor's matrix to be shifted
#' @param  kz : number of common exogenous factors
#' @param  n1 : number of domestic variables
#' @param  p  : the lag length of domestic variables in Z2 which is also the lag length of exogenous common factors
#' @param  p2 : the lag length of foreign  variables in Z2
#' @return a shifted Z2 if there are exogenous common factors. It returns Z2 without shift if there are no common factors.
#'
#' @export
#'
#' @keywords internal
ShiftZ2m <- function(Z2,kz,n1,p,p2) {
  if ((kz>0)&(p>0)) {
    cc = (1:(kz*p))*0
    for (j in 1:p) {
      for (i in 1:kz) {
        cc[(j-1)*kz+i] = (j-1)*(n1+kz)+i
      }
    }
    ccc=c(cc,(p*(n1+kz)+p2*n1)+cc)
    Z2 = cbind(Z2[,-ccc],Z2[,ccc])
  }
  return(Z2)
}
