# utils.R
# (re)generated by tools/02_split_to_modules.R



#'
#' This function creates independent common stochastic trends and idiosyncratic trends.
#'
#' @param m number of variables
#' @param p lags
#' @param T number of observations
#' @param r_npo roots of the characteristic polynomial
#' @param Ncommtrend number of common trends
#' @param n number of countries
#'
#' @return A list containing the parameter matrix of the domestic variables, the cointegration vectors and the adjustment vectors
#' @export
#' @keywords internal
#'
varb_commtrend <- function (m, p, T, r_npo, Ncommtrend, n)
{
  alpha = list()
  beta = list()
  if (missing(Ncommtrend)) {
    Ncommtrend = NA
  }
  if (Ncommtrend==0) Ncommtrend <- NA
  Pmax = max(p[, 1:2])
  Pmin = min(p[, 1:2][p[, 1:2] > 0])
  Bo = (1:(m * m * Pmax * n)) * 0
  dim(Bo) = c(m, m, Pmax, n)
  if (anyNA(Ncommtrend)) {
    for (i in 1:n) {
      r_np = c(1:(m * p[i, 1])) * 0
      dim(r_np) = c(m, p[i, 1])
      r_np = r_npo[, 1:p[i, 1], i]
      VARD = var_data(m, p[i, 1], T, r_np = r_np)
      Bo[, , 1:p[i, 1], i] = VARD$B
      alpha[[i]] = b2_cib(VARD$B)[[2]]
      beta[[i]] = b2_cib(VARD$B)[[3]]
    }
  }
  if (!anyNA(Ncommtrend)) {
    B = matrix(stats::rnorm(m * m), m, m)
    Nnocommtrend = m - Ncommtrend
    B[(Nnocommtrend + 1):m, ] = 0
    B = B + diag(m)
    r_np = c(1:(Ncommtrend * Pmin))/c(1:(Ncommtrend * Pmin)) *
      1.5
    dim(r_np) = c(Ncommtrend, Pmin)
    r_np[1:Ncommtrend, 1] = 1
    VAR_IONE = var_data(n = Ncommtrend, p = Pmin, T = 100,
                       r_np = r_np)
    for (i in 1:n) {
      B = matrix(stats::rnorm(m * m), m, m)
      B[(Nnocommtrend + 1):m, ] = 0
      B = B + diag(m)
      Nnocommtrend = m - Ncommtrend
      r_np = c(1:(Nnocommtrend * p[i, 1])) * 0
      dim(r_np) = c(Nnocommtrend, p[i, 1])
      r_np <- r_npo[(Ncommtrend + 1):m, 1:p[i, 1], i]
      dim(r_np) = c(Nnocommtrend, p[i, 1])
      VAR_IZero = var_data(Nnocommtrend, p[i, 1], T = 100,
                          r_np = r_np)
      for (j in 1:p[i, 1]) {
        Dblock = matrix(0, m, m)
        Dblock[1:Nnocommtrend, 1:Nnocommtrend] = VAR_IZero$B[,
                                                             , j]
        if (dim(VAR_IONE$B)[3] >= j)
          Dblock[(Nnocommtrend + 1):m, (Nnocommtrend +
                                          1):m] = VAR_IONE$B[, , j]
        Bo[, , j, i] = B %*% Dblock %*% solve(B)
      }
      alpha[[i]] = b2_cib(Bo[, , 1:p[i, 1], i])[[2]]
      beta[[i]] = b2_cib(Bo[, , 1:p[i, 1], i])[[3]]
    }
  }
  return(list(Bo, alpha, beta))
}



#' @param sname The elements in column names to be replaced
#' @export
#' @keywords internal
#'
summary_civar <- function(lm1=lm1,sname ="Z2\\[,4:9\\]") {
  #### this function replace the Matrix name and leave the colnames in the output
  summ =summary(lm1)
  n = length(summ)
  if (n>1) {
    for (i in 1:n) {
      LL <- dimnames(summ[[i]]$coefficients)[[1]]
      dimnames(summ[[i]]$coefficients)[[1]] <- sub(sname, "", LL)
    }
  }  else {
    LL <- dimnames(summ$coefficients)[[1]]
    dimnames(summ$coefficients)[[1]] <- sub(sname, "", LL)

  }
  return(summ)
}



#'
#' @param param The parameter of an estimated VECM
#' @param beta The cointegration vectors
#' @param q A vector specifying different type of VECMs
#' @param s The indicator of multi regime VECMs
#' @param kz The number of exogenous common factors
#' @param Dxflag Indicator whether the foreign variables enter the cointegration space
#'
#' @return A list of (A, B, C) with B the auto regression parameter matrix, C the parameter of the deterministic components, and A the parameter matrix of foreign variables for CIGVAR.
#' @export
#' @keywords internal
#'
#'
vecm2_var <- function(param, beta, q = c(1, 2, 2, 2, 2),s=NA,kz=0,Dxflag=0)
{
  m = dim(param)[2]
  VECB = t(param)
  if (missing(s))  s = NA
  if (anyNA(s)) {
    if (!q[3] == 0) {   # for GVAR with foreign variables
      B = (1:(m * m * (q[2] + 1))) * 0
      dim(B) = c(m, m, (q[2] + 1))
      A = (1:(m * m * (q[3] + 1))) * 0
      D = NA
      dim(A) = c(m, m, (q[3] + 1))
      AB = VECB[, 1:q[1]] %*% t(beta)
      B[, , 1] = AB[, kz+(1:m)]
      if (Dxflag == 1 ) A[, , 1] = AB[,kz+(m + 1):(2 * m)]
      if (Dxflag == 0 ) A[, , 1] = A[, , 1]*0
      for (i in 2:(q[2] + 1)) B[, , i] = VECB[, q[1] + ((i - 2) * m + 1):((i - 2) * m + m)]
      for (i in 2:(q[3] + 1)) A[, , i] = VECB[, (q[1] + q[2] * m) + ((i - 2) * m + 1):((i - 2) * m + m)]

      B = cib3_b(B)
      A = cia2_a(A)
      if ( kz > 0 ) {
        D = (1:(m*kz*(q[2]+1)))*0; dim(D) =c(m,kz,q[2]+1)
        D[,,1] = AB[,1:kz]
        for (i in 2:(q[2] + 1)) D[, , i] = VECB[, dim(VECB)[2]-q[2]*kz + (((i - 2) * kz + 1):((i - 2) * kz + kz))]
        D = cia2_a(D)
      }
    }
    else {
      B = (1:(m * m * (q[2] + 1))) * 0
      dim(B) = c(m, m, (q[2] + 1))
      AB = VECB[, 1:q[1]] %*% t(beta)
      B[, , 1] = AB[, 1:m]
      if (q[2] > 0) {
        for (i in 2:(q[2] + 1)) B[, , i] = VECB[, q[1] +
                                                  ((i - 2) * m + 1):((i - 2) * m + m)]
        B <- cib3_b(CIB = B)
      }
      if (q[2] == 0) {
        B[, , 1] = B[, , 1] + diag(m)
      }
      A = NA
    }
    if (dim(param)[1] > q[1] + (q[2] + q[3]) * m + q[2]*kz) {
      C = as.matrix(t(param)[, (q[1] + (q[2] + q[3]) * m + 1):(dim(param)[1]-q[2]*kz) ])
    }
    else C = NA
  }
  else {
    if (length(q) == 5) {
      P = max(q[-1])
      B = (1:(m * m * (P + 1) * 2)) * 0
      dim(B) = c(m, m, (P + 1), 2)
      A = B
      AB = VECB[, 1:q[1]] %*% t(beta)
      B[, , 1, 1] = AB[, 1:m]
      A[, , 1, 1] = AB[, (m + 1):(2 * m)]
      B[, , 1, 2] = AB[, 1:m]
      A[, , 1, 2] = AB[, (m + 1):(2 * m)]
      for (i in 2:(q[2] + 1)) B[, , i, 1] = VECB[, q[1] +
                                                   ((i - 2) * m + 1):((i - 2) * m + m)]
      for (i in 2:(q[3] + 1)) A[, , i, 1] = VECB[, (q[1] +
                                                      q[2] * m) + ((i - 2) * m + 1):((i - 2) * m +
                                                                                       m)]
      for (i in 2:(q[4] + 1)) B[, , i, 2] = VECB[, (q[1] +
                                                      (q[2] + q[3]) * m) + ((i - 2) * m + 1):((i -
                                                                                                 2) * m + m)]
      for (i in 2:(q[5] + 1)) A[, , i, 2] = VECB[, (q[1] +
                                                      (q[2] + q[3] + q[4]) * m) + ((i - 2) * m + 1):((i -
                                                                                                        2) * m + m)]
      B[, , 1:(q[2] + 1), 1] = cib3_b(B[, , 1:(q[2] + 1),
                                       1])
      B[, , 1:(q[4] + 1), 2] = cib3_b(B[, , 1:(q[4] + 1),
                                       2])
      A[, , 1:(q[3] + 1), 1] = cia2_a(A[, , 1:(q[3] + 1),
                                       1])
      A[, , 1:(q[5] + 1), 2] = cia2_a(A[, , 1:(q[5] + 1),
                                       2])
      if (dim(param)[1] > q[1] + (sum(q[-1])) * m) {
        C = (1:(m * 2)) * 0
        dim(C) = c(m, 1, 2)
        C[, 1, 1] = as.matrix(t(param)[, q[1] + sum(q[-1]) *
                                         m + 1])
        C[, 1, 2] = as.matrix(t(param)[, q[1] + sum(q[-1]) *
                                         m + 2])
      }
      else {
        C = NA
      }
    }
    if (length(q) == 3) {
      P = max(q[-1])
      B = (1:(m * m * (P + 1) * 2)) * 0
      dim(B) = c(m, m, (P + 1), 2)
      AB = VECB[, 1:q[1]] %*% t(beta)
      B[, , 1, 1] = AB[, 1:m]
      B[, , 1, 2] = AB[, 1:m]
      for (i in 2:(q[2] + 1)) B[, , i, 1] = VECB[, q[1] +
                                                   ((i - 2) * m + 1):((i - 2) * m + m)]
      for (i in 2:(q[3] + 1)) B[, , i, 2] = VECB[, (q[1] +
                                                      q[2] * m) + ((i - 2) * m + 1):((i - 2) * m +
                                                                                       m)]
      B[, , 1:(q[2] + 1), 1] = cib3_b(B[, , 1:(q[2] + 1),
                                       1])
      B[, , 1:(q[3] + 1), 2] = cib3_b(B[, , 1:(q[3] + 1),
                                       2])
      A = NA
      if (dim(param)[1] > q[1] + (sum(q[-1])) * m) {
        C = (1:(m * 2)) * 0
        dim(C) = c(m, 1, 2)
        C[, 1, 1] = as.matrix(t(param)[, q[1] + sum(q[-1]) *
                                         m + 1])
        C[, 1, 2] = as.matrix(t(param)[, q[1] + sum(q[-1]) *
                                         m + 2])
      }
      else {
        C = NA
      }
    }
  }
  return(list(B, A, C, D))
}



#'
#' @param  B  an (m,m,L) array containing the coefficients of the level VAR.
#' @return A list containing three components.
#' \itemize{
#'    \item CIB        : the coefficients matrix of the error correction form
#'    \item alpha	     : the adjustment coefficients
#'    \item beta       : the cointegration vectors
#'    \item sm         : the discrepancy between the selected alpha beta and CIB.
#' }
#' @export
#' @keywords internal
#'
b2_cib <- function (B)
{
  CIB = B * 0
  L = dim(B)[3]
  n = dim(B)[1]
  for (i in L:1) for (j in L:i) CIB[, , i] = CIB[, , i] - B[, , j]
  CIB[, , 1] = -diag(n) - CIB[, , 1]
  P = eigen(CIB[, , 1])$vectors
  lambda = eigen(CIB[, , 1])$values
  P=P[,sort(Mod(lambda),decreasing = FALSE,index.return=TRUE)$ix]
  lambda <- lambda[sort(Mod(lambda),decreasing = FALSE,index.return=TRUE)$ix]

  k = 0
  for (i in 1:(n - 1)) {
    sm = sum(abs(CIB[, , 1] - P[, i:n] %*% diag(lambda[i:n]) %*% solve(P)[i:n, ]))
    if (sm < 1e-06)
      k = i
  }
  sm = sum(abs(CIB[, , 1] - as.matrix(P[, n:n]) %*% lambda[n:n] %*% t(as.matrix(solve(P)[n:n, ]))))
  if (sm < 1e-06)
    k = n
  if (k < n) {
    alpha = P[, k:n] %*% diag(lambda[k:n])
    beta = t(solve(P)[k:n, ])
    sm = sum(abs(CIB[, , 1] - alpha %*% t(beta)))
  }
  if (k == n) {
    alpha = as.matrix(P[, n:n] * lambda[n:n])
    beta = as.matrix(solve(P)[n:n, ])
    sm = sum(abs(CIB[, , 1] - alpha %*% t(beta)))
  }
  return(list(CIB, alpha, beta, sm))
}



#'
#' @param  tst  : an output of CIGVARest
#' @return A list containing three components.
#' \itemize{
#'     \item B          : the coefficient matrices of the domestic variables
#'     \item A	        : the coefficient matrices of the foreign variables
#'     \item C          : the coefficient matrices of the deterministic components
#' }
#' @export
#' @keywords internal
#'
cib2_b = function(tst) {
  P  = tst$P
  r  = ncol(as.matrix(tst$beta))
  m  = ncol(tst[[2]]$coefficients)
  C  = matrix(0,m,1)
  C1 = C
  C2 = C
  mx = tst$NN1
  if (r==1) PI = as.matrix(tst[[2]]$coefficients[1:r,])%*%t(tst$beta)
  if (r>1 ) PI = t(tst[[2]]$coefficients[1:r,])%*%t(tst$beta)
  if (tst$model=="II"|tst$model=="IV") C1 = as.matrix(PI[,m+mx+1])
  PI = PI[,1:(m+mx)]
  BB = t(tst[[2]]$coefficients[(r+1):(r+(P[1]-1)*m),])
  BA = t(tst[[2]]$coefficients[(r+(P[1]-1)*m+1):(r+(P[1]-1)*m+(P[2]-1)*mx) ,])
  #BBAA  = t(tst[[2]]$coefficients[(r+1:(r+(P[1]-1)*m+(P[2]-1)*mx),])

  if (tst$model=="III"|tst$model=="IV") C2 = as.matrix(tst[[2]]$coefficients[nrow(tst[[2]]$coefficients),])
  C  = C1 + C2
  B  = (1:(m*m*P[1]))*0; dim(B) = c(m,m,P[1])
  A  = (1:(m*mx*P[2]))*0; dim(A) = c(m,mx,P[2])

  if ( P[1]==1 )  B[,,1] = PI[,1:m]+diag(m)
  if ( P[1]==2 ) {B[,,1] = PI[,1:m] + BB[,1:m] +diag(m); B[,,2] = - BB[,1:m]}

  if ( P[1]>2 ) {
    B[,,1] = PI[,1:m] + BB[,1:m] + diag(m)
    for (i in 2:(P[1]-1)) {
      B[,,i]    = - BB[,((i-2)*m+1):((i-2)*m+m)] + BB[,((i-1)*m+1):((i-1)*m+m)];
    }
    B[,,P[1]] = - BB[,((P[1]-2)*m+1):((P[1]-2)*m+m)]
  }


  if ( P[2]==1 )  A[,,1] = PI[,(m+1):(m+mx)]
  if ( P[2]==2 ) {A[,,1] = PI[,(m+1):(m+mx)] + BA[,1:mx]; A[,,2] = - BA[,1:mx]}

  if ( P[2]>2 ) {
    A[,,1] = PI[,(m+1):(m+mx)] + BA[,1:mx]
    for (i in 2:(P[2]-1)) {
      A[,,i]    = - BA[,((i-2)*mx+1):((i-2)*mx+mx)] + BA[,((i-1)*mx+1):((i-1)*mx+mx)];
    }
    A[,,P[2]] = - BA[,((P[2]-2)*mx+1):((P[2]-2)*mx+mx)]
  }

  return(list(B,A,C))
}



#'
#' @param CIB an (m,m,L) array of the coefficients matrices of a VECM with lag L-1.
#' @return B (m,m,L) array the coefficients of a VAR with lag L
#' @export
#' @keywords internal
#'
cib3_b = function(CIB) {
  BB = CIB*0
  L = dim(CIB)[3]
  n = dim(BB)[1]
  if (L==1) BB = CIB + diag(4)
  if (L==2) {BB[,,1] = CIB[,,1]+CIB[,,2]+diag(n); BB[,,2] = - CIB[,,2]}
  if (L>2)  {
    BB[,,1] = CIB[,,1]+CIB[,,2]+diag(n)
    for (i in 2:(L-1))  BB[,,i] = CIB[,,i+1]-CIB[,,i]
    BB[,,L] = - CIB[,,L]
  }
  return(BB)
}



#'
#' @param CIA a coefficient matrix of VECM
#'
#' @return the coefficient matrix of the corresponding VAR in level
#' @export
#' @keywords internal
#'
cia2_a = function(CIA) {
	AA = CIA*0
	L = dim(CIA)[3]
      n = dim(AA)[1]
	if (L==1) AA = CIA
	if (L==2) {AA[,,1] = CIA[,,1]+CIA[,,2]; AA[,,2] = - CIA[,,2]}
	if (L>2)  {
     		AA[,,1] = CIA[,,1]+CIA[,,2]
     		for (i in 2:(L-1))  AA[,,i] = CIA[,,i+1]-CIA[,,i]
     		AA[,,L] = - CIA[,,L]
	}
return(AA)
}



#'
#' @param G a coefficient matrix of dimension (n x n x p) of an VAR(p) object.
#'
#' @return Roots of the characteristic polynomial of VAR(p)
#' @export
spectral_radius = function(G) {
   L = dim(G)[3]
   m = dim(G)[1]
   PP=matrix(0,m*L,m*L)
   PP[1:m,] = G[,,]
   if (L>1 ) {
     for ( i in 1:(L-1) ) PP[(i*m+1):(i*m+m),((i-1)*m+1):((i-1)*m+m)] = diag(m)
     eigen(PP)$values
   }  else {
     eigen(G[,,1])$values
   }
}



#'
#' @param param estimated parameters of a conditional VECM
#' @param beta the estimated cointegration vecters
#' @param p a vector specifying different types of conditional VECM
#' @param s indicator variable of different regimes
#' @param N2 dimension of the conditioning variables
#'
#' @return A list of (A, B, C) with B the conditional VAR parameter matrix, C the parameter of the deterministic components, and A the parameter matrix of foreign variables for CIGVAR.
#' @export
#'
cvecm2_cvar <- function (param, beta, p = c(1, 2, 2, 2, 2), s = NA, N2)
{
  m = dim(param)[2]
  VECB = t(param)
  if (anyNA(s)) {                                #### one regime
    if (!p[3] == 0) {
      B = (1:(m * m * (p[2] + 1))) * 0
      dim(B) = c(m, m, (p[2] + 1))
      A = (1:(m * N2 * (p[3] + 1))) * 0
      dim(A) = c(m, N2, (p[3] + 1))
      AB = VECB[, 1:p[1]] %*% t(beta)
      B[, , 1] = AB[, 1:m]
      A[, , 1] = AB[, (m + 1):(m+N2)]
      for (i in 2:(p[2] + 1)) B[, , i] = VECB[, p[1] +  ((i - 2) * m + 1):((i - 2) * m + m)]
      for (i in 2:(p[3] + 1)) A[, , i] = VECB[, (p[1] +  p[2] * m) + ((i - 2) * N2 + 1):((i - 2) * N2 + N2)]
      B <- cib3_b(B)
      A <- cia2_a(A)
    }
    else {
      B = (1:(m * m * (p[2] + 1))) * 0
      dim(B) = c(m, m, (p[2] + 1))
      AB = VECB[, 1:p[1]] %*% t(beta)
      B[, , 1] = AB[, 1:m]
      if (p[2] > 0)
        for (i in 2:(p[2] + 1)) B[, , i] = VECB[, p[1] +
                                                  ((i - 2) * m + 1):((i - 2) * m + m)]
      B <- cib3_b(CIB = B)
      A = NA
    }
    if (dim(param)[1] > p[1] + (p[2]*m + p[3]*N2) ) {
      C = as.matrix(t(param)[, (p[1] + (p[2]*m + p[3]*N2) + 1):dim(param)[1]])
    }      else C = NA
  }
  else {                                #### MRCIGVAR (crk, lag_domestic_1,lag_foreign_1,lag_domestic_2,lag_foreign_2)
    if (length(p) == 5) {
      P = max(p[-1])
      B = (1:(m * m * (P + 1) * 2)) * 0
      dim(B) = c(m, m, (P + 1), 2)
      A = B
      AB = VECB[, 1:p[1]] %*% t(beta)
      B[, , 1, 1] = AB[, 1:m]
      A[, , 1, 1] = AB[, (m + 1):(2 * m)]
      B[, , 1, 2] = AB[, 1:m]
      A[, , 1, 2] = AB[, (m + 1):(2 * m)]
      for (i in 2:(p[2] + 1)) B[, , i, 1] = VECB[, p[1] +
                                                   ((i - 2) * m + 1):((i - 2) * m + m)]
      for (i in 2:(p[3] + 1)) A[, , i, 1] = VECB[, (p[1] +
                                                      p[2] * m) + ((i - 2) * m + 1):((i - 2) * m +
                                                                                       m)]
      for (i in 2:(p[4] + 1)) B[, , i, 2] = VECB[, (p[1] +
                                                      (p[2] + p[3]) * m) + ((i - 2) * m + 1):((i -
                                                                                                 2) * m + m)]
      for (i in 2:(p[5] + 1)) A[, , i, 2] = VECB[, (p[1] +
                                                      (p[2] + p[3] + p[4]) * m) + ((i - 2) * m + 1):((i -
                                                                                                        2) * m + m)]
      B[, , 1:(p[2] + 1), 1] = cib3_b(B[, , 1:(p[2] + 1),
                                       1])
      B[, , 1:(p[4] + 1), 2] = cib3_b(B[, , 1:(p[4] + 1),
                                       2])
      A[, , 1:(p[3] + 1), 1] = cia2_a(A[, , 1:(p[3] + 1),
                                       1])
      A[, , 1:(p[5] + 1), 2] = cia2_a(A[, , 1:(p[5] + 1),
                                       2])
      if (dim(param)[1] > p[1] + (sum(p[-1])) * m) {
        C = (1:(m * 2)) * 0
        dim(C) = c(m, 1, 2)
        C[, 1, 1] = as.matrix(t(param)[, p[1] + sum(p[-1]) *
                                         m + 1])
        C[, 1, 2] = as.matrix(t(param)[, p[1] + sum(p[-1]) *
                                         m + 2])
      }
      else {
        C = NA
      }
    }
    if (length(p) == 3) {                       ### MRCIVAR  crk, lag of regime 1,  lag of regime two
      P = max(p[-1])
      B = (1:(m * m * (P + 1) * 2)) * 0
      dim(B) = c(m, m, (P + 1), 2)
      AB = VECB[, 1:p[1]] %*% t(beta)
      B[, , 1, 1] = AB[, 1:m]
      B[, , 1, 2] = AB[, 1:m]
      for (i in 2:(p[2] + 1)) B[, , i, 1] = VECB[, p[1] +
                                                   ((i - 2) * m + 1):((i - 2) * m + m)]
      for (i in 2:(p[3] + 1)) B[, , i, 2] = VECB[, (p[1] +
                                                      p[2] * m) + ((i - 2) * m + 1):((i - 2) * m +
                                                                                       m)]
      B[, , 1:(p[2] + 1), 1] = cib3_b(B[, , 1:(p[2] + 1),
                                       1])
      B[, , 1:(p[3] + 1), 2] = cib3_b(B[, , 1:(p[3] + 1),
                                       2])
      A = NA
      if (dim(param)[1] > p[1] + (sum(p[-1])) * m) {
        C = (1:(m * 2)) * 0
        dim(C) = c(m, 1, 2)
        C[, 1, 1] = as.matrix(t(param)[, p[1] + sum(p[-1]) *
                                         m + 1])
        C[, 1, 2] = as.matrix(t(param)[, p[1] + sum(p[-1]) *
                                         m + 2])
      }
      else {
        C = NA
      }
    }
  }
  return(list(B, A, C))
}



#'
#' @param N1 dimension of the endogenous variables
#' @param N2 dimension of the exogenous variables
#' @param p lag length
#'
#' @return a new index
#' @export
#' @keywords internal
#'
redex = function(N1,N2,p) {
  M     = N1 + N2
  index = c(1:((p-1)*M))
  Rindex = index*0
  for (i in 1:(p-1)) {
    Rindex[((i-1)*N1+1):((i-1)*N1+N1)]          =  index[((i-1)*M+1):((i-1)*M+N1)]
    Rindex[N1*(p-1)+((i-1)*N2+1):((i-1)*N2+N2)] =  index[((i-1)*M+1+N1):((i-1)*M+N1+N2)]
  }
  Rindex
}



#'
#' This function estimates the unknown parameters of a multi regime conditional VECM based on provided data.
#'
#'
#' @param y data matrix of the endogenous variables
#' @param x data matrix of the exogenous variables
#' @param model type of the specification of the deterministic components. "none" and "const" are two options.
#' @param type =c("eigen", "trace")
#' @param crk cointegration rank
#' @param p lag length in level
#' @param q significance level
#'
#' @return a list of estimated parameters and test statistics
#' @export
#' @keywords internal
#'
cvecm <- function (y,x,model = c("I","II","III","IV","V"),type = c("eigen", "trace"), crk=2, p = 1, q = 0.95)
{
  y <- as.matrix(y)
  if (q != 0.9 && q != 0.95 && q != 0.99) {
    return("please correct significance level")
  }

  p <- as.integer(p)
  N1 <- ncol(as.matrix(y))
  N  <- ncol(as.matrix(y))
  if (N1<crk) {
    return("y's dimension must be larger than crk")
  }

  if  ( length(x) == 1 ) {  z <- y }
  else {
    z <- cbind(y,x)
  }

  M1 <- ncol(as.matrix(z))
  T <- nrow(as.matrix(z))
  #Z <- embed(diff(z), p)
  Z <- embed_ts(diff(z), p)

  Y0 <- Z[, c(1:N1)]                # \Delta Y
  #X0 <- Z[,c((N1+1):M1)]           # \Delta X
  Z1 <- z[-T, ][p:(T - 1), ]        #      Z_1
  if ((p==1)&(length(x)==1)) {
    Z2 = NULL
    NOLAG = 1
  }
  else {
    Z2 <- Z[, c((M1+1):(M1*p))]               # \Delta Z_
    Z2 <- Z2[, redex(N1=N1,N2=ncol(x),p)]       # \Delta Z_
  }
  T1 <- nrow(as.matrix(Y0))
  #lT = (1:T1)/(1:T1)
  #Trend <- matrix(1:T1, T1, 1)
  lT = matrix(1,T1,1); colnames(lT) <- "Const"
  Trend <- matrix(1, T1, 1); colnames(Trend) <- "Trend"

  if ( model == "I" ) {
    Y0 = Y0
    Z1 = Z1
    Z2 = Z2
  }
  if ( model == "II" ) {
    Y0 = Y0
    Z1 = cbind(lT,Z1)
    Z2 = Z2
  }
  if ( model == "III" ) {
    Y0 = Y0
    Z1 = Z1
    Z2 = cbind(Z2,lT)
  }
  if ( model == "IV" ) {
    Y0 = Y0
    Z1 = cbind(Trend,Z1)
    Z2 = cbind(Z2,lT)
  }
  if ( model == "V" ) {
    Y0 = Y0
    Z1 = cbind(Z1)
    Z2 = cbind(Z2,lT,Trend)
  }

  if (length(Z2)==0) {
    R0 <- Y0
    R1 <- Z1
  }
  else {

    M00 <- crossprod(Y0)/T1
    M11 <- crossprod(Z1)/T1
    M22 <- crossprod(Z2)/T1
    M01 <- crossprod(Y0, Z1)/T1
    M02 <- crossprod(Y0, Z2)/T1
    M10 <- crossprod(Z1, Y0)/T1
    M20 <- crossprod(Z2, Y0)/T1
    M12 <- crossprod(Z1, Z2)/T1
    M21 <- crossprod(Z2, Z1)/T1
    M22inv <- solve(M22)
    R0 <- Y0 - t(M02 %*% M22inv %*% t(Z2))
    R1 <- Z1 - t(M12 %*% M22inv %*% t(Z2))
  }
  S00 <- crossprod(R0)/T1
  S01 <- crossprod(R0, R1)/T1
  S10 <- crossprod(R1, R0)/T1
  S11 <- crossprod(R1)/T1
  Ctemp <- chol(S11, pivot = TRUE)
  pivot <- attr(Ctemp, "pivot")
  oo <- order(pivot)
  C <- t(Ctemp[, oo])
  Cinv <- solve(C)
  S00inv <- solve(S00)
  valeigen <- eigen(Cinv %*% S10 %*% S00inv %*% S01 %*% t(Cinv))

  #valeigen <- eigen(S11inv %*% S10 %*% S00inv %*% S01 )
  lambda <- Re(valeigen$values)
  e      <- Re(valeigen$vector)

  V <- t(Cinv) %*% e
  Vorg <- V
  V <- sapply(1:M1, function(j) V[, j]/V[1, j])
  #W <- S01 %*% V %*% solve(t(V) %*% S11 %*% V)
  PI <- S01 %*% solve(S11)
  #DELTA <- S00 - S01 %*% V %*% solve(t(V) %*% S11 %*% V) %*% t(V) %*% S10
  if (length(Z2)==0) {
    GAMMA = NULL
  }
  else {
    GAMMA <- M02 %*% M22inv - PI %*% M12 %*% M22inv
  }
  beta   <- V[,1:crk]

  if ((crk>0)&(length(Z2)>0)) {
    CI = Z1%*%beta
    VECM<-stats::lm(Y0~0+CI+Z2)
  }
  if ((crk>0)&(length(Z2)==0)) {
    CI = Z1%*%beta
    VECM<-stats::lm(Y0~0+CI)
  }
  if ((crk == 0)&(length(Z2)>0)) {
    CI = 0
    VECM<-stats::lm(Y0~0+Z2)
  }
  if ((crk == 0)&(length(Z2)==0)) {
    CI = 0
    VECM<-NULL
  }
  E = -T1 * log(1 - lambda)
  E = E[1:N]
  ##### Estimation of VECM

  resultsvecm <- summary(VECM)

  if (model == "I")   {    Tab <- Tab1  }
  if (model == "II")  {    Tab <- Tab2  }
  if (model == "III") {    Tab <- Tab3  }
  if (model == "IV")  {    Tab <- Tab4  }
  if (model == "V")   {    Tab <- Tab5  }


  b = c(1:12)
  for (i in 1:12)   { b[i] = Tab[2*(i-1)+1,2+M1-N1] }
  a = c(1:12)
  for (i in 1:12)   { a[i] = Tab[2*i,2+M1-N1] }

  if (type == "eigen") {
    critical_vals = b
    M = matrix(0, N, 1)
    j = 1
    rank = 0
    while (j <= N && E[j] > critical_vals[N + 1 - j]) {
      M[j, ] = M[j, ] + 1
      j = j + 1
      rank = rank + 1
    }
    erg <- cbind(E, critical_vals[N:1])
    colnames(erg) <- c("teststatistic", "critical_value")

    if ( N > 1 ) {
      rownames(erg) <- c("crk <= 0 |", paste("crk <= ", 1:(N - 1),  " |", sep = ""))
    }
    if ( N == 1 ) {
      rownames(erg) <- c("crk <= 0 |" )
    }

    coint_rank <- paste("Johansen-Test (with maximum-eigenvalue-teststatistic) indicates",
                        rank, "cointegrating equation(s) at the", 1 - q,
                        "level")
    #print(coint_rank)
    result <- new.env()
    result$erg = erg
    result$estimation = VECM
    result$lambda     = E
    result$z          = z
    result$Z2         = Z2
    result$beta       = beta
    result$PI         = PI
    result$GAMMA      = GAMMA
    result$model      = model
    rr<-as.list(result)
    return(rr)
  }
  else {
    type = "trace"
    critical_vals = a
    stat = matrix(0, N, 1)
    for (i in 1:N) {
      sum = 0
      for (j in i:N) {
        sum = sum + E[j]
      }
      stat[i] = sum
    }
    M = matrix(0, N, 1)
    j = 1
    rank = 0
    while (stat[j] > critical_vals[N + 1 - j] && j <= N) {
      M[j, ] = M[j, ] + 1
      j = j + 1
      rank = rank + 1
    }
    erg <- cbind(stat, critical_vals[N:1])
    colnames(erg) <- c("teststatistic", "critical_value")

    if ( N > 1 ) {
      rownames(erg) <- c("crk <= 0 |", paste("crk <= ", 1:(N - 1),  " |", sep = ""))
    }
    if ( N == 1 ) {
      rownames(erg) <- c("crk <= 0 |")
    }

    coint_rank <- paste("Johansen-Test (with trace-teststatistic) indicates",
                        rank, "cointegrating equation(s) at the", 1 - q,
                        "level")
    #print(coint_rank)
    result <- new.env()
    result$erg = erg
    result$estimation = VECM
    result$lambda     = E
    result$z          = z
    result$Z2         = Z2
    result$beta       = beta
    result$PI         = PI
    result$GAMMA      = GAMMA
    result$model      = model
    rr<-as.list(result)
    return(rr)
  }
}



#'
#' @param alpha : a matrix with independent columns
#'
#' @return  the orthogonal complementary matrix
#' @export
#' @keywords internal
#'
alpha_perpf = function(alpha=(alpha)) {

  alpha <- as.matrix(alpha)
  n = dim(alpha)[1]
  nx = dim(alpha)[2]
  nz = n-nx
  c = diag(n)[,(nz+1):(nz+nx)]
  c_perp = diag(n)[,1:nz]
  alpha_perp = (diag(n)-c%*%solve(t(alpha)%*%c)%*%t(alpha))%*%c_perp
  t(alpha)%*%alpha_perp
  return(alpha_perp)
}



#'
#'
#' @param x 	  : difference between the reduced form and the AB form
#' @param A0	  : A matrix in an AB_SVAR model
#' @param B0    : B matrix in an AB_SVAR model
#' @param Sigma : Covariance matrix of the reduced form
#'
#' @return  difference
#' @export
#' @keywords internal
#'
x_abf <-  function(x,A0,B0,Sigma) {
  ### this function solves A and B from the reduced form Sigma for a AB-SVAR
  n = dim(A0)[1]
  if (sum((A0==0)|(A0==1))+sum((B0==0)|(B0==1))!= 2*n*n-n*(n+1)/2) return("not exactly identified")
  if (length(x)!=n*(n+1)/2)  return("dimension of x is incorrect")
  A = A0
  B = B0
  VA = as.vector(A)
  VB = as.vector(B)

  VA[!((VA==0)|(VA==1))] = x[1:length(VA[!((VA==0)|(VA==1))])]

  VB[!((VB==0)|(VB==1))] = x[(length(VA[!((VA==0)|(VA==1))])+1):(length(VA[!((VA==0)|(VA==1))])+length(VB[!((VB==0)|(VB==1))]))]

  A = matrix(VA,n,n)
  B = matrix(VB,n,n)
  return(sum((A%*%Sigma%*%t(A)-B%*%t(B))^2))
}



#'
#'
#' @param x0	  : difference between the reduced form and the AB form
#' @param A0	  : A matrix in an AB_SVAR model
#' @param B0    : B matrix in an AB_SVAR model
#' @param Sigma : Covariance matrix of the reduced form
#'
#' @return  a list contains A B and the difference
#' @export
#'
absvar = function(x0,A0,B0,Sigma) {
  ## This function solve AB_SVAR from the reduced form and return the A, B matrices and the sum of squared errors
  n =dim(A0)[1]
  ABdiff <- stats::nlm(x_abf,x0,A0,B0,Sigma,gradtol=0.000000000000001 )
  x = ABdiff$estimate
  A = A0
  B = B0
  VA = as.vector(A)
  VB = as.vector(B)
  VA[!((VA==0)|(VA==1))] = x[1:length(VA[!((VA==0)|(VA==1))])]
  VB[!((VB==0)|(VB==1))] = (x[(length(VA[!((VA==0)|(VA==1))])+1):(length(VA[!((VA==0)|(VA==1))])+length(VB[!((VB==0)|(VB==1))]))])
  A = matrix(VA,n,n)
  B = abs(matrix(VB,n,n))
  diff <-sum((A%*%Sigma%*%t(A)-B%*%t(B))^2)
  ## identification
  diag(solve(A)%*%B)
  return(list(A,B,diff))
}



#'
#' @param Bo parameter matrix of domestic variables
#' @param Ao parameter matrix of foreign variables
#' @param W the weighting vector of the GVAR model
#' @param m the number of variables
#' @param n the number of countries
#' @param p lags
#'
#' @return An (mn, mn, p ) array of the GVAR(m,n,p) coefficients.
#' @export
#' @keywords internal
#'
bo_ao_w2_g = function(Bo,Ao,W,m,n,p) {
  dim(Bo) = c(m,m,p,n)
  dim(Ao) = c(m,m,p,n)
  G = (1:(n*m*n*m*p))*0
  dim(G) = c(n*m,n*m,p)
  for (i in 1:n) {
      for (j in 1:n) {
         for (L in 1:p)    G[(1+(i-1)*m):(i*m),(1+(j-1)*m):(j*m),L] = Ao[,,L,i]*W[i,j]
      }
  }
  for (i in 1:n) {
	for (L in 1:p)       G[(1+(i-1)*m):(i*m),(1+(i-1)*m):(i*m),L]  = Bo[,,L,i]
  }
  dim(G) = c(n*m,n*m,p)
return(G)
}



#'
#' @param G The GVAR parameter matrix
#' @param W The weighting matrix of the GVAR model
#'
#' @return A list containing the parameter matrices of domestric variables and foreign variables
#' @export
#' @keywords internal
#'
gw2_bo_ao = function(G,W) {
  n = dim(W)[1]
  m = dim(G)[1]/n

  if (is.na(dim(G)[3])) dim(G) = c(m*n,m*n,1)
  p = dim(G)[3]
  Bo = (1:(m*m*p*n))*0
  dim(Bo) = c(m,m,p,n)
  Ao = Bo
  for (i in 1:n) {
      for (j in 1:n) {
         for (L in 1:p)   if (!j==i) Ao[,,L,i] = G[(1+(i-1)*m):(i*m),(1+(j-1)*m):(j*m),L]/W[i,j]
      }
  }
  for (i in 1:n) {
	for (L in 1:p)       Bo[,,L,i] = G[(1+(i-1)*m):(i*m),(1+(i-1)*m):(i*m),L]
  }
  result = list(Bo,Ao)
  names(result) = c("Bo","Ao")
return(result)
}



#'
#' @param W the weighting vector
#'
#' @return the corresponding weighting matrix
#' @export
#' @keywords internal
#'
w2_wmat = function(W) {
 n = length(W)
 Wmat = matrix(0,n,n)
 for (i in 1:n ) {
    Wmat[i,-i] = W[-i]/sum(W[-i])
 }
 return(Wmat)
}



#'
#' @param SW The weighting vector
#' @param n The number of variables
#' @param N The number of countries
#' @param K The number
#'
#' @return The weighting matrix
#' @export
#' @keywords internal
#'
sw2comb = function(SW,n,N,K)
{
  comb = matrix(0,n*N,N*n)
  SW = SW/sum(SW)
  for (i in 1:n) {
    comb[(i-1)*N+K,1] = SW[i]
  }
  return(comb)
}



#'
#' @param m Number of variables of a country
#' @param p Lags
#' @param T Number of observations
#' @param r Number of stochastic trends
#' @param Ncommtrend Number of common trends
#' @param n Number of countries in the GVAR model
#' @param S Number of regimes
#' @param r_npo A matrix specifying the  roots of the characteristic polynomial in lags
#'
#' @return A list contain VAR parameters B, alpha, and beta
#' @export
#' @keywords internal
#'
#'
varbs_commtrend = function(m,p,T,r, Ncommtrend,n,S,r_npo) {
  alpha   = list()
  beta    = list()
  VAR_Ione = list()
  if (missing(Ncommtrend))  {Ncommtrend=NA}
  Pmax = max(p[,1:2,])
  Pmin = min(p[,1:2,][p[,1:2,]>0])
  Bo = (1:(m * m * Pmax * n * S)) * 0
  dim(Bo) = c(m, m, Pmax, n, S)


  for (i in 1:n) {
      Pmini             = min(p[i,1:2,][p[i,1:2,]>0])
	r_npi 		= c(1:(r[i]*Pmini))/c(1:(r[i]*Pmini))*1.5
      dim(r_npi) 		= c(r[i],Pmini)
      r_npi[1:r[i],1]  	= 1
	VAR_Ione[[i]]  	= VARDatavar_data,p=Pmini,T=100,r_np=r_npi)
  }



  if (!anyNA(Ncommtrend)) {
     	r_npc  = c(1:(Ncommtrend*Pmin))/c(1:(Ncommtrend*Pmin))*1.5
      dim(r_npc) = c(Ncommtrend,Pmin)
      r_npc[1:Ncommtrend,1]  = 1
      VAR_IoneC = var_data(n=Ncommtrend,p=Pmin,T=100,r_np=r_npc)
   	for (i in 1:n) {
		VAR_Ione[[i]]$B[1:Ncommtrend,1:Ncommtrend,]=0
            VAR_Ione[[i]]$B[1:Ncommtrend,1:Ncommtrend,1:Pmin] = VAR_IoneC$B
	}
  }

      for (i in 1:n) {
 		NIzero = m - r[i]
         	#B =  matrix(rnorm(m*m),m,m)                 ### jizhu 0 nadiao
      	#B[(NIzero+1):m,] = 0
      	#B = B + diag(m)
            B = diag(m)
            #B = eigen(t(B)%*%B)$vectors
            alphai = list()
            betai = list()
            for (s in 1:S) {
      		r_np = c(1:(NIzero * p[i,1,s]))*0
            	dim(r_np) = c(NIzero,p[i,1,s])
            	r_np <- r_npo[(r[i]+1):m,1:p[i,1,s],i,s]
            	dim(r_np) = c(NIzero,p[i,1,s])
                  #A = matrix(rnorm(NIzero*NIzero),NIzero,NIzero); A = eigen(t(A)%*%A)[[2]]
	            VAR_IZero = VARDatavar_data, p[i, 1,s],T=100,r_np=r_np,)

            	for (j in 1: p[i,1,s]) {
               		Dblock    = matrix(0,m,m)
               		Dblock[1:NIzero,1:NIzero]     = VAR_IZero$B[,,j]
               		if (dim(VAR_Ione[[i]]$B)[3]>=j) Dblock[(NIzero+1):m,(NIzero+1):m] = VAR_Ione[[i]]$B[,,j]
               		Bo[, , j, i,s] = B%*%Dblock%*%solve(B)
      		}
            	#alpha[[i]] = B2CIB(VARD$B)[[2]]
            	#beta[[i]]  = B2CIB(VARD$B)[[3]]
			B2CIBab  	= B2CIB(Bo[, , 1:p[i, 1,s], ib2_cib            	alphai[[s]] = B2CIBab[[2]]
            	betai[[s]]  = B2CIBab[[3]]
      	}
            alpha[[i]] = alphai
		beta[[i]]  = betai
  	}



  return(list(Bo,alpha,beta))
}



#'
#' This function calculates Ao coefficients from Bo with common trends.
#'
#' @param m Number of variables
#' @param p Lags
#' @param T Number of observations
#' @param r Number of stochastic trends
#' @param Ncommtrend Number of the common trends
#' @param n Number of countries
#' @param S Number of regimes
#' @param r_npo The matrix containing the roots of the characteristic polynomial
#' @param DFYflag switching indicator whether the foreign variables enter the cointegration space
#'
#' @return Parameter matrix of the foreign variables in the country equation of the GVAR model
#' @export
#' @keywords internal
#'
bo2_ao <- function(m,p,T,r, Ncommtrend,n,S,r_npo,DFYflag=NA) {
  if ( anyNA(DFYflag) ) DFYflag = 0
  Boab  = varbs_commtrend(m,p,T,r,Ncommtrend,n,S,r_npo)
  Pmax = max(p[,1:2,])
  beta  = Boab[[3]]
  alpha = Boab[[2]]
  Ao = (1:(m * m * Pmax * n * S)) * 0
  dim(Ao) = c(m, m, Pmax, n, S)
  for (i in 1:n) {
    for (s in 1:S) {
      if (p[i,2,s] < 2) Ao = Ao
      if (p[i,2,s] >= 2) {
        VARD = var_data(m, p=(p[i, 2,s]-1),T)
        BB = VARD$B
        Ao[,,1,i,s] = BB[,,1]+alpha[[i]][[s]]%*%t(beta[[i]][[s]])*DFYflag
        Ao[,,p[i,2,s],i,s] = -BB[,,p[i,2,s]-1]
        if ((p[i, 2,s]-1)>=2) { for (L in 2:(p[i, 2,s]-1)) Ao[, ,L, i,s] = BB[,,L]-BB[,,L-1]}
      }
    }
  }

  return(Ao)
}



#'
#' This function calculates a full rank linear transformation of initial Bo and Ao matrices with independent common trends and idiosyncratic trends.
#'
#' @param Bo The initial Bo matrix
#' @param Ao The initial Ao matrix
#' @param W  A weighting matrix of the GVAR model
#' @param S Number of regimes
#'
#' @return Transformed Bo and Ao matrices
#' @export
#' @keywords internal
#'
bo_ao2_t_bo_ao = function(Bo,Ao,W,S) {
  TBo = Bo*0
  TAo = Ao*0
  n = dim(W)[1]
  m = dim(Bo)[1]
  L = dim(Bo)[3]
  BD = matrix(0,m*n,m*n)
  B =  matrix(stats::rnorm(m*m),m,m)
  for (i in 1:n) {
    BD[((i-1)*m+1):((i-1)*m+m),((i-1)*m+1):((i-1)*m+m)] = B
  }
  for (j in 1:L) {
    for ( s in 1: S ) {

      BoDj =  matrix(0,m*n,m*n)
      AoDj =  matrix(0,m*n,m*n)

      for (i in 1:n)  {
        BoDj[((i-1)*m+1):((i-1)*m+m),((i-1)*m+1):((i-1)*m+m)]=Bo[,,j,i,s]
        AoDj[((i-1)*m+1):((i-1)*m+m),((i-1)*m+1):((i-1)*m+m)]=Ao[,,j,i,s]
      }
      B_h = BD%*%BoDj%*%solve(BD)
      A_h = BD%*%AoDj%*%kronecker(W,diag(m))%*%solve(BD)%*%solve(kronecker(W,diag(m)))
      for (i in 1:n)  {
        TBo[,,j,i,s] = B_h[((i-1)*m+1):((i-1)*m+m),((i-1)*m+1):((i-1)*m+m)]
        TAo[,,j,i,s] = A_h[((i-1)*m+1):((i-1)*m+m),((i-1)*m+1):((i-1)*m+m)]
      }
    }
  }
  return(list(TBo,TAo))
}



#'
#' @param param The coefficient matrix of the estimated multi regime vector error correction model
#' @param beta The estimated cointegration vectors
#' @param p The lags of the MRCIVAR model
#' @param s Types of MRCIVAR models
#'
#' @return The parameter of the multi regime cointegrated VAR
#' @export
#' @keywords internal
#'
#'
vecm2_va_rm = function (param, beta, p = c(1, 2, 2, 2, 2), s = NA)
{
    m = dim(param)[2]
    VECB = t(param)
    if (anyNA(s)) {                                            ## One Regime
        if (!p[3] == 0) {                                        ## CIGVAR
            B = (1:(m * m * (p[2] + 1))) * 0
            dim(B) = c(m, m, (p[2] + 1))
            A = (1:(m * m * (p[3] + 1))) * 0
            dim(A) = c(m, m, (p[3] + 1))
            AB1 = VECB[, 1:p[1]] %*% t(beta)
            AB2 = VECB[, (1 + p[1]):(p[1] + p[1])] %*% t(beta)
            B[, , 1] = AB[, 1:m]
            A[, , 1] = AB[, (m + 1):(2 * m)]
            for (i in 2:(p[2] + 1)) B[, , i] = VECB[, p[1] *
                2 + ((i - 2) * m + 1):((i - 2) * m + m)]
            for (i in 2:(p[3] + 1)) A[, , i] = VECB[, (p[1] *
                2 + p[2] * m) + ((i - 2) * m + 1):((i - 2) *
                m + m)]
            B = cib3_b(B)
            A = cia2_a(A)
        }
        else {                                                   ##CIVAR
            B = (1:(m * m * (p[2] + 1))) * 0
            dim(B) = c(m, m, (p[2] + 1))
            AB = VECB[, 1:p[1]] %*% t(beta)
            B[, , 1] = AB[, 1:m]
            for (i in 2:(p[2] + 1)) B[, , i] = VECB[, p[1] +
                ((i - 2) * m + 1):((i - 2) * m + m)]
            B = cib3_b(B)
            A = NA
        }
        if (dim(param)[1] > p[1] + (p[2] + p[3]) * m)            ## whehter C is empty
            C = as.matrix(t(param)[, (p[1] + (p[2] + p[3]) * m + 1):dim(param)[1]])
        else C = NA
    }
    else {                                                    ## Multi Regime
        if (length(p) == 5) {                                    ## MRCIGVAR
            P = max(p[-1])
            B = (1:(m * m * (P + 1) * 2)) * 0
            dim(B) = c(m, m, (P + 1), 2)
            A = B
            AB = VECB[, 1:p[1]] %*% t(beta)
            B[, , 1, 1] = AB[, 1:m]
            A[, , 1, 1] = AB[, (m + 1):(2 * m)]
            B[, , 1, 2] = AB[, 1:m]
            A[, , 1, 2] = AB[, (m + 1):(2 * m)]
            for (i in 2:(p[2] + 1)) B[, , i, 1] = VECB[, p[1] +
                ((i - 2) * m + 1):((i - 2) * m + m)]
            for (i in 2:(p[3] + 1)) A[, , i, 1] = VECB[, (p[1] +
                p[2] * m) + ((i - 2) * m + 1):((i - 2) * m +
                m)]
            for (i in 2:(p[4] + 1)) B[, , i, 2] = VECB[, (p[1] +
                (p[2] + p[3]) * m) + ((i - 2) * m + 1):((i -
                2) * m + m)]
            for (i in 2:(p[5] + 1)) A[, , i, 2] = VECB[, (p[1] +
                (p[2] + p[3] + p[4]) * m) + ((i - 2) * m + 1):((i -
                2) * m + m)]
            B[, , 1:(p[2] + 1), 1] = cib3_b(B[, , 1:(p[2] + 1),
                1])
            B[, , 1:(p[4] + 1), 2] = cib3_b(B[, , 1:(p[4] + 1),
                2])
            A[, , 1:(p[3] + 1), 1] = cia2_a(A[, , 1:(p[3] + 1),
                1])
            A[, , 1:(p[5] + 1), 2] = cia2_a(A[, , 1:(p[5] + 1),
                2])
            if (dim(param)[1] > p[1] + (sum(p[-1])) * m) {
                C = (1:(m * 2)) * 0
                dim(C) = c(m, 1, 2)
                C[, 1, 1] = as.matrix(t(param)[, p[1] * 2 + sum(p[-1]) *
                  m + 1])
                C[, 1, 2] = as.matrix(t(param)[, p[1] * 2 + sum(p[-1]) *
                  m + 2])
            }
            else {
                C = NA
            }
        }
        if (length(p) == 3) {                                     ## MRCIVAR
            P = max(p[-1])
            B = (1:(m * m * (P + 1) * 2)) * 0
            dim(B) = c(m, m, (P + 1), 2)
            AB1 = VECB[, 1:p[1]] %*% t(beta)
            AB2 = VECB[, (1 + p[1]):(p[1] + p[1])] %*% t(beta)
            B[, , 1, 1] = AB1[, 1:m]
            B[, , 1, 2] = AB2[, 1:m]
            for (i in 2:(p[2] + 1)) B[, , i, 1] = VECB[, 2 *
                p[1] + ((i - 2) * m + 1):((i - 2) * m + m)]
            for (i in 2:(p[3] + 1)) B[, , i, 2] = VECB[, (2 *
                p[1] + p[2] * m) + ((i - 2) * m + 1):((i - 2) *
                m + m)]
            B[, , 1:(p[2] + 1), 1] = cib3_b(B[, , 1:(p[2] + 1),
                1])
            B[, , 1:(p[3] + 1), 2] = cib3_b(B[, , 1:(p[3] + 1),
                2])
            A = NA
            if (dim(param)[1] > p[1] * 2 + (sum(p[-1])) * m) {		## Whether C is empty  differnt adjustment speed
                km = (dim(param)[1]- (p[1] * 2 + (sum(p[-1])) * m))/2
                C = (1:(m * km* 2)) * 0
                dim(C) = c(m, km, 2)
                C[, 1:km, 1] = as.matrix(t(param)[, (p[1] * 2 + sum(p[-1]) * m + 1):(p[1] * 2 + sum(p[-1]) * m + km)])
                C[, 1:km, 2] = as.matrix(t(param)[,  (p[1] * 2 + sum(p[-1]) * m + km +1):(p[1] * 2 + sum(p[-1]) * m + km+km) ])
            }
            else {
                C = NA
            }
        }
    }
    return(list(B, A, C))
}



#'
#' @param Bo Parmeter matrices of the domestic variables
#' @param Ao Parameter matrices of the foreign variables
#' @param W The weighting matrix of the GVAR model
#' @param m Number of variables of a country
#' @param n Number of countries in the GVAR model
#' @param p Lag specifications
#' @param state A vector specifying state of the GVAR parameters
#'
#' @return The auto regression paramters of the GVAR model
#' @export
#' @keywords internal
#'
bo_ao_ws2_gs = function(Bo,Ao,W,m,n,p,state) {
  Bo_s=Bo[,,,,1]*0;dim(Bo_s) = c(m,m,p,n)
  Ao_s=Ao[,,,,1]*0;dim(Ao_s) = c(m,m,p,n)
  for (i in 1:n ) {
    Bo_s[,,,i] = Bo[,,,i,state[i]]
    Ao_s[,,,i] = Ao[,,,i,state[i]]
  }
  Go_s = bo_ao_w2_g(Bo_s,Ao_s,W,m,n,p)
  return(Go_s)
}



#'
#' @param X The data matrix of exogenous variables
#'
#' @return An array of containing exogenous data
#' @export
#' @keywords internal
#'
bind_exogenous_by_state = function(X) {
### X: the T x Nx x S array collecting the exogenous variables in MRVAR with state dependent exog variables
	S  = dim(X)[3]
      Nx = dim(X)[2]
      ss = 0
      sidx = 0
	for (s in 1:S) {
        if (sum(colSums(X[,,s] != 0) !=0)>ss ) {
           ss = sum(colSums(X[,,s] != 0) !=0)
           sidx = s
      }
      }
      XX = X[,1:ss,sidx]
      return(XX)
}



#'
#' @param B The coefficient matrix of a VAR object
#' @param sigma The covariance matrix of a VAR object
#' @param irf Types of impulse response functions
#' @param comb Types of concerted policy actions
#' @param G The matrix used in the permanent and transitory decomposition
#' @param smat An explicit decomposition matrix that defines a structural shock.
#'
#' @return The transformation matrix for a shock decomposition
#' @export
#' @keywords internal
#'
u1=function(B,sigma,irf = c("gen", "chol", "chol1","gen1","genN1","comb", "comb1","smat","concerts1","concerts0","concertc"),comb,G=NA,smat=NA)
  {
    ##-----debug--------
    ##browser()
    ##------------------
    neq <- dim(B)[1]
    nvar <- dim(B)[2]
    lags <- dim(B)[3]
    n <- dim(sigma)[1]
    if (irf == "smat")     {  smat = (smat)    }

    if (irf == "chol") 	   {        smat = chol(sigma)    					    }
    if (irf == "PTdecomp") {        smat = chol(G%*%sigma%*%t(G))          		    }
    if (irf == "gen")      {        smat = t(sigma %*% diag(1/(sqrt(diag(sigma)))))     }
    if (irf == "chol1")    {        smat = chol(sigma) %*% diag(1/diag(chol(sigma)))    }
    if (irf == "gen1")     {        smat = t(sigma %*% diag(1/(diag(sigma))))           }
    if (irf == "genN1")    {        smat = t(sigma %*% diag(-1/(diag(sigma))))          }
    if ( irf == "concerts1") { smat  = t((sigma%*%diag(1/(diag(sigma))))%*%comb)        };
    if ( irf == "concerts0") { smat  = t((sigma%*%diag(1/(sqrt(diag(sigma)))))%*%comb)  };

    if ( irf == "concertc") {
      c     = as.numeric(!(comb[,1]==0));
      smat  = matrix(0,n,n);
      for (i in 1: n) { smat[i,] = sigma[i,]%*%diag(c)%*%invi(sigma,c,i)%*%comb; }
      smat = t(smat);
    };

    if (irf == "comb") {
      DD = diag(t(comb) %*% sigma %*% comb)
      for (i in 1:length(DD)) {
        if (DD[i] > 0)
          DD[i] = sqrt(1/DD[i])
      }
      DD = diag(DD)
      smat = t(sigma %*% comb %*% DD)
    }
    if (irf == "comb1") {
      DD = diag(t(comb) %*% sigma %*% comb)
      for (i in 1:length(DD)) {
        if (DD[i] > 0)
          DD[i] = (1/DD[i])
      }
      DD = diag(DD)
      smat = t(sigma %*% comb %*% DD)
    }
    if(dim(smat)[2] != dim(B)[2]) stop("B and smat conflict on # of variables")
    return(smat)
  }



#'
#' @param x A character vector with one element.
#' @param split What to split on.
#'
#' @return A character vector.
#' @export
#'
#' @examples
#' x <- "alfa,bravo,charlie,delta"
#' strsplit1(x, split = ",")
strsplit1 <- function(x, split) {
  strsplit(x, split = split)[[1]]
}


#'
#' This function will output type according to specification of Co and EXOG and type.
#' @param Co The coefficients of the deterministic components
#' @param EXOG The exogenous variables
#' @param type The type of the deterministic specification for comparison
#'
#' @return type
#' @export
#'
#' @examples
#' Type(Co=matrix(c(0,0,1,1),2,2),EXOG= c(1:10),type="exog0")
#' Type(Co=matrix(c(1,1,1,1),2,2),EXOG= c(1:10),type="exog1")
#' Type(Co=matrix(c(1,1,1,1,0,0),2,3),EXOG= c(1:10),type=NA)
#' Type(Co=c(1,1),EXOG= NA,type=NA)
#' Type(Co=c(0,0),EXOG= NA,type=NA)
#' VARData(n=2,p=2,T=100,Co=matrix(c(2,2,1,1),2,2),type="exog0",X=c(1:100))
#' VARData(n=2,p=2,T=100,Co=matrix(c(1,1,1,1),2,2),type="exog1",X=c(1:100))
infer_deterministic_type <- function (Co, EXOG, type)
{
  if (anyNA(Co) & anyNA(EXOG) & anyNA(type))
    type = "const"
  if (anyNA(Co) & !anyNA(EXOG) & anyNA(type))
    type = "exog1"
  if (anyNA(Co) & !anyNA(EXOG) & !anyNA(type))
    type = type
  if (!anyNA(Co) & anyNA(EXOG)) {
    if (sum(Co == 0) == length(Co))
      type = "none"
    else type = "const"
  }
  if (!anyNA(Co) & !anyNA(EXOG)) {
    if (ncol(as.matrix(Co)) == ncol(as.matrix(EXOG)) + 1) {
      if (sum(as.matrix(Co)[, 1] == 0) == length(as.matrix(Co)[, 1]))
        type = "exog0"
      else type = "exog1"
    }
    else type = " Co column<> EXOG column "
  }
  return(type)
}



#'
#' Given the roots of a characteristic polynom in lags, output the coefficients of the corresponding AR process.
#' @param p The lag length
#' @param r_p A p-vector of roots outside the unit circle
#'
#' @return A vector of AR coefficients
#' @export
#'
#' @examples
#' @keywords internal
#' Roots2coef(3,c(1.1,1.2,1.3))
roots_to_coef = function(p,r_p) {
   if (missing(r_p)) r_p <- 0.5/(stats::runif(p)-0.5)  #random number outside unit circle
   if (min(abs(r_p)) < 1) {
   	return("r_p is within the unit circle")
   	#print("r_p is within the unit circle")
   }
   a = matrix(0,p,p)
   a[1,1] = 1/r_p[1]
   if ( p>1 ) {
   for (i in 2:p) {
      for ( j in 1:i ) {
         if (j == 1)           a[i,j] = a[i-1,j] + 1/r_p[i]
         if ((j > 1) & (j<i))  a[i,j] = a[i-1,j] - a[i-1,j-1]/r_p[i]
         if (j == i)           a[i,j] = -a[i-1,i-1]/r_p[i]
      }
   }
   }

   #R = matrix(0,p,p)
   #for (i in 1: p)     {
   #   for (j in 1: p ) {
   #        R[i,j] = r_p[j]^i
   #   }
   #}
   #a[p,]%*%R[,]
   return(a[p,])
}



#'
#' This function will generate iid multivariate normal random time series.
#'
#' @param T Length of the generated time series
#' @param sigma An (n x n) covariance matrix of the normal series
#' @return T x n matrix of iid normal time series
#' @export
#' @keywords internal
rnorm_sigma = function(T,sigma) {
    # generate random numbers from iid multivariate normal distribution with covariance matrix Sigma
    n = dim(sigma)[1]
    U = stats::rnorm(T*n)
    dim(U) = c(T,n)
    U = U%*%chol(sigma)
    return(U)
}



#'
#' This function generates random numbers from iid multivariate conditional normal distribution with covariance matrix Sigma, given i-th component has the value of v, this will be an (n-1) dimensional random number
#'
#' @param T Length of generated time series
#' @param sigma The (n x n) covariance matrix of the normal series
#' @param I Index of conditioning component
#' @param v The value of the conditioning component
#' @param switch A switch variable: switch = 1 gives the conditional random series and switch = 0 gives the expected values.
#'
#' @return A (T x (n-1)) matrix of iid conditional normal time series or the conditional expected values
#' @export
#' @keywords internal
rnorm_sigma_cond = function(T,sigma,I,v,switch) {
    # generate random numbers from iid multivariate conditional normal distribution with covariance matrix Sigma, given
    # i-th component has the value of v, this will be an (n-1) dimensional random number
      sigma_cond = as.matrix(sigma[-I,-I])-sigma[-I,I]%*%solve(sigma[I,I])%*%sigma[I,-I]
      mu_cond = sigma[-I,I]%*%solve(sigma[I,I])%*%v
      U = rnorm_sigma(T,sigma_cond)*switch+as.vector(c(1:T)/c(1:T))%*%t(mu_cond)
      return(U)
}



#'
#' @param N The number of elements to be selected
#' @param T The total number of elements
#' @export
#' @keywords internal
sample_n_out_of_t = function(N,T) {
  unique(round(stats::runif(3*N)*(T-1)))[1:N]+1
}



#'
#' Embeds the time series y into a low-dimensional Euclidean space with column names.
#'
#' @param y The time series to be embedded
#' @param p Number of lags for embedding
#' @param prefix Prefix of the column names
#'
#' @return A matrix containing the embedded time series y.
#' @export
#' @keywords internal
embed_ts <- function(y=tseries::ts(c(1:20)),p=3,prefix="") {
  YY = stats::embed(y,p)
  if (!is.null(colnames(y))) {
    strc = colnames(y)
    strc = paste(prefix,strc,sep="")
    str0 = strc
    if (p > 1) {
      for (i in 1:(p-1)) {
        stri <- paste(str0, ".", sep="")
        stri <- paste(stri,as.character(i),sep="")
        strc <- cbind(strc,stri)
      }
    }
    colnames(YY) <- as.vector(strc)
  }
  return(YY)
}



#'
#' @param sigma The input covariance matrix
#' @param c The weighting vector of a concerted policy action
#' @param i The index of responding variables
#'
#' @return A response matrix
#' @export
#' @keywords internal
invi = function(sigma,c,i) {
  n = dim(sigma)[1]
  sigmaout = matrix(0,n,n)
  cc = as.numeric(c>0)*(1:n)
  sigmai = sigma
  for (j in 1:n)         {
    for (k in 1:n)  {
      if ((j==i)|(k==i)) sigmai[j,k] = 0
    }
  }
  sigmai[i,i] = sigma[i,i]
  invsigmai = solve(sigmai[cc,cc])
  sigmaout[cc,cc] = invsigmai
  return(sigmaout)
}



#'
#' @param x A vector containing the parameters in the cointegration vectors.
#' @param beta The initial value of the cointegration vectors
#' @param Z1 The lagged I(1) series of the model
#' @param St The indicator series of regime 1
#' @param NSt The indicator series of regime 2
#' @param Y0 The first difference series
#' @param Z2 The lagged difference series
#'
#' @export
#' @keywords internal
f <- function(x,beta,Z1,St,NSt,Y0,Z2) {
  dim(x) = dim(beta)
  CI = Z1%*%x
  CI1 = CI*St
  CI2 = CI*NSt
  residuals <-stats::lm(Y0~0+CI1+CI2+Z2)$residuals
  SSR = sum(diag(t(residuals)%*%residuals))
  return(SSR)
}



#'
#' This function generates impulse response functions of an estimated CIGVAR(m,n,p) with confidence bands.
#'
#' @param  Z2 : Regressor's matrix to be shifted
#' @param  kz : number of common exogenous factors
#' @param  n1 : number of domestic variables
#' @param  p  : the lag length of domestic variables in Z2 which is also the lag length of exogenous common factors
#' @return a shifted Z2 if there are exogenous common factors. It returns Z2 without shift if there are no common factors.
#'
#' @export
#'
#' @keywords internal
shift_z2 <- function(Z2,kz,n1,p) {
  # kz : number of Commfakts
  # Z2 : Regressiors on the auxiliery regression
  # n1 : number of domestic variables in a country
  # p  : lag length of domestic regressors. It is the same as the lag length of common factors (p[1,1]-1)
  if ((kz>0)&(p>0)) {
    cc = (1:(kz*p))*0
    for (j in 1:p) {
      for (i in 1:kz) {
        cc[(j-1)*kz+i] = (j-1)*(n1+kz)+i
      }
    }
    Z2 = cbind(Z2[,-cc],Z2[,cc])
  }
  return(Z2)
}



#'
#' This function generates impulse response functions of an estimated CIGVAR(m,n,p) with confidence bands.
#'
#' @param  Z2 : Regressor's matrix to be shifted
#' @param  kz : number of common exogenous factors
#' @param  n1 : number of domestic variables
#' @param  p  : the lag length of domestic variables in Z2 which is also the lag length of exogenous common factors
#' @param  p2 : the lag length of foreign  variables in Z2
#' @return a shifted Z2 if there are exogenous common factors. It returns Z2 without shift if there are no common factors.
#'
#' @export
#'
#' @keywords internal
shift_z2m <- function(Z2,kz,n1,p,p2) {
  if ((kz>0)&(p>0)) {
    cc = (1:(kz*p))*0
    for (j in 1:p) {
      for (i in 1:kz) {
        cc[(j-1)*kz+i] = (j-1)*(n1+kz)+i
      }
    }
    ccc=c(cc,(p*(n1+kz)+p2*n1)+cc)
    Z2 = cbind(Z2[,-ccc],Z2[,ccc])
  }
  return(Z2)
}
