# utils.R
# (re)generated by tools/02_split_to_modules.R



#'
#' Generate VAR coefficients with common and idiosyncratic trends
#'
#' Construct domestic VAR coefficient arrays together with implied
#' cointegration and adjustment matrices under user-specified characteristic
#' roots and an optional number of common stochastic trends.
#'
#' @param m Integer scalar giving the number of variables per country.
#' @param p Lag-order specification.
#' @param T Integer scalar giving the number of observations used when building
#'   auxiliary VAR objects.
#' @param r_npo Array of characteristic roots used to generate the VAR
#'   coefficients.
#' @param Ncommtrend Integer scalar giving the number of common stochastic
#'   trends. Use `NA` or `0` to omit common trends.
#' @param n Integer scalar giving the number of countries.
#' @return A list with three elements: domestic coefficient arrays `Bo`,
#'   adjustment matrices `alpha`, and cointegration matrices `beta`.
#' @export
#' @keywords internal
#'
#' @examples
#' \dontrun{
#' m <- 3
#' p <- matrix(c(1, 2,
#'               2, 1), ncol = 2, byrow = TRUE)
#' T <- 100
#' n <- 2
#' Pmax <- max(p[, 1])
#'
#' # Provide valid roots array (see package vignette for recommended settings)
#' r_npo <- array(runif(m * Pmax * n), dim = c(m, Pmax, n))
#'
#' Ncommtrend <- 1
#' result <- varb_commtrend(m, p, T, r_npo, Ncommtrend, n)
#' print(result)
#' }
#'
varb_commtrend <- function (m, p, T, r_npo, Ncommtrend, n) {
  alpha = list()
  beta = list()
  if (missing(Ncommtrend)) {
    Ncommtrend = NA
  }
  if (Ncommtrend == 0) Ncommtrend <- NA
  Pmax = max(p[, 1:2])
  Pmin = min(p[, 1:2][p[, 1:2] > 0])
  Bo = (1:(m * m * Pmax * n)) * 0
  dim(Bo) = c(m, m, Pmax, n)
  if (anyNA(Ncommtrend)) {
    for (i in 1:n) {
      r_np = c(1:(m * p[i, 1])) * 0
      dim(r_np) = c(m, p[i, 1])
      r_np = r_npo[, 1:p[i, 1], i]
      VARD = var_data(m, p[i, 1], T, r_np = r_np)
      Bo[, , 1:p[i, 1], i] = VARD$B
      alpha[[i]] = b2_cib(VARD$B)[[2]]
      beta[[i]] = b2_cib(VARD$B)[[3]]
    }
  }
  if (!anyNA(Ncommtrend)) {
    B = matrix(stats::rnorm(m * m), m, m)
    Nnocommtrend = m - Ncommtrend
    B[(Nnocommtrend + 1):m, ] = 0
    B = B + diag(m)
    r_np = c(1:(Ncommtrend * Pmin)) / c(1:(Ncommtrend * Pmin)) * 1.5
    dim(r_np) = c(Ncommtrend, Pmin)
    r_np[1:Ncommtrend, 1] = 1
    VAR_IONE = var_data(n = Ncommtrend, p = Pmin, T = 100, r_np = r_np)
    for (i in 1:n) {
      B = matrix(stats::rnorm(m * m), m, m)
      B[(Nnocommtrend + 1):m, ] = 0
      B = B + diag(m)
      Nnocommtrend = m - Ncommtrend
      r_np = c(1:(Nnocommtrend * p[i, 1])) * 0
      dim(r_np) = c(Nnocommtrend, p[i, 1])
      r_np <- r_npo[(Ncommtrend + 1):m, 1:p[i, 1], i]
      dim(r_np) = c(Nnocommtrend, p[i, 1])
      VAR_IZero = var_data(Nnocommtrend, p[i, 1], T = 100, r_np = r_np)
      for (j in 1:p[i, 1]) {
        Dblock = matrix(0, m, m)
        Dblock[1:Nnocommtrend, 1:Nnocommtrend] = VAR_IZero$B[, , j]
        if (dim(VAR_IONE$B)[3] >= j)
          Dblock[(Nnocommtrend + 1):m, (Nnocommtrend + 1):m] = VAR_IONE$B[, , j]
        Bo[, , j, i] = B %*% Dblock %*% solve(B)
      }
      alpha[[i]] = b2_cib(Bo[, , 1:p[i, 1], i])[[2]]
      beta[[i]] = b2_cib(Bo[, , 1:p[i, 1], i])[[3]]
    }
  }
  return(list(Bo, alpha, beta))
}



#' Summarize a conditional VAR fit
#'
#' Generate a summary for a conditional VAR fit and optionally clean the
#' coefficient names by removing a user-specified pattern.
#'
#' @param lm1 A fitted model, a `summary.lm` object, or a list of such objects.
#' @param sname Character string giving the pattern to remove from coefficient
#'   row names.
#' @export
#' @keywords internal
#'
#' @examples
#' set.seed(1)
#' dat <- data.frame(
#'   y  = rnorm(50),
#'   x1 = rnorm(50),
#'   x2 = rnorm(50)
#' )
#' model <- lm(y ~ x1 + x2, data = dat)
#' summary_result <- summary_civar(model, sname ="Z2\\[,4:9\\]")
#' print(summary_result)
summary_civar <- function(lm1=lm1, sname = "Z2\\[,4:9\\]") {
  # Helper: rewrite rownames of a coefficients matrix if present
  fix_coeff_names <- function(summ_obj) {
    coefs <- summ_obj$coefficients
    if (is.null(coefs) || is.null(dimnames(coefs)) || is.null(dimnames(coefs)[[1]])) {
      return(summ_obj)
    }
    rn <- dimnames(coefs)[[1]]
    dimnames(coefs)[[1]] <- sub(sname, "", rn)
    summ_obj$coefficients <- coefs
    summ_obj
  }

  # Case 1: user passes a list of models or summaries
  if (is.list(lm1) && !inherits(lm1, "lm") && !inherits(lm1, "summary.lm")) {
    return(lapply(lm1, function(obj) fix_coeff_names(summary(obj))))
  }

  # Case 2: single model / single summary
  summ <- if (inherits(lm1, "summary.lm")) lm1 else summary(lm1)
  fix_coeff_names(summ)
}



#'
#' Convert VECM parameters to VAR coefficient arrays
#'
#' Transform estimated VECM parameters into the corresponding VAR coefficient
#' arrays for single-regime and multi-regime conditional specifications.
#'
#' @param param Matrix of estimated VECM parameters.
#' @param beta Cointegration matrix.
#' @param q Integer vector describing the VECM specification.
#' @param s Optional regime indicator. Use `NA` for a single-regime model.
#' @param kz Integer scalar giving the number of exogenous common factors.
#' @param Dxflag Integer flag indicating whether foreign variables enter the
#'   cointegration space.
#' @return A list containing domestic coefficient arrays `B`, foreign
#'   coefficient arrays `A`, deterministic parameters `C`, and common-factor
#'   parameters `D`.
#' @export
#' @keywords internal
#'
#' @examples
#' # Example usage of vecm2_var function
#' set.seed(1)
#' m <- 3
#' q <- c(2, 2, 2, 2, 2)
#' n_rows <- q[1] + sum(q[-1]) * m  # minimum rows needed when kz = 0
#' param <- matrix(rnorm(n_rows * m), nrow = n_rows, ncol = m)
#' beta  <- matrix(rnorm(m * q[1]), nrow = m, ncol = q[1])
#' result <- vecm2_var(param, beta, q = q, s = NA, kz = 0, Dxflag = 0)
#' str(result)
vecm2_var <- function(param, beta, q = c(1, 2, 2, 2, 2), s = NA, kz = 0, Dxflag = 0) {
  m = dim(param)[2]
  VECB = t(param)
  if (missing(s)) s = NA
  if (anyNA(s)) {
    if (!q[3] == 0) {   # for GVAR with foreign variables
      B = (1:(m * m * (q[2] + 1))) * 0
      dim(B) = c(m, m, (q[2] + 1))
      A = (1:(m * m * (q[3] + 1))) * 0
      D = NA
      dim(A) = c(m, m, (q[3] + 1))
      AB = VECB[, 1:q[1]] %*% t(beta)
      B[, , 1] = AB[, kz + (1:m)]
      if (Dxflag == 1) A[, , 1] = AB[, kz + (m + 1):(2 * m)]
      if (Dxflag == 0) A[, , 1] = A[, , 1] * 0
      for (i in 2:(q[2] + 1)) B[, , i] = VECB[, q[1] + ((i - 2) * m + 1):((i - 2) * m + m)]
      for (i in 2:(q[3] + 1)) A[, , i] = VECB[, (q[1] + q[2] * m) + ((i - 2) * m + 1):((i - 2) * m + m)]
      
      B = cib3_b(B)
      A = cia2_a(A)
      if (kz > 0) {
        D = (1:(m * kz * (q[2] + 1))) * 0
        dim(D) = c(m, kz, q[2] + 1)
        D[, , 1] = AB[, 1:kz]
        for (i in 2:(q[2] + 1)) D[, , i] = VECB[, dim(VECB)[2] - q[2] * kz + (((i - 2) * kz + 1):((i - 2) * kz + kz))]
        D = cia2_a(D)
      }
    } else {
      B = (1:(m * m * (q[2] + 1))) * 0
      dim(B) = c(m, m, (q[2] + 1))
      AB = VECB[, 1:q[1]] %*% t(beta)
      B[, , 1] = AB[, 1:m]
      if (q[2] > 0) {
        for (i in 2:(q[2] + 1)) B[, , i] = VECB[, q[1] + ((i - 2) * m + 1):((i - 2) * m + m)]
        B <- cib3_b(CIB = B)
      }
      if (q[2] == 0) {
        B[, , 1] = B[, , 1] + diag(m)
      }
      A = NA
    }
    if (dim(param)[1] > q[1] + (q[2] + q[3]) * m + q[2] * kz) {
      C = as.matrix(t(param)[, (q[1] + (q[2] + q[3]) * m + 1):(dim(param)[1] - q[2] * kz)])
    } else C = NA
  } else {
    if (length(q) == 5) {
      P = max(q[-1])
      B = (1:(m * m * (P + 1) * 2)) * 0
      dim(B) = c(m, m, (P + 1), 2)
      A = B
      AB = VECB[, 1:q[1]] %*% t(beta)
      B[, , 1, 1] = AB[, 1:m]
      A[, , 1, 1] = AB[, (m + 1):(2 * m)]
      B[, , 1, 2] = AB[, 1:m]
      A[, , 1, 2] = AB[, (m + 1):(2 * m)]
      for (i in 2:(q[2] + 1)) B[, , i, 1] = VECB[, q[1] + ((i - 2) * m + 1):((i - 2) * m + m)]
      for (i in 2:(q[3] + 1)) A[, , i, 1] = VECB[, (q[1] + q[2] * m) + ((i - 2) * m + 1):((i - 2) * m + m)]
      for (i in 2:(q[4] + 1)) B[, , i, 2] = VECB[, (q[1] + (q[2] + q[3]) * m) + ((i - 2) * m + 1):((i - 2) * m + m)]
      for (i in 2:(q[5] + 1)) A[, , i, 2] = VECB[, (q[1] + (q[2] + q[3] + q[4]) * m) + ((i - 2) * m + 1):((i - 2) * m + m)]
      B[, , 1:(q[2] + 1), 1] = cib3_b(B[, , 1:(q[2] + 1), 1])
      B[, , 1:(q[4] + 1), 2] = cib3_b(B[, , 1:(q[4] + 1), 2])
      A[, , 1:(q[3] + 1), 1] = cia2_a(A[, , 1:(q[3] + 1), 1])
      A[, , 1:(q[5] + 1), 2] = cia2_a(A[, , 1:(q[5] + 1), 2])
      if (dim(param)[1] > q[1] + (sum(q[-1])) * m) {
        C = (1:(m * 2)) * 0
        dim(C) = c(m, 1, 2)
        C[, 1, 1] = as.matrix(t(param)[, q[1] + sum(q[-1]) * m + 1])
        C[, 1, 2] = as.matrix(t(param)[, q[1] + sum(q[-1]) * m + 2])
      } else {
        C = NA
      }
    }
    if (length(q) == 3) {
      P = max(q[-1])
      B = (1:(m * m * (P + 1) * 2)) * 0
      dim(B) = c(m, m, (P + 1), 2)
      AB = VECB[, 1:q[1]] %*% t(beta)
      B[, , 1, 1] = AB[, 1:m]
      B[, , 1, 2] = AB[, 1:m]
      for (i in 2:(q[2] + 1)) B[, , i, 1] = VECB[, q[1] + ((i - 2) * m + 1):((i - 2) * m + m)]
      for (i in 2:(q[3] + 1)) B[, , i, 2] = VECB[, (q[1] + q[2] * m) + ((i - 2) * m + 1):((i - 2) * m + m)]
      B[, , 1:(q[2] + 1), 1] = cib3_b(B[, , 1:(q[2] + 1), 1])
      B[, , 1:(q[3] + 1), 2] = cib3_b(B[, , 1:(q[3] + 1), 2])
      A = NA
      if (dim(param)[1] > q[1] + (sum(q[-1])) * m) {
        C = (1:(m * 2)) * 0
        dim(C) = c(m, 1, 2)
        C[, 1, 1] = as.matrix(t(param)[, q[1] + sum(q[-1]) * m + 1])
        C[, 1, 2] = as.matrix(t(param)[, q[1] + sum(q[-1]) * m + 2])
      } else {
        C = NA
      }
    }
  }
  return(list(B, A, C, D))
}



#'
#' Convert VAR coefficients to error-correction form
#'
#' Transform a level VAR coefficient array into its error-correction
#' representation and recover the associated adjustment and cointegration
#' matrices.
#'
#' @param B Three-dimensional array of VAR coefficients with dimensions `(m, m,
#'   L)`.
#' @return A list containing the error-correction coefficients `CIB`, the
#'   adjustment matrix `alpha`, the cointegration matrix `beta`, and the fit
#'   discrepancy `sm`.
#' @export
#' @keywords internal
#'
#' @examples
#' # Example usage of b2_cib function
#' B <- array(rnorm(27), dim = c(3, 3, 3))  # Example VAR coefficients
#' result <- b2_cib(B)
#' print(result)
b2_cib <- function (B) {
  CIB = B * 0
  L = dim(B)[3]
  n = dim(B)[1]
  for (i in L:1) for (j in L:i) CIB[, , i] = CIB[, , i] - B[, , j]
  CIB[, , 1] = -diag(n) - CIB[, , 1]
  P = eigen(CIB[, , 1])$vectors
  lambda = eigen(CIB[, , 1])$values
  P = P[, sort(Mod(lambda), decreasing = FALSE, index.return = TRUE)$ix]
  lambda <- lambda[sort(Mod(lambda), decreasing = FALSE, index.return = TRUE)$ix]

  k = 0
  for (i in 1:(n - 1)) {
    sm = sum(abs(CIB[, , 1] - P[, i:n] %*% diag(lambda[i:n]) %*% solve(P)[i:n, ]))
    if (sm < 1e-06)
      k = i
  }
  sm = sum(abs(CIB[, , 1] - as.matrix(P[, n:n]) %*% lambda[n:n] %*% t(as.matrix(solve(P)[n:n, ]))))
  if (sm < 1e-06)
    k = n
  if (k < n) {
    alpha = P[, k:n] %*% diag(lambda[k:n])
    beta = t(solve(P)[k:n, ])
    sm = sum(abs(CIB[, , 1] - alpha %*% t(beta)))
  }
  if (k == n) {
    alpha = as.matrix(P[, n:n] * lambda[n:n])
    beta = as.matrix(solve(P)[n:n, ])
    sm = sum(abs(CIB[, , 1] - alpha %*% t(beta)))
  }
  return(list(CIB, alpha, beta, sm))
}



#' Convert CIGVAR estimates to coefficient arrays
#'
#' Extract domestic, foreign, and deterministic coefficient arrays from a
#' `cigvar_estimate()` result.
#'
#' @param tst Object returned by `cigvar_estimate()`.
#' @return A list containing domestic coefficient arrays `B`, foreign
#'   coefficient arrays `A`, and deterministic coefficients `C`.
#'
#' @examples
#' # NOTE: This is a minimal, illustrative example. It fabricates a `tst` object
#' # with the fields this function expects, so it can run without the full package
#' # estimation pipeline.
#' \dontrun{
#' set.seed(1)
#' tst <- list()
#' tst$P <- c(2, 2)         # domestic and foreign lag orders
#' tst$NN1 <- 2             # mx (number of foreign variables)
#' tst$model <- "II"        # one of: "II", "III", "IV"
#' tst$beta <- matrix(rnorm(2), ncol = 1)  # r = 1
#'
#' # stub for tst[[2]]$coefficients and tst[[2]] dimensionalities
#' m <- 3
#' tst[[2]] <- list()
#' tst[[2]]$coefficients <- matrix(rnorm(100), nrow = 10)  # oversized on purpose
#' tst[[2]][[1]] <- matrix(rnorm(20), nrow = 10, ncol = m) # so ncol(tst[[2]]$coefficients) is valid
#'
#' res <- cib2_b(tst)
#' str(res)
#' }
#'
#' @export
#' @keywords internal
cib2_b <- function(tst) {
  P  = tst$P
  r  = ncol(as.matrix(tst$beta))
  m  = ncol(tst[[2]]$coefficients)
  C  = matrix(0,m,1)
  C1 = C
  C2 = C
  mx = tst$NN1
  if (r==1) PI = as.matrix(tst[[2]]$coefficients[1:r,])%*%t(tst$beta)
  if (r>1 ) PI = t(tst[[2]]$coefficients[1:r,])%*%t(tst$beta)
  if (tst$model=="II"|tst$model=="IV") C1 = as.matrix(PI[,m+mx+1])
  PI = PI[,1:(m+mx)]
  BB = t(tst[[2]]$coefficients[(r+1):(r+(P[1]-1)*m),])
  BA = t(tst[[2]]$coefficients[(r+(P[1]-1)*m+1):(r+(P[1]-1)*m+(P[2]-1)*mx) ,])
  #BBAA  = t(tst[[2]]$coefficients[(r+1:(r+(P[1]-1)*m+(P[2]-1)*mx),])

  if (tst$model=="III"|tst$model=="IV") C2 = as.matrix(tst[[2]]$coefficients[nrow(tst[[2]]$coefficients),])
  C  = C1 + C2
  B  = (1:(m*m*P[1]))*0; dim(B) = c(m,m,P[1])
  A  = (1:(m*mx*P[2]))*0; dim(A) = c(m,mx,P[2])

  if ( P[1]==1 )  B[,,1] = PI[,1:m]+diag(m)
  if ( P[1]==2 ) {B[,,1] = PI[,1:m] + BB[,1:m] +diag(m); B[,,2] = - BB[,1:m]}

  if ( P[1]>2 ) {
    B[,,1] = PI[,1:m] + BB[,1:m] + diag(m)
    for (i in 2:(P[1]-1)) {
      B[,,i]    = - BB[,((i-2)*m+1):((i-2)*m+m)] + BB[,((i-1)*m+1):((i-1)*m+m)];
    }
    B[,,P[1]] = - BB[,((P[1]-2)*m+1):((P[1]-2)*m+m)]
  }


  if ( P[2]==1 )  A[,,1] = PI[,(m+1):(m+mx)]
  if ( P[2]==2 ) {A[,,1] = PI[,(m+1):(m+mx)] + BA[,1:mx]; A[,,2] = - BA[,1:mx]}

  if ( P[2]>2 ) {
    A[,,1] = PI[,(m+1):(m+mx)] + BA[,1:mx]
    for (i in 2:(P[2]-1)) {
      A[,,i]    = - BA[,((i-2)*mx+1):((i-2)*mx+mx)] + BA[,((i-1)*mx+1):((i-1)*mx+mx)];
    }
    A[,,P[2]] = - BA[,((P[2]-2)*mx+1):((P[2]-2)*mx+mx)]
  }

  return(list(B,A,C))
}



#' Convert VECM coefficient arrays to VAR coefficient arrays
#'
#' Transform an array of VECM coefficients into the corresponding VAR
#' coefficients in levels.
#'
#' @param CIB Three-dimensional array of VECM coefficients.
#' @return A three-dimensional array of VAR coefficients.
#'
#' @examples
#' # Example with m = 3 variables and L = 2 (so VECM lag is L-1 = 1)
#' set.seed(1)
#' m <- 3
#' L <- 2
#' CIB <- array(rnorm(m * m * L), dim = c(m, m, L))
#' B <- cib3_b(CIB)
#' dim(B)
#' B[,,1]
#'
#' @export
#' @keywords internal
cib3_b <- function(CIB) {
  BB = CIB*0
  L = dim(CIB)[3]
  n = dim(BB)[1]
  if (L==1) BB = CIB + diag(4)
  if (L==2) {BB[,,1] = CIB[,,1]+CIB[,,2]+diag(n); BB[,,2] = - CIB[,,2]}
  if (L>2)  {
    BB[,,1] = CIB[,,1]+CIB[,,2]+diag(n)
    for (i in 2:(L-1))  BB[,,i] = CIB[,,i+1]-CIB[,,i]
    BB[,,L] = - CIB[,,L]
  }
  return(BB)
}



#' Convert foreign-block VECM coefficients to VAR levels form
#'
#' Transform an array of foreign-block VECM coefficients into the corresponding
#' VAR coefficient arrays in levels.
#'
#' @param CIA Three-dimensional array of VECM coefficients.
#' @return A three-dimensional array of VAR coefficients.
#'
#' @examples
#' # Example with m = 2 variables and L = 3 lags in the array
#' set.seed(1)
#' m <- 2
#' L <- 3
#' CIA <- array(rnorm(m * m * L), dim = c(m, m, L))
#' A <- cia2_a(CIA)
#' dim(A)
#' A[,,1]
#'
#' @export
#' @keywords internal
cia2_a <- function(CIA) {
  AA = CIA*0
  L = dim(CIA)[3]
  n = dim(AA)[1]
  if (L==1) AA = CIA
  if (L==2) {AA[,,1] = CIA[,,1]+CIA[,,2]; AA[,,2] = - CIA[,,2]}
  if (L>2)  {
    AA[,,1] = CIA[,,1]+CIA[,,2]
    for (i in 2:(L-1))  AA[,,i] = CIA[,,i+1]-CIA[,,i]
    AA[,,L] = - CIA[,,L]
  }
  return(AA)
}



#' Compute characteristic roots of a VAR companion matrix
#'
#' Build the companion matrix implied by a VAR coefficient array and return its
#' eigenvalues.
#'
#' @param G Three-dimensional array of VAR coefficients with dimensions `(m, m,
#'   p)`.
#' @return A complex vector of characteristic roots.
#'
#' @examples
#' # Example: VAR(2) with m = 2 variables
#' set.seed(1)
#' m <- 2
#' p <- 2
#' G <- array(rnorm(m * m * p), dim = c(m, m, p))
#' roots <- spectral_radius(G)
#' roots
#' Mod(roots)  # magnitudes of roots
#'
#' @export
spectral_radius <- function(G) {
  L = dim(G)[3]
  m = dim(G)[1]
  PP = matrix(0, m*L, m*L)
  PP[1:m,] = G[,,]
  if (L>1 ) {
    for ( i in 1:(L-1) ) PP[(i*m+1):(i*m+m),((i-1)*m+1):((i-1)*m+m)] = diag(m)
    eigen(PP)$values
  }  else {
    eigen(G[,,1])$values
  }
}



#' Convert conditional VECM parameters to conditional VAR arrays
#'
#' Transform conditional VECM parameter estimates into domestic, conditioning,
#' and deterministic coefficient arrays for the associated conditional VAR in
#' levels.
#'
#' @param param Matrix of estimated conditional VECM parameters.
#' @param beta Cointegration matrix.
#' @param p Integer vector describing the conditional VECM specification.
#' @param s Optional regime indicator. Use `NA` for a single-regime model.
#' @param N2 Integer scalar giving the number of conditioning variables.
#' @return A list containing domestic coefficient arrays `B`, conditioning
#'   coefficient arrays `A`, and deterministic coefficients `C`.
#'
#' @examples
#' # Minimal illustrative example (fabricated inputs)
#' # The shapes below are chosen so the function can run without the full estimation pipeline.
#' set.seed(1)
#'
#' # Example: single-regime with domestic lags and foreign lags
#' m  <- 2
#' N2 <- 1
#' p  <- c(1, 1, 1, 2, 2)  # only p[1:3] are used in single-regime branch
#'
#' # param is used transposed as VECB; ensure it has enough columns for indexing
#' # Here we build param as (k x m) so t(param) is (m x k)
#' k <- p[1] + p[2]*m + p[3]*N2 + 1
#' param <- matrix(rnorm(k * m), nrow = k, ncol = m)
#'
#' # beta must have ncol(beta) = p[1], and nrow(beta) = m + N2 for AB split
#' beta <- matrix(rnorm((m + N2) * p[1]), nrow = (m + N2), ncol = p[1])
#'
#' out <- cvecm2_cvar(param = param, beta = beta, p = p, s = NA, N2 = N2)
#' str(out)
#'
#' @export
cvecm2_cvar <- function (param, beta, p = c(1, 2, 2, 2, 2), s = NA, N2)
{
  m = dim(param)[2]
  VECB = t(param)
  if (anyNA(s)) {                                #### one regime
    if (!p[3] == 0) {
      B = (1:(m * m * (p[2] + 1))) * 0
      dim(B) = c(m, m, (p[2] + 1))
      A = (1:(m * N2 * (p[3] + 1))) * 0
      dim(A) = c(m, N2, (p[3] + 1))
      AB = VECB[, 1:p[1]] %*% t(beta)
      B[, , 1] = AB[, 1:m]
      A[, , 1] = AB[, (m + 1):(m+N2)]
      for (i in 2:(p[2] + 1)) B[, , i] = VECB[, p[1] +  ((i - 2) * m + 1):((i - 2) * m + m)]
      for (i in 2:(p[3] + 1)) A[, , i] = VECB[, (p[1] +  p[2] * m) + ((i - 2) * N2 + 1):((i - 2) * N2 + N2)]
      B <- cib3_b(B)
      A <- cia2_a(A)
    }
    else {
      B = (1:(m * m * (p[2] + 1))) * 0
      dim(B) = c(m, m, (p[2] + 1))
      AB = VECB[, 1:p[1]] %*% t(beta)
      B[, , 1] = AB[, 1:m]
      if (p[2] > 0)
        for (i in 2:(p[2] + 1)) B[, , i] = VECB[, p[1] +
                                                  ((i - 2) * m + 1):((i - 2) * m + m)]
      B <- cib3_b(CIB = B)
      A = NA
    }
    if (dim(param)[1] > p[1] + (p[2]*m + p[3]*N2) ) {
      C = as.matrix(t(param)[, (p[1] + (p[2]*m + p[3]*N2) + 1):dim(param)[1]])
    }      else C = NA
  }
  else {                                #### MRCIGVAR (crk, lag_domestic_1,lag_foreign_1,lag_domestic_2,lag_foreign_2)
    if (length(p) == 5) {
      P = max(p[-1])
      B = (1:(m * m * (P + 1) * 2)) * 0
      dim(B) = c(m, m, (P + 1), 2)
      A = B
      AB = VECB[, 1:p[1]] %*% t(beta)
      B[, , 1, 1] = AB[, 1:m]
      A[, , 1, 1] = AB[, (m + 1):(2 * m)]
      B[, , 1, 2] = AB[, 1:m]
      A[, , 1, 2] = AB[, (m + 1):(2 * m)]
      for (i in 2:(p[2] + 1)) B[, , i, 1] = VECB[, p[1] +
                                                   ((i - 2) * m + 1):((i - 2) * m + m)]
      for (i in 2:(p[3] + 1)) A[, , i, 1] = VECB[, (p[1] +
                                                      p[2] * m) + ((i - 2) * m + 1):((i - 2) * m +
                                                                                       m)]
      for (i in 2:(p[4] + 1)) B[, , i, 2] = VECB[, (p[1] +
                                                      (p[2] + p[3]) * m) + ((i - 2) * m + 1):((i -
                                                                                                 2) * m + m)]
      for (i in 2:(p[5] + 1)) A[, , i, 2] = VECB[, (p[1] +
                                                      (p[2] + p[3] + p[4]) * m) + ((i - 2) * m + 1):((i -
                                                                                                        2) * m + m)]
      B[, , 1:(p[2] + 1), 1] = cib3_b(B[, , 1:(p[2] + 1),
                                       1])
      B[, , 1:(p[4] + 1), 2] = cib3_b(B[, , 1:(p[4] + 1),
                                       2])
      A[, , 1:(p[3] + 1), 1] = cia2_a(A[, , 1:(p[3] + 1),
                                       1])
      A[, , 1:(p[5] + 1), 2] = cia2_a(A[, , 1:(p[5] + 1),
                                       2])
      if (dim(param)[1] > p[1] + (sum(p[-1])) * m) {
        C = (1:(m * 2)) * 0
        dim(C) = c(m, 1, 2)
        C[, 1, 1] = as.matrix(t(param)[, p[1] + sum(p[-1]) *
                                         m + 1])
        C[, 1, 2] = as.matrix(t(param)[, p[1] + sum(p[-1]) *
                                         m + 2])
      }
      else {
        C = NA
      }
    }
    if (length(p) == 3) {                       ### MRCIVAR  crk, lag of regime 1,  lag of regime two
      P = max(p[-1])
      B = (1:(m * m * (P + 1) * 2)) * 0
      dim(B) = c(m, m, (P + 1), 2)
      AB = VECB[, 1:p[1]] %*% t(beta)
      B[, , 1, 1] = AB[, 1:m]
      B[, , 1, 2] = AB[, 1:m]
      for (i in 2:(p[2] + 1)) B[, , i, 1] = VECB[, p[1] +
                                                   ((i - 2) * m + 1):((i - 2) * m + m)]
      for (i in 2:(p[3] + 1)) B[, , i, 2] = VECB[, (p[1] +
                                                      p[2] * m) + ((i - 2) * m + 1):((i - 2) * m +
                                                                                       m)]
      B[, , 1:(p[2] + 1), 1] = cib3_b(B[, , 1:(p[2] + 1),
                                       1])
      B[, , 1:(p[3] + 1), 2] = cib3_b(B[, , 1:(p[3] + 1),
                                       2])
      A = NA
      if (dim(param)[1] > p[1] + (sum(p[-1])) * m) {
        C = (1:(m * 2)) * 0
        dim(C) = c(m, 1, 2)
        C[, 1, 1] = as.matrix(t(param)[, p[1] + sum(p[-1]) *
                                         m + 1])
        C[, 1, 2] = as.matrix(t(param)[, p[1] + sum(p[-1]) *
                                         m + 2])
      }
      else {
        C = NA
      }
    }
  }
  return(list(B, A, C))
}



#' Reorder indices for endogenous and exogenous lag blocks
#'
#' Create an index vector that moves endogenous lag blocks ahead of exogenous
#' lag blocks in a stacked regressor layout.
#'
#' @param N1 Integer scalar giving the number of endogenous variables.
#' @param N2 Integer scalar giving the number of exogenous variables.
#' @param p Integer scalar giving the lag length.
#' @return An integer vector defining the reordered index mapping.
#'
#' @examples
#' # Example: N1 = 2 endogenous vars, N2 = 1 exogenous var, p = 3 lags
#' # There are (p-1) = 2 lag blocks, each of size M = N1 + N2 = 3
#' # The returned index maps from original stacking to reordered stacking.
#' redex(N1 = 2, N2 = 1, p = 3)
#'
#' @export
#' @keywords internal
redex <- function(N1, N2, p) {
  M     = N1 + N2
  index = c(1:((p-1)*M))
  Rindex = index*0
  for (i in 1:(p-1)) {
    Rindex[((i-1)*N1+1):((i-1)*N1+N1)]          =  index[((i-1)*M+1):((i-1)*M+N1)]
    Rindex[N1*(p-1)+((i-1)*N2+1):((i-1)*N2+N2)] =  index[((i-1)*M+1+N1):((i-1)*M+N1+N2)]
  }
  Rindex
}



#' Estimate a conditional VECM with Johansen statistics
#'
#' Estimate a conditional VECM using the Johansen procedure under alternative
#' deterministic specifications and return the fitted model together with
#' cointegration test statistics.
#'
#' @param y Numeric matrix of endogenous variables.
#' @param x Numeric matrix of conditioning variables. If `length(x) == 1`, the
#'   model is estimated without additional conditioning variables.
#' @param model Character string specifying the deterministic setup. Supported
#'   values are `"I"`, `"II"`, `"III"`, `"IV"`, and `"V"`.
#' @param type Character string specifying the Johansen statistic. Supported
#'   values are `"eigen"` and `"trace"`.
#' @param crk Integer scalar giving the cointegration rank.
#' @param p Integer scalar giving the lag length in levels.
#' @param q Significance level used for critical values.
#' @return A list containing Johansen test results, the fitted VECM, estimated
#'   cointegration objects, and the data matrices used in estimation.
#'
#' @examples
#' # Minimal illustrative example (fabricated data)
#' set.seed(1)
#' T <- 120
#' y <- cbind(
#'   y1 = cumsum(rnorm(T)),
#'   y2 = cumsum(rnorm(T))
#' )
#' x <- cbind(
#'   x1 = cumsum(rnorm(T))
#' )
#'
#' # Estimate with a constant in the cointegration relation (model II),
#' # using the maximum-eigenvalue test statistic.
#' fit <- cvecm(y = y, x = x, model = "II", type = "eigen", crk = 1, p = 2, q = 0.95)
#' fit$erg
#' fit$beta
#'
#' @export
#' @keywords internal
cvecm <- function (y,x,model = c("I","II","III","IV","V"),type = c("eigen", "trace"), crk=2, p = 1, q = 0.95)
{
  y <- as.matrix(y)
  if (q != 0.9 && q != 0.95 && q != 0.99) {
    return("please correct significance level")
  }

  p <- as.integer(p)
  N1 <- ncol(as.matrix(y))
  N  <- ncol(as.matrix(y))
  if (N1<crk) {
    return("y's dimension must be larger than crk")
  }

  if  ( length(x) == 1 ) {  z <- y }
  else {
    z <- cbind(y,x)
  }

  M1 <- ncol(as.matrix(z))
  T <- nrow(as.matrix(z))
  #Z <- embed(diff(z), p)
  Z <- embed_ts(diff(z), p)

  Y0 <- Z[, c(1:N1)]                # \Delta Y
  #X0 <- Z[,c((N1+1):M1)]           # \Delta X
  Z1 <- z[-T, ][p:(T - 1), ]        #      Z_1
  if ((p==1)&(length(x)==1)) {
    Z2 = NULL
    NOLAG = 1
  }
  else {
    Z2 <- Z[, c((M1+1):(M1*p))]               # \Delta Z_
    Z2 <- Z2[, redex(N1=N1,N2=ncol(x),p)]       # \Delta Z_
  }
  T1 <- nrow(as.matrix(Y0))
  #lT = (1:T1)/(1:T1)
  #Trend <- matrix(1:T1, T1, 1)
  lT = matrix(1,T1,1); colnames(lT) <- "Const"
  Trend <- matrix(1, T1, 1); colnames(Trend) <- "Trend"

  if ( model == "I" ) {
    Y0 = Y0
    Z1 = Z1
    Z2 = Z2
  }
  if ( model == "II" ) {
    Y0 = Y0
    Z1 = cbind(lT,Z1)
    Z2 = Z2
  }
  if ( model == "III" ) {
    Y0 = Y0
    Z1 = Z1
    Z2 = cbind(Z2,lT)
  }
  if ( model == "IV" ) {
    Y0 = Y0
    Z1 = cbind(Trend,Z1)
    Z2 = cbind(Z2,lT)
  }
  if ( model == "V" ) {
    Y0 = Y0
    Z1 = cbind(Z1)
    Z2 = cbind(Z2,lT,Trend)
  }

  if (length(Z2)==0) {
    R0 <- Y0
    R1 <- Z1
  }
  else {

    M00 <- crossprod(Y0)/T1
    M11 <- crossprod(Z1)/T1
    M22 <- crossprod(Z2)/T1
    M01 <- crossprod(Y0, Z1)/T1
    M02 <- crossprod(Y0, Z2)/T1
    M10 <- crossprod(Z1, Y0)/T1
    M20 <- crossprod(Z2, Y0)/T1
    M12 <- crossprod(Z1, Z2)/T1
    M21 <- crossprod(Z2, Z1)/T1
    M22inv <- solve(M22)
    R0 <- Y0 - t(M02 %*% M22inv %*% t(Z2))
    R1 <- Z1 - t(M12 %*% M22inv %*% t(Z2))
  }
  S00 <- crossprod(R0)/T1
  S01 <- crossprod(R0, R1)/T1
  S10 <- crossprod(R1, R0)/T1
  S11 <- crossprod(R1)/T1
  Ctemp <- chol(S11, pivot = TRUE)
  pivot <- attr(Ctemp, "pivot")
  oo <- order(pivot)
  C <- t(Ctemp[, oo])
  Cinv <- solve(C)
  S00inv <- solve(S00)
  valeigen <- eigen(Cinv %*% S10 %*% S00inv %*% S01 %*% t(Cinv))

  #valeigen <- eigen(S11inv %*% S10 %*% S00inv %*% S01 )
  lambda <- Re(valeigen$values)
  e      <- Re(valeigen$vector)

  V <- t(Cinv) %*% e
  Vorg <- V
  V <- sapply(1:M1, function(j) V[, j]/V[1, j])
  #W <- S01 %*% V %*% solve(t(V) %*% S11 %*% V)
  PI <- S01 %*% solve(S11)
  #DELTA <- S00 - S01 %*% V %*% solve(t(V) %*% S11 %*% V) %*% t(V) %*% S10
  if (length(Z2)==0) {
    GAMMA = NULL
  }
  else {
    GAMMA <- M02 %*% M22inv - PI %*% M12 %*% M22inv
  }
  beta   <- V[,1:crk]

  if ((crk>0)&(length(Z2)>0)) {
    CI = Z1%*%beta
    VECM<-stats::lm(Y0~0+CI+Z2)
  }
  if ((crk>0)&(length(Z2)==0)) {
    CI = Z1%*%beta
    VECM<-stats::lm(Y0~0+CI)
  }
  if ((crk == 0)&(length(Z2)>0)) {
    CI = 0
    VECM<-stats::lm(Y0~0+Z2)
  }
  if ((crk == 0)&(length(Z2)==0)) {
    CI = 0
    VECM<-NULL
  }
  E = -T1 * log(1 - lambda)
  E = E[1:N]
  ##### Estimation of VECM

  resultsvecm <- summary(VECM)

  if (model == "I")   {    Tab <- Tab1  }
  if (model == "II")  {    Tab <- Tab2  }
  if (model == "III") {    Tab <- Tab3  }
  if (model == "IV")  {    Tab <- Tab4  }
  if (model == "V")   {    Tab <- Tab5  }


  b = c(1:12)
  for (i in 1:12)   { b[i] = Tab[2*(i-1)+1,2+M1-N1] }
  a = c(1:12)
  for (i in 1:12)   { a[i] = Tab[2*i,2+M1-N1] }

  if (type == "eigen") {
    critical_vals = b
    M = matrix(0, N, 1)
    j = 1
    rank = 0
    while (j <= N && E[j] > critical_vals[N + 1 - j]) {
      M[j, ] = M[j, ] + 1
      j = j + 1
      rank = rank + 1
    }
    erg <- cbind(E, critical_vals[N:1])
    colnames(erg) <- c("teststatistic", "critical_value")

    if ( N > 1 ) {
      rownames(erg) <- c("crk <= 0 |", paste("crk <= ", 1:(N - 1),  " |", sep = ""))
    }
    if ( N == 1 ) {
      rownames(erg) <- c("crk <= 0 |" )
    }

    coint_rank <- paste("Johansen-Test (with maximum-eigenvalue-teststatistic) indicates",
                        rank, "cointegrating equation(s) at the", 1 - q,
                        "level")
    #print(coint_rank)
    result <- new.env()
    result$erg = erg
    result$estimation = VECM
    result$lambda     = E
    result$z          = z
    result$Z2         = Z2
    result$beta       = beta
    result$PI         = PI
    result$GAMMA      = GAMMA
    result$model      = model
    rr<-as.list(result)
    return(rr)
  }
  else {
    type = "trace"
    critical_vals = a
    stat = matrix(0, N, 1)
    for (i in 1:N) {
      sum = 0
      for (j in i:N) {
        sum = sum + E[j]
      }
      stat[i] = sum
    }
    M = matrix(0, N, 1)
    j = 1
    rank = 0
    while (stat[j] > critical_vals[N + 1 - j] && j <= N) {
      M[j, ] = M[j, ] + 1
      j = j + 1
      rank = rank + 1
    }
    erg <- cbind(stat, critical_vals[N:1])
    colnames(erg) <- c("teststatistic", "critical_value")

    if ( N > 1 ) {
      rownames(erg) <- c("crk <= 0 |", paste("crk <= ", 1:(N - 1),  " |", sep = ""))
    }
    if ( N == 1 ) {
      rownames(erg) <- c("crk <= 0 |")
    }

    coint_rank <- paste("Johansen-Test (with trace-teststatistic) indicates",
                        rank, "cointegrating equation(s) at the", 1 - q,
                        "level")
    #print(coint_rank)
    result <- new.env()
    result$erg = erg
    result$estimation = VECM
    result$lambda     = E
    result$z          = z
    result$Z2         = Z2
    result$beta       = beta
    result$PI         = PI
    result$GAMMA      = GAMMA
    result$model      = model
    rr<-as.list(result)
    return(rr)
  }
}



#' Compute an orthogonal complement of a matrix
#'
#' Construct a matrix whose columns span the orthogonal complement of the
#' column space of `alpha`.
#'
#' @param alpha Matrix with full-column rank.
#' @return A matrix whose columns form a basis for the orthogonal complement of
#'   `alpha`.
#'
#' @examples
#' set.seed(1)
#' n <- 5
#' r <- 2
#' alpha <- matrix(rnorm(n * r), nrow = n, ncol = r)
#' alpha_perp <- alpha_perpf(alpha)
#'
#' # Check orthogonality (should be close to zero)
#' t(alpha) %*% alpha_perp
#'
#' @export
#' @keywords internal
alpha_perpf <- function(alpha = (alpha)) {

  alpha <- as.matrix(alpha)
  n = dim(alpha)[1]
  nx = dim(alpha)[2]
  nz = n-nx
  c = diag(n)[,(nz+1):(nz+nx)]
  c_perp = diag(n)[,1:nz]
  alpha_perp = (diag(n)-c%*%solve(t(alpha)%*%c)%*%t(alpha))%*%c_perp
  t(alpha)%*%alpha_perp
  return(alpha_perp)
}



#' Evaluate the AB-SVAR covariance objective
#'
#' Compute the sum of squared deviations between the structural covariance
#' implied by `A0` and `B0` and the reduced-form covariance matrix `Sigma`.
#'
#' @param x Numeric vector of free structural parameters.
#' @param A0 Structural `A` template matrix with fixed entries coded as `0` or
#'   `1`.
#' @param B0 Structural `B` template matrix with fixed entries coded as `0` or
#'   `1`.
#' @param Sigma Reduced-form covariance matrix.
#' @return A single numeric objective value, or a character message if the
#'   identification or parameter dimensions are invalid.
#'
#' @examples
#' # Minimal illustrative example (fabricated matrices)
#' set.seed(1)
#' n <- 3
#' Sigma <- crossprod(matrix(rnorm(n * 50), nrow = 50)) / 50
#'
#' # A0 and B0 use 0/1 as fixed entries; any other value marks a free parameter slot
#' A0 <- diag(1, n)
#' B0 <- diag(1, n)
#'
#' # Make a few entries "free" by setting them to 2 (any value not 0/1 works)
#' A0[2, 1] <- 2
#' A0[3, 1] <- 2
#' B0[2, 2] <- 2
#'
#' # Number of free parameters must match n*(n+1)/2 for this function
#' n_free <- sum(!((as.vector(A0) == 0) | (as.vector(A0) == 1))) +
#'           sum(!((as.vector(B0) == 0) | (as.vector(B0) == 1)))
#' x <- rnorm(n_free)
#'
#' x_abf(x = x, A0 = A0, B0 = B0, Sigma = Sigma)
#'
#' @export
#' @keywords internal
x_abf <-  function(x, A0, B0, Sigma) {
  ### this function solves A and B from the reduced form Sigma for a AB-SVAR
  n = dim(A0)[1]
  if (sum((A0==0)|(A0==1))+sum((B0==0)|(B0==1))!= 2*n*n-n*(n+1)/2) return("not exactly identified")
  if (length(x)!=n*(n+1)/2)  return("dimension of x is incorrect")
  A = A0
  B = B0
  VA = as.vector(A)
  VB = as.vector(B)

  VA[!((VA==0)|(VA==1))] = x[1:length(VA[!((VA==0)|(VA==1))])]

  VB[!((VB==0)|(VB==1))] = x[(length(VA[!((VA==0)|(VA==1))])+1):(length(VA[!((VA==0)|(VA==1))])+length(VB[!((VB==0)|(VB==1))]))]

  A = matrix(VA,n,n)
  B = matrix(VB,n,n)
  return(sum((A%*%Sigma%*%t(A)-B%*%t(B))^2))
}



#' Estimate an AB-SVAR from reduced-form covariance
#'
#' Estimate exactly identified AB-SVAR structural matrices by minimizing the
#' covariance-matching objective defined in `x_abf()`.
#'
#' @param x0 Numeric vector of initial values for the free parameters.
#' @param A0 Structural `A` template matrix with fixed entries coded as `0` or
#'   `1`.
#' @param B0 Structural `B` template matrix with fixed entries coded as `0` or
#'   `1`.
#' @param Sigma Reduced-form covariance matrix.
#' @return A list containing the estimated structural matrices `A` and `B`, and
#'   the minimized objective value `diff`.
#'
#' @examples
#' \dontrun{
#' set.seed(1)
#' n <- 3
#' Sigma <- crossprod(matrix(rnorm(n * 80), nrow = 80)) / 80
#'
#' # Fixed entries coded as 0/1, free entries marked by any other value (e.g., 2)
#' A0 <- diag(1, n)
#' B0 <- diag(1, n)
#' A0[2, 1] <- 2
#' A0[3, 1] <- 2
#' B0[2, 2] <- 2
#'
#' # Initial values for free parameters
#' n_free <- sum(!((as.vector(A0) == 0) | (as.vector(A0) == 1))) +
#'           sum(!((as.vector(B0) == 0) | (as.vector(B0) == 1)))
#' x0 <- rnorm(n_free)
#'
#' res <- absvar(x0 = x0, A0 = A0, B0 = B0, Sigma = Sigma)
#' res[[1]]  # A
#' res[[2]]  # B
#' res[[3]]  # diff
#' }
#'
#' @export
absvar <- function(x0, A0, B0, Sigma) {
  ## This function solve AB_SVAR from the reduced form and return the A, B matrices and the sum of squared errors
  n =dim(A0)[1]
  ABdiff <- stats::nlm(x_abf,x0,A0,B0,Sigma,gradtol=0.000000000000001 )
  x = ABdiff$estimate
  A = A0
  B = B0
  VA = as.vector(A)
  VB = as.vector(B)
  VA[!((VA==0)|(VA==1))] = x[1:length(VA[!((VA==0)|(VA==1))])]
  VB[!((VB==0)|(VB==1))] = (x[(length(VA[!((VA==0)|(VA==1))])+1):(length(VA[!((VA==0)|(VA==1))])+length(VB[!((VB==0)|(VB==1))]))])
  A = matrix(VA,n,n)
  B = abs(matrix(VB,n,n))
  diff <-sum((A%*%Sigma%*%t(A)-B%*%t(B))^2)
  ## identification
  diag(solve(A)%*%B)
  return(list(A,B,diff))
}



#' Assemble a GVAR coefficient array from domestic and foreign blocks
#'
#' Build the stacked GVAR coefficient array by combining domestic coefficient
#' blocks, foreign coefficient blocks, and the weighting matrix.
#'
#' @param Bo Domestic coefficient array, reshaped internally to `(m, m, p, n)`
#'   if needed.
#' @param Ao Foreign coefficient array, reshaped internally to `(m, m, p, n)`
#'   if needed.
#' @param W GVAR weighting matrix of dimension `(n, n)`.
#' @param m Integer scalar giving the number of variables per country.
#' @param n Integer scalar giving the number of countries.
#' @param p Integer scalar giving the lag order.
#' @return A three-dimensional array of stacked GVAR coefficients with
#'   dimensions `(m * n, m * n, p)`.
#'
#' @examples
#' # Example with n = 2 countries, m = 2 variables, p = 2 lags
#' set.seed(1)
#' n <- 2
#' m <- 2
#' p <- 2
#'
#' # Domestic and foreign blocks as arrays already
#' Bo <- array(rnorm(m * m * p * n), dim = c(m, m, p, n))
#' Ao <- array(rnorm(m * m * p * n), dim = c(m, m, p, n))
#'
#' # Simple weights (rows sum to 1)
#' W <- matrix(c(0.7, 0.3,
#'               0.4, 0.6), nrow = n, byrow = TRUE)
#'
#' G <- bo_ao_w2_g(Bo = Bo, Ao = Ao, W = W, m = m, n = n, p = p)
#' dim(G)
#' G[,,1]  # lag 1 global coefficient matrix
#'
#' @export
#' @keywords internal
bo_ao_w2_g <- function(Bo, Ao, W, m, n, p) {
  dim(Bo) = c(m, m, p, n)
  dim(Ao) = c(m, m, p, n)
  G = (1:(n*m*n*m*p))*0
  dim(G) = c(n*m, n*m, p)
  for (i in 1:n) {
    for (j in 1:n) {
      for (L in 1:p)    G[(1+(i-1)*m):(i*m),(1+(j-1)*m):(j*m),L] = Ao[,,L,i]*W[i,j]
    }
  }
  for (i in 1:n) {
    for (L in 1:p)       G[(1+(i-1)*m):(i*m),(1+(i-1)*m):(i*m),L]  = Bo[,,L,i]
  }
  dim(G) = c(n*m, n*m, p)
  return(G)
}



#' Extract domestic and foreign blocks from a GVAR coefficient array
#'
#' Decompose a stacked GVAR coefficient array into country-specific domestic and
#' foreign coefficient arrays.
#'
#' @param G Stacked GVAR coefficient array of dimension `(m * n, m * n, p)`, or
#'   a matrix for `p = 1`.
#' @param W GVAR weighting matrix of dimension `(n, n)`.
#' @return A list with two elements: domestic coefficient arrays `Bo` and
#'   foreign coefficient arrays `Ao`.
#'
#' @examples
#' set.seed(1)
#' n <- 2
#' m <- 2
#' p <- 2
#'
#' # Build a GVAR array from blocks, then recover them back
#' Bo0 <- array(rnorm(m * m * p * n), dim = c(m, m, p, n))
#' Ao0 <- array(rnorm(m * m * p * n), dim = c(m, m, p, n))
#' W <- matrix(c(0.7, 0.3,
#'               0.4, 0.6), nrow = n, byrow = TRUE)
#'
#' G <- bo_ao_w2_g(Bo = Bo0, Ao = Ao0, W = W, m = m, n = n, p = p)
#' out <- gw2_bo_ao(G = G, W = W)
#' str(out)
#'
#' @export
#' @keywords internal
gw2_bo_ao <- function(G, W) {
  n = dim(W)[1]
  m = dim(G)[1]/n

  if (is.na(dim(G)[3])) dim(G) = c(m*n,m*n,1)
  p = dim(G)[3]
  Bo = (1:(m*m*p*n))*0
  dim(Bo) = c(m,m,p,n)
  Ao = Bo
  for (i in 1:n) {
    for (j in 1:n) {
      for (L in 1:p)   if (!j==i) Ao[,,L,i] = G[(1+(i-1)*m):(i*m),(1+(j-1)*m):(j*m),L]/W[i,j]
    }
  }
  for (i in 1:n) {
    for (L in 1:p)       Bo[,,L,i] = G[(1+(i-1)*m):(i*m),(1+(i-1)*m):(i*m),L]
  }
  result = list(Bo,Ao)
  names(result) = c("Bo","Ao")
  return(result)
}



#' Convert a weight vector into a GVAR-style weighting matrix
#'
#' Constructs an (n x n) weighting matrix from a length-n weight vector `W`, where
#' each row `i` contains the normalised weights of all *other* units (excluding `i`)
#' and the diagonal is set to zero. In other words, for each `i`, the off-diagonal
#' entries are `W[-i] / sum(W[-i])`.
#'
#' @param W A numeric vector of weights of length `n`.
#'
#' @return An (n, n) weighting matrix with zero diagonal and row-wise normalised
#' off-diagonal weights.
#'
#' @examples
#' W <- c(1, 2, 3, 4)
#' Wmat <- w2_wmat(W)
#' Wmat
#' rowSums(Wmat)   # should all be 1
#' diag(Wmat)      # should all be 0
#'
#' @export
#' @keywords internal
w2_wmat <- function(W) {
 n = length(W)
 Wmat = matrix(0,n,n)
 for (i in 1:n ) {
    Wmat[i,-i] = W[-i]/sum(W[-i])
 }
 return(Wmat)
}



#' Build a single-row selection/weighting matrix for stacked GVAR variables
#'
#' Creates an (nN x nN) matrix `comb` with exactly one non-zero column (the first),
#' where `n` normalised weights from `SW` are inserted at positions corresponding to
#' the K-th country within each variable block. This is typically used to construct a
#' linear combination (selection) over a stacked (variable x country) ordering.
#'
#' @param SW A weighting vector of length `n` (will be normalised to sum to 1).
#' @param n Number of variables.
#' @param N Number of countries.
#' @param K Index of the selected country within each variable block (1..N).
#'
#' @return An (nN, nN) matrix with weights placed in the first column at the selected
#' indices.
#'
#' @examples
#' # Example with n = 3 variables, N = 4 countries, selecting K = 2
#' SW <- c(2, 1, 3)
#' comb <- sw2comb(SW = SW, n = 3, N = 4, K = 2)
#' dim(comb)
#' comb[, 1]  # only this column has non-zeros
#'
#' @export
#' @keywords internal
sw2comb <- function(SW, n, N, K)
{
  comb = matrix(0, n*N, N*n)
  SW = SW/sum(SW)
  for (i in 1:n) {
    comb[(i-1)*N+K, 1] = SW[i]
  }
  return(comb)
}



#' Generate regime-specific VAR parameters with (optional) common stochastic trends
#'
#' Simulates/constructs VAR coefficient arrays for a multi-country, multi-regime setup
#' where each country can have a specified number of stochastic trends, and an optional
#' subset of those trends can be imposed as *common* across countries. The function
#' returns the regime-specific domestic VAR parameters (`Bo`) along with the implied
#' error-correction representations (`alpha`, `beta`) obtained via `b2_cib()`.
#'
#' Internally, the function:
#' - builds a “unit-root/trend” VAR block for the stochastic-trend subspace per country,
#' - optionally replaces the first `Ncommtrend` trend block with a shared (common) trend
#'   process across all countries, and
#' - builds a stable VAR block for the remaining subspace using provided characteristic
#'   roots (`r_npo`), then combines blocks into full (m x m) coefficient matrices.
#'
#' @param m Number of variables per country.
#' @param p Lags (country- and regime-specific). Used as indexed in the function.
#' @param T Number of observations.
#' @param r Number of stochastic trends per country.
#' @param Ncommtrend Number of common trends (optional). If missing, treated as `NA`.
#' @param n Number of countries in the GVAR model.
#' @param S Number of regimes.
#' @param r_npo A matrix/array specifying the roots of the characteristic polynomial in lags.
#'
#' @return A list containing:
#' \itemize{
#'   \item Bo: VAR coefficient array of dimension (m, m, Pmax, n, S)
#'   \item alpha: list of regime-specific adjustment matrices per country
#'   \item beta: list of regime-specific cointegration matrices per country
#' }
#'
#' @examples
#' # Minimal illustrative example (fabricated shapes; relies on var_data() and b2_cib())
#' # This example shows how to call the function, assuming the helper functions exist.
#' \dontrun{
#' set.seed(1)
#' m <- 4
#' n <- 2
#' S <- 2
#' T <- 100
#' r <- c(1, 1)
#' p <- array(2, dim = c(n, 2, S))
#'
#' # r_npo must satisfy var_data()'s “roots specification” requirements.
#' # See vignette for recommended construction.
#' r_npo <- array(0.5, dim = c(m, max(p[, 1, ]), n, S))
#'
#' out <- varbs_commtrend(m = m, p = p, T = T, r = r, Ncommtrend = 1, n = n, S = S, r_npo = r_npo)
#' str(out)
#' }
#'
#' @export
#' @keywords internal
varbs_commtrend <- function(m, p, T, r, Ncommtrend, n, S, r_npo) {
  alpha   = list()
  beta    = list()
  VAR_Ione = list()
  if (missing(Ncommtrend))  {Ncommtrend=NA}
  Pmax = max(p[,1:2,])
  Pmin = min(p[,1:2,][p[,1:2,]>0])
  Bo = (1:(m * m * Pmax * n * S)) * 0
  dim(Bo) = c(m, m, Pmax, n, S)


  for (i in 1:n) {
      Pmini             = min(p[i,1:2,][p[i,1:2,]>0])
	r_npi 		= c(1:(r[i]*Pmini))/c(1:(r[i]*Pmini))*1.5
      dim(r_npi) 		= c(r[i],Pmini)
      r_npi[1:r[i],1]  	= 1
	VAR_Ione[[i]]  	= var_data(n=r[i],p=Pmini,T=100,r_np=r_npi)
  }



  if (!anyNA(Ncommtrend)) {
     	r_npc  = c(1:(Ncommtrend*Pmin))/c(1:(Ncommtrend*Pmin))*1.5
      dim(r_npc) = c(Ncommtrend,Pmin)
      r_npc[1:Ncommtrend,1]  = 1
      VAR_IoneC = var_data(n=Ncommtrend,p=Pmin,T=100,r_np=r_npc)
   	for (i in 1:n) {
		VAR_Ione[[i]]$B[1:Ncommtrend,1:Ncommtrend,]=0
            VAR_Ione[[i]]$B[1:Ncommtrend,1:Ncommtrend,1:Pmin] = VAR_IoneC$B
	}
  }

      for (i in 1:n) {
 		NIzero = m - r[i]
         	#B =  matrix(rnorm(m*m),m,m)                 ### jizhu 0 nadiao
      	#B[(NIzero+1):m,] = 0
      	#B = B + diag(m)
            B = diag(m)
            #B = eigen(t(B)%*%B)$vectors
            alphai = list()
            betai = list()
            for (s in 1:S) {
      		r_np = c(1:(NIzero * p[i,1,s]))*0
            	dim(r_np) = c(NIzero,p[i,1,s])
            	r_np <- r_npo[(r[i]+1):m,1:p[i,1,s],i,s]
            	dim(r_np) = c(NIzero,p[i,1,s])
                  #A = matrix(rnorm(NIzero*NIzero),NIzero,NIzero); A = eigen(t(A)%*%A)[[2]]
	            VAR_IZero = var_data(NIzero, p[i, 1,s],T=100,r_np=r_np,)

            	for (j in 1: p[i,1,s]) {
               		Dblock    = matrix(0,m,m)
               		Dblock[1:NIzero,1:NIzero]     = VAR_IZero$B[,,j]
               		if (dim(VAR_Ione[[i]]$B)[3]>=j) Dblock[(NIzero+1):m,(NIzero+1):m] = VAR_Ione[[i]]$B[,,j]
               		Bo[, , j, i,s] = B%*%Dblock%*%solve(B)
      		}
            	#alpha[[i]] = b2_cib(VARD$B)[[2]]
            	#beta[[i]]  = b2_cib(VARD$B)[[3]]
			B2CIBab  	= b2_cib(Bo[, , 1:p[i, 1,s], i,s])
            	alphai[[s]] = B2CIBab[[2]]
            	betai[[s]]  = B2CIBab[[3]]
      	}
            alpha[[i]] = alphai
		beta[[i]]  = betai
  	}



  return(list(Bo,alpha,beta))
}



#' Construct foreign-variable coefficient arrays (Ao) from domestic dynamics with common trends
#'
#' Computes the regime- and country-specific foreign-variable coefficient arrays `Ao`
#' for a GVAR-type country equation when domestic dynamics `Bo` are generated under
#' (optional) common stochastic trends. Internally, `Bo` (and the implied error-correction
#' components `alpha` and `beta`) are obtained from `varbs_commtrend()`. For each country
#' and regime, a stable VAR block is generated via `var_data()` and then mapped into
#' `Ao` in levels. If `DFYflag = 1`, the term `alpha %*% t(beta)` is added into the first
#' lag to allow foreign variables to enter the cointegration space.
#'
#' @param m Number of variables.
#' @param p Lags (country- and regime-specific). Used as indexed in the function.
#' @param T Number of observations.
#' @param r Number of stochastic trends per country.
#' @param Ncommtrend Number of common trends.
#' @param n Number of countries.
#' @param S Number of regimes.
#' @param r_npo The matrix/array containing the roots of the characteristic polynomial.
#' @param DFYflag Switching indicator of whether foreign variables enter the cointegration space.
#' Defaults to `0` when `NA`.
#'
#' @return An array `Ao` of dimension (m, m, Pmax, n, S) containing the parameter matrices
#' of the foreign variables in each country equation of the GVAR model.
#'
#' @examples
#' # Minimal illustrative example (fabricated shapes; relies on varbs_commtrend() and var_data())
#' \dontrun{
#' set.seed(1)
#' m <- 4
#' n <- 2
#' S <- 2
#' T <- 100
#' r <- c(1, 1)
#'
#' # p indexed as p[i, 1:2, s] inside the function, so we create an array with that shape
#' p <- array(3, dim = c(n, 2, S))
#'
#' # r_npo is passed through to varbs_commtrend()
#' r_npo <- array(0.5, dim = c(m, max(p[,1,]), n, S))
#'
#' Ao <- bo2_ao(m = m, p = p, T = T, r = r, Ncommtrend = 1, n = n, S = S, r_npo = r_npo, DFYflag = 1)
#' dim(Ao)
#' }
#'
#' @export
#' @keywords internal
bo2_ao <- function(m, p, T, r, Ncommtrend, n, S, r_npo, DFYflag = NA) {
  if ( anyNA(DFYflag) ) DFYflag = 0
  Boab  = varbs_commtrend(m, p, T, r, Ncommtrend, n, S, r_npo)
  Pmax = max(p[,1:2,])
  beta  = Boab[[3]]
  alpha = Boab[[2]]
  Ao = (1:(m * m * Pmax * n * S)) * 0
  dim(Ao) = c(m, m, Pmax, n, S)
  for (i in 1:n) {
    for (s in 1:S) {
      if (p[i,2,s] < 2) Ao = Ao
      if (p[i,2,s] >= 2) {
        VARD = var_data(m, p=(p[i, 2,s]-1), T)
        BB = VARD$B
        Ao[,,1,i,s] = BB[,,1]+alpha[[i]][[s]]%*%t(beta[[i]][[s]])*DFYflag
        Ao[,,p[i,2,s],i,s] = -BB[,,p[i,2,s]-1]
        if ((p[i, 2,s]-1)>=2) { for (L in 2:(p[i, 2,s]-1)) Ao[, ,L, i,s] = BB[,,L]-BB[,,L-1]}
      }
    }
  }

  return(Ao)
}



#' Apply a full-rank linear transformation to Bo and Ao in a multi-regime GVAR
#'
#' Applies a block-diagonal, full-rank linear transformation to the initial domestic
#' (`Bo`) and foreign (`Ao`) coefficient arrays in a (multi-country) GVAR setting.
#' The transformation is identical across countries (same m x m block repeated along
#' the diagonal), and is applied for each lag and regime. For `Ao`, the transformation
#' additionally accounts for the GVAR weighting structure via `kronecker(W, diag(m))`.
#'
#' This is useful for reparameterising a system with independent common trends and
#' idiosyncratic trends while preserving the model structure under an invertible
#' change of basis.
#'
#' @param Bo The initial domestic coefficient array.
#' @param Ao The initial foreign coefficient array.
#' @param W A weighting matrix of the GVAR model (n x n).
#' @param S Number of regimes.
#'
#' @return A list containing:
#' \itemize{
#'   \item TBo: transformed domestic coefficient array (same shape as `Bo`)
#'   \item TAo: transformed foreign coefficient array (same shape as `Ao`)
#' }
#'
#' @examples
#' # Minimal illustrative example (fabricated arrays)
#' set.seed(1)
#' n <- 2
#' m <- 3
#' L <- 2
#' S <- 2
#'
#' Bo <- array(rnorm(m * m * L * n * S), dim = c(m, m, L, n, S))
#' Ao <- array(rnorm(m * m * L * n * S), dim = c(m, m, L, n, S))
#' W  <- matrix(c(0.7, 0.3,
#'                0.4, 0.6), nrow = n, byrow = TRUE)
#'
#' out <- bo_ao2_t_bo_ao(Bo = Bo, Ao = Ao, W = W, S = S)
#' str(out)
#'
#' @export
#' @keywords internal
bo_ao2_t_bo_ao <- function(Bo, Ao, W, S) {
  TBo = Bo*0
  TAo = Ao*0
  n = dim(W)[1]
  m = dim(Bo)[1]
  L = dim(Bo)[3]
  BD = matrix(0, m*n, m*n)
  B =  matrix(stats::rnorm(m*m), m, m)
  for (i in 1:n) {
    BD[((i-1)*m+1):((i-1)*m+m), ((i-1)*m+1):((i-1)*m+m)] = B
  }
  for (j in 1:L) {
    for ( s in 1: S ) {

      BoDj =  matrix(0, m*n, m*n)
      AoDj =  matrix(0, m*n, m*n)

      for (i in 1:n)  {
        BoDj[((i-1)*m+1):((i-1)*m+m), ((i-1)*m+1):((i-1)*m+m)] = Bo[,,j,i,s]
        AoDj[((i-1)*m+1):((i-1)*m+m), ((i-1)*m+1):((i-1)*m+m)] = Ao[,,j,i,s]
      }
      B_h = BD%*%BoDj%*%solve(BD)
      A_h = BD%*%AoDj%*%kronecker(W, diag(m))%*%solve(BD)%*%solve(kronecker(W, diag(m)))
      for (i in 1:n)  {
        TBo[,,j,i,s] = B_h[((i-1)*m+1):((i-1)*m+m), ((i-1)*m+1):((i-1)*m+m)]
        TAo[,,j,i,s] = A_h[((i-1)*m+1):((i-1)*m+m), ((i-1)*m+1):((i-1)*m+m)]
      }
    }
  }
  return(list(TBo, TAo))
}



#' Convert (multi-regime) VECM parameters to (multi-regime) cointegrated VAR parameters
#'
#' Converts an estimated vector error correction model (VECM) parameter matrix into
#' the corresponding cointegrated VAR parameter arrays in levels. The function supports
#' both single-regime and multi-regime specifications, including CIVAR/CIGVAR and their
#' multi-regime counterparts (MRCIVAR/MRCIGVAR), depending on the lag specification `p`
#' and the regime indicator `s`.
#'
#' The output contains:
#' - `B`: domestic VAR coefficient array (in levels),
#' - `A`: foreign/conditioning VAR coefficient array (in levels) when applicable, and
#' - `C`: deterministic-component parameters when present.
#'
#' @param param The coefficient matrix of the estimated multi-regime vector error correction model.
#' @param beta The estimated cointegration vectors.
#' @param p The lag specification. Its interpretation depends on the model class (single vs multi-regime).
#' @param s Types/indicator of MRCIVAR models. If `NA`, a single-regime model is assumed.
#'
#' @return A list with components `B`, `A`, and `C` corresponding to the parameters of the
#' (multi-regime) cointegrated VAR.
#'
#' @examples
#' # Minimal illustrative example (fabricated shapes; relies on cib3_b() and cia2_a())
#' set.seed(1)
#' m <- 3
#' p <- c(1, 2, 0, 2, 2)   # single-regime CIVAR example uses p[1], p[2], p[3]
#'
#' # param is used transposed as VECB; build as (k x m)
#' k <- p[1] + (p[2] + p[3]) * m + 1
#' param <- matrix(rnorm(k * m), nrow = k, ncol = m)
#'
#' # beta must conform for AB = VECB[, 1:p[1]] %*% t(beta)
#' beta <- matrix(rnorm(m * p[1]), nrow = m, ncol = p[1])
#'
#' out <- vecm2_va_rm(param = param, beta = beta, p = p, s = NA)
#' str(out)
#'
#' @export
#' @keywords internal
vecm2_va_rm <- function (param, beta, p = c(1, 2, 2, 2, 2), s = NA)
{
    m = dim(param)[2]
    VECB = t(param)
    if (anyNA(s)) {                                            ## One Regime
        if (!p[3] == 0) {                                        ## CIGVAR
            B = (1:(m * m * (p[2] + 1))) * 0
            dim(B) = c(m, m, (p[2] + 1))
            A = (1:(m * m * (p[3] + 1))) * 0
            dim(A) = c(m, m, (p[3] + 1))
            AB1 = VECB[, 1:p[1]] %*% t(beta)
            AB2 = VECB[, (1 + p[1]):(p[1] + p[1])] %*% t(beta)
            B[, , 1] = AB[, 1:m]
            A[, , 1] = AB[, (m + 1):(2 * m)]
            for (i in 2:(p[2] + 1)) B[, , i] = VECB[, p[1] *
                2 + ((i - 2) * m + 1):((i - 2) * m + m)]
            for (i in 2:(p[3] + 1)) A[, , i] = VECB[, (p[1] *
                2 + p[2] * m) + ((i - 2) * m + 1):((i - 2) *
                m + m)]
            B = cib3_b(B)
            A = cia2_a(A)
        }
        else {                                                   ##CIVAR
            B = (1:(m * m * (p[2] + 1))) * 0
            dim(B) = c(m, m, (p[2] + 1))
            AB = VECB[, 1:p[1]] %*% t(beta)
            B[, , 1] = AB[, 1:m]
            for (i in 2:(p[2] + 1)) B[, , i] = VECB[, p[1] +
                ((i - 2) * m + 1):((i - 2) * m + m)]
            B = cib3_b(B)
            A = NA
        }
        if (dim(param)[1] > p[1] + (p[2] + p[3]) * m)            ## whehter C is empty
            C = as.matrix(t(param)[, (p[1] + (p[2] + p[3]) * m + 1):dim(param)[1]])
        else C = NA
    }
    else {                                                    ## Multi Regime
        if (length(p) == 5) {                                    ## MRCIGVAR
            P = max(p[-1])
            B = (1:(m * m * (P + 1) * 2)) * 0
            dim(B) = c(m, m, (P + 1), 2)
            A = B
            AB = VECB[, 1:p[1]] %*% t(beta)
            B[, , 1, 1] = AB[, 1:m]
            A[, , 1, 1] = AB[, (m + 1):(2 * m)]
            B[, , 1, 2] = AB[, 1:m]
            A[, , 1, 2] = AB[, (m + 1):(2 * m)]
            for (i in 2:(p[2] + 1)) B[, , i, 1] = VECB[, p[1] +
                ((i - 2) * m + 1):((i - 2) * m + m)]
            for (i in 2:(p[3] + 1)) A[, , i, 1] = VECB[, (p[1] +
                p[2] * m) + ((i - 2) * m + 1):((i - 2) * m +
                m)]
            for (i in 2:(p[4] + 1)) B[, , i, 2] = VECB[, (p[1] +
                (p[2] + p[3]) * m) + ((i - 2) * m + 1):((i -
                2) * m + m)]
            for (i in 2:(p[5] + 1)) A[, , i, 2] = VECB[, (p[1] +
                (p[2] + p[3] + p[4]) * m) + ((i - 2) * m + 1):((i -
                2) * m + m)]
            B[, , 1:(p[2] + 1), 1] = cib3_b(B[, , 1:(p[2] + 1),
                1])
            B[, , 1:(p[4] + 1), 2] = cib3_b(B[, , 1:(p[4] + 1),
                2])
            A[, , 1:(p[3] + 1), 1] = cia2_a(A[, , 1:(p[3] + 1),
                1])
            A[, , 1:(p[5] + 1), 2] = cia2_a(A[, , 1:(p[5] + 1),
                2])
            if (dim(param)[1] > p[1] + (sum(p[-1])) * m) {
                C = (1:(m * 2)) * 0
                dim(C) = c(m, 1, 2)
                C[, 1, 1] = as.matrix(t(param)[, p[1] * 2 + sum(p[-1]) *
                  m + 1])
                C[, 1, 2] = as.matrix(t(param)[, p[1] * 2 + sum(p[-1]) *
                  m + 2])
            }
            else {
                C = NA
            }
        }
        if (length(p) == 3) {                                     ## MRCIVAR
            P = max(p[-1])
            B = (1:(m * m * (P + 1) * 2)) * 0
            dim(B) = c(m, m, (P + 1), 2)
            AB1 = VECB[, 1:p[1]] %*% t(beta)
            AB2 = VECB[, (1 + p[1]):(p[1] + p[1])] %*% t(beta)
            B[, , 1, 1] = AB1[, 1:m]
            B[, , 1, 2] = AB2[, 1:m]
            for (i in 2:(p[2] + 1)) B[, , i, 1] = VECB[, 2 *
                p[1] + ((i - 2) * m + 1):((i - 2) * m + m)]
            for (i in 2:(p[3] + 1)) B[, , i, 2] = VECB[, (2 *
                p[1] + p[2] * m) + ((i - 2) * m + 1):((i - 2) *
                m + m)]
            B[, , 1:(p[2] + 1), 1] = cib3_b(B[, , 1:(p[2] + 1),
                1])
            B[, , 1:(p[3] + 1), 2] = cib3_b(B[, , 1:(p[3] + 1),
                2])
            A = NA
            if (dim(param)[1] > p[1] * 2 + (sum(p[-1])) * m) {		## Whether C is empty  differnt adjustment speed
                km = (dim(param)[1]- (p[1] * 2 + (sum(p[-1])) * m))/2
                C = (1:(m * km* 2)) * 0
                dim(C) = c(m, km, 2)
                C[, 1:km, 1] = as.matrix(t(param)[, (p[1] * 2 + sum(p[-1]) * m + 1):(p[1] * 2 + sum(p[-1]) * m + km)])
                C[, 1:km, 2] = as.matrix(t(param)[,  (p[1] * 2 + sum(p[-1]) * m + km +1):(p[1] * 2 + sum(p[-1]) * m + km+km) ])
            }
            else {
                C = NA
            }
        }
    }
    return(list(B, A, C))
}



#' Assemble regime-specific GVAR coefficient array given a state vector
#'
#' Selects, for each country, the regime-specific domestic (`Bo`) and foreign (`Ao`)
#' coefficient matrices according to `state`, then assembles the corresponding stacked
#' GVAR coefficient array using the weighting matrix `W`. This is a convenience wrapper
#' around `bo_ao_w2_g()` for multi-regime GVAR parameters.
#'
#' @param Bo Parameter arrays of the domestic variables (m x m x p x n x S).
#' @param Ao Parameter arrays of the foreign variables (m x m x p x n x S).
#' @param W The weighting matrix of the GVAR model (n x n).
#' @param m Number of variables per country.
#' @param n Number of countries in the GVAR model.
#' @param p Lag order.
#' @param state Integer vector of length `n`, where `state[i]` indicates the regime
#' to use for country `i` (values in 1..S).
#'
#' @return An (mn, mn, p) array of autoregressive parameters for the regime-specific GVAR.
#'
#' @examples
#' set.seed(1)
#' n <- 3
#' m <- 2
#' p <- 2
#' S <- 2
#'
#' Bo <- array(rnorm(m * m * p * n * S), dim = c(m, m, p, n, S))
#' Ao <- array(rnorm(m * m * p * n * S), dim = c(m, m, p, n, S))
#' W  <- matrix(1, n, n)
#' diag(W) <- 0
#' W <- W / rowSums(W)
#'
#' state <- c(1, 2, 1)  # choose regime per country
#' Gs <- bo_ao_ws2_gs(Bo = Bo, Ao = Ao, W = W, m = m, n = n, p = p, state = state)
#' dim(Gs)
#'
#' @export
#' @keywords internal
bo_ao_ws2_gs <- function(Bo, Ao, W, m, n, p, state) {
  Bo_s = Bo[,,,,1]*0;dim(Bo_s) = c(m,m,p,n)
  Ao_s = Ao[,,,,1]*0;dim(Ao_s) = c(m,m,p,n)
  for (i in 1:n ) {
    Bo_s[,,,i] = Bo[,,,i,state[i]]
    Ao_s[,,,i] = Ao[,,,i,state[i]]
  }
  Go_s = bo_ao_w2_g(Bo_s,Ao_s,W,m,n,p)
  return(Go_s)
}



#' Extract the active exogenous design matrix across states
#'
#' Extracts a single exogenous data matrix from a state-dependent exogenous
#' variable array by selecting the state that contains the largest number of
#' active, non-zero exogenous variable columns.
#'
#' This helper is intended for regime-switching VAR-type models where
#' exogenous variables may be stored in a three-dimensional array with separate
#' slices for each state, and some states may contain padded zero columns.
#' The function identifies the state with the richest exogenous specification
#' and returns only the corresponding non-zero block of exogenous data.
#'
#' @param X A three-dimensional numeric array of exogenous variables with
#'   dimensions `T x Nx x S`, where:
#'   \describe{
#'     \item{`T`}{number of time observations,}
#'     \item{`Nx`}{maximum number of exogenous variables across states,}
#'     \item{`S`}{number of states or regimes.}
#'   }
#'   Each slice `X[,,s]` contains the exogenous data for state `s`. Columns that
#'   are not used in a given state are assumed to be zero-filled.
#'
#' @details
#' For each state `s`, the function counts how many columns in `X[,,s]` contain
#' at least one non-zero value. It then finds the state with the largest such
#' count and returns the first `ss` columns from that state, where `ss` is the
#' maximum number of active exogenous variables detected across all states.
#'
#' This is useful when a model stores state-dependent exogenous regressors in a
#' padded array and a single representative exogenous matrix is needed for
#' downstream calculations or reconstruction of the model design matrix.
#'
#' If multiple states have the same maximum number of active columns, the first
#' such state encountered is used.
#'
#' @return A numeric matrix of dimension `T x ss` containing the exogenous data
#'   extracted from the state with the largest number of active exogenous
#'   variables, where `ss` is the maximum number of non-zero columns across
#'   states.
#'
#' @examples
#' \dontrun{
#' ## T = 5 observations, Nx = 4 possible exogenous variables, S = 2 states
#' X = array(0, dim = c(5, 4, 2))
#'
#' ## state 1 uses two exogenous variables
#' X[, 1, 1] = rnorm(5)
#' X[, 2, 1] = rnorm(5)
#'
#' ## state 2 uses three exogenous variables
#' X[, 1, 2] = rnorm(5)
#' X[, 2, 2] = rnorm(5)
#' X[, 3, 2] = rnorm(5)
#'
#' XX = bind_exogenous_by_state(X)
#' dim(XX)   ## 5 x 3
#' }
#'
#' @export
#' @keywords internal
bind_exogenous_by_state = function(X) {
### X: the T x Nx x S array collecting the exogenous variables in MRVAR with state dependent exog variables
	S  = dim(X)[3]
      Nx = dim(X)[2]
      ss = 0
      sidx = 0
	for (s in 1:S) {
        if (sum(colSums(X[,,s] != 0) !=0)>ss ) {
           ss = sum(colSums(X[,,s] != 0) !=0)
           sidx = s
      }
      }
      XX = X[,1:ss,sidx]
      return(XX)
}



#' Construct a shock transformation matrix for impulse response analysis
#'
#' Builds the shock transformation matrix used to generate impulse response
#' functions (IRFs) under different identification schemes in a VAR-type model.
#' Depending on the selected `irf` option, the function returns a matrix that
#' maps reduced-form innovations into orthogonalised, generalised, concerted,
#' or user-defined structural shocks.
#'
#' This is an internal helper for IRF computation. It supports standard
#' Cholesky-based identification, generalised impulse responses, normalised
#' variants, concerted policy shocks, linear combinations of shocks, and an
#' explicitly supplied structural shock matrix.
#'
#' @param B A numeric coefficient array of a VAR object, typically with
#'   dimensions `n x n x p`, where `n` is the number of endogenous variables
#'   and `p` is the lag order. Only the variable dimension is used here to
#'   validate compatibility with the shock matrix.
#' @param sigma A numeric covariance matrix of the reduced-form residuals, with
#'   dimension `n x n`.
#' @param irf Character string specifying the type of shock transformation to
#'   construct. Supported values include:
#'   \describe{
#'     \item{`"gen"`}{generalised impulse responses, scaled by residual standard
#'     deviations.}
#'     \item{`"chol"`}{standard Cholesky decomposition of `sigma`.}
#'     \item{`"chol1"`}{column-normalised Cholesky decomposition.}
#'     \item{`"gen1"`}{generalised impulse responses scaled by residual
#'     variances.}
#'     \item{`"genN1"`}{negative version of `"gen1"`.}
#'     \item{`"comb"`}{linear combinations of shocks, scaled to unit variance.}
#'     \item{`"comb1"`}{linear combinations of shocks, scaled by variance
#'     rather than standard deviation.}
#'     \item{`"smat"`}{user-supplied transformation matrix `smat`.}
#'     \item{`"concerts1"`}{concerted shock based on `comb`, scaled by
#'     variances.}
#'     \item{`"concerts0"`}{concerted shock based on `comb`, scaled by standard
#'     deviations.}
#'     \item{`"concertc"`}{concerted conditional shock using `comb` and
#'     `invi()`.}
#'     \item{`"PTdecomp"`}{permanent-transitory decomposition based on `G`.}
#'   }
#' @param comb Optional numeric matrix defining linear combinations or
#'   concerted policy actions. This is required when `irf` is one of
#'   `"comb"`, `"comb1"`, `"concerts1"`, `"concerts0"`, or `"concertc"`.
#' @param G Optional numeric matrix used in the permanent-transitory
#'   decomposition when `irf = "PTdecomp"`. The transformation is based on the
#'   Cholesky decomposition of `G %*% sigma %*% t(G)`.
#' @param smat Optional numeric matrix giving an explicit structural shock
#'   decomposition. This is only used when `irf = "smat"`.
#'
#' @details
#' The function returns a transformation matrix `smat` that determines how a
#' shock is defined before the impulse responses are propagated through the VAR.
#'
#' Different options correspond to different identification strategies:
#' \itemize{
#'   \item \strong{Cholesky-based IRFs}: `"chol"` and `"chol1"` use a recursive
#'   ordering implied by the covariance matrix `sigma`.
#'   \item \strong{Generalised IRFs}: `"gen"`, `"gen1"`, and `"genN1"` do not
#'   require orthogonalisation through variable ordering in the same way as
#'   Cholesky IRFs.
#'   \item \strong{Combined or concerted shocks}: `"comb"`, `"comb1"`,
#'   `"concerts1"`, `"concerts0"`, and `"concertc"` allow shocks to be defined
#'   as user-specified linear combinations of the reduced-form innovations.
#'   \item \strong{User-defined structural shocks}: `"smat"` directly uses the
#'   matrix supplied in `smat`.
#'   \item \strong{Permanent-transitory decomposition}: `"PTdecomp"` uses `G`
#'   to transform the covariance structure before decomposition.
#' }
#'
#' For the `"comb"` and `"comb1"` options, the function rescales the combined
#' shocks using the diagonal elements of `t(comb) %*% sigma %*% comb`.
#'
#' A dimension check is performed at the end to ensure that the number of shock
#' columns in `smat` matches the number of variables in `B`.
#'
#' @return A numeric matrix `smat` defining the shock transformation used for
#'   the requested impulse response identification scheme.
#'
#' @seealso
#' \code{\link{chol}}, \code{\link{diag}}
#'
#' @examples
#' \dontrun{
#' ## Example covariance matrix
#' sigma = matrix(c(1.0, 0.3,
#'                  0.3, 2.0), 2, 2)
#'
#' ## Example VAR coefficient array
#' B = array(0, dim = c(2, 2, 1))
#'
#' ## Cholesky identification
#' u1(B, sigma, irf = "chol")
#'
#' ## Generalised identification
#' u1(B, sigma, irf = "gen")
#'
#' ## Combined shock affecting both variables
#' comb = matrix(c(1, 1,
#'                 0, 1), 2, 2)
#' u1(B, sigma, irf = "comb", comb = comb)
#'
#' ## User-specified structural matrix
#' smat = diag(2)
#' u1(B, sigma, irf = "smat", smat = smat)
#' }
#'
#' @export
#' @keywords internal
u1=function(B,sigma,irf = c("gen", "chol", "chol1","gen1","genN1","comb", "comb1","smat","concerts1","concerts0","concertc"),comb,G=NA,smat=NA)
  {
    ##-----debug--------
    ##browser()
    ##------------------
    neq <- dim(B)[1]
    nvar <- dim(B)[2]
    lags <- dim(B)[3]
    n <- dim(sigma)[1]
    if (irf == "smat")     {  smat = (smat)    }

    if (irf == "chol") 	   {        smat = chol(sigma)    					    }
    if (irf == "PTdecomp") {        smat = chol(G%*%sigma%*%t(G))          		    }
    if (irf == "gen")      {        smat = t(sigma %*% diag(1/(sqrt(diag(sigma)))))     }
    if (irf == "chol1")    {        smat = chol(sigma) %*% diag(1/diag(chol(sigma)))    }
    if (irf == "gen1")     {        smat = t(sigma %*% diag(1/(diag(sigma))))           }
    if (irf == "genN1")    {        smat = t(sigma %*% diag(-1/(diag(sigma))))          }
    if ( irf == "concerts1") { smat  = t((sigma%*%diag(1/(diag(sigma))))%*%comb)        };
    if ( irf == "concerts0") { smat  = t((sigma%*%diag(1/(sqrt(diag(sigma)))))%*%comb)  };

    if ( irf == "concertc") {
      c     = as.numeric(!(comb[,1]==0));
      smat  = matrix(0,n,n);
      for (i in 1: n) { smat[i,] = sigma[i,]%*%diag(c)%*%invi(sigma,c,i)%*%comb; }
      smat = t(smat);
    };

    if (irf == "comb") {
      DD = diag(t(comb) %*% sigma %*% comb)
      for (i in 1:length(DD)) {
        if (DD[i] > 0)
          DD[i] = sqrt(1/DD[i])
      }
      DD = diag(DD)
      smat = t(sigma %*% comb %*% DD)
    }
    if (irf == "comb1") {
      DD = diag(t(comb) %*% sigma %*% comb)
      for (i in 1:length(DD)) {
        if (DD[i] > 0)
          DD[i] = (1/DD[i])
      }
      DD = diag(DD)
      smat = t(sigma %*% comb %*% DD)
    }
    if(dim(smat)[2] != dim(B)[2]) stop("B and smat conflict on # of variables")
    return(smat)
  }



#' Split a single string into a character vector
#'
#' A small helper that wraps `base::strsplit()` but returns the first (and only)
#' element directly, which is handy when `x` is a length-1 character vector.
#'
#' @param x A character vector with one element.
#' @param split A character string (or regular expression) to split on.
#'
#' @return A character vector of the split pieces.
#'
#' @examples
#' x <- "alfa,bravo,charlie,delta"
#' strsplit1(x, split = ",")
#'
#' @export
strsplit1 <- function(x, split) {
  strsplit(x, split = split)[[1]]
}


#' Infer deterministic specification type from Co and exogenous regressors
#'
#' Infers the deterministic specification label (`type`) based on whether the
#' deterministic coefficient matrix `Co` and/or the exogenous regressor matrix
#' `EXOG` are provided, and on simple structural checks (for example, whether `Co`
#' contains only zeros, or whether `Co` has one more column than `EXOG`).
#'
#' The returned value is one of:
#' - `"none"`  : no deterministic component (all elements of `Co` are zero, and no `EXOG`)
#' - `"const"` : constant-only deterministic component
#' - `"exog0"` : exogenous regressors present and the first column of `Co` is all zeros
#' - `"exog1"` : exogenous regressors present and the first column of `Co` is not all zeros
#' - `" Co column<> EXOG column "` : shape mismatch between `Co` and `EXOG`
#'
#' @param Co The coefficients of the deterministic components (or `NA`).
#' @param EXOG The exogenous variables (or `NA`).
#' @param type The type of the deterministic specification for comparison (or `NA`).
#'
#' @return A character string giving the inferred deterministic specification type.
#'
#' @examples
#' infer_deterministic_type(Co=matrix(c(0,0,1,1),2,2),EXOG= c(1:10),type="exog0")
#' infer_deterministic_type(Co=matrix(c(1,1,1,1),2,2),EXOG= c(1:10),type="exog1")
#' infer_deterministic_type(Co=matrix(c(1,1,1,1,0,0),2,3),EXOG= c(1:10),type=NA)
#' infer_deterministic_type(Co=c(1,1),EXOG= NA,type=NA)
#' infer_deterministic_type(Co=c(0,0),EXOG= NA,type=NA)
#' var_data(n=2,p=2,T=100,Co=matrix(c(2,2,1,1),2,2),type="exog0",X=c(1:100))
#' var_data(n=2,p=2,T=100,Co=matrix(c(1,1,1,1),2,2),type="exog1",X=c(1:100))
#'
#' @export
infer_deterministic_type <- function (Co, EXOG, type)
{
  if (anyNA(Co) & anyNA(EXOG) & anyNA(type))
    type = "const"
  if (anyNA(Co) & !anyNA(EXOG) & anyNA(type))
    type = "exog1"
  if (anyNA(Co) & !anyNA(EXOG) & !anyNA(type))
    type = type
  if (!anyNA(Co) & anyNA(EXOG)) {
    if (sum(Co == 0) == length(Co))
      type = "none"
    else type = "const"
  }
  if (!anyNA(Co) & !anyNA(EXOG)) {
    if (ncol(as.matrix(Co)) == ncol(as.matrix(EXOG)) + 1) {
      if (sum(as.matrix(Co)[, 1] == 0) == length(as.matrix(Co)[, 1]))
        type = "exog0"
      else type = "exog1"
    }
    else type = " Co column<> EXOG column "
  }
  return(type)
}



#' Convert characteristic roots to AR coefficients
#'
#' Given the roots of a characteristic polynomial in lags (all outside the unit circle),
#' this function computes the coefficients of the corresponding autoregressive (AR)
#' process of order `p`. If `r_p` is not provided, random roots outside the unit circle
#' are generated.
#'
#' @param p The lag length (AR order).
#' @param r_p A length-`p` vector of characteristic roots outside the unit circle.
#'
#' @return A numeric vector of length `p` containing the AR coefficients. Returns a
#' character message if any root lies within the unit circle.
#'
#' @examples
#' roots_to_coef(3, c(1.1, 1.2, 1.3))
#'
#' @export
#' @keywords internal
roots_to_coef <- function(p, r_p) {
   if (missing(r_p)) r_p <- 0.5/(stats::runif(p)-0.5)  #random number outside unit circle
   if (min(abs(r_p)) < 1) {
   	return("r_p is within the unit circle")
   	#print("r_p is within the unit circle")
   }
   a = matrix(0,p,p)
   a[1,1] = 1/r_p[1]
   if ( p>1 ) {
   for (i in 2:p) {
      for ( j in 1:i ) {
         if (j == 1)           a[i,j] = a[i-1,j] + 1/r_p[i]
         if ((j > 1) & (j<i))  a[i,j] = a[i-1,j] - a[i-1,j-1]/r_p[i]
         if (j == i)           a[i,j] = -a[i-1,i-1]/r_p[i]
      }
   }
   }

   #R = matrix(0,p,p)
   #for (i in 1: p)     {
   #   for (j in 1: p ) {
   #        R[i,j] = r_p[j]^i
   #   }
   #}
   #a[p,]%*%R[,]
   return(a[p,])
}



#' Generate iid multivariate normal time series with a given covariance
#'
#' Simulates an iid multivariate normal series of length `T` with zero mean and
#' covariance matrix `sigma`. The output is a `T x n` matrix, where `n` is the
#' dimension of `sigma`.
#'
#' @param T Length of the generated time series.
#' @param sigma An (n x n) covariance matrix of the normal series.
#'
#' @return A `T x n` matrix of iid normal time series.
#'
#' @examples
#' set.seed(1)
#' sigma <- matrix(c(1, 0.3,
#'                   0.3, 2), nrow = 2, byrow = TRUE)
#' x <- rnorm_sigma(T = 100, sigma = sigma)
#' dim(x)
#' cov(x)
#'
#' @export
#' @keywords internal
rnorm_sigma <- function(T, sigma) {
    # generate random numbers from iid multivariate normal distribution with covariance matrix Sigma
    n = dim(sigma)[1]
    U = stats::rnorm(T*n)
    dim(U) = c(T,n)
    U = U%*%chol(sigma)
    return(U)
}



#' Generate iid conditional multivariate normal time series
#'
#' Simulates an iid conditional multivariate normal series given that the `I`-th
#' component is fixed at value `v`. The function returns an (n-1)-dimensional series
#' with conditional covariance and conditional mean implied by `sigma`.
#'
#' If `switch = 1`, the output is a random series drawn from the conditional normal.
#' If `switch = 0`, the output is the conditional expected value repeated over time.
#'
#' @param T Length of generated time series.
#' @param sigma The (n x n) covariance matrix of the normal series.
#' @param I Index of conditioning component (integer in 1..n).
#' @param v The value of the conditioning component.
#' @param switch A switch variable: `switch = 1` gives the conditional random series and
#' `switch = 0` gives the expected values.
#'
#' @return A (T x (n-1)) matrix of iid conditional normal time series (or conditional expected values).
#'
#' @examples
#' set.seed(1)
#' sigma <- matrix(c(1, 0.4, 0.2,
#'                   0.4, 2, 0.5,
#'                   0.2, 0.5, 1.5), nrow = 3, byrow = TRUE)
#'
#' # Condition on component I = 2 being v = 1
#' x_rand <- rnorm_sigma_cond(T = 100, sigma = sigma, I = 2, v = 1, switch = 1)
#' dim(x_rand)  # 100 x (3-1)
#'
#' # Conditional mean only (repeated over time)
#' x_mean <- rnorm_sigma_cond(T = 5, sigma = sigma, I = 2, v = 1, switch = 0)
#' x_mean
#'
#' @export
#' @keywords internal
rnorm_sigma_cond <- function(T, sigma, I, v, switch) {
    # generate random numbers from iid multivariate conditional normal distribution with covariance matrix Sigma, given
    # i-th component has the value of v, this will be an (n-1) dimensional random number
      sigma_cond = as.matrix(sigma[-I,-I])-sigma[-I,I]%*%solve(sigma[I,I])%*%sigma[I,-I]
      mu_cond = sigma[-I,I]%*%solve(sigma[I,I])%*%v
      U = rnorm_sigma(T,sigma_cond)*switch+as.vector(c(1:T)/c(1:T))%*%t(mu_cond)
      return(U)
}



#' Sample N unique indices from 1..T
#'
#' Draws `N` (approximately) uniformly distributed integer indices from `1` to `T`
#' using random uniforms, rounding, and de-duplication. The function returns the
#' first `N` unique values after shifting into the `1..T` range.
#'
#' @param N The number of elements to be selected.
#' @param T The total number of elements.
#'
#' @return An integer vector of length `N` with values in `1..T`.
#'
#' @examples
#' set.seed(1)
#' sample_n_out_of_t(N = 5, T = 100)
#'
#' @export
#' @keywords internal
sample_n_out_of_t <- function(N, T) {
  unique(round(stats::runif(3*N)*(T-1)))[1:N] + 1
}



#' Embed a time series with lagged columns and informative names
#'
#' Wraps `stats::embed()` to create a lag-embedded matrix from a univariate or
#' multivariate time series `y`. If `y` has column names, the embedded matrix
#' columns are named using those series names plus lag suffixes (".1", ".2", ...),
#' optionally preceded by `prefix`.
#'
#' @param y The time series (vector, matrix, or `ts`) to be embedded.
#' @param p Number of lags for embedding.
#' @param prefix Prefix to prepend to the original column names (default `""`).
#'
#' @return A matrix containing the lag-embedded time series.
#'
#' @examples
#' \dontrun{
#' # Univariate example
#' y <- stats::ts(1:20)
#' YY <- embed_ts(y, p = 3)
#' dim(YY)
#'
#' # Multivariate example with column names
#' y2 <- cbind(a = 1:20, b = 21:40)
#' YY2 <- embed_ts(y2, p = 2, prefix = "X_")
#' colnames(YY2)
#' }
#'
#' @export
#' @keywords internal
embed_ts <- function(y=stats::ts(c(1:20)), p=3, prefix="") {
  YY = stats::embed(y,p)
  if (!is.null(colnames(y))) {
    strc = colnames(y)
    strc = paste(prefix,strc,sep="")
    str0 = strc
    if (p > 1) {
      for (i in 1:(p-1)) {
        stri <- paste(str0, ".", sep="")
        stri <- paste(stri,as.character(i),sep="")
        strc <- cbind(strc,stri)
      }
    }
    colnames(YY) <- as.vector(strc)
  }
  return(YY)
}



#' Compute a masked inverse covariance matrix for selected variables
#'
#' Forms an inverse covariance matrix for a selected subset of variables defined by
#' the weighting vector `c`, while zeroing out the covariance contributions of a
#' designated responding variable index `i` (except for its own variance term).
#' The inverse is computed only on the selected submatrix and then placed back into
#' a zero-filled (n x n) matrix.
#'
#' @param sigma The input covariance matrix (n x n).
#' @param c The weighting vector of a concerted policy action. Positive entries indicate
#' selected variables.
#' @param i The index of responding variables (integer in 1..n).
#'
#' @return An (n x n) matrix containing the inverse of the selected, masked covariance
#' submatrix in the corresponding positions, and zeros elsewhere.
#'
#' @examples
#' set.seed(1)
#' n <- 4
#' sigma <- crossprod(matrix(rnorm(80), nrow = 20)) / 20
#' c <- c(1, 0, 1, 1)   # select variables 1, 3, 4
#' i <- 2               # responding variable
#' out <- invi(sigma = sigma, c = c, i = i)
#' out
#'
#' @export
#' @keywords internal
invi <- function(sigma, c, i) {
  n = dim(sigma)[1]
  sigmaout = matrix(0,n,n)
  cc = as.numeric(c>0)*(1:n)
  sigmai = sigma
  for (j in 1:n)         {
    for (k in 1:n)  {
      if ((j==i)|(k==i)) sigmai[j,k] = 0
    }
  }
  sigmai[i,i] = sigma[i,i]
  invsigmai = solve(sigmai[cc,cc])
  sigmaout[cc,cc] = invsigmai
  return(sigmaout)
}



#' Sum of squared residuals for regime-specific cointegration vectors
#'
#' Computes the sum of squared residuals (SSR) from a VECM-style regression where the
#' cointegration term is allowed to differ across two regimes. The parameter vector
#' `x` is reshaped to match `beta`, used to construct the cointegration index
#' `CI = Z1 %*% x`, and then split into regime-specific components via the indicator
#' series `St` and `NSt`. The SSR is computed from the regression
#' `Y0 ~ 0 + CI1 + CI2 + Z2`.
#'
#' @param x A vector containing the parameters in the cointegration vectors (will be
#' reshaped to `dim(beta)`).
#' @param beta The initial value (shape template) of the cointegration vectors.
#' @param Z1 The lagged I(1) series of the model.
#' @param St The indicator series of regime 1.
#' @param NSt The indicator series of regime 2.
#' @param Y0 The first difference series.
#' @param Z2 The lagged difference series.
#'
#' @return A numeric scalar: the sum of squared residuals.
#'
#' @examples
#' set.seed(1)
#' T <- 50
#' k <- 3
#' r <- 1
#'
#' Z1 <- matrix(rnorm(T * k), nrow = T, ncol = k)
#' beta <- matrix(rnorm(k * r), nrow = k, ncol = r)
#' x <- as.vector(beta)
#'
#' St <- matrix(rbinom(T, 1, 0.5), nrow = T, ncol = 1)
#' NSt <- 1 - St
#'
#' Y0 <- matrix(rnorm(T * r), nrow = T, ncol = r)
#' Z2 <- matrix(rnorm(T * 2), nrow = T, ncol = 2)
#'
#' f(x = x, beta = beta, Z1 = Z1, St = St, NSt = NSt, Y0 = Y0, Z2 = Z2)
#'
#' @export
#' @keywords internal
f <- function(x, beta, Z1, St, NSt, Y0, Z2) {
  dim(x) = dim(beta)
  CI = Z1%*%x
  CI1 = CI*St
  CI2 = CI*NSt
  residuals <-stats::lm(Y0~0+CI1+CI2+Z2)$residuals
  SSR = sum(diag(t(residuals)%*%residuals))
  return(SSR)
}



#' Shift common-factor regressors to the end of Z2
#'
#' Reorders the auxiliary-regression regressor matrix `Z2` by moving the lagged
#' exogenous common-factor blocks (if present) to the end of the matrix. If there are
#' no common factors (`kz = 0`) or no lags (`p = 0`), `Z2` is returned unchanged.
#'
#' This is used when the regressor matrix is stacked by lag as
#' (domestic variables, common factors) for each lag, and a downstream routine expects
#' domestic regressors first, followed by all common-factor regressors.
#'
#' @param Z2 Regressor matrix to be shifted.
#' @param kz Number of common exogenous factors.
#' @param n1 Number of domestic variables.
#' @param p Lag length of domestic regressors in `Z2` (also the lag length of common factors).
#'
#' @return A regressor matrix with common-factor columns shifted to the end (when applicable).
#'
#' @examples
#' set.seed(1)
#' T <- 10
#' n1 <- 2
#' kz <- 1
#' p <- 3
#'
#' # Z2 columns are arranged by lag blocks: (n1 domestic + kz factors) per lag
#' Z2 <- matrix(rnorm(T * (n1 + kz) * p), nrow = T)
#' Z2s <- shift_z2(Z2 = Z2, kz = kz, n1 = n1, p = p)
#' dim(Z2s)
#'
#' @export
#' @keywords internal
shift_z2 <- function(Z2, kz, n1, p) {
  # kz : number of Commfakts
  # Z2 : Regressiors on the auxiliery regression
  # n1 : number of domestic variables in a country
  # p  : lag length of domestic regressors. It is the same as the lag length of common factors (p[1,1]-1)
  if ((kz>0)&(p>0)) {
    cc = (1:(kz*p))*0
    for (j in 1:p) {
      for (i in 1:kz) {
        cc[(j-1)*kz+i] = (j-1)*(n1+kz)+i
      }
    }
    Z2 = cbind(Z2[,-cc],Z2[,cc])
  }
  return(Z2)
}



#' Shift common-factor regressors to the end of a mixed lag matrix
#'
#' Reorder a regressor matrix so that lagged common-factor columns are moved to
#' the end when both domestic and foreign lag blocks are present.
#'
#' @param Z2 Regressor matrix to reorder.
#' @param kz Integer scalar giving the number of common exogenous factors.
#' @param n1 Integer scalar giving the number of domestic variables.
#' @param p Integer scalar giving the domestic lag length.
#' @param p2 Integer scalar giving the foreign lag length.
#' @return A reordered regressor matrix.
#'
#' @examples
#' set.seed(1)
#' T <- 10
#' n1 <- 2
#' kz <- 1
#' p <- 2
#' p2 <- 2
#'
#' # Fabricate a Z2 with enough columns for the intended indexing pattern
#' # (Exact layout depends on how Z2 is constructed upstream.)
#' ncol_Z2 <- 2 * (p * (n1 + kz) + p2 * n1)
#' Z2 <- matrix(rnorm(T * ncol_Z2), nrow = T, ncol = ncol_Z2)
#'
#' Z2s <- shift_z2m(Z2 = Z2, kz = kz, n1 = n1, p = p, p2 = p2)
#' dim(Z2s)
#'
#' @export
#' @keywords internal
shift_z2m <- function(Z2, kz, n1, p, p2) {
  if ((kz>0)&(p>0)) {
    cc = (1:(kz*p))*0
    for (j in 1:p) {
      for (i in 1:kz) {
        cc[(j-1)*kz+i] = (j-1)*(n1+kz)+i
      }
    }
    ccc=c(cc,(p*(n1+kz)+p2*n1)+cc)
    Z2 = cbind(Z2[,-ccc],Z2[,ccc])
  }
  return(Z2)
}
